// src/renderer/src/components/mcp/MCPServerItem.vue
<script setup lang="ts">
import KeyValueEditor from './KeyValueEditor.vue'
import type { MCPServerConfig, MCPConnectionStatus, MCPTransportType } from '@renderer/types'

interface Props {
  config: MCPServerConfig
  status?: MCPConnectionStatus
  expanded: boolean
  connecting: boolean
  testing: boolean
}

interface Emits {
  (e: 'toggle-expand', name: string): void
  (e: 'connect', name: string): void
  (e: 'disconnect', name: string): void
  (e: 'delete', name: string): void
  (e: 'test', config: MCPServerConfig): void
  (e: 'save', config: MCPServerConfig): void
  (e: 'toggle-enabled', config: MCPServerConfig): void
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

/**
 * 更新配置
 */
function updateConfig(updates: Partial<MCPServerConfig>): void {
  emit('save', { ...props.config, ...updates })
}

/**
 * 更新传输类型
 */
function updateTransport(value: string): void {
  emit('save', { ...props.config, transport: value as MCPTransportType })
}

/**
 * 切换展开状态
 */
function handleToggle(): void {
  emit('toggle-expand', props.config.name)
}
</script>

<template>
  <div class="model-item">
    <div class="model-header" @click="handleToggle">
      <span class="expand-icon">{{ expanded ? '▼' : '▶' }}</span>
      <span class="model-name">{{ config.name }}</span>
      <!-- 连接状态指示器 -->
      <span
        class="status-indicator"
        :class="{
          connected: status?.connected,
          error: status?.error
        }"
        :title="status?.error || ''"
      >
        {{ status?.connected ? '已连接' : '未连接' }}
      </span>
      <span class="transport-badge">{{ config.transport }}</span>
      <div class="model-actions">
        <button
          v-if="!status?.connected"
          class="btn btn-small"
          :disabled="connecting"
          @click.stop="emit('connect', config.name)"
        >
          {{ connecting ? '连接中...' : '连接' }}
        </button>
        <button v-else class="btn btn-small" @click.stop="emit('disconnect', config.name)">
          断开
        </button>
        <button class="btn btn-small" :disabled="testing" @click.stop="emit('test', config)">
          {{ testing ? '测试中...' : '测试' }}
        </button>
        <button class="btn btn-small btn-danger-text" @click.stop="emit('delete', config.name)">
          删除
        </button>
      </div>
    </div>

    <!-- 展开的详情 -->
    <div v-if="expanded" class="model-details">
      <div class="form-group">
        <label>传输类型</label>
        <select
          :value="config.transport"
          class="input"
          @change="updateTransport(($event.target as HTMLSelectElement).value)"
        >
          <option value="stdio">stdio (本地进程)</option>
          <option value="sse">SSE (Server-Sent Events)</option>
          <option value="streamableHttp">Streamable HTTP</option>
        </select>
      </div>

      <!-- stdio 配置 -->
      <template v-if="config.transport === 'stdio'">
        <div class="form-group">
          <label>执行命令</label>
          <input
            :value="config.command"
            type="text"
            class="input"
            placeholder="例如: npx, node, python"
            @blur="updateConfig({ command: ($event.target as HTMLInputElement).value })"
          />
        </div>
        <div class="form-group">
          <label>命令参数 (每行一个)</label>
          <textarea
            :value="config.args?.join('\n') || ''"
            class="input textarea-small"
            placeholder="-y&#10;@modelcontextprotocol/server-xxx"
            @blur="
              updateConfig({
                args: ($event.target as HTMLTextAreaElement).value
                  .split('\n')
                  .filter((s) => s.trim())
              })
            "
          ></textarea>
        </div>
        <div class="form-group">
          <label>环境变量 (KEY=VALUE 格式，每行一个)</label>
          <KeyValueEditor
            :model-value="config.env || {}"
            placeholder="API_KEY=xxx"
            @update:model-value="updateConfig({ env: $event })"
          />
        </div>
      </template>

      <!-- HTTP/SSE 配置 -->
      <template v-else>
        <div class="form-group">
          <label>服务地址</label>
          <input
            :value="config.url"
            type="text"
            class="input"
            placeholder="https://example.com/mcp"
            @blur="updateConfig({ url: ($event.target as HTMLInputElement).value })"
          />
        </div>
        <div class="form-group">
          <label>认证头 (KEY=VALUE 格式，每行一个)</label>
          <KeyValueEditor
            :model-value="config.headers || {}"
            placeholder="Authorization=Bearer xxx"
            @update:model-value="updateConfig({ headers: $event })"
          />
        </div>
      </template>

      <!-- 启用状态 -->
      <div class="form-group">
        <label class="checkbox-label">
          <input
            type="checkbox"
            :checked="config.enabled"
            @change="emit('toggle-enabled', config)"
          />
          <span>启用此服务器</span>
        </label>
      </div>

      <!-- 工具列表 -->
      <div v-if="status?.connected" class="tools-section">
        <h4 class="tools-title">可用工具 ({{ status.tools.length || 0 }})</h4>
        <div class="tools-list">
          <div v-for="tool in status.tools" :key="tool.name" class="tool-item">
            <span class="tool-name">{{ tool.name }}</span>
            <span class="tool-desc">{{ tool.description }}</span>
          </div>
          <div v-if="!status.tools?.length" class="empty-tools">暂无可用工具</div>
        </div>
      </div>
    </div>
  </div>
</template>

// src/renderer/src/components/mcp/MCPServerItem.tsx
import { useState, useEffect, useCallback } from 'react'
import type { MCPServerConfig, MCPConnectionStatus, MCPTransportType } from '@shared/types/mcp'
import KeyValueEditor from './KeyValueEditor'
import styles from './MCPServerItem.module.css'

interface MCPServerItemProps {
  config: MCPServerConfig
  status?: MCPConnectionStatus
  expanded: boolean
  connecting: boolean
  testing: boolean
  onToggleExpand: () => void
  onConnect: () => void
  onDisconnect: () => void
  onDelete: () => void
  onTest: (config: MCPServerConfig) => void
  onSave: (config: MCPServerConfig) => void
}

/** MCP 服务器配置项：内联编辑、传输类型切换，使用 localConfig 管理编辑状态，失焦时保存 */
export default function MCPServerItem({
  config,
  status,
  expanded,
  connecting,
  testing,
  onToggleExpand,
  onConnect,
  onDisconnect,
  onDelete,
  onTest,
  onSave
}: MCPServerItemProps) {
  const [localConfig, setLocalConfig] = useState<MCPServerConfig>({ ...config })
  const [argsText, setArgsText] = useState((config.args || []).join('\n'))
  const [warningMessage, setWarningMessage] = useState('')

  // 同步 props.config → localConfig
  useEffect(() => {
    setLocalConfig({
      ...config,
      command: config.command || '',
      args: [...(config.args || [])],
      env: { ...(config.env || {}) },
      url: config.url || '',
      headers: { ...(config.headers || {}) }
    })
    setArgsText((config.args || []).join('\n'))
  }, [config])

  // 构建待保存的配置（清除不相关字段）
  const buildConfigToSave = useCallback((): MCPServerConfig => {
    const isStdio = localConfig.transport === 'stdio'
    return {
      ...localConfig,
      name: localConfig.name.trim(),
      command: isStdio ? localConfig.command?.trim() || '' : '',
      args: isStdio
        ? argsText
            .split('\n')
            .map((item) => item.trim())
            .filter((item) => item)
        : [],
      env: isStdio ? { ...(localConfig.env || {}) } : {},
      url: isStdio ? '' : localConfig.url?.trim() || '',
      headers: isStdio ? {} : { ...(localConfig.headers || {}) }
    }
  }, [localConfig, argsText])

  // 校验配置
  const validateConfig = useCallback((cfg: MCPServerConfig): string => {
    if (!cfg.name) return '服务器名称不能为空'
    if (cfg.transport === 'stdio') {
      if (!cfg.command) return `MCP 服务"${cfg.name}"的执行命令不能为空`
    } else if (!cfg.url) {
      return `MCP 服务"${cfg.name}"的服务地址不能为空`
    }
    return ''
  }, [])

  // 持久化配置（失焦保存）
  const persistConfig = useCallback(() => {
    const cfg = buildConfigToSave()
    const msg = validateConfig(cfg)
    if (msg) {
      setWarningMessage(msg)
      return
    }
    setWarningMessage('')
    onSave(cfg)
  }, [buildConfigToSave, validateConfig, onSave])

  // 更新配置字段
  const updateConfig = useCallback((updates: Partial<MCPServerConfig>) => {
    setLocalConfig((prev) => ({ ...prev, ...updates }))
  }, [])

  // 切换传输类型（清除不相关字段）
  const updateTransport = useCallback(
    (value: string) => {
      const transport = value as MCPTransportType
      if (transport === 'stdio') {
        updateConfig({ transport, url: '', headers: {} })
      } else if (localConfig.transport === 'stdio') {
        updateConfig({ transport, command: '', args: [], env: {} })
        setArgsText('')
      } else {
        updateConfig({ transport })
      }
      setWarningMessage('')
    },
    [localConfig.transport, updateConfig]
  )

  // 参数失焦处理
  const handleArgsBlur = useCallback(() => {
    const parsedArgs = argsText
      .split('\n')
      .map((item) => item.trim())
      .filter((item) => item)
    setLocalConfig((prev) => ({ ...prev, args: parsedArgs }))
    persistConfig()
  }, [argsText, persistConfig])

  // 环境变量变更
  const handleEnvChange = useCallback(
    (value: Record<string, string>) => {
      updateConfig({ env: value || {} })
      // 延迟保存，让 React 先更新 localConfig
      setTimeout(() => persistConfig(), 0)
    },
    [updateConfig, persistConfig]
  )

  // 请求头变更
  const handleHeadersChange = useCallback(
    (value: Record<string, string>) => {
      updateConfig({ headers: value || {} })
      setTimeout(() => persistConfig(), 0)
    },
    [updateConfig, persistConfig]
  )

  // 测试连接
  const handleTest = useCallback(() => {
    const cfg = buildConfigToSave()
    const msg = validateConfig(cfg)
    if (msg) {
      setWarningMessage(msg)
      return
    }
    setWarningMessage('')
    onTest(cfg)
  }, [buildConfigToSave, validateConfig, onTest])

  return (
    <div className={styles['mcp-server-item']}>
      <div className={styles['mcp-server-header']} onClick={onToggleExpand}>
        <span className={styles['expand-icon']}>{expanded ? '▼' : '▶'}</span>
        <span className={styles['mcp-server-name']}>{config.name}</span>
        <span
          className={[
            styles['status-indicator'],
            status?.connected ? styles.connected : '',
            status?.error ? styles.error : ''
          ]
            .filter(Boolean)
            .join(' ')}
          title={status?.error || ''}
        >
          {status?.connected ? '已连接' : '未连接'}
        </span>
        <span className={styles['transport-badge']}>{localConfig.transport}</span>
        <div className={styles['mcp-server-actions']}>
          {!status?.connected ? (
            <button
              className="sm-button sm-button--small"
              disabled={connecting}
              onClick={(e) => {
                e.stopPropagation()
                onConnect()
              }}
            >
              {connecting ? '连接中...' : '连接'}
            </button>
          ) : (
            <button
              className="sm-button sm-button--small"
              onClick={(e) => {
                e.stopPropagation()
                onDisconnect()
              }}
            >
              断开
            </button>
          )}
          <button
            className="sm-button sm-button--small"
            disabled={testing}
            onClick={(e) => {
              e.stopPropagation()
              handleTest()
            }}
          >
            {testing ? '测试中...' : '测试'}
          </button>
          <button
            className={[
              'sm-button',
              'sm-button--small',
              'sm-button--danger',
              styles['btn-danger-text']
            ].join(' ')}
            onClick={(e) => {
              e.stopPropagation()
              onDelete()
            }}
          >
            删除
          </button>
        </div>
      </div>

      {/* 展开的详情 */}
      {expanded && (
        <div className={styles['mcp-server-details']}>
          <div className={styles['form-group']}>
            <label>传输类型</label>
            <select
              value={localConfig.transport}
              className="sm-select"
              onChange={(e) => updateTransport(e.target.value)}
            >
              <option value="stdio">stdio (本地进程)</option>
              <option value="sse">SSE (Server-Sent Events)</option>
              <option value="streamableHttp">Streamable HTTP</option>
            </select>
          </div>

          {/* stdio 配置 */}
          {localConfig.transport === 'stdio' && (
            <>
              <div className={styles['form-group']}>
                <label>执行命令</label>
                <input
                  type="text"
                  className="sm-input"
                  placeholder="例如: npx, node, python"
                  value={localConfig.command || ''}
                  onChange={(e) => updateConfig({ command: e.target.value })}
                  onBlur={() => persistConfig()}
                />
              </div>
              <div className={styles['form-group']}>
                <label>命令参数 (每行一个)</label>
                <textarea
                  className={['sm-textarea', styles['textarea-small']].join(' ')}
                  placeholder={'-y\n@modelcontextprotocol/server-xxx'}
                  value={argsText}
                  onChange={(e) => setArgsText(e.target.value)}
                  onBlur={handleArgsBlur}
                />
              </div>
              <div className={styles['form-group']}>
                <label>环境变量 (KEY=VALUE 格式，每行一个)</label>
                <KeyValueEditor
                  value={localConfig.env || {}}
                  placeholder="API_KEY=xxx"
                  onChange={handleEnvChange}
                />
              </div>
            </>
          )}

          {/* HTTP/SSE 配置 */}
          {localConfig.transport !== 'stdio' && (
            <>
              <div className={styles['form-group']}>
                <label>服务地址</label>
                <input
                  type="text"
                  className="sm-input"
                  placeholder="https://example.com/mcp"
                  value={localConfig.url || ''}
                  onChange={(e) => updateConfig({ url: e.target.value })}
                  onBlur={() => persistConfig()}
                />
              </div>
              <div className={styles['form-group']}>
                <label>认证头 (KEY=VALUE 格式，每行一个)</label>
                <KeyValueEditor
                  value={localConfig.headers || {}}
                  placeholder="Authorization=Bearer xxx"
                  onChange={handleHeadersChange}
                />
              </div>
            </>
          )}

          {warningMessage && <div className={styles['inline-warning']}>{warningMessage}</div>}

          {/* 工具列表 */}
          {status?.connected && (
            <div className={styles['tools-section']}>
              <h4 className={styles['tools-title']}>可用工具 ({status.tools?.length || 0})</h4>
              <div className={styles['tools-list']}>
                {status.tools?.map((tool) => (
                  <div key={tool.name} className={styles['tool-item']}>
                    <span className={styles['tool-name']}>{tool.name}</span>
                    <span className={styles['tool-desc']}>{tool.description}</span>
                  </div>
                ))}
                {(!status.tools || status.tools.length === 0) && (
                  <div className={styles['empty-tools']}>暂无可用工具</div>
                )}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
