// src/renderer/src/components/knowledge/file-selector/components/FileItemRow.vue
<script setup lang="ts">
/**
 * 文件行项组件
 * 显示单个文件的选择状态和信息
 */
import type { FileItem } from '@renderer/types'
import { useFileStore } from '@renderer/stores'
import { FileIcon } from '../../shared/components'
import { getFileSourceClass, getFileSourceLabel, getFileSubtitle } from '../../utils/fileSource'
import styles from './FileItemRow.module.css'

defineProps<{
  /** 文件信息 */
  file: FileItem
  /** 是否被选中 */
  selected?: boolean
  /** 是否正在关联 */
  linking?: boolean
}>()

const emit = defineEmits<{
  (e: 'toggle', fileId: string): void
}>()

const fileStore = useFileStore()
</script>

<template>
  <div
    :class="[styles['file-item'], { [styles.selected]: selected, [styles.linking]: linking }]"
    @click="emit('toggle', file.id)"
  >
    <div :class="styles['file-checkbox']">
      <input type="checkbox" :checked="selected" @click.stop @change="emit('toggle', file.id)" />
    </div>

    <FileIcon :file-type="file.fileType" :size="24" />

    <div :class="styles['file-details']">
      <div :class="styles['file-title-line']">
        <div :class="styles['file-name']">{{ file.name }}</div>
        <span :class="[styles['source-badge'], styles[getFileSourceClass(file)]]">
          {{ getFileSourceLabel(file) }}
        </span>
      </div>
      <div :class="styles['file-subtitle']" :title="getFileSubtitle(file)">
        {{ getFileSubtitle(file) }}
      </div>
      <div :class="styles['file-meta']">
        <span class="badge">{{ file.fileType.toUpperCase() }}</span>
        <span>{{ fileStore.formatFileSize(file.size) }}</span>
        <span>{{ fileStore.formatDate(file.uploadedAt) }}</span>
      </div>
    </div>

    <div v-if="linking" :class="styles['linking-indicator']">
      <span class="sm-spinner"></span>
    </div>
  </div>
</template>

// src/renderer/src/components/knowledge/file-selector/components/FileItemRow.tsx
import type { FileItem } from '@renderer/types'
import { useFileStore } from '@renderer/stores'
import FileIcon from '../../shared/components/FileIcon'
import { getFileSourceClass, getFileSourceLabel, getFileSubtitle } from '../../utils/fileSource'
import styles from './FileItemRow.module.css'

interface FileItemRowProps {
  file: FileItem
  selected?: boolean
  linking?: boolean
  onToggle: (fileId: string) => void
}

export default function FileItemRow({ file, selected, linking, onToggle }: FileItemRowProps) {
  const fileStore = useFileStore()

  return (
    <div
      className={`${styles['file-item']} ${selected ? styles.selected : ''} ${linking ? styles.linking : ''}`}
      onClick={() => onToggle(file.id)}
    >
      <div className={styles['file-checkbox']}>
        <input
          type="checkbox"
          checked={selected}
          readOnly
          onClick={(e) => e.stopPropagation()}
          onChange={() => onToggle(file.id)}
        />
      </div>

      <FileIcon fileType={file.fileType} size={24} />

      <div className={styles['file-details']}>
        <div className={styles['file-title-line']}>
          <div className={styles['file-name']}>{file.name}</div>
          <span className={`${styles['source-badge']} ${styles[getFileSourceClass(file)]}`}>
            {getFileSourceLabel(file)}
          </span>
        </div>
        <div className={styles['file-subtitle']} title={getFileSubtitle(file)}>
          {getFileSubtitle(file)}
        </div>
        <div className={styles['file-meta']}>
          <span className="badge">{file.fileType.toUpperCase()}</span>
          <span>{fileStore.formatFileSize(file.size)}</span>
          <span>{fileStore.formatDate(file.uploadedAt)}</span>
        </div>
      </div>

      {linking && (
        <div className={styles['linking-indicator']}>
          <span className="sm-spinner"></span>
        </div>
      )}
    </div>
  )
}
