// src/renderer/src/components/lab/creator/CreateActions.tsx
import type { LabCreateType } from '@renderer/stores/lab/types'
import styles from './CreateActions.module.css'

interface CreateActionsProps {
  isCreating: boolean
  canCreate: boolean
  createType: LabCreateType
  createPhaseText: string
  onClose: () => void
  onCreate: () => void
}

export default function CreateActions({
  isCreating,
  canCreate,
  createType,
  createPhaseText,
  onClose,
  onCreate
}: CreateActionsProps) {
  return (
    <div className={styles['creator-footer']}>
      <button className={styles['btn']} onClick={onClose} disabled={isCreating}>
        取消
      </button>
      <button
        className={styles['btn-primary']}
        disabled={!canCreate || isCreating}
        onClick={onCreate}
      >
        {isCreating
          ? createPhaseText || '创建中...'
          : createType === 'existing'
            ? '选择并使用'
            : '创建并运行'}
      </button>
    </div>
  )
}

// src/renderer/src/components/lab/creator/CreateActions.vue
<script setup lang="ts">
import type { LabCreateType } from '@renderer/stores/lab/types'
import styles from './CreateActions.module.css'

defineProps<{
  isCreating: boolean
  canCreate: boolean
  createType: LabCreateType
  createPhaseText: string
}>()

const emit = defineEmits<{
  (e: 'close'): void
  (e: 'create'): void
}>()
</script>

<template>
  <div :class="styles['creator-footer']">
    <button :class="styles['btn']" :disabled="isCreating" @click="emit('close')">取消</button>
    <button
      :class="styles['btn-primary']"
      :disabled="!canCreate || isCreating"
      @click="emit('create')"
    >
      {{ isCreating ? createPhaseText : createType === 'existing' ? '选择并使用' : '创建并运行' }}
    </button>
  </div>
</template>
