// src/renderer/src/components/sandbox/creator/PortMappingSection.vue
<script setup lang="ts">
import type { SandboxCreateType, PortMapping } from '@renderer/stores/sandbox/types'

defineProps<{
  createType: SandboxCreateType
  portMappings: PortMapping[]
}>()

const emit = defineEmits<{
  (e: 'refresh'): void
  (e: 'add'): void
  (e: 'update', index: number, patch: Partial<PortMapping>): void
  (e: 'remove', index: number): void
}>()
</script>

<template>
  <div v-if="createType === 'compose' || createType === 'dockerfile'" class="port-mapping-section">
    <div class="port-mapping-header">
      <h3 class="port-mapping-title">
        端口映射
        <span v-if="portMappings.length > 0" class="port-count">({{ portMappings.length }})</span>
      </h3>
      <div class="port-mapping-actions">
        <button class="btn-small" @click="emit('refresh')">重新解析</button>
        <button class="btn-small" @click="emit('add')">+ 添加</button>
      </div>
    </div>
    <p class="port-mapping-hint">
      已从{{
        createType === 'compose' ? 'docker-compose.yaml' : 'Dockerfile EXPOSE 指令'
      }}自动解析端口映射，您可以手动修改
    </p>

    <div v-if="portMappings.length === 0" class="port-mapping-empty">
      未检测到端口映射，点击“添加”手动配置
    </div>

    <div v-else class="port-mapping-list">
      <div v-for="(mapping, index) in portMappings" :key="index" class="port-mapping-item">
        <div class="port-field host-port">
          <label>主机端口</label>
          <input
            type="number"
            :value="mapping.hostPort ?? ''"
            placeholder="自动"
            min="1"
            max="65535"
            @input="
              emit('update', index, {
                hostPort: ($event.target as HTMLInputElement).value
                  ? parseInt(($event.target as HTMLInputElement).value, 10)
                  : null
              })
            "
          />
        </div>
        <span class="port-arrow">→</span>
        <div class="port-field container-port">
          <label>容器端口</label>
          <input
            type="number"
            :value="mapping.containerPort"
            min="1"
            max="65535"
            @input="
              emit('update', index, {
                containerPort: parseInt(($event.target as HTMLInputElement).value, 10)
              })
            "
          />
        </div>
        <div class="port-field protocol">
          <label>协议</label>
          <select
            :value="mapping.protocol"
            @change="
              emit('update', index, {
                protocol: ($event.target as HTMLSelectElement).value as 'tcp' | 'udp'
              })
            "
          >
            <option value="tcp">TCP</option>
            <option value="udp">UDP</option>
          </select>
        </div>
        <button class="btn-remove" title="删除此端口映射" @click="emit('remove', index)">×</button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.port-mapping-section {
  padding: 16px 20px;
  border-top: 1px solid var(--theme-border);
  background-color: var(--theme-bg);
}

.port-mapping-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 8px;
}

.port-mapping-title {
  margin: 0;
  font-size: 14px;
  font-weight: 600;
  color: var(--theme-text);
  display: flex;
  align-items: center;
  gap: 6px;
}

.port-count {
  font-size: 12px;
  font-weight: 400;
  color: var(--theme-text-secondary);
}

.port-mapping-actions {
  display: flex;
  gap: 8px;
}

.btn-small {
  padding: 4px 10px;
  font-size: 12px;
  font-family: var(--theme-font);
  background-color: var(--theme-bg-secondary);
  border: 1px solid var(--theme-border);
  border-radius: 4px;
  color: var(--theme-text-secondary);
  cursor: pointer;
}

.port-mapping-hint {
  margin: 0 0 12px 0;
  font-size: 12px;
  color: var(--theme-text-secondary);
  line-height: 1.5;
}

.port-mapping-empty {
  padding: 16px;
  border: 1px dashed var(--theme-border);
  border-radius: 8px;
  color: var(--theme-text-secondary);
  font-size: 13px;
  text-align: center;
}

.port-mapping-list {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.port-mapping-item {
  display: grid;
  grid-template-columns: 1fr auto 1fr 120px auto;
  gap: 10px;
  align-items: end;
}

.port-field {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.port-field label {
  font-size: 12px;
  color: var(--theme-text-secondary);
}

.port-field input,
.port-field select {
  padding: 8px 10px;
  border: 1px solid var(--theme-border);
  border-radius: 6px;
  background-color: var(--theme-bg-secondary);
  color: var(--theme-text);
  font-family: var(--theme-font);
}

.port-arrow {
  padding-bottom: 8px;
  color: var(--theme-text-secondary);
}

.btn-remove {
  width: 32px;
  height: 32px;
  border: 1px solid var(--theme-border);
  border-radius: 6px;
  background-color: var(--theme-bg-secondary);
  color: var(--theme-danger);
  cursor: pointer;
}

@media (max-width: 768px) {
  .port-mapping-item {
    grid-template-columns: 1fr;
  }

  .port-arrow {
    display: none;
  }
}
</style>

// src/renderer/src/components/lab/creator/PortMappingSection.tsx
import type { LabCreateType, PortMapping } from '@renderer/stores/lab/types'

import styles from './PortMappingSection.module.css'

type PortMappingCreateType = Extract<LabCreateType, 'compose' | 'dockerfile'>

interface PortMappingSectionProps {
  createType: PortMappingCreateType
  portMappings: PortMapping[]
  onRefresh: () => void
  onAdd: () => void
  onUpdate: (index: number, patch: Partial<PortMapping>) => void
  onRemove: (index: number) => void
}

function parseOptionalPort(value: string): number | null {
  if (!value) return null
  const parsed = Number.parseInt(value, 10)
  return Number.isFinite(parsed) ? parsed : null
}

function parseRequiredPort(value: string): number {
  const parsed = Number.parseInt(value, 10)
  return Number.isFinite(parsed) ? parsed : 0
}

export default function PortMappingSection({
  createType,
  portMappings,
  onRefresh,
  onAdd,
  onUpdate,
  onRemove
}: PortMappingSectionProps) {
  return (
    <div className={styles['port-mapping-section']}>
      <div className={styles['port-mapping-header']}>
        <h3 className={styles['port-mapping-title']}>
          端口映射
          {portMappings.length > 0 && (
            <span className={styles['port-count']}>({portMappings.length})</span>
          )}
        </h3>
        <div className={styles['port-mapping-actions']}>
          <button type="button" className={styles['btn-small']} onClick={onRefresh}>
            重新解析
          </button>
          <button type="button" className={styles['btn-small']} onClick={onAdd}>
            + 添加
          </button>
        </div>
      </div>

      <p className={styles['port-mapping-hint']}>
        已从{createType === 'compose' ? 'docker-compose.yaml' : 'Dockerfile EXPOSE 指令'}
        自动解析端口映射，您可以手动修改
      </p>

      {portMappings.length === 0 ? (
        <div className={styles['port-mapping-empty']}>未检测到端口映射，点击"添加"手动配置</div>
      ) : (
        <div className={styles['port-mapping-list']}>
          {portMappings.map((mapping, index) => (
            <div key={index} className={styles['port-mapping-item']}>
              <div className={[styles['port-field'], styles['host-port']].join(' ')}>
                <label>主机端口</label>
                <input
                  type="number"
                  value={mapping.hostPort ?? ''}
                  placeholder="自动"
                  min="1"
                  max="65535"
                  onChange={(e) => onUpdate(index, { hostPort: parseOptionalPort(e.target.value) })}
                />
              </div>

              <span className={styles['port-arrow']}>→</span>

              <div className={[styles['port-field'], styles['container-port']].join(' ')}>
                <label>容器端口</label>
                <input
                  type="number"
                  value={mapping.containerPort || ''}
                  min="1"
                  max="65535"
                  onChange={(e) =>
                    onUpdate(index, { containerPort: parseRequiredPort(e.target.value) })
                  }
                />
              </div>

              <div className={[styles['port-field'], styles.protocol].join(' ')}>
                <label>协议</label>
                <select
                  value={mapping.protocol}
                  onChange={(e) =>
                    onUpdate(index, { protocol: e.target.value as PortMapping['protocol'] })
                  }
                >
                  <option value="tcp">TCP</option>
                  <option value="udp">UDP</option>
                </select>
              </div>

              <button
                type="button"
                className={styles['btn-remove']}
                title="删除此端口映射"
                onClick={() => onRemove(index)}
              >
                ×
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
