// src/renderer/src/components/knowledge/FileSelectorModal.vue
<script setup lang="ts">
/**
 * 文件选择模态框
 * 从已有文件选择或上传新文件到知识库
 */
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useZustandStore } from '@renderer/composables/useZustandStore'
import { useFileStore } from '@renderer/stores'
import type { FileItem } from '@renderer/types'
import type { UploadResult } from './shared/composables/useFileUpload'
import { FileSelectorHeader, FileSelectorTabs, ExistingFilesTab, UploadTab } from './file-selector'
import { useFileSelection } from './file-selector/composables/useFileSelection'
import styles from './FileSelectorModal.module.css'

const props = defineProps<{
  kbId: string
  linkedFileIds: string[]
}>()

const emit = defineEmits<{
  (e: 'close'): void
  (e: 'filesLinked', files: FileItem[]): void
}>()

// 标签页
type TabType = 'existing' | 'upload'
const activeTab = ref<TabType>('existing')
const visibleTab = ref<TabType>('existing')
const isPanelContentVisible = ref(true)
const containerRef = ref<HTMLElement | null>(null)
const panelShellRef = ref<HTMLElement | null>(null)
const existingPanelRef = ref<HTMLElement | null>(null)
const uploadPanelRef = ref<HTMLElement | null>(null)
const isPanelMeasured = ref(false)
let panelResizeObserver: ResizeObserver | null = null
let panelHeightAnimationFrame: number | null = null
let pendingVisibleTab: TabType | null = null
let panelTransitionTimer: number | null = null
let isPanelHeightTransitioning = false

const PANEL_HEIGHT_TRANSITION_MS = 220
const PANEL_HEIGHT_TRANSITION_FALLBACK_MS = PANEL_HEIGHT_TRANSITION_MS + 80

// 文件管理
const fileStore = useZustandStore(useFileStore)
const files = computed(() => fileStore.files)

// 文件选择逻辑
const {
  selectedFileIds,
  linkingFileIds,
  toggleSelection,
  selectAll,
  deselectAll,
  linkSelectedFiles
} = useFileSelection(files, props.kbId)

// 处理选择切换
function handleToggle(fileId: string): void {
  toggleSelection(fileId)
}

// 处理全选
function handleSelectAll(availableFiles: FileItem[]): void {
  selectAll(availableFiles)
}

// 处理关联选中文件
async function handleLinkSelected(): Promise<void> {
  const linkedFiles = await linkSelectedFiles()
  if (linkedFiles.length > 0) {
    emit('filesLinked', linkedFiles)
  }
}

// 处理上传完成
function handleUploadComplete(result: UploadResult): void {
  // useFileUpload 已在 autoLinkToKB 模式下完成关联，直接通知父组件更新 UI
  const newFiles = [...result.uploaded, ...result.duplicates]
  if (newFiles.length > 0) {
    emit('filesLinked', newFiles)
  }
}

function getPanelElement(tab: TabType): HTMLElement | null {
  return tab === 'existing' ? existingPanelRef.value : uploadPanelRef.value
}

function readPanelHeight(tab: TabType): number {
  const panel = getPanelElement(tab)
  if (!panel) {
    return 0
  }

  return Math.min(Math.ceil(panel.scrollHeight), readPanelAvailableHeight())
}

function readPanelAvailableHeight(): number {
  const container = containerRef.value
  const panelShell = panelShellRef.value
  if (!container || !panelShell) {
    return Number.POSITIVE_INFINITY
  }

  const containerStyles = window.getComputedStyle(container)
  const panelShellRect = panelShell.getBoundingClientRect()
  const containerRect = container.getBoundingClientRect()
  const maxContainerHeight = parseFloat(containerStyles.maxHeight)
  const containerHeightLimit = Number.isFinite(maxContainerHeight)
    ? maxContainerHeight
    : container.clientHeight
  const panelShellTop = panelShellRect.top - containerRect.top
  const availableHeight = Math.floor(containerHeightLimit - panelShellTop)

  return Math.max(1, availableHeight)
}

function clearPanelHeightAnimationFrame(): void {
  if (panelHeightAnimationFrame !== null) {
    window.cancelAnimationFrame(panelHeightAnimationFrame)
    panelHeightAnimationFrame = null
  }
}

function setPanelShellHeight(height: number): void {
  const panelShell = panelShellRef.value
  if (!panelShell || height <= 0) {
    return
  }

  isPanelMeasured.value = true
  panelShell.style.height = `${Math.min(height, readPanelAvailableHeight())}px`
}

function lockPanelShellHeight(): number {
  const panelShell = panelShellRef.value
  if (!panelShell) {
    return 0
  }

  const currentHeight = Math.ceil(panelShell.offsetHeight)
  setPanelShellHeight(currentHeight)
  void panelShell.offsetHeight
  return currentHeight
}

function animatePanelShellHeightTo(nextHeight: number): void {
  clearPanelHeightAnimationFrame()

  panelHeightAnimationFrame = window.requestAnimationFrame(() => {
    panelHeightAnimationFrame = null
    setPanelShellHeight(nextHeight)
  })
}

function syncVisiblePanelHeight(): void {
  const nextHeight = readPanelHeight(visibleTab.value)
  if (nextHeight > 0) {
    lockPanelShellHeight()
    animatePanelShellHeightTo(nextHeight)
  }
}

function observePanelContent(): void {
  panelResizeObserver?.disconnect()

  if (typeof ResizeObserver === 'undefined') {
    return
  }

  panelResizeObserver = new ResizeObserver(() => {
    if (!pendingVisibleTab && !isPanelHeightTransitioning && isPanelContentVisible.value) {
      syncVisiblePanelHeight()
    }
  })

  if (existingPanelRef.value) {
    panelResizeObserver.observe(existingPanelRef.value)
  }
  if (uploadPanelRef.value) {
    panelResizeObserver.observe(uploadPanelRef.value)
  }
}

function clearPanelTransitionTimer(): void {
  if (panelTransitionTimer !== null) {
    window.clearTimeout(panelTransitionTimer)
    panelTransitionTimer = null
  }
}

function finishPendingPanelTransition(): void {
  if (!pendingVisibleTab) {
    return
  }

  visibleTab.value = pendingVisibleTab
  pendingVisibleTab = null
  isPanelContentVisible.value = true
  isPanelHeightTransitioning = false
  clearPanelTransitionTimer()

  nextTick(() => {
    observePanelContent()
    syncVisiblePanelHeight()
  })
}

function handlePanelShellTransitionEnd(event: TransitionEvent): void {
  if (
    event.target !== panelShellRef.value ||
    event.propertyName !== 'height' ||
    !isPanelHeightTransitioning
  ) {
    return
  }

  isPanelHeightTransitioning = false

  if (pendingVisibleTab) {
    finishPendingPanelTransition()
    return
  }

  clearPanelTransitionTimer()
  observePanelContent()
}

watch(activeTab, async () => {
  pendingVisibleTab = null
  clearPanelTransitionTimer()
  clearPanelHeightAnimationFrame()
  lockPanelShellHeight()

  await nextTick()
  const nextHeight = readPanelHeight(activeTab.value)
  if (nextHeight <= 0) {
    return
  }

  isPanelHeightTransitioning = true
  isPanelContentVisible.value = false
  pendingVisibleTab = activeTab.value
  await nextTick()
  void panelShellRef.value?.offsetHeight
  animatePanelShellHeightTo(nextHeight)
  panelTransitionTimer = window.setTimeout(
    finishPendingPanelTransition,
    PANEL_HEIGHT_TRANSITION_FALLBACK_MS
  )
})

// 生命周期
onMounted(async () => {
  await fileStore.loadFiles()
  await nextTick()
  observePanelContent()
  syncVisiblePanelHeight()
  window.addEventListener('resize', syncVisiblePanelHeight)
})

onBeforeUnmount(() => {
  panelResizeObserver?.disconnect()
  clearPanelTransitionTimer()
  clearPanelHeightAnimationFrame()
  window.removeEventListener('resize', syncVisiblePanelHeight)
})
</script>

<template>
  <div :class="['sm-modal__overlay', styles['file-selector-overlay']]" @click.self="emit('close')">
    <div ref="containerRef" :class="['sm-modal__surface', styles['file-selector-container']]">
      <FileSelectorHeader @close="emit('close')" />

      <FileSelectorTabs v-model:active-tab="activeTab" />

      <div
        ref="panelShellRef"
        :class="[styles['file-selector-panel-shell'], { [styles['is-measured']]: isPanelMeasured }]"
        @transitionend="handlePanelShellTransitionEnd"
      >
        <div
          ref="existingPanelRef"
          :class="[
            styles['file-selector-panel'],
            { [styles['is-active']]: visibleTab === 'existing' && isPanelContentVisible }
          ]"
          :aria-hidden="visibleTab !== 'existing' || !isPanelContentVisible"
          :inert="visibleTab !== 'existing' || !isPanelContentVisible"
        >
          <ExistingFilesTab
            :kb-id="kbId"
            :linked-file-ids="linkedFileIds"
            :selected-file-ids="selectedFileIds"
            :linking-file-ids="linkingFileIds"
            @toggle="handleToggle"
            @select-all="handleSelectAll"
            @deselect-all="deselectAll"
            @link-selected="handleLinkSelected"
            @close="emit('close')"
          />
        </div>

        <div
          ref="uploadPanelRef"
          :class="[
            styles['file-selector-panel'],
            { [styles['is-active']]: visibleTab === 'upload' && isPanelContentVisible }
          ]"
          :aria-hidden="visibleTab !== 'upload' || !isPanelContentVisible"
          :inert="visibleTab !== 'upload' || !isPanelContentVisible"
        >
          <UploadTab :kb-id="kbId" @close="emit('close')" @upload-complete="handleUploadComplete" />
        </div>
      </div>
    </div>
  </div>
</template>

// src/renderer/src/components/knowledge/FileSelectorModal.tsx
import { useState, useCallback, useEffect, useRef } from 'react'
import { useFileStore } from '@renderer/stores'
import type { FileItem } from '@renderer/types'
import type { UploadResult } from './hooks/useFileUpload'
import FileSelectorHeader from './file-selector/components/FileSelectorHeader'
import FileSelectorTabs from './file-selector/components/FileSelectorTabs'
import ExistingFilesTab from './file-selector/components/ExistingFilesTab'
import UploadTab from './file-selector/components/UploadTab'
import { useFileSelection } from './hooks/useFileSelection'
import styles from './FileSelectorModal.module.css'

type TabType = 'existing' | 'upload'

interface FileSelectorModalProps {
  kbId: string
  linkedFileIds: string[]
  onClose: () => void
  onFilesLinked: (files: FileItem[]) => void
}

const PANEL_HEIGHT_TRANSITION_FALLBACK_MS = 300

export default function FileSelectorModal({
  kbId,
  linkedFileIds,
  onClose,
  onFilesLinked
}: FileSelectorModalProps) {
  const files = useFileStore((s) => s.files)
  const loadFiles = useFileStore((s) => s.loadFiles)

  const [activeTab, setActiveTab] = useState<TabType>('existing')
  const [visibleTab, setVisibleTab] = useState<TabType>('existing')
  const [isPanelContentVisible, setIsPanelContentVisible] = useState(true)
  const [isPanelMeasured, setIsPanelMeasured] = useState(false)

  const containerRef = useRef<HTMLDivElement>(null)
  const panelShellRef = useRef<HTMLDivElement>(null)
  const existingPanelRef = useRef<HTMLDivElement>(null)
  const uploadPanelRef = useRef<HTMLDivElement>(null)
  const pendingVisibleTabRef = useRef<TabType | null>(null)
  const panelTransitionTimerRef = useRef<number | null>(null)
  const panelHeightAnimationFrameRef = useRef<number | null>(null)
  const panelResizeObserverRef = useRef<ResizeObserver | null>(null)
  const isPanelHeightTransitioningRef = useRef(false)

  const {
    selectedFileIds,
    linkingFileIds,
    toggleSelection,
    selectAll,
    deselectAll,
    linkSelectedFiles
  } = useFileSelection(files, kbId)

  // Panel height helpers
  const getPanelElement = useCallback(
    (tab: TabType): HTMLElement | null =>
      tab === 'existing' ? existingPanelRef.current : uploadPanelRef.current,
    []
  )

  const readPanelAvailableHeight = useCallback((): number => {
    const container = containerRef.current
    const panelShell = panelShellRef.current
    if (!container || !panelShell) return Number.POSITIVE_INFINITY

    const containerStyles = window.getComputedStyle(container)
    const panelShellRect = panelShell.getBoundingClientRect()
    const containerRect = container.getBoundingClientRect()
    const maxContainerHeight = parseFloat(containerStyles.maxHeight)
    const containerHeightLimit = Number.isFinite(maxContainerHeight)
      ? maxContainerHeight
      : container.clientHeight
    const panelShellTop = panelShellRect.top - containerRect.top
    const availableHeight = Math.floor(containerHeightLimit - panelShellTop)

    return Math.max(1, availableHeight)
  }, [])

  const readPanelHeight = useCallback(
    (tab: TabType): number => {
      const panel = getPanelElement(tab)
      if (!panel) return 0
      return Math.min(Math.ceil(panel.scrollHeight), readPanelAvailableHeight())
    },
    [getPanelElement, readPanelAvailableHeight]
  )

  const setPanelShellHeight = useCallback(
    (height: number) => {
      const panelShell = panelShellRef.current
      if (!panelShell || height <= 0) return
      setIsPanelMeasured(true)
      panelShell.style.height = `${Math.min(height, readPanelAvailableHeight())}px`
    },
    [readPanelAvailableHeight]
  )

  const lockPanelShellHeight = useCallback((): number => {
    const panelShell = panelShellRef.current
    if (!panelShell) return 0
    const currentHeight = Math.ceil(panelShell.offsetHeight)
    setPanelShellHeight(currentHeight)
    void panelShell.offsetHeight
    return currentHeight
  }, [setPanelShellHeight])

  const clearPanelHeightAnimationFrame = useCallback(() => {
    if (panelHeightAnimationFrameRef.current !== null) {
      window.cancelAnimationFrame(panelHeightAnimationFrameRef.current)
      panelHeightAnimationFrameRef.current = null
    }
  }, [])

  const animatePanelShellHeightTo = useCallback(
    (nextHeight: number) => {
      clearPanelHeightAnimationFrame()
      panelHeightAnimationFrameRef.current = window.requestAnimationFrame(() => {
        panelHeightAnimationFrameRef.current = null
        setPanelShellHeight(nextHeight)
      })
    },
    [clearPanelHeightAnimationFrame, setPanelShellHeight]
  )

  const syncVisiblePanelHeight = useCallback(() => {
    const nextHeight = readPanelHeight(visibleTab)
    if (nextHeight > 0) {
      lockPanelShellHeight()
      animatePanelShellHeightTo(nextHeight)
    }
  }, [visibleTab, readPanelHeight, lockPanelShellHeight, animatePanelShellHeightTo])

  const clearPanelTransitionTimer = useCallback(() => {
    if (panelTransitionTimerRef.current !== null) {
      window.clearTimeout(panelTransitionTimerRef.current)
      panelTransitionTimerRef.current = null
    }
  }, [])

  const observePanelContent = useCallback(() => {
    panelResizeObserverRef.current?.disconnect()

    if (typeof ResizeObserver === 'undefined') return

    panelResizeObserverRef.current = new ResizeObserver(() => {
      if (
        !pendingVisibleTabRef.current &&
        !isPanelHeightTransitioningRef.current &&
        isPanelContentVisible
      ) {
        syncVisiblePanelHeight()
      }
    })

    if (existingPanelRef.current) {
      panelResizeObserverRef.current.observe(existingPanelRef.current)
    }
    if (uploadPanelRef.current) {
      panelResizeObserverRef.current.observe(uploadPanelRef.current)
    }
  }, [isPanelContentVisible, syncVisiblePanelHeight])

  const finishPendingPanelTransition = useCallback(() => {
    const pendingTab = pendingVisibleTabRef.current
    if (!pendingTab) return

    setVisibleTab(pendingTab)
    pendingVisibleTabRef.current = null
    setIsPanelContentVisible(true)
    isPanelHeightTransitioningRef.current = false
    clearPanelTransitionTimer()

    // Use setTimeout to let React render first, then measure
    setTimeout(() => {
      observePanelContent()
      syncVisiblePanelHeight()
    }, 0)
  }, [clearPanelTransitionTimer, observePanelContent, syncVisiblePanelHeight])

  // Handle tab switch
  const handleTabChange = useCallback((tab: TabType) => {
    setActiveTab(tab)
  }, [])

  // Effect: handle tab animation
  useEffect(() => {
    if (activeTab === visibleTab && !pendingVisibleTabRef.current) return

    pendingVisibleTabRef.current = null
    clearPanelTransitionTimer()
    clearPanelHeightAnimationFrame()
    lockPanelShellHeight()

    // Read next height after React renders
    const rafId = requestAnimationFrame(() => {
      const nextHeight = readPanelHeight(activeTab)
      if (nextHeight <= 0) return

      isPanelHeightTransitioningRef.current = true
      setIsPanelContentVisible(false)
      pendingVisibleTabRef.current = activeTab

      requestAnimationFrame(() => {
        void panelShellRef.current?.offsetHeight
        animatePanelShellHeightTo(nextHeight)
        panelTransitionTimerRef.current = window.setTimeout(
          finishPendingPanelTransition,
          PANEL_HEIGHT_TRANSITION_FALLBACK_MS
        )
      })
    })

    return () => cancelAnimationFrame(rafId)
  }, [
    activeTab,
    visibleTab,
    lockPanelShellHeight,
    readPanelHeight,
    animatePanelShellHeightTo,
    finishPendingPanelTransition,
    clearPanelTransitionTimer,
    clearPanelHeightAnimationFrame
  ])

  // Handle panel shell transition end
  const handlePanelShellTransitionEnd = useCallback(
    (event: React.TransitionEvent) => {
      if (
        event.target !== panelShellRef.current ||
        event.propertyName !== 'height' ||
        !isPanelHeightTransitioningRef.current
      ) {
        return
      }

      isPanelHeightTransitioningRef.current = false

      if (pendingVisibleTabRef.current) {
        finishPendingPanelTransition()
        return
      }

      clearPanelTransitionTimer()
      observePanelContent()
    },
    [finishPendingPanelTransition, clearPanelTransitionTimer, observePanelContent]
  )

  // Lifecycle: load files, setup observer
  useEffect(() => {
    loadFiles()

    // After initial render, observe and sync
    const rafId = requestAnimationFrame(() => {
      observePanelContent()
      syncVisiblePanelHeight()
    })

    const handleResize = () => syncVisiblePanelHeight()
    window.addEventListener('resize', handleResize)

    return () => {
      cancelAnimationFrame(rafId)
      panelResizeObserverRef.current?.disconnect()
      clearPanelTransitionTimer()
      clearPanelHeightAnimationFrame()
      window.removeEventListener('resize', handleResize)
    }
  }, [
    loadFiles,
    observePanelContent,
    syncVisiblePanelHeight,
    clearPanelTransitionTimer,
    clearPanelHeightAnimationFrame
  ])

  // Handlers
  const handleToggle = useCallback((fileId: string) => toggleSelection(fileId), [toggleSelection])

  const handleLinkSelected = useCallback(async () => {
    const linkedFiles = await linkSelectedFiles()
    if (linkedFiles.length > 0) {
      onFilesLinked(linkedFiles)
    }
  }, [linkSelectedFiles, onFilesLinked])

  const handleUploadComplete = useCallback(
    (result: UploadResult) => {
      const newFiles = [...result.uploaded, ...result.duplicates]
      if (newFiles.length > 0) {
        onFilesLinked(newFiles)
      }
    },
    [onFilesLinked]
  )

  return (
    <div className={`sm-modal__overlay ${styles['file-selector-overlay']}`} onClick={onClose}>
      <div
        ref={containerRef}
        className={`sm-modal__surface ${styles['file-selector-container']}`}
        onClick={(e) => e.stopPropagation()}
      >
        <FileSelectorHeader onClose={onClose} />

        <FileSelectorTabs activeTab={activeTab} onTabChange={handleTabChange} />

        <div
          ref={panelShellRef}
          className={`${styles['file-selector-panel-shell']} ${isPanelMeasured ? styles['is-measured'] : ''}`}
          onTransitionEnd={handlePanelShellTransitionEnd}
        >
          <div
            ref={existingPanelRef}
            className={`${styles['file-selector-panel']} ${visibleTab === 'existing' && isPanelContentVisible ? styles['is-active'] : ''}`}
            aria-hidden={visibleTab !== 'existing' || !isPanelContentVisible}
          >
            <ExistingFilesTab
              kbId={kbId}
              linkedFileIds={linkedFileIds}
              selectedFileIds={selectedFileIds}
              linkingFileIds={linkingFileIds}
              onToggle={handleToggle}
              onSelectAll={selectAll}
              onDeselectAll={deselectAll}
              onLinkSelected={handleLinkSelected}
              onClose={onClose}
            />
          </div>

          <div
            ref={uploadPanelRef}
            className={`${styles['file-selector-panel']} ${visibleTab === 'upload' && isPanelContentVisible ? styles['is-active'] : ''}`}
            aria-hidden={visibleTab !== 'upload' || !isPanelContentVisible}
          >
            <UploadTab kbId={kbId} onClose={onClose} onUploadComplete={handleUploadComplete} />
          </div>
        </div>
      </div>
    </div>
  )
}
