// src/renderer/src/App.vue
<script setup lang="ts">
import { ref, watch, onMounted, onBeforeUnmount } from 'vue'
import { storeToRefs } from 'pinia'
import KnowledgePage from './pages/KnowledgePage.vue'
import SandboxPage from './pages/SandboxPage.vue'
import PaperReaderPage from './pages/PaperReaderPage.vue'
import ErrorBanner from './components/ErrorBanner.vue'
import NotificationCenter from './components/NotificationCenter.vue'
import SettingsModal from './components/SettingsModal.vue'
import SvgIcon from './components/icons/SvgIcon.vue'
import WorkspaceSidebarHost from './components/chrome/WorkspaceSidebarHost.vue'
import WorkspaceToolbar from './components/chrome/WorkspaceToolbar.vue'

// Composables
import { useLifecycle } from './composables/lifecycle/useLifecycle'
import { useTheme } from './composables/useTheme'

// Stores
import { useUIStateStore, useConfigStore } from './stores'

// ==================== 主题初始化 ====================
const { initTheme } = useTheme()

// ==================== UI 状态管理（直接使用 Store）====================
const uiState = useUIStateStore()
const { currentView, isKnowledgeView, isPaperView, isCurrentSidebarCollapsed, configError } =
  storeToRefs(uiState)

// 配置 Store - 用于加载语音识别等配置
const configStore = useConfigStore()

// 设置弹窗状态（本地状态）
const showSettings = ref(false)

function openSettings(): void {
  showSettings.value = true
}

function closeSettings(): void {
  showSettings.value = false
}

function toggleSidebar(): void {
  uiState.toggleCurrentSidebar()
}

function dismissError(): void {
  uiState.dismissConfigError()
}

function handleMCPUpdated(): void {
  uiState.notifyMcpUpdate()
  uiState.loadConfigStatus()
}

// ==================== 视图切换监听 ====================
watch(
  () => currentView.value,
  (newView, oldView) => {
    window.api.logger.debug('[App] 视图切换', {
      from: oldView,
      to: newView
    })
  },
  { immediate: true }
)

// ==================== 生命周期 ====================
useLifecycle({
  loadConfigStatus: () => uiState.loadConfigStatus(),
  setupStreamListener: undefined,
  cleanupStreamListener: undefined,
  loadSessionList: undefined,
  loadKnowledgeBases: undefined
})

// 初始化主题和配置
onMounted(async () => {
  // 先加载配置（包含语音识别配置等）
  await configStore.loadConfig()
  // 再初始化主题
  await initTheme()
})

// ==================== 全局外部链接拦截 ====================
/**
 * 拦截页面内所有 <a> 标签点击，将 http/https 外部链接通过系统默认浏览器打开
 * 防止链接在 Electron 窗口内导航
 */
function handleGlobalLinkClick(event: MouseEvent): void {
  const target = event.target as HTMLElement
  const anchor = target.closest('a') as HTMLAnchorElement | null
  if (!anchor || !anchor.href) return

  try {
    const url = new URL(anchor.href)
    if (url.protocol === 'http:' || url.protocol === 'https:') {
      event.preventDefault()
      window.api.window.openExternal(anchor.href)
    }
  } catch {
    // 非合法 URL，忽略
  }
}

onMounted(() => {
  document.addEventListener('click', handleGlobalLinkClick, true)
})

onBeforeUnmount(() => {
  document.removeEventListener('click', handleGlobalLinkClick, true)
})
</script>

<template>
  <div class="sm-app">
    <!-- 配置加载错误提示(仅在加载失败时显示) -->
    <Transition name="sm-feedback" appear>
      <ErrorBanner v-if="configError" :error="configError" @dismiss="dismissError" />
    </Transition>

    <!-- 全局通知中心 -->
    <NotificationCenter />

    <!-- 主布局 -->
    <div class="sm-shell sm-workspace-page">
      <div class="sm-workspace-page__drag-region" aria-hidden="true"></div>
      <div class="sm-workspace-page__chrome-actions" aria-label="窗口快捷操作">
        <button
          class="sm-icon-button sm-workspace-page__chrome-button"
          title="设置"
          aria-label="打开设置"
          @click="openSettings"
        >
          <SvgIcon name="settings" :size="14" />
        </button>

        <button
          class="sm-icon-button sm-workspace-page__chrome-button"
          :title="isCurrentSidebarCollapsed ? '展开侧边栏' : '折叠侧边栏'"
          :aria-label="isCurrentSidebarCollapsed ? '展开侧边栏' : '折叠侧边栏'"
          @click="toggleSidebar"
        >
          <SvgIcon name="sidebar-toggle" :size="14" />
        </button>
      </div>

      <WorkspaceSidebarHost />

      <div class="sm-workspace-main">
        <WorkspaceToolbar />

        <div class="sm-workspace-main__body sm-workspace-main__body--fill">
          <Transition name="sm-workspace-switch" mode="out-in" appear>
            <!-- 论文阅读器视图 -->
            <PaperReaderPage v-if="isPaperView" key="paper" />

            <!-- 知识库视图 -->
            <KnowledgePage v-else-if="isKnowledgeView" key="knowledge" />

            <!-- 沙箱视图 -->
            <SandboxPage v-else key="sandbox" />
          </Transition>
        </div>
      </div>
    </div>

    <!-- 设置弹窗 -->
    <Transition name="sm-modal" appear>
      <SettingsModal v-if="showSettings" @close="closeSettings" @mcp-updated="handleMCPUpdated" />
    </Transition>
  </div>
</template>

<style scoped>
.sm-workspace-page__drag-region {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  height: var(--sm-space-3);
  z-index: 3;
  -webkit-app-region: drag;
  user-select: none;
}

.sm-workspace-page__chrome-actions {
  position: absolute;
  top: 12px;
  left: 90px;
  z-index: 6;
  display: flex;
  align-items: center;
  gap: 0;
  -webkit-app-region: no-drag;
}

.sm-workspace-page__chrome-button {
  width: 24px;
  height: 30px;
  border-color: transparent;
  border-radius: 0;
  background: transparent;
  -webkit-app-region: no-drag;
}

.sm-workspace-page__chrome-button:hover,
.sm-workspace-page__chrome-button:active,
.sm-workspace-page__chrome-button:focus-visible {
  border-color: transparent;
  background: transparent;
  color: var(--sm-color-text-primary);
}
</style>

// src/renderer/src/App.tsx
import { useState, useEffect, useCallback, useMemo } from 'react'
import { useUIStateStore } from '@renderer/stores/uiStateStore'
import { useConfigStore } from '@renderer/stores/configStore'
import { usePaperReaderStore } from '@renderer/stores/paperReaderStore'
import { getRuntimePlatform } from '@renderer/composables/runtimePlatformCore'

import NotificationCenter from '@renderer/components/NotificationCenter'
import SettingsModal from '@renderer/components/SettingsModal'
import SvgIcon from '@renderer/components/icons/SvgIcon'
import WindowControls from '@renderer/components/chrome/WindowControls'
import WorkspaceSidebarHost from '@renderer/components/chrome/WorkspaceSidebarHost'
import WorkspaceToolbar from '@renderer/components/chrome/WorkspaceToolbar'

import KnowledgePage from '@renderer/pages/KnowledgePage'
import LabPage from '@renderer/pages/LabPage'
import PaperReaderPage from '@renderer/pages/PaperReaderPage'

import styles from './App.module.css'

export default function App() {
  const currentView = useUIStateStore((s) => s.currentView)
  const isCurrentSidebarCollapsed = useUIStateStore((s) => s.isCurrentSidebarCollapsed())
  const toggleCurrentSidebar = useUIStateStore((s) => s.toggleCurrentSidebar)
  const loadConfigStatus = useUIStateStore((s) => s.loadConfigStatus)
  const paperReaderStore = usePaperReaderStore()

  const { isMac, isWindows, usesCustomWindowControls } = useMemo(() => getRuntimePlatform(), [])

  const [showSettings, setShowSettings] = useState(false)

  const isPaperView = currentView === 'paper'
  const isKnowledgeView = currentView === 'knowledge'

  const workspacePageClasses = [
    styles.workspacePage,
    `sm-workspace-page--${currentView}`,
    isCurrentSidebarCollapsed && styles.sidebarCollapsed,
    isMac && 'sm-workspace-page--mac',
    isWindows && styles.windows
  ]
    .filter(Boolean)
    .join(' ')

  // Initialize on mount
  useEffect(() => {
    const uiState = useUIStateStore.getState()
    const configStore = useConfigStore.getState()

    void uiState.initTheme()
    void loadConfigStatus()
    void configStore.loadConfig()
    paperReaderStore.loadPaperReaderPreferences()
  }, [loadConfigStatus, paperReaderStore])

  // Global link interceptor
  useEffect(() => {
    function handleGlobalLinkClick(event: MouseEvent): void {
      const target = event.target as HTMLElement
      const anchor = target.closest('a') as HTMLAnchorElement | null
      if (!anchor?.href) return

      try {
        const url = new URL(anchor.href)
        if (url.protocol === 'http:' || url.protocol === 'https:') {
          event.preventDefault()
          window.api.window.openExternal(anchor.href)
        }
      } catch {
        // Not a valid URL, ignore
      }
    }

    document.addEventListener('click', handleGlobalLinkClick, true)
    return () => {
      document.removeEventListener('click', handleGlobalLinkClick, true)
    }
  }, [])

  const openSettings = useCallback(() => setShowSettings(true), [])
  const closeSettings = useCallback(() => setShowSettings(false), [])

  return (
    <div className="sm-app">
      <NotificationCenter />

      <div className={`sm-shell sm-workspace-page ${workspacePageClasses}`}>
        <div className={styles.dragRegion} aria-hidden="true" />

        <div className={styles.chromeActions} aria-label="窗口快捷操作">
          <button
            className={`sm-icon-button ${styles.chromeButton}`}
            title="设置"
            aria-label="打开设置"
            onClick={openSettings}
          >
            <SvgIcon name="settings" size={14} />
          </button>

          {isPaperView && (
            <button
              className={`sm-icon-button ${styles.chromeButton}`}
              title={isCurrentSidebarCollapsed ? '展开侧边栏' : '折叠侧边栏'}
              aria-label={isCurrentSidebarCollapsed ? '展开侧边栏' : '折叠侧边栏'}
              onClick={toggleCurrentSidebar}
            >
              <SvgIcon name="sidebar-toggle" size={14} />
            </button>
          )}
        </div>

        {usesCustomWindowControls && (
          <div className={styles.winControls}>
            <WindowControls />
          </div>
        )}

        <WorkspaceSidebarHost />

        <div className="sm-workspace-main">
          <WorkspaceToolbar />

          <div className="sm-workspace-main__body sm-workspace-main__body--fill">
            {isPaperView && <PaperReaderPage key="paper" />}
            {isKnowledgeView && <KnowledgePage key="knowledge" />}
            {!isPaperView && !isKnowledgeView && <LabPage key="lab" />}
          </div>
        </div>
      </div>

      {showSettings && <SettingsModal onClose={closeSettings} />}
    </div>
  )
}
