// src/renderer/src/components/knowledge/file-manager/components/FileManagerHeader.vue
<script setup lang="ts">
/**
 * 文件管理模态框头部组件
 */
import SvgIcon from '@renderer/components/icons/SvgIcon.vue'
import styles from './FileManagerHeader.module.css'

const emit = defineEmits<{
  (e: 'close'): void
}>()
</script>

<template>
  <div :class="['sm-pane-header', styles['file-manager-header']]">
    <h2>文件管理</h2>
    <button class="sm-icon-button close-btn" @click="emit('close')">
      <SvgIcon name="close" :size="16" />
    </button>
  </div>
</template>

// src/renderer/src/components/knowledge/file-manager/components/FileManagerHeader.tsx
import SvgIcon from '@renderer/components/icons/SvgIcon'
import styles from './FileManagerHeader.module.css'

interface FileManagerHeaderProps {
  onClose: () => void
}

export default function FileManagerHeader({ onClose }: FileManagerHeaderProps) {
  return (
    <div className={`sm-pane-header ${styles['file-manager-header']}`}>
      <h2>文件管理</h2>
      <button className="sm-icon-button close-btn" onClick={onClose}>
        <SvgIcon name="close" size={16} />
      </button>
    </div>
  )
}
