// src/renderer/src/components/knowledge/file-manager/components/FileManagerToolbar.vue
<script setup lang="ts">
/**
 * 文件管理工具栏组件
 * 包含搜索框和文件统计
 */
import { useZustandStore } from '@renderer/composables/useZustandStore'
import { useFileStore } from '@renderer/stores'
import styles from './FileManagerToolbar.module.css'

const fileStore = useZustandStore(useFileStore)
</script>

<template>
  <div :class="styles['file-manager-toolbar']">
    <div :class="styles['toolbar-search']">
      <input
        :value="fileStore.searchQuery"
        type="text"
        :class="['sm-input', styles['search-input']]"
        placeholder="搜索文件..."
        @input="fileStore.searchFiles(($event.target as HTMLInputElement).value)"
      />
    </div>
    <div :class="styles['file-stats']">
      <span :class="styles['file-stats__label']">文件资源池</span>
      <span :class="styles['file-stats__count']">{{ fileStore.filteredFiles.length }} 个文件</span>
    </div>
  </div>
</template>

// src/renderer/src/components/knowledge/file-manager/components/FileManagerToolbar.tsx
import { useFileStore } from '@renderer/stores'
import styles from './FileManagerToolbar.module.css'

export default function FileManagerToolbar() {
  const searchQuery = useFileStore((s) => s.searchQuery)
  const searchFiles = useFileStore((s) => s.searchFiles)
  const filteredFiles = useFileStore((s) => s.filteredFiles())

  return (
    <div className={styles['file-manager-toolbar']}>
      <div className={styles['toolbar-search']}>
        <input
          value={searchQuery}
          type="text"
          className={`sm-input ${styles['search-input']}`}
          placeholder="搜索文件..."
          onChange={(e) => searchFiles(e.target.value)}
        />
      </div>
      <div className={styles['file-stats']}>
        <span className={styles['file-stats__label']}>文件资源池</span>
        <span className={styles['file-stats__count']}>{filteredFiles.length} 个文件</span>
      </div>
    </div>
  )
}
