// src/renderer/src/components/lab/LabMainContent.tsx
import { useState, useEffect, useMemo } from 'react'
import { useContainerStore, useLabStore } from '@renderer/stores'
import { useUIStateStore } from '@renderer/stores/uiStateStore'
import { useNotification } from '@renderer/composables/useNotification'
import OrphanLabAlert from './OrphanLabAlert'
import SshReconnectPrompt from './SshReconnectPrompt'
import TabNavigation from './lab-detail/TabNavigation'
import LabDetailEmptyState from './LabDetailEmptyState'
import LabStatsTab from './LabStatsTab'
import LabTerminalTab from './LabTerminalTab'
import LabLogsTab from './LabLogsTab'
import { useLabAutoRefresh } from './hooks/useLabAutoRefresh'
import type { LabData, DockerStatus } from '@renderer/types/lab'
import styles from './LabMainContent.module.css'

interface LabMainContentProps {
  currentLab: LabData | null
  dockerStatus?: DockerStatus | null
}

export default function LabMainContent({ currentLab, dockerStatus }: LabMainContentProps) {
  const containerStore = useContainerStore()
  const labStore = useLabStore()
  const notify = useNotification()

  const selectedContainer = useContainerStore((s) => s.selectedContainer) || null
  const containerStats = useContainerStore((s) => s.containerStats) || null
  const storeLoading = useContainerStore((s) => s.isLoading) || false
  const labDetailTab = useUIStateStore((s) => s.labDetailTab)
  const setLabDetailTab = useUIStateStore((s) => s.setLabDetailTab)

  const isOrphan = currentLab?.isOrphan || false
  const isLabFrontend = !!currentLab?.frontend
  const isSshLab = currentLab?.backendType === 'ssh'
  const isDockerLab = !!currentLab && !isSshLab
  const isDockerReady = dockerStatus?.available ?? false
  const showDockerReadOnlyState = isDockerLab && dockerStatus?.available === false
  const isSshConnected = currentLab?.status === 'running'

  const showFrontendRecoveryBanner = isLabFrontend && currentLab?.status === 'error' && !isOrphan

  const frontendRecoveryMessage = useMemo(() => {
    const frontend = currentLab?.frontend
    if (!frontend) return ''
    return (
      frontend.bootstrapError || '前端服务尚未恢复，请重试初始化；如果运行容器已损坏，可直接重建。'
    )
  }, [currentLab?.frontend])

  const [isStartingContainer, setIsStartingContainer] = useState(false)
  const [isStoppingContainer, setIsStoppingContainer] = useState(false)
  const [isRestartingContainer, setIsRestartingContainer] = useState(false)
  const [isRetryingFrontend, setIsRetryingFrontend] = useState(false)
  const [isRebuildingFrontend, setIsRebuildingFrontend] = useState(false)
  const [isConnectingSsh, setIsConnectingSsh] = useState(false)
  const [sshReconnectPassword, setSshReconnectPassword] = useState('')

  const autoRefresh = useLabAutoRefresh({
    currentLab,
    selectedContainer,
    labDetailTab,
    isOrphan,
    isLabFrontend
  })

  useEffect(() => {
    setSshReconnectPassword('')
  }, [currentLab?.labId])

  useEffect(() => {
    if (isSshLab && labDetailTab === 'logs') {
      setLabDetailTab('stats')
    }
  }, [isSshLab, labDetailTab, setLabDetailTab])

  // 监听 SSH 连接状态
  useEffect(() => {
    const removeListener = window.api.ssh?.onConnectionStatus((event) => {
      if (event.labId === currentLab?.labId) {
        labStore.loadLab(event.labId, true, { silent: true })
      }
    })
    return () => {
      removeListener?.()
    }
  }, [currentLab?.labId, labStore])

  async function handleContainerStart(): Promise<void> {
    if (!isDockerReady) return
    setIsStartingContainer(true)
    try {
      if (selectedContainer?.id) await containerStore.startContainer(selectedContainer.id)
    } finally {
      setIsStartingContainer(false)
    }
  }

  async function handleContainerStop(): Promise<void> {
    if (!isDockerReady) return
    setIsStoppingContainer(true)
    try {
      if (selectedContainer?.id) await containerStore.stopContainer(selectedContainer.id)
    } finally {
      setIsStoppingContainer(false)
    }
  }

  async function handleContainerRestart(): Promise<void> {
    if (!isDockerReady) return
    setIsRestartingContainer(true)
    try {
      if (selectedContainer?.id) await containerStore.restartContainer(selectedContainer.id)
    } finally {
      setIsRestartingContainer(false)
    }
  }

  async function handleRetryFrontend(): Promise<void> {
    if (!currentLab?.labId || isRetryingFrontend) return
    setIsRetryingFrontend(true)
    try {
      await labStore.retryFrontendInitialization(currentLab.labId)
    } finally {
      setIsRetryingFrontend(false)
    }
  }

  async function handleRebuildFrontend(): Promise<void> {
    if (!currentLab?.labId || isRebuildingFrontend) return
    setIsRebuildingFrontend(true)
    try {
      await labStore.rebuildFrontendRuntime(currentLab.labId)
    } finally {
      setIsRebuildingFrontend(false)
    }
  }

  async function handleSshConnect(): Promise<void> {
    const labId = currentLab?.labId
    const ssh = currentLab?.ssh
    if (!labId || !ssh) return

    if (ssh.authType === 'password' && !sshReconnectPassword.trim()) {
      notify.warning('请输入 SSH 密码', '密码认证的连接需要重新输入密码后再连接', { source: 'lab' })
      return
    }

    setIsConnectingSsh(true)
    try {
      const connected = await labStore.connectSsh(labId, {
        host: ssh.host,
        port: ssh.port,
        username: ssh.username,
        authType: ssh.authType,
        password: ssh.authType === 'password' ? sshReconnectPassword : undefined,
        keyName: ssh.keyName
      })
      if (connected) {
        setSshReconnectPassword('')
        await labStore.loadLab(labId, true)
      }
    } finally {
      setIsConnectingSsh(false)
    }
  }

  async function handleCleanupOrphan(labId: string): Promise<void> {
    await labStore.handleDeleteLab(labId)
  }

  function handleDeleteLab(): void {
    if (currentLab) labStore.handleDeleteLab(currentLab.labId)
  }

  function formatDateTime(value?: string): string {
    if (!value) {
      return '-'
    }

    return new Date(value).toLocaleString('zh-CN', {
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit'
    })
  }

  async function handleRefreshStats(): Promise<void> {
    await autoRefresh.handleRefreshStats()
  }

  const hasLab = !!currentLab
  const labCreationTypeLabel = useMemo(() => {
    const labelMap: Record<string, string> = {
      existing: '已有容器',
      compose: 'Docker Compose',
      dockerfile: 'Dockerfile',
      ssh: 'SSH 远程服务器'
    }
    return currentLab ? labelMap[currentLab.creationType] || '' : ''
  }, [currentLab])

  return (
    <main className={styles['lab-main-content']}>
      {!hasLab ? (
        <div className={styles['lab-empty-state']}>
          <div className={`sm-empty ${styles['lab-empty-card']}`}>
            <h2>{isDockerReady ? '选择一个实验室开始' : '通过 SSH 连接远程服务器'}</h2>
            <p>
              {isDockerReady
                ? '从左侧接管现有环境，或创建一个实验室以进入容器监控、终端和日志工作流。'
                : '从左侧发起 SSH 连接，填写远程主机信息后进入终端和监控工作流。'}
            </p>
          </div>
        </div>
      ) : (
        <>
          <header className={styles['workspace-header']}>
            <div className={styles['workspace-header__copy']}>
              <div className={styles['workspace-header__headline']}>
                <div className={styles['workspace-header__titles']}>
                  <h1>{currentLab.name}</h1>
                  <div className={styles['workspace-header__badges']}>
                    <span className="sm-badge">{labCreationTypeLabel}</span>
                    {!isSshLab && (
                      <span className="sm-badge">
                        {currentLab.containerIds?.length || 0} 个容器
                      </span>
                    )}
                    {isSshLab && currentLab.ssh?.authType && (
                      <span className="sm-badge">
                        {currentLab.ssh.authType === 'password' ? '密码认证' : '密钥认证'}
                      </span>
                    )}
                    <span className={`sm-badge ${styles[`status-${currentLab.status}`]}`}>
                      {isSshLab
                        ? {
                            creating: '连接中',
                            running: '已连接',
                            stopped: '未连接',
                            error: '连接失败'
                          }[currentLab.status]
                        : {
                            creating: '创建中',
                            running: '运行中',
                            stopped: '已停止',
                            error: '异常'
                          }[currentLab.status]}
                    </span>
                  </div>
                </div>
              </div>
              <div className={styles['workspace-header__submeta']}>
                <span>
                  实验室 ID <code>{currentLab.labId}</code>
                </span>
                <span>最近更新 {formatDateTime(currentLab.updatedAt)}</span>
              </div>
            </div>
            <div className={styles['workspace-header__actions']}>
              {isSshLab && currentLab && !isSshConnected && (
                <SshReconnectPrompt
                  password={sshReconnectPassword}
                  lab={currentLab}
                  connecting={isConnectingSsh}
                  onUpdatePassword={setSshReconnectPassword}
                  onConnect={handleSshConnect}
                />
              )}
              {!showDockerReadOnlyState && <TabNavigation visible={hasLab} showLogs={!isSshLab} />}
            </div>
          </header>

          <div className={styles['content-body']}>
            {showDockerReadOnlyState ? (
              <div className={styles['tab-content']}>
                <LabDetailEmptyState
                  title="实验室记录已保留"
                  message="当前仅展示这个实验室的历史信息，不提供本地运行环境操作。远程 SSH 实验室仍可正常连接和使用。"
                />
              </div>
            ) : (
              <>
                <OrphanLabAlert
                  visible={isOrphan}
                  lab={currentLab}
                  isReloading={isRebuildingFrontend}
                  canRecover={isLabFrontend}
                  recoverLabel={isLabFrontend ? '重建运行容器' : '重新关联容器'}
                  onRecover={handleRebuildFrontend}
                  onCleanup={handleCleanupOrphan}
                />

                {showFrontendRecoveryBanner && (
                  <div className={styles['frontend-recovery-banner']}>
                    <div className={styles['frontend-recovery-copy']}>
                      <span className={styles['frontend-recovery-copy__eyebrow']}>恢复提示</span>
                      <h3>前端服务未就绪</h3>
                      <p>{frontendRecoveryMessage}</p>
                    </div>
                    <div className={styles['frontend-recovery-actions']}>
                      <button
                        className="sm-button sm-button--secondary"
                        disabled={isRetryingFrontend || isRebuildingFrontend}
                        onClick={handleRetryFrontend}
                      >
                        {isRetryingFrontend ? '重试中...' : '重试初始化'}
                      </button>
                      <button
                        className="sm-button sm-button--primary"
                        disabled={isRetryingFrontend || isRebuildingFrontend}
                        onClick={handleRebuildFrontend}
                      >
                        {isRebuildingFrontend ? '重建中...' : '重建运行容器'}
                      </button>
                    </div>
                  </div>
                )}

                <div
                  style={{ display: labDetailTab === 'stats' ? 'block' : 'none' }}
                  className={styles['tab-content']}
                >
                  <LabStatsTab
                    isSshLab={isSshLab}
                    isDockerReady={isDockerReady}
                    isStatsTabActive={labDetailTab === 'stats'}
                    currentLab={currentLab}
                    selectedContainer={selectedContainer}
                    containerStats={containerStats}
                    storeLoading={storeLoading}
                    isManualRefreshingStats={autoRefresh.isManualRefreshingStats}
                    startingContainer={isStartingContainer}
                    stoppingContainer={isStoppingContainer}
                    restartingContainer={isRestartingContainer}
                    creationType={currentLab.creationType}
                    labName={currentLab.name}
                    onStart={handleContainerStart}
                    onStop={handleContainerStop}
                    onRestart={handleContainerRestart}
                    onRemove={handleDeleteLab}
                    onOpenTerminal={() => setLabDetailTab('terminal')}
                    onViewLogs={() => setLabDetailTab('logs')}
                    onRefreshStats={() => void handleRefreshStats()}
                  />
                </div>

                <div
                  style={{ display: labDetailTab === 'terminal' ? 'block' : 'none' }}
                  className={styles['tab-content']}
                >
                  <LabTerminalTab
                    isSshLab={isSshLab}
                    isDockerReady={isDockerReady}
                    currentLab={currentLab}
                    selectedContainer={selectedContainer}
                    isSshConnected={isSshConnected}
                    labDetailTab={labDetailTab as string}
                  />
                </div>

                {!isSshLab && (
                  <div
                    style={{ display: labDetailTab === 'logs' ? 'block' : 'none' }}
                    className={styles['tab-content']}
                  >
                    <LabLogsTab
                      isDockerReady={isDockerReady}
                      selectedContainerId={selectedContainer?.id}
                    />
                  </div>
                )}
              </>
            )}
          </div>
        </>
      )}
    </main>
  )
}

// src/renderer/src/components/sandbox/LabMainContent.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue'
import { storeToRefs } from 'pinia'
import { useContainerStore, useUIStateStore, useSandboxStore } from '@renderer/stores'
import { useNotification } from '@renderer/composables/useNotification'
import TerminalPanel from './TerminalPanel.vue'
import ContainerLogs from './ContainerLogs.vue'
import ContainerDetailPanel from './ContainerDetailPanel.vue'
import OrphanLabAlert from './OrphanLabAlert.vue'
import { TabNavigation } from './sandbox-detail'
import {
  useContainerLogs as useContainerLogsComposable,
  useContainerActions
} from './sandbox-detail'
import type { ContainerDetails, SandboxData } from '@shared/types/sandbox'

const SANDBOX_AUTO_REFRESH_INTERVAL = 3000

// ==================== Props & Emits ====================

const props = defineProps<{
  currentSandbox: SandboxData | null
}>()

// ==================== Store ====================

const containerStore = useContainerStore()
const uiStateStore = useUIStateStore()
const sandboxStore = useSandboxStore()
const notify = useNotification()

const {
  selectedContainer,
  containerStats,
  terminalLogs,
  isLoading: storeLoading
} = storeToRefs(containerStore)

const { sandboxDetailTab } = storeToRefs(uiStateStore)

const sandboxRefreshTimerId = ref<number | null>(null)
const isRefreshingStats = ref(false)
const isManualRefreshingStats = ref(false)
const isRefreshingSandboxState = ref(false)
const isRetryingFrontend = ref(false)
const isRebuildingFrontend = ref(false)
const isValidatingFrontendBuild = ref(false)

// 容器生命周期操作加载状态
const isStartingContainer = ref(false)
const isStoppingContainer = ref(false)
const isRestartingContainer = ref(false)

// ==================== Computed ====================

const hasSandbox = computed(() => !!props.currentSandbox)

const isOrphan = computed(() => props.currentSandbox?.isOrphan || false)
const isFrontendSandbox = computed(() => !!props.currentSandbox?.frontend)
const showFrontendRecoveryBanner = computed(
  () => isFrontendSandbox.value && props.currentSandbox?.status === 'error' && !isOrphan.value
)
const frontendRecoveryMessage = computed(() => {
  const frontend = props.currentSandbox?.frontend
  if (!frontend) {
    return ''
  }

  if (frontend.bootstrapError) {
    return frontend.bootstrapError
  }

  return '前端服务尚未恢复，请重试初始化；如果运行容器已损坏，可直接重建。'
})
const orphanRecoverLabel = computed(() =>
  isFrontendSandbox.value ? '重建运行容器' : '重新关联容器'
)

const sandboxCreationTypeLabel = computed(() => {
  const labelMap: Record<SandboxData['creationType'], string> = {
    existing: '已有容器',
    compose: 'Docker Compose',
    dockerfile: 'Dockerfile'
  }

  return props.currentSandbox ? labelMap[props.currentSandbox.creationType] : ''
})

const sandboxStatusLabel = computed(() => {
  const labelMap: Record<SandboxData['status'], string> = {
    creating: '创建中',
    running: '运行中',
    stopped: '已停止',
    error: '异常'
  }

  return props.currentSandbox ? labelMap[props.currentSandbox.status] : ''
})

const sandboxStatusClass = computed(() => {
  return props.currentSandbox ? `status-${props.currentSandbox.status}` : ''
})

const sandboxContainerCount = computed(() => props.currentSandbox?.containerIds.length || 0)

// 用于 composables 的响应式引用
const currentSandboxRef = computed(() => props.currentSandbox)
const selectedContainerRef = computed(() => selectedContainer.value)

// ==================== Composables ====================

// 容器日志
const { containerLogs, logsLoading, loadContainerLogs, handleRefreshLogs, handleExportLogs } =
  useContainerLogsComposable(selectedContainerRef)

// 容器操作
const {
  handleContainerStart: _handleContainerStart,
  handleContainerStop: _handleContainerStop,
  handleContainerRestart: _handleContainerRestart,
  handleExecuteCommand,
  handleClearTerminal
} = useContainerActions(currentSandboxRef, selectedContainerRef)

// 包装容器操作函数，添加加载状态管理
async function handleContainerStart(): Promise<void> {
  isStartingContainer.value = true
  try {
    await _handleContainerStart()
  } finally {
    isStartingContainer.value = false
  }
}

async function handleContainerStop(): Promise<void> {
  isStoppingContainer.value = true
  try {
    await _handleContainerStop()
  } finally {
    isStoppingContainer.value = false
  }
}

async function handleContainerRestart(): Promise<void> {
  isRestartingContainer.value = true
  try {
    await _handleContainerRestart()
  } finally {
    isRestartingContainer.value = false
  }
}

// ==================== Watch ====================

async function refreshStats(options?: { silent?: boolean }): Promise<void> {
  const containerId = selectedContainer.value?.id
  if (!containerId || isRefreshingStats.value) {
    return
  }

  isRefreshingStats.value = true
  try {
    await containerStore.loadContainerStats(containerId, options)
  } finally {
    isRefreshingStats.value = false
  }
}

function shouldKeepSandboxAutoRefresh(container?: ContainerDetails | null): boolean {
  const currentContainer = container || selectedContainer.value
  if (!props.currentSandbox || !currentContainer) {
    return false
  }

  if (props.currentSandbox.frontend && !isOrphan.value) {
    return true
  }

  return sandboxDetailTab.value === 'stats' && currentContainer.state === 'running'
}

async function validateFrontendBuildOnRefresh(): Promise<void> {
  const sandboxId = props.currentSandbox?.sandboxId
  const frontend = props.currentSandbox?.frontend

  if (
    !sandboxId ||
    !frontend ||
    isOrphan.value ||
    frontend.buildValidated ||
    props.currentSandbox?.status !== 'running' ||
    isValidatingFrontendBuild.value
  ) {
    return
  }

  isValidatingFrontendBuild.value = true
  try {
    await sandboxStore.validateFrontendBuild(sandboxId, {
      silent: true
    })
  } finally {
    isValidatingFrontendBuild.value = false
  }
}

async function runSandboxRefreshCycle(options?: { silentStats?: boolean }): Promise<void> {
  const sandboxId = props.currentSandbox?.sandboxId
  if (!sandboxId || isRefreshingSandboxState.value) {
    return
  }

  isRefreshingSandboxState.value = true
  try {
    await sandboxStore.loadSandbox(sandboxId, true, {
      silent: true
    })

    const container = selectedContainer.value
    if (!container) {
      containerStore.clearContainerStats()
      return
    }

    if (sandboxDetailTab.value === 'stats' && container.state === 'running') {
      await refreshStats({
        silent: options?.silentStats
      })
    } else if (container.state !== 'running') {
      containerStore.clearContainerStats()
    }

    await validateFrontendBuildOnRefresh()
  } finally {
    isRefreshingSandboxState.value = false
  }
}

function stopSandboxAutoRefresh(): void {
  if (sandboxRefreshTimerId.value !== null) {
    clearInterval(sandboxRefreshTimerId.value)
    sandboxRefreshTimerId.value = null
  }
}

function startSandboxAutoRefresh(): void {
  stopSandboxAutoRefresh()

  if (!shouldKeepSandboxAutoRefresh()) {
    return
  }

  sandboxRefreshTimerId.value = window.setInterval(() => {
    if (!shouldKeepSandboxAutoRefresh()) {
      stopSandboxAutoRefresh()
      return
    }

    void runSandboxRefreshCycle({ silentStats: true })
  }, SANDBOX_AUTO_REFRESH_INTERVAL)
}

async function syncSandboxAutoRefresh(): Promise<void> {
  const container = selectedContainer.value
  if (!container || !props.currentSandbox) {
    stopSandboxAutoRefresh()
    return
  }

  await runSandboxRefreshCycle()

  if (
    shouldKeepSandboxAutoRefresh(selectedContainer.value) &&
    selectedContainer.value?.id === container.id
  ) {
    startSandboxAutoRefresh()
  } else {
    stopSandboxAutoRefresh()
  }
}

async function handleRefreshStats(): Promise<void> {
  if (isManualRefreshingStats.value) {
    return
  }

  isManualRefreshingStats.value = true
  try {
    await refreshStats()
  } finally {
    isManualRefreshingStats.value = false
  }
}

// Tab 切换时加载数据
watch(
  () => sandboxDetailTab.value,
  async (tab) => {
    if (tab === 'logs' && selectedContainer.value) {
      await loadContainerLogs()
    }

    await syncSandboxAutoRefresh()
  },
  { immediate: true }
)

// 容器变化时重新加载数据
watch(
  () => selectedContainer.value?.id,
  async (newId, oldId) => {
    if (newId !== oldId) {
      containerStore.clearContainerStats()
    }

    if (newId) {
      if (sandboxDetailTab.value === 'logs') {
        await loadContainerLogs()
      }

      await syncSandboxAutoRefresh()
      return
    }

    stopSandboxAutoRefresh()
  }
)

watch(
  () => selectedContainer.value?.state,
  async () => {
    await syncSandboxAutoRefresh()
  }
)

watch(
  () => [
    props.currentSandbox?.sandboxId,
    props.currentSandbox?.status,
    props.currentSandbox?.frontend?.buildValidated
  ],
  async () => {
    await syncSandboxAutoRefresh()
  }
)

onBeforeUnmount(() => {
  stopSandboxAutoRefresh()
})

// ==================== Methods ====================

function setDetailTab(tab: 'stats' | 'terminal' | 'logs'): void {
  uiStateStore.setSandboxDetailTab(tab)
}

async function handleOpenTerminal(): Promise<void> {
  setDetailTab('terminal')
}

async function handleViewLogs(): Promise<void> {
  setDetailTab('logs')
}

/**
 * 删除实验室 - 弹出确认对话框
 */
function handleDeleteSandbox(): void {
  if (props.currentSandbox) {
    sandboxStore.handleDeleteSandbox(props.currentSandbox.sandboxId)
  }
}

// ==================== 孤儿实验室操作 ====================

async function handleRecoverOrphan(): Promise<void> {
  if (props.currentSandbox?.frontend) {
    await handleRebuildFrontendRuntime()
    return
  }

  notify.warning(
    '暂不支持自动恢复',
    '当前只有前端实验室支持基于持久化工作区自动重建容器。其他类型请手动恢复容器后重新关联。',
    { source: 'sandbox' }
  )
}

async function handleCleanupOrphan(sandboxId: string): Promise<void> {
  await sandboxStore.handleDeleteSandbox(sandboxId)
}

async function handleRetryFrontendInitialization(): Promise<void> {
  const sandboxId = props.currentSandbox?.sandboxId
  if (!sandboxId || isRetryingFrontend.value) {
    return
  }

  isRetryingFrontend.value = true
  try {
    await sandboxStore.retryFrontendInitialization(sandboxId)
  } finally {
    isRetryingFrontend.value = false
  }
}

async function handleRebuildFrontendRuntime(): Promise<void> {
  const sandboxId = props.currentSandbox?.sandboxId
  if (!sandboxId || isRebuildingFrontend.value) {
    return
  }

  isRebuildingFrontend.value = true
  try {
    await sandboxStore.rebuildFrontendRuntime(sandboxId)
  } finally {
    isRebuildingFrontend.value = false
  }
}

function handleCloseOrphanAlert(): void {
  window.api.logger.info('[SandboxMainContent] 用户关闭孤儿实验室提示')
}

function formatDateTime(value?: string): string {
  if (!value) {
    return '-'
  }

  return new Date(value).toLocaleString('zh-CN', {
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit'
  })
}
</script>

<template>
  <main class="lab-main-content">
    <div v-if="!hasSandbox" class="lab-empty-state">
      <div class="sm-empty lab-empty-card">
        <h2>选择一个实验室开始</h2>
        <p>从左侧接管现有环境，或创建一个实验室以进入容器监控、终端和日志工作流。</p>
      </div>
    </div>

    <template v-else>
      <header class="workspace-header">
        <div class="workspace-header__copy">
          <div class="workspace-header__headline">
            <div class="workspace-header__titles">
              <h1>{{ currentSandbox?.name }}</h1>
              <div class="workspace-header__badges">
                <span class="sm-badge">{{ sandboxCreationTypeLabel }}</span>
                <span class="sm-badge">{{ sandboxContainerCount }} 个容器</span>
                <span class="sm-badge" :class="sandboxStatusClass">{{ sandboxStatusLabel }}</span>
              </div>
            </div>
          </div>

          <div class="workspace-header__submeta">
            <span>
              实验室 ID
              <code>{{ currentSandbox?.sandboxId }}</code>
            </span>
            <span>最近更新 {{ formatDateTime(currentSandbox?.updatedAt) }}</span>
          </div>
        </div>

        <TabNavigation :visible="hasSandbox" />
      </header>

      <div class="content-body">
        <OrphanLabAlert
          :visible="isOrphan"
          :sandbox="currentSandbox"
          :is-reloading="isRebuildingFrontend"
          :can-recover="isFrontendSandbox"
          :recover-label="orphanRecoverLabel"
          @recover="handleRecoverOrphan"
          @cleanup="handleCleanupOrphan"
          @close="handleCloseOrphanAlert"
        />

        <div v-if="showFrontendRecoveryBanner" class="frontend-recovery-banner">
          <div class="frontend-recovery-copy">
            <span class="frontend-recovery-copy__eyebrow">恢复提示</span>
            <h3>前端服务未就绪</h3>
            <p>{{ frontendRecoveryMessage }}</p>
          </div>
          <div class="frontend-recovery-actions">
            <button
              class="sm-button sm-button--secondary"
              :disabled="isRetryingFrontend || isRebuildingFrontend"
              @click="handleRetryFrontendInitialization"
            >
              {{ isRetryingFrontend ? '重试中...' : '重试初始化' }}
            </button>
            <button
              class="sm-button sm-button--primary"
              :disabled="isRetryingFrontend || isRebuildingFrontend"
              @click="handleRebuildFrontendRuntime"
            >
              {{ isRebuildingFrontend ? '重建中...' : '重建运行容器' }}
            </button>
          </div>
        </div>

        <!-- 监控 Tab -->
        <div v-if="sandboxDetailTab === 'stats'" class="tab-content">
          <div v-if="!selectedContainer" class="detail-empty-state">
            <div class="sm-empty detail-empty-card">
              <h2>请先选择一个容器</h2>
              <p>选中主容器后，这里会显示运行指标、端口映射和环境细节。</p>
            </div>
          </div>
          <ContainerDetailPanel
            v-else
            :container="selectedContainer"
            :stats="containerStats"
            :loading="storeLoading"
            :refreshing-stats="isManualRefreshingStats"
            :creation-type="currentSandbox?.creationType"
            :sandbox-name="currentSandbox?.name"
            :starting-container="isStartingContainer"
            :stopping-container="isStoppingContainer"
            :restarting-container="isRestartingContainer"
            @start="handleContainerStart"
            @stop="handleContainerStop"
            @restart="handleContainerRestart"
            @remove="handleDeleteSandbox"
            @open-terminal="handleOpenTerminal"
            @view-logs="handleViewLogs"
            @refresh-stats="handleRefreshStats"
          />
        </div>

        <!-- 终端 Tab -->
        <div v-else-if="sandboxDetailTab === 'terminal'" class="tab-content">
          <div v-if="!selectedContainer" class="detail-empty-state">
            <div class="sm-empty detail-empty-card">
              <h2>终端尚未绑定容器</h2>
              <p>选中目标容器后，可在这里执行临时命令、定位问题并确认运行环境。</p>
            </div>
          </div>
          <TerminalPanel
            v-else
            :container-id="selectedContainer.id"
            :container-name="selectedContainer.names[0]?.replace(/^\//, '') || '未命名'"
            :logs="terminalLogs"
            :loading="storeLoading"
            @execute="handleExecuteCommand"
            @clear="handleClearTerminal"
          />
        </div>

        <!-- 日志 Tab -->
        <div v-else-if="sandboxDetailTab === 'logs'" class="tab-content">
          <div v-if="!selectedContainer" class="detail-empty-state">
            <div class="sm-empty detail-empty-card">
              <h2>日志尚未绑定容器</h2>
              <p>选中目标容器后，可在这里检索输出、导出日志并追踪最近的运行记录。</p>
            </div>
          </div>
          <ContainerLogs
            v-else
            :container-id="selectedContainer.id"
            :container-name="selectedContainer.names[0]?.replace(/^\//, '') || '未命名'"
            :logs="containerLogs"
            :loading="logsLoading"
            @refresh="handleRefreshLogs"
            @export="handleExportLogs"
          />
        </div>
      </div>
    </template>
  </main>
</template>

<style scoped>
.lab-main-content {
  flex: 1;
  min-width: 0;
  min-height: 0;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.lab-empty-state {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: var(--sm-space-6);
}

.lab-empty-card {
  width: min(520px, 100%);
  background: var(--sm-color-surface-2);
  border-style: solid;
}
.lab-empty-card h2 {
  margin: 0;
  font-size: 18px;
  color: var(--sm-color-text-primary);
}

.lab-empty-card p {
  margin: 0;
  max-width: 420px;
  line-height: 1.6;
}

.workspace-header {
  display: flex;
  align-items: flex-end;
  justify-content: space-between;
  gap: var(--sm-space-5);
  padding: var(--sm-space-6);
}

.workspace-header__copy {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: var(--sm-space-3);
}

.workspace-header__headline {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: var(--sm-space-4);
}

.workspace-header__titles {
  display: flex;
  flex-direction: column;
  gap: var(--sm-space-2);
  flex: 1;
  min-width: 0;
}

.workspace-header__titles h1 {
  margin: 0;
  font-size: 28px;
  line-height: 1.2;
  color: var(--sm-color-text-primary);
}

.workspace-header__badges {
  display: flex;
  flex-wrap: wrap;
  gap: var(--sm-space-2);
  justify-content: flex-start;
}

.workspace-header__submeta {
  display: flex;
  flex-wrap: wrap;
  gap: var(--sm-space-4);
  font-size: 12px;
  color: var(--sm-color-text-secondary);
}

.workspace-header__submeta code {
  display: inline-block;
  margin-left: 6px;
  padding: 2px 6px;
  border: 1px solid var(--sm-color-border-subtle);
  border-radius: 999px;
  background: var(--sm-color-bg-embedded);
  color: var(--sm-color-text-primary);
  font-family: var(--sm-font-mono);
  font-size: 11px;
}

.workspace-header__badges .status-running {
  border-color: rgba(127, 176, 138, 0.28);
  background: rgba(127, 176, 138, 0.08);
  color: #7fb08a;
}

.workspace-header__badges .status-creating {
  border-color: var(--sm-color-accent-28);
  background: var(--sm-color-accent-08);
  color: var(--sm-color-accent-hover);
}

.workspace-header__badges .status-stopped {
  border-color: var(--sm-color-border-default);
  background: rgba(255, 255, 255, 0.04);
  color: var(--sm-color-text-secondary);
}

.workspace-header__badges .status-error {
  border-color: rgba(199, 120, 120, 0.28);
  background: rgba(199, 120, 120, 0.08);
  color: #c77878;
}

.content-body {
  flex: 1;
  min-height: 0;
  display: flex;
  flex-direction: column;
  gap: var(--sm-space-4);
  overflow: hidden;
  padding: 0 var(--sm-space-6) var(--sm-space-6);
  position: relative;
}

.tab-content {
  flex: 1;
  min-height: 0;
  overflow: hidden;
}

.frontend-recovery-banner {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: var(--sm-space-4);
  padding: var(--sm-space-4);
  border: 1px solid rgba(210, 153, 34, 0.35);
  border-radius: var(--sm-radius-md);
  background: rgba(210, 153, 34, 0.08);
}

.frontend-recovery-copy {
  display: flex;
  flex-direction: column;
  gap: var(--sm-space-2);
}

.frontend-recovery-copy__eyebrow {
  font-size: 11px;
  font-weight: 600;
  line-height: 1;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: #c5a165;
}

.frontend-recovery-copy h3 {
  margin: 0;
  font-size: 14px;
  color: var(--sm-color-text-primary);
}

.frontend-recovery-copy p {
  margin: 0;
  font-size: 13px;
  line-height: 1.5;
  color: var(--sm-color-text-secondary);
}

.frontend-recovery-actions {
  display: flex;
  flex-wrap: wrap;
  gap: var(--sm-space-2);
  flex-shrink: 0;
}

.detail-empty-state {
  display: flex;
  height: 100%;
  align-items: center;
  justify-content: center;
}

.detail-empty-card {
  width: min(460px, 100%);
  background: var(--sm-color-surface-2);
  border-style: solid;
}

.detail-empty-card h2 {
  margin: 0;
  font-size: 17px;
  color: var(--sm-color-text-primary);
}

.detail-empty-card p {
  margin: 0;
  max-width: 380px;
  line-height: 1.6;
}

@media (max-width: 920px) {
  .workspace-header,
  .workspace-header__headline,
  .frontend-recovery-banner {
    flex-direction: column;
  }
}

@media (max-width: 720px) {
  .workspace-header {
    padding: var(--sm-space-5);
  }

  .content-body {
    padding: 0 var(--sm-space-5) var(--sm-space-5);
  }
}
</style>
