// src/renderer/src/components/SettingsModal.tsx
import { useState, useEffect, useRef, useCallback } from 'react'
import { useConfigStore } from '@renderer/stores'
import ThemeSettings from './settings/ThemeSettings'
import ModelSettings from './settings/ModelSettings'
import MCPSettings from './settings/MCPSettings'
import EmbeddingModelSettings from './settings/EmbeddingModelSettings'
import KnowledgeMCPSettings from './settings/KnowledgeMCPSettings'
import PaperReaderSettings from './settings/PaperReaderSettings'
import ToolStatsSettings from './settings/ToolStatsSettings'
import UpdateSettings from './settings/UpdateSettings'
import styles from './SettingsModal.module.css'

type SettingsTabKey =
  | 'model'
  | 'embedding'
  | 'paperReader'
  | 'mcp'
  | 'knowledge'
  | 'toolStats'
  | 'theme'
  | 'update'

interface SettingsModalProps {
  onClose: () => void
  onMcpUpdated?: () => void
}

const settingsTabs: Array<{ id: SettingsTabKey; label: string; description: string }> = [
  { id: 'model', label: '对话模型配置', description: '管理默认模型、接口地址与上下文参数。' },
  { id: 'embedding', label: '嵌入模型配置', description: '维护知识检索所需的向量模型清单。' },
  { id: 'paperReader', label: '论文阅读配置', description: '配置论文 OCR 识别服务与翻译模型。' },
  { id: 'mcp', label: 'MCP 服务', description: '连接外部工具链并管理服务传输方式。' },
  { id: 'knowledge', label: '知识库服务', description: '管理知识库 MCP 对外服务与共享说明。' },
  { id: 'toolStats', label: '工具调用统计', description: '查看工具调用量、成功率和耗时分布。' },
  { id: 'theme', label: '主题设置', description: '切换当前工作主题并查看主题预览。' },
  { id: 'update', label: '升级版本', description: '检查应用更新并查看版本历史。' }
]

export default function SettingsModal({ onClose, onMcpUpdated }: SettingsModalProps) {
  const [activeTab, setActiveTab] = useState<SettingsTabKey>('model')

  const configLoading = useConfigStore((s) => s.loading)
  const configState = useConfigStore((s) => ({
    themeConfig: s.themeConfig
  }))
  const updateThemeConfig = useConfigStore((s) => s.updateThemeConfig)
  const loadConfig = useConfigStore((s) => s.loadConfig)

  const navRef = useRef<HTMLElement>(null)

  // Load config on mount
  useEffect(() => {
    loadConfig()
  }, [loadConfig])

  // Keyboard handler
  useEffect(() => {
    function handleKeyDown(event: KeyboardEvent): void {
      if (event.key === 'Escape') {
        onClose()
      }
    }
    document.addEventListener('keydown', handleKeyDown)
    return () => {
      document.removeEventListener('keydown', handleKeyDown)
    }
  }, [onClose])

  // Scroll handling for nav
  const handleNavScroll = useCallback(() => {
    const el = navRef.current
    if (!el) return
    el.classList.add('is-scrolling')
    // Remove after 800ms
    setTimeout(() => {
      el?.classList.remove('is-scrolling')
    }, 800)
  }, [])

  function handleThemeChange(themeId: string): void {
    window.api.logger.info('[SettingsModal] 主题已切换', { themeId })
  }

  return (
    <div className={['sm-modal__overlay', styles['settings-overlay']].join(' ')} onClick={(e) => { if (e.target === e.currentTarget) onClose() }}>
      <div className={['sm-modal__surface', styles['settings-container']].join(' ')}>
        <div className={['sm-pane-header', styles['settings-header']].join(' ')}>
          <div className={styles['settings-header__info']}>
            <h2 className={styles['settings-title']}>设置中心</h2>
          </div>
          <button className={['sm-button', styles['close-btn']].join(' ')} onClick={onClose}>
            关闭
          </button>
        </div>

        <div className={['sm-settings-layout', styles['settings-body']].join(' ')}>
          <aside ref={navRef} className="sm-settings-nav settings-nav" onScroll={handleNavScroll}>
            <div className="sm-settings-nav__list">
              {settingsTabs.map((tab) => (
                <button
                  key={tab.id}
                  className={[
                    'sm-settings-nav__item',
                    activeTab === tab.id && 'is-active'
                  ]
                    .filter(Boolean)
                    .join(' ')}
                  onClick={() => setActiveTab(tab.id)}
                >
                  <span className="sm-settings-nav__label">{tab.label}</span>
                  <span className="sm-settings-nav__meta">{tab.description}</span>
                </button>
              ))}
            </div>
          </aside>

          <section className="sm-settings-panel settings-panel">
            <div className={['sm-settings-panel__body', styles['settings-content']].join(' ')}>
              {configLoading ? (
                <div className="sm-settings-empty">正在加载当前配置...</div>
              ) : (
                <>
                  {activeTab === 'model' && <ModelSettings />}
                  {activeTab === 'mcp' && <MCPSettings onMcpUpdated={onMcpUpdated} />}
                  {activeTab === 'embedding' && <EmbeddingModelSettings />}
                  {activeTab === 'theme' && (
                    <ThemeSettings
                      value={configState.themeConfig}
                      onThemeChange={handleThemeChange}
                    />
                  )}
                  {activeTab === 'knowledge' && <KnowledgeMCPSettings />}
                  {activeTab === 'toolStats' && <ToolStatsSettings />}
                  {activeTab === 'paperReader' && <PaperReaderSettings />}
                  {activeTab === 'update' && <UpdateSettings />}
                </>
              )}
            </div>
          </section>
        </div>
      </div>
    </div>
  )
}

// src/renderer/src/components/SettingsModal.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { storeToRefs } from 'pinia'
import ThemeSettings from './settings/ThemeSettings.vue'
import ModelSettings from './settings/ModelSettings.vue'
import MCPSettings from './settings/MCPSettings.vue'
import EmbeddingModelSettings from './settings/EmbeddingModelSettings.vue'
import KnowledgeMCPSettings from './settings/KnowledgeMCPSettings.vue'
import PaperReaderSettings from './settings/PaperReaderSettings.vue'
import ToolStatsSettings from './settings/ToolStatsSettings.vue'
import UpdateSettings from './settings/UpdateSettings.vue'
import { useConfigStore } from '@renderer/stores'
import { useNotification } from '@renderer/composables/useNotification'

const emit = defineEmits<{
  (e: 'close'): void
  (e: 'mcp-updated'): void
}>()

type SettingsTabKey =
  | 'theme'
  | 'model'
  | 'mcp'
  | 'embedding'
  | 'knowledge'
  | 'toolStats'
  | 'paperReader'
  | 'update'

// 使用 configStore
const configStore = useConfigStore()
const { loading, themeConfig } = storeToRefs(configStore)
const notify = useNotification()

// 当前激活的 Tab
const activeTab = ref<SettingsTabKey>('model')

const settingsTabs: Array<{
  id: SettingsTabKey
  label: string
  description: string
}> = [
  {
    id: 'model',
    label: '对话模型配置',
    description: '管理默认模型、接口地址与上下文参数。'
  },
  {
    id: 'embedding',
    label: '嵌入模型配置',
    description: '维护知识检索所需的向量模型清单。'
  },
  {
    id: 'paperReader',
    label: '论文阅读配置',
    description: '配置论文 OCR 识别服务与翻译模型。'
  },
  {
    id: 'mcp',
    label: 'MCP 服务',
    description: '连接外部工具链并管理服务传输方式。'
  },
  {
    id: 'knowledge',
    label: '知识库服务',
    description: '管理知识库 MCP 对外服务与共享说明。'
  },
  {
    id: 'toolStats',
    label: '工具调用统计',
    description: '查看工具调用量、成功率和耗时分布。'
  },
  {
    id: 'theme',
    label: '主题设置',
    description: '切换当前工作主题并查看主题预览。'
  },
  {
    id: 'update',
    label: '升级版本',
    description: '检查应用更新并查看版本历史。'
  }
]

// 关闭弹窗
function handleClose(): void {
  emit('close')
}

// 主题变化处理（立即生效，无需保存）
function handleThemeChange(themeId: string): void {
  window.api.logger.info('[SettingsModal] 主题已切换', { themeId })
  notify.success('主题设置', '主题已应用', { source: 'settings' })
}

// 键盘事件处理
function handleKeyDown(event: KeyboardEvent): void {
  if (event.key === 'Escape') {
    handleClose()
  }
}

onMounted(() => {
  configStore.loadConfig()
  document.addEventListener('keydown', handleKeyDown)
})

onUnmounted(() => {
  document.removeEventListener('keydown', handleKeyDown)
})
</script>

<template>
  <div class="sm-modal__overlay settings-overlay" @click.self="handleClose">
    <div class="sm-modal__surface settings-container">
      <div class="sm-pane-header settings-header">
        <div class="settings-header__info">
          <h2 class="settings-title">设置中心</h2>
        </div>
        <button class="sm-button close-btn" @click="handleClose">关闭</button>
      </div>

      <div class="sm-settings-layout settings-body">
        <aside class="sm-settings-nav settings-nav">
          <div class="sm-settings-nav__list">
            <button
              v-for="tab in settingsTabs"
              :key="tab.id"
              class="sm-settings-nav__item"
              :class="{ 'is-active': activeTab === tab.id }"
              @click="activeTab = tab.id"
            >
              <span class="sm-settings-nav__label">{{ tab.label }}</span>
              <span class="sm-settings-nav__meta">{{ tab.description }}</span>
            </button>
          </div>
        </aside>

        <section class="sm-settings-panel settings-panel">
          <div class="sm-settings-panel__body settings-content">
            <div v-if="loading" class="sm-settings-empty">正在加载当前配置...</div>

            <ModelSettings v-else-if="activeTab === 'model'" />

            <MCPSettings v-else-if="activeTab === 'mcp'" @mcp-updated="emit('mcp-updated')" />

            <EmbeddingModelSettings v-else-if="activeTab === 'embedding'" />
            <ThemeSettings
              v-else-if="activeTab === 'theme'"
              :model-value="themeConfig"
              @update:model-value="configStore.updateThemeConfig"
              @theme-change="handleThemeChange"
            />

            <KnowledgeMCPSettings v-else-if="activeTab === 'knowledge'" />

            <ToolStatsSettings v-else-if="activeTab === 'toolStats'" />

            <PaperReaderSettings v-else-if="activeTab === 'paperReader'" />

            <UpdateSettings v-else-if="activeTab === 'update'" />
          </div>
        </section>
      </div>
    </div>
  </div>
</template>

<style scoped>
.settings-overlay {
  z-index: 1000;
  overflow: hidden;
}

.settings-container {
  width: min(1100px, calc(100vw - 48px));
  height: min(750px, calc(100vh - 96px - env(safe-area-inset-top, 0px)));
  min-width: 400px;
  min-height: 300px;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  background: var(--sm-color-surface-3);
  border-color: var(--sm-color-border-default);
  box-shadow: none;
}

.settings-header {
  flex-shrink: 0;
}

.settings-header__info {
  display: flex;
  flex-direction: column;
}

.settings-title {
  font-size: 18px;
  font-weight: 600;
  color: var(--sm-color-text-primary);
  margin: 0;
  letter-spacing: -0.01em;
}

.close-btn {
  min-width: 64px;
}

.settings-body {
  overflow: hidden;
}

.settings-content {
  background: var(--sm-color-surface-2);
}

@media (max-width: 1060px) {
  .settings-container {
    width: min(1050px, calc(100vw - 40px));
    height: min(700px, calc(100vh - 88px - env(safe-area-inset-top, 0px)));
  }
}

@media (max-width: 768px) {
  .settings-overlay {
    padding: calc(44px + env(safe-area-inset-top, 0px)) 12px 12px;
  }

  .settings-container {
    width: 100%;
    height: min(100%, calc(100vh - 56px - env(safe-area-inset-top, 0px)));
  }
}

@media (max-width: 600px) {
  .settings-title {
    font-size: 16px;
  }
}

@media (max-width: 480px) {
  .settings-header {
    align-items: flex-start;
    flex-direction: column;
  }

  .close-btn {
    width: 100%;
  }
}
</style>
