// src/renderer/src/components/settings/MCPSettings.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { useZustandStore } from '@renderer/composables/useZustandStore'
import MCPServerItem from '../mcp/MCPServerItem.vue'
import MCPNewServerForm from '../mcp/MCPNewServerForm.vue'
import { useMCPStore } from '@renderer/stores'
import { useNotification } from '@renderer/composables/useNotification'
import type { MCPServerConfig } from '@renderer/types'
import styles from './MCPSettings.module.css'

interface Emits {
  (e: 'mcp-updated'): void
}

const emit = defineEmits<Emits>()

// 使用 MCP Store
const mcpStore = useZustandStore(useMCPStore)

const notify = useNotification()

// UI 状态
const showNewMCPForm = ref(false)
const testResult = ref<{ type: 'success' | 'error'; message: string } | null>(null)
const showImportPanel = ref(false)
const importJsonContent = ref('')
const isImporting = ref(false)

// 导入 JSON 示例
const importPlaceholder = `例如：
{
  "mcpServers": {
    "server-name": {
      "command": "npx",
      "args": ["-y", "some-mcp"]
    }
  }
}`

// 显示消息
function showError(message: string): void {
  notify.error('MCP 服务', message, { source: 'settings' })
}

function showSuccess(message: string): void {
  notify.success('MCP 服务', message, { source: 'settings' })
}

function validateMCPConfig(config: MCPServerConfig): string {
  if (!config.name.trim()) {
    return '请输入服务器名称'
  }

  if (config.transport === 'stdio') {
    if (!config.command?.trim()) {
      return `MCP 服务“${config.name}”的执行命令不能为空`
    }
  } else if (!config.url?.trim()) {
    return `MCP 服务“${config.name}”的服务地址不能为空`
  }

  return ''
}

// 切换 MCP 服务器展开状态
function toggleMCPExpand(name: string): void {
  mcpStore.toggleServerExpanded(name)
}

// 连接 MCP 服务器
async function handleConnect(name: string): Promise<void> {
  const success = await mcpStore.connect(
    name,
    (msg) => showSuccess(msg),
    (msg) => showError(msg)
  )
  if (success) {
    await mcpStore.loadConfigs()
    emit('mcp-updated')
  }
}

// 断开 MCP 服务器
async function handleDisconnect(name: string): Promise<void> {
  const success = await mcpStore.disconnect(name, (msg) => showError(msg))
  if (success) {
    await mcpStore.loadConfigs()
    emit('mcp-updated')
  }
}

// 测试 MCP 连接
async function handleTest(config: MCPServerConfig): Promise<void> {
  const validationMessage = validateMCPConfig(config)
  if (validationMessage) {
    showError(validationMessage)
    return
  }

  const success = await mcpStore.testConnection(
    config,
    (msg) => showSuccess(msg),
    (msg) => showError(msg)
  )
  testResult.value = success
    ? { type: 'success', message: `${config.name} 连接测试成功` }
    : { type: 'error', message: `${config.name} 连接测试失败` }
}

// 删除 MCP 配置
async function handleDelete(name: string): Promise<void> {
  const success = await mcpStore.deleteConfig(name)
  if (success) {
    mcpStore.expandedServers.delete(name)
    emit('mcp-updated')
  }
}

// 保存 MCP 配置
async function handleSave(config: MCPServerConfig): Promise<boolean> {
  const validationMessage = validateMCPConfig(config)
  if (validationMessage) {
    showError(validationMessage)
    return false
  }

  const success = await mcpStore.saveConfig(config)
  if (success) {
    emit('mcp-updated')
  }
  return success
}

// 添加新 MCP 配置
async function handleAddNew(config: MCPServerConfig): Promise<void> {
  const validationMessage = validateMCPConfig(config)
  if (validationMessage) {
    showError(validationMessage)
    return
  }

  const success = await mcpStore.saveConfig(config)
  if (success) {
    showNewMCPForm.value = false
    emit('mcp-updated')
  }
}

// 测试新建的 MCP 配置
async function handleTestNew(config: MCPServerConfig): Promise<void> {
  await handleTest(config)
}

// 切换导入面板显示状态
function toggleImportPanel(): void {
  showImportPanel.value = !showImportPanel.value
  if (!showImportPanel.value) {
    importJsonContent.value = ''
  }
}

// 导入 MCP 配置
async function importMCPConfigs(): Promise<void> {
  const jsonContent = importJsonContent.value.trim()
  if (!jsonContent) {
    showError('请输入 MCP 配置 JSON')
    return
  }

  isImporting.value = true

  try {
    const result = await window.api.mcp.importConfigs(jsonContent)
    if (result.success) {
      showSuccess(`成功导入 ${result.imported} 个配置`)
      if (result.errors.length > 0) {
        window.api.logger.warn('[MCPSettings] 导入过程中存在错误', {
          errors: result.errors
        })
      }
      importJsonContent.value = ''
      showImportPanel.value = false
      await mcpStore.loadConfigs()
      emit('mcp-updated')
    } else {
      showError(`导入失败: ${result.errors.join(', ')}`)
    }
  } catch (error) {
    showError(`导入失败: ${error instanceof Error ? error.message : String(error)}`)
  } finally {
    isImporting.value = false
  }
}

// 组件挂载时加载配置并设置状态监听
onMounted(() => {
  mcpStore.loadConfigs()
  mcpStore.setupStatusListener()
})

// 组件卸载时清理监听
onUnmounted(() => {
  mcpStore.cleanupStatusListener()
})
</script>

<template>
  <div class="sm-settings-page tab-content">
    <header class="sm-settings-page__header">
      <h2 class="sm-settings-page__title">MCP 服务配置</h2>
      <p class="sm-settings-page__description">
        管理工具服务的连接、传输方式和导入配置，保持与聊天工作区同一套工程控制台语言。
      </p>
    </header>

    <section class="sm-settings-page__section">
      <div class="sm-settings-page__section-header">
        <div>
          <h3 class="sm-settings-page__section-title">服务清单</h3>
          <p class="sm-settings-page__section-description">
            当前共 {{ mcpStore.configs.length }} 个 MCP 服务配置，可逐项测试、连接或编辑。
          </p>
        </div>
      </div>

      <div :class="styles['mcp-server-list']">
        <MCPServerItem
          v-for="config in mcpStore.configs"
          :key="config.name"
          :config="config"
          :status="mcpStore.getStatus(config.name)"
          :expanded="mcpStore.expandedServers.has(config.name)"
          :connecting="mcpStore.connecting === config.name"
          :testing="mcpStore.testing === config.name"
          @toggle-expand="toggleMCPExpand"
          @connect="handleConnect"
          @disconnect="handleDisconnect"
          @delete="handleDelete"
          @test="handleTest"
          @save="handleSave"
        />

        <div v-if="mcpStore.configs.length === 0 && !showNewMCPForm" class="sm-settings-empty">
          <p>暂无 MCP 服务配置</p>
        </div>
      </div>

      <MCPNewServerForm
        v-if="showNewMCPForm"
        :existing-names="mcpStore.configs.map((c) => c.name)"
        @submit="handleAddNew"
        @cancel="showNewMCPForm = false"
        @test="handleTestNew"
      />

      <div v-if="!showNewMCPForm" :class="['sm-settings-actions', styles['settings-actions']]">
        <button :class="['sm-button', styles['add-mcp-btn']]" @click="showNewMCPForm = true">
          添加 MCP 服务器
        </button>
        <button :class="['sm-button', styles['import-btn']]" @click="toggleImportPanel">
          {{ showImportPanel ? '收起导入' : '导入 JSON 配置' }}
        </button>
      </div>

      <div v-if="showImportPanel && !showNewMCPForm" :class="styles['import-panel']">
        <label :class="styles['import-label']" for="mcp-import-json">粘贴 MCP 配置 JSON</label>
        <textarea
          id="mcp-import-json"
          v-model="importJsonContent"
          :class="['sm-textarea', styles['import-textarea']]"
          :placeholder="importPlaceholder"
        />
        <div :class="styles['import-actions']">
          <button
            class="sm-button sm-button--small sm-button--primary"
            :disabled="isImporting"
            @click="importMCPConfigs"
          >
            {{ isImporting ? '导入中...' : '确认导入' }}
          </button>
          <button
            class="sm-button sm-button--small sm-button--secondary"
            :disabled="isImporting"
            @click="toggleImportPanel"
          >
            取消
          </button>
        </div>
      </div>
    </section>
  </div>
</template>

// src/renderer/src/components/settings/MCPSettings.tsx
import { useState, useEffect, useCallback, useMemo } from 'react'
import type { MCPServerConfig } from '@shared/types/mcp'
import { useMCPStore } from '@renderer/stores/mcpStore'
import { notifySuccess, notifyError } from '@renderer/composables/notificationCore'
import MCPServerItem from '../mcp/MCPServerItem'
import MCPNewServerForm from '../mcp/MCPNewServerForm'
import styles from './MCPSettings.module.css'

interface MCPSettingsProps {
  onMcpUpdated?: () => void
}

/** MCP 服务配置设置页：管理外部工具链连接，支持添加/编辑/删除/连接/断开/测试/JSON 导入 */
export default function MCPSettings({ onMcpUpdated }: MCPSettingsProps) {
  // Zustand selectors
  const configs = useMCPStore((s) => s.configs)
  const expandedServers = useMCPStore((s) => s.expandedServers)
  const connecting = useMCPStore((s) => s.connecting)
  const testing = useMCPStore((s) => s.testing)

  // Store 方法
  const loadConfigs = useMCPStore((s) => s.loadConfigs)
  const setupStatusListener = useMCPStore((s) => s.setupStatusListener)
  const cleanupStatusListener = useMCPStore((s) => s.cleanupStatusListener)
  const toggleServerExpanded = useMCPStore((s) => s.toggleServerExpanded)
  const getStatus = useMCPStore((s) => s.getStatus)
  const connectStore = useMCPStore((s) => s.connect)
  const disconnectStore = useMCPStore((s) => s.disconnect)
  const testConnectionStore = useMCPStore((s) => s.testConnection)
  const saveConfigStore = useMCPStore((s) => s.saveConfig)
  const deleteConfigStore = useMCPStore((s) => s.deleteConfig)

  // UI 状态
  const [showNewMCPForm, setShowNewMCPForm] = useState(false)
  const [showImportPanel, setShowImportPanel] = useState(false)
  const [importJsonContent, setImportJsonContent] = useState('')
  const [isImporting, setIsImporting] = useState(false)

  // 导入 JSON 示例
  const importPlaceholder = useMemo(
    () => `例如：
{
  "mcpServers": {
    "server-name": {
      "command": "npx",
      "args": ["-y", "some-mcp"]
    }
  }
}`,
    []
  )

  // 校验 MCP 配置
  const validateMCPConfig = useCallback((config: MCPServerConfig): string => {
    if (!config.name.trim()) return '请输入服务器名称'
    if (config.transport === 'stdio') {
      if (!config.command?.trim()) return `MCP 服务"${config.name}"的执行命令不能为空`
    } else if (!config.url?.trim()) {
      return `MCP 服务"${config.name}"的服务地址不能为空`
    }
    return ''
  }, [])

  // 现有服务器名称列表
  const existingNames = useMemo(() => configs.map((c) => c.name), [configs])

  // 切换展开状态
  const handleToggleExpand = useCallback(
    (name: string) => {
      toggleServerExpanded(name)
    },
    [toggleServerExpanded]
  )

  // 连接
  const handleConnect = useCallback(
    async (name: string) => {
      const success = await connectStore(
        name,
        (msg) => notifySuccess('MCP 服务', msg, { source: 'settings' }),
        (msg) => notifyError('MCP 服务', msg, { source: 'settings' })
      )
      if (success) {
        await loadConfigs()
        onMcpUpdated?.()
      }
    },
    [connectStore, loadConfigs, onMcpUpdated]
  )

  // 断开
  const handleDisconnect = useCallback(
    async (name: string) => {
      const success = await disconnectStore(name, (msg) =>
        notifyError('MCP 服务', msg, { source: 'settings' })
      )
      if (success) {
        await loadConfigs()
        onMcpUpdated?.()
      }
    },
    [disconnectStore, loadConfigs, onMcpUpdated]
  )

  // 测试连接
  const handleTest = useCallback(
    async (config: MCPServerConfig) => {
      const msg = validateMCPConfig(config)
      if (msg) {
        notifyError('MCP 服务', msg, { source: 'settings' })
        return
      }
      await testConnectionStore(
        config,
        (m) => notifySuccess('MCP 服务', m, { source: 'settings' }),
        (m) => notifyError('MCP 服务', m, { source: 'settings' })
      )
    },
    [validateMCPConfig, testConnectionStore]
  )

  // 删除配置
  const handleDelete = useCallback(
    async (name: string) => {
      const success = await deleteConfigStore(name)
      if (success) {
        onMcpUpdated?.()
      }
    },
    [deleteConfigStore, onMcpUpdated]
  )

  // 保存配置（编辑已有服务器）
  const handleSave = useCallback(
    async (config: MCPServerConfig): Promise<boolean> => {
      const msg = validateMCPConfig(config)
      if (msg) {
        notifyError('MCP 服务', msg, { source: 'settings' })
        return false
      }
      const success = await saveConfigStore(config)
      if (success) {
        onMcpUpdated?.()
      }
      return success
    },
    [validateMCPConfig, saveConfigStore, onMcpUpdated]
  )

  // 添加新服务器
  const handleAddNew = useCallback(
    async (config: MCPServerConfig) => {
      const msg = validateMCPConfig(config)
      if (msg) {
        notifyError('MCP 服务', msg, { source: 'settings' })
        return
      }
      const success = await saveConfigStore(config)
      if (success) {
        setShowNewMCPForm(false)
        onMcpUpdated?.()
      }
    },
    [validateMCPConfig, saveConfigStore, onMcpUpdated]
  )

  // 切换导入面板
  const toggleImportPanel = useCallback(() => {
    setShowImportPanel((prev) => {
      if (prev) setImportJsonContent('')
      return !prev
    })
  }, [])

  // 导入 MCP 配置
  const importMCPConfigs = useCallback(async () => {
    const jsonContent = importJsonContent.trim()
    if (!jsonContent) {
      notifyError('MCP 服务', '请输入 MCP 配置 JSON', { source: 'settings' })
      return
    }

    setIsImporting(true)
    try {
      const result = await window.api.mcp.importConfigs(jsonContent)
      if (result.success) {
        notifySuccess('MCP 服务', `成功导入 ${result.imported} 个配置`, { source: 'settings' })
        if (result.errors.length > 0) {
          window.api.logger.warn('[MCPSettings] 导入过程中存在错误', { errors: result.errors })
        }
        setImportJsonContent('')
        setShowImportPanel(false)
        await loadConfigs()
        onMcpUpdated?.()
      } else {
        notifyError('MCP 服务', `导入失败: ${result.errors.join(', ')}`, { source: 'settings' })
      }
    } catch (error) {
      notifyError(
        'MCP 服务',
        `导入失败: ${error instanceof Error ? error.message : String(error)}`,
        { source: 'settings' }
      )
    } finally {
      setIsImporting(false)
    }
  }, [importJsonContent, loadConfigs, onMcpUpdated])

  // 组件挂载时加载配置并设置状态监听
  useEffect(() => {
    loadConfigs()
    setupStatusListener()
    return () => {
      cleanupStatusListener()
    }
  }, [loadConfigs, setupStatusListener, cleanupStatusListener])

  return (
    <div className={['sm-settings-page', 'tab-content'].join(' ')}>
      <header className="sm-settings-page__header">
        <h2 className="sm-settings-page__title">MCP 服务配置</h2>
        <p className="sm-settings-page__description">
          管理工具服务的连接、传输方式和导入配置，保持与聊天工作区同一套工程控制台语言。
        </p>
      </header>

      <section className="sm-settings-page__section">
        <div className="sm-settings-page__section-header">
          <div>
            <h3 className="sm-settings-page__section-title">服务清单</h3>
            <p className="sm-settings-page__section-description">
              当前共 {configs.length} 个 MCP 服务配置，可逐项测试、连接或编辑。
            </p>
          </div>
        </div>

        <div className={styles['mcp-server-list']}>
          {configs.map((config) => (
            <MCPServerItem
              key={config.name}
              config={config}
              status={getStatus(config.name)}
              expanded={expandedServers.has(config.name)}
              connecting={connecting === config.name}
              testing={testing === config.name}
              onToggleExpand={() => handleToggleExpand(config.name)}
              onConnect={() => handleConnect(config.name)}
              onDisconnect={() => handleDisconnect(config.name)}
              onDelete={() => handleDelete(config.name)}
              onTest={handleTest}
              onSave={handleSave}
            />
          ))}

          {configs.length === 0 && !showNewMCPForm && (
            <div className="sm-settings-empty">
              <p>暂无 MCP 服务配置</p>
            </div>
          )}
        </div>

        {showNewMCPForm && (
          <MCPNewServerForm
            existingNames={existingNames}
            onSubmit={handleAddNew}
            onCancel={() => setShowNewMCPForm(false)}
            onTest={handleTest}
          />
        )}

        {!showNewMCPForm && (
          <div className={['sm-settings-actions', styles['settings-actions']].join(' ')}>
            <button
              className={['sm-button', styles['add-mcp-btn']].join(' ')}
              onClick={() => setShowNewMCPForm(true)}
            >
              添加 MCP 服务器
            </button>
            <button
              className={['sm-button', styles['import-btn']].join(' ')}
              onClick={toggleImportPanel}
            >
              {showImportPanel ? '收起导入' : '导入 JSON 配置'}
            </button>
          </div>
        )}

        {showImportPanel && !showNewMCPForm && (
          <div className={styles['import-panel']}>
            <label className={styles['import-label']} htmlFor="mcp-import-json">
              粘贴 MCP 配置 JSON
            </label>
            <textarea
              id="mcp-import-json"
              className={['sm-textarea', styles['import-textarea']].join(' ')}
              placeholder={importPlaceholder}
              value={importJsonContent}
              onChange={(e) => setImportJsonContent(e.target.value)}
            />
            <div className={styles['import-actions']}>
              <button
                className="sm-button sm-button--small sm-button--primary"
                disabled={isImporting}
                onClick={importMCPConfigs}
              >
                {isImporting ? '导入中...' : '确认导入'}
              </button>
              <button
                className="sm-button sm-button--small sm-button--secondary"
                disabled={isImporting}
                onClick={toggleImportPanel}
              >
                取消
              </button>
            </div>
          </div>
        )}
      </section>
    </div>
  )
}
