// src/renderer/src/components/settings/ModelSettings.tsx
import { useState, useRef, useCallback } from 'react'
import { useConfigStore } from '@renderer/stores/configStore'
import { useUIStateStore } from '@renderer/stores/uiStateStore'
import { notifySuccess, notifyError, notifyWarning } from '@renderer/composables/notificationCore'
import type { LLMConfig } from '@shared/types/config'
import styles from './ModelSettings.module.css'

const MODEL_FIELD_LABELS: Record<'base_url' | 'api_key' | 'model_name', string> = {
  base_url: 'API Base URL',
  api_key: 'API Key',
  model_name: '模型名称'
}

const EMPTY_NEW_MODEL: LLMConfig = { base_url: '', api_key: '', model_name: '' }

export default function ModelSettings() {
  // Zustand selectors
  const llmConfigs = useConfigStore((s) => s.llmConfigs)
  const defaultModel = useConfigStore((s) => s.defaultModel)
  const saving = useConfigStore((s) => s.saving)
  const updateLLMConfigs = useConfigStore((s) => s.updateLLMConfigs)
  const updateDefaultModel = useConfigStore((s) => s.updateDefaultModel)
  const notifyConfigUpdate = useUIStateStore((s) => s.notifyConfigUpdate)

  // UI 状态
  const [expandedModels, setExpandedModels] = useState<Set<number>>(new Set())
  const [showNewModelForm, setShowNewModelForm] = useState(false)
  const [newModelConfig, setNewModelConfig] = useState<LLMConfig>({ ...EMPTY_NEW_MODEL })
  const [testingModelIndex, setTestingModelIndex] = useState<number | null>(null)
  const [testingNewModel, setTestingNewModel] = useState(false)

  // Auto-save 互斥锁
  const autoSavePending = useRef(false)
  const autoSaveRunning = useRef(false)

  // 辅助函数
  const getModelItemName = useCallback((config: LLMConfig, index: number): string => {
    return config.model_name.trim() || `第 ${index + 1} 个模型`
  }, [])

  const validateModelConfig = useCallback(
    (config: LLMConfig, index: number): string => {
      const requiredFields: Array<keyof typeof MODEL_FIELD_LABELS> = [
        'base_url',
        'api_key',
        'model_name'
      ]

      for (const field of requiredFields) {
        if (!config[field].trim()) {
          return `模型配置"${getModelItemName(config, index)}"的 ${MODEL_FIELD_LABELS[field]} 不能为空`
        }
      }

      return ''
    },
    [getModelItemName]
  )

  const validateAllModelConfigs = useCallback((): boolean => {
    const { llmConfigs: configs } = useConfigStore.getState()
    for (const [index, config] of configs.entries()) {
      const validationMessage = validateModelConfig(config, index)
      if (validationMessage) {
        notifyWarning('模型配置校验失败', validationMessage, { source: 'settings' })
        return false
      }
    }
    return true
  }, [validateModelConfig])

  // Auto-save 队列
  const flushAutoSaveQueue = useCallback(async () => {
    if (autoSaveRunning.current) {
      autoSavePending.current = true
      return
    }

    autoSaveRunning.current = true
    let shouldNotify = false

    try {
      do {
        autoSavePending.current = false
        if (!validateAllModelConfigs()) return

        const success = await useConfigStore.getState().saveConfig({ silent: true })
        if (success) shouldNotify = true
      } while (autoSavePending.current)
    } finally {
      autoSaveRunning.current = false
    }

    if (shouldNotify) {
      notifyConfigUpdate()
    }
  }, [validateAllModelConfigs, notifyConfigUpdate])

  const triggerAutoSave = useCallback(() => {
    void flushAutoSaveQueue()
  }, [flushAutoSaveQueue])

  // 模型操作
  const addNewModel = useCallback(() => {
    const { llmConfigs: configs } = useConfigStore.getState()
    const validationMessage = validateModelConfig(newModelConfig, configs.length)
    if (validationMessage) {
      notifyWarning('模型配置校验失败', validationMessage, { source: 'settings' })
      return
    }

    const newConfigs = [...configs, { ...newModelConfig }]
    updateLLMConfigs(newConfigs)
    setExpandedModels((prev) => new Set(prev).add(newConfigs.length - 1))

    if (newConfigs.length === 1) {
      updateDefaultModel(newModelConfig.model_name)
    }

    triggerAutoSave()
    setShowNewModelForm(false)
    setNewModelConfig({ ...EMPTY_NEW_MODEL })
  }, [newModelConfig, validateModelConfig, updateLLMConfigs, updateDefaultModel, triggerAutoSave])

  const deleteModel = useCallback(
    (modelIndex: number) => {
      const { llmConfigs: configs, defaultModel: dm } = useConfigStore.getState()
      const modelName = configs[modelIndex]?.model_name
      if (modelName === undefined) return

      const newConfigs = configs.filter((_, index) => index !== modelIndex)
      updateLLMConfigs(newConfigs)

      setExpandedModels(
        (prev) =>
          new Set(
            Array.from(prev)
              .filter((index) => index !== modelIndex)
              .map((index) => (index > modelIndex ? index - 1 : index))
          )
      )

      if (dm === modelName) {
        updateDefaultModel(newConfigs.length > 0 ? newConfigs[0].model_name : '')
      }

      triggerAutoSave()
    },
    [updateLLMConfigs, updateDefaultModel, triggerAutoSave]
  )

  const toggleModelExpand = useCallback((modelIndex: number) => {
    setExpandedModels((prev) => {
      const next = new Set(prev)
      if (next.has(modelIndex)) {
        next.delete(modelIndex)
      } else {
        next.add(modelIndex)
      }
      return next
    })
  }, [])

  const setDefaultModel = useCallback(
    (modelName: string) => {
      if (useConfigStore.getState().defaultModel === modelName) return
      updateDefaultModel(modelName)
      triggerAutoSave()
    },
    [updateDefaultModel, triggerAutoSave]
  )

  const testModelConnection = useCallback(
    async (modelIndex: number) => {
      const config = useConfigStore.getState().llmConfigs[modelIndex]
      if (!config) return

      const validationMessage = validateModelConfig(config, modelIndex)
      if (validationMessage) {
        notifyWarning('模型配置校验失败', validationMessage, { source: 'settings' })
        return
      }

      setTestingModelIndex(modelIndex)
      try {
        const result = await window.api.config.testModelConnection({ ...config })
        if (result.success) {
          notifySuccess('模型连接测试成功', `模型"${getModelItemName(config, modelIndex)}"可用`, {
            source: 'settings'
          })
        } else {
          notifyError('模型连接测试失败', result.error || '连接测试失败', { source: 'settings' })
        }
      } catch (error) {
        notifyError('模型连接测试失败', error instanceof Error ? error.message : String(error), {
          source: 'settings'
        })
      } finally {
        setTestingModelIndex(null)
      }
    },
    [validateModelConfig, getModelItemName]
  )

  const testNewModelConnection = useCallback(async () => {
    const { llmConfigs: configs } = useConfigStore.getState()
    const validationMessage = validateModelConfig(newModelConfig, configs.length)
    if (validationMessage) {
      notifyWarning('模型配置校验失败', validationMessage, { source: 'settings' })
      return
    }

    setTestingNewModel(true)
    try {
      const result = await window.api.config.testModelConnection({ ...newModelConfig })
      if (result.success) {
        notifySuccess('模型连接测试成功', `模型"${newModelConfig.model_name}"可用`, {
          source: 'settings'
        })
      } else {
        notifyError('模型连接测试失败', result.error || '连接测试失败', { source: 'settings' })
      }
    } catch (error) {
      notifyError('模型连接测试失败', error instanceof Error ? error.message : String(error), {
        source: 'settings'
      })
    } finally {
      setTestingNewModel(false)
    }
  }, [newModelConfig, validateModelConfig])

  const updateModelConfig = useCallback(
    (modelIndex: number, field: keyof LLMConfig, value: string) => {
      const { llmConfigs: configs, defaultModel: dm } = useConfigStore.getState()
      const currentConfig = configs[modelIndex]
      if (!currentConfig || currentConfig[field] === value) return

      const newConfigs = [...configs]
      newConfigs[modelIndex] = { ...currentConfig, [field]: value }

      updateLLMConfigs(newConfigs)

      if (field === 'model_name' && dm === currentConfig.model_name) {
        updateDefaultModel(value)
      }

      triggerAutoSave()
    },
    [updateLLMConfigs, updateDefaultModel, triggerAutoSave]
  )

  // 保存配置
  const handleSave = useCallback(async () => {
    if (!validateAllModelConfigs()) return
    const success = await useConfigStore.getState().saveConfig()
    if (success) notifyConfigUpdate()
  }, [validateAllModelConfigs, notifyConfigUpdate])

  return (
    <div className={['sm-settings-page', 'tab-content'].join(' ')}>
      <header className="sm-settings-page__header">
        <h2 className="sm-settings-page__title">对话模型配置</h2>
        <p className="sm-settings-page__description">
          管理对话模型列表和默认模型。修改字段后会自动同步到本地配置。
        </p>
      </header>

      <section className="sm-settings-page__section">
        <div className="sm-settings-page__section-header">
          <div>
            <h3 className="sm-settings-page__section-title">模型列表</h3>
            <p className="sm-settings-page__section-description">
              当前共 {llmConfigs.length} 个模型，默认模型会同步到会话工作区的模型选择器。
            </p>
          </div>

          <span
            className={['sm-settings-chip', llmConfigs.length > 0 && 'sm-settings-chip--accent']
              .filter(Boolean)
              .join(' ')}
          >
            默认模型: {defaultModel || '未设置'}
          </span>
        </div>

        <div className={styles['model-list']}>
          {llmConfigs.map((config, index) => (
            <div key={index} className={styles['model-item']}>
              <div className={styles['model-header']} onClick={() => toggleModelExpand(index)}>
                <span className={styles['model-name']}>{config.model_name || '未命名模型'}</span>
                {defaultModel === config.model_name && (
                  <span className={styles['default-badge']}>默认</span>
                )}
                <span className={styles['expand-state']}>
                  {expandedModels.has(index) ? '收起' : '展开'}
                </span>
                <div className={styles['model-actions']}>
                  <button
                    className="sm-button sm-button--small"
                    disabled={testingModelIndex === index}
                    onClick={(e) => {
                      e.stopPropagation()
                      void testModelConnection(index)
                    }}
                  >
                    {testingModelIndex === index ? '测试中...' : '测试'}
                  </button>
                  {defaultModel !== config.model_name && (
                    <button
                      className="sm-button sm-button--small"
                      onClick={(e) => {
                        e.stopPropagation()
                        setDefaultModel(config.model_name)
                      }}
                    >
                      设为默认
                    </button>
                  )}
                  <button
                    className={[
                      'sm-button',
                      'sm-button--small',
                      'sm-button--danger',
                      styles['model-action--danger']
                    ].join(' ')}
                    onClick={(e) => {
                      e.stopPropagation()
                      deleteModel(index)
                    }}
                  >
                    删除
                  </button>
                </div>
              </div>
              {expandedModels.has(index) && (
                <div className={styles['model-details']}>
                  <div className={styles['form-group']}>
                    <label>API Base URL</label>
                    <input
                      value={config.base_url}
                      type="text"
                      className="sm-input"
                      placeholder="https://api.openai.com/v1"
                      onChange={(e) => updateModelConfig(index, 'base_url', e.target.value)}
                    />
                  </div>
                  <div className={styles['form-group']}>
                    <label>API Key</label>
                    <input
                      value={config.api_key}
                      type="password"
                      className="sm-input"
                      placeholder="sk-..."
                      onChange={(e) => updateModelConfig(index, 'api_key', e.target.value)}
                    />
                  </div>
                  <div className={styles['model-name-field']}>
                    <label>模型名称</label>
                    <input
                      value={config.model_name}
                      type="text"
                      className="sm-input"
                      placeholder="gpt-4"
                      onChange={(e) => updateModelConfig(index, 'model_name', e.target.value)}
                    />
                  </div>
                </div>
              )}
            </div>
          ))}

          {llmConfigs.length === 0 && !showNewModelForm && (
            <div className="sm-settings-empty">
              <p>暂无模型配置</p>
            </div>
          )}
        </div>

        {showNewModelForm && (
          <div className={styles['new-model-form']}>
            <h3 className={styles['form-section-title']}>添加新模型配置</h3>
            <div className={styles['form-group']}>
              <label>
                API Base URL <span className={styles.required}>*</span>
              </label>
              <input
                type="text"
                className="sm-input"
                placeholder="https://api.openai.com/v1"
                value={newModelConfig.base_url}
                onChange={(e) =>
                  setNewModelConfig((prev) => ({ ...prev, base_url: e.target.value }))
                }
              />
            </div>
            <div className={styles['form-group']}>
              <label>
                API Key <span className={styles.required}>*</span>
              </label>
              <input
                type="password"
                className="sm-input"
                placeholder="sk-..."
                value={newModelConfig.api_key}
                onChange={(e) =>
                  setNewModelConfig((prev) => ({ ...prev, api_key: e.target.value }))
                }
              />
            </div>
            <div className={styles['model-name-field']}>
              <label>
                模型名称 <span className={styles.required}>*</span>
              </label>
              <input
                type="text"
                className="sm-input"
                placeholder="gpt-4"
                value={newModelConfig.model_name}
                onChange={(e) =>
                  setNewModelConfig((prev) => ({ ...prev, model_name: e.target.value }))
                }
              />
            </div>
            <div className="form-actions">
              <button
                className="sm-button"
                onClick={() => {
                  setShowNewModelForm(false)
                  setNewModelConfig({ ...EMPTY_NEW_MODEL })
                }}
              >
                取消
              </button>
              <button
                className="sm-button sm-button--secondary"
                disabled={testingNewModel}
                onClick={() => void testNewModelConnection()}
              >
                {testingNewModel ? '测试中...' : '测试连接'}
              </button>
              <button className="sm-button sm-button--primary" onClick={addNewModel}>
                添加
              </button>
            </div>
          </div>
        )}

        {!showNewModelForm && (
          <button
            className={['sm-button', styles['add-model-btn']].join(' ')}
            onClick={() => setShowNewModelForm(true)}
          >
            添加模型配置
          </button>
        )}
      </section>

      <div className={styles['save-actions']}>
        <button
          className="sm-button sm-button--primary"
          disabled={saving}
          onClick={() => void handleSave()}
        >
          {saving ? '保存中...' : '保存配置'}
        </button>
      </div>
    </div>
  )
}

// src/renderer/src/components/settings/ModelSettings.vue
<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useZustandStore } from '@renderer/composables/useZustandStore'
import type { LLMConfig } from '@renderer/types'
import { useConfigStore } from '@renderer/stores'
import { useUIStateStore } from '@renderer/stores'
import { useNotification } from '@renderer/composables/useNotification'

const configStore = useZustandStore(useConfigStore)
const uiStateStore = useZustandStore(useUIStateStore)
const notify = useNotification()

// 展开的模型配置项（使用索引避免编辑 model_name 时丢失展开状态）
const expandedModels = ref<Set<number>>(new Set())
const autoSavePending = ref(false)
const autoSaveRunning = ref(false)
const testingModelIndex = ref<number | null>(null)
const testingNewModel = ref(false)

const MODEL_FIELD_LABELS: Record<'base_url' | 'api_key' | 'model_name', string> = {
  base_url: 'API Base URL',
  api_key: 'API Key',
  model_name: '模型名称'
}

// 新模型表单
const showNewModelForm = ref(false)
const newModelConfig = reactive<LLMConfig>({
  base_url: '',
  api_key: '',
  model_name: ''
})

function showValidationWarning(message: string): void {
  notify.warning('模型配置校验失败', message, { source: 'settings' })
}

function getModelItemName(config: LLMConfig, index: number): string {
  return config.model_name.trim() || `第 ${index + 1} 个模型`
}

function validateModelConfig(config: LLMConfig, index: number): string {
  const requiredFields: Array<keyof typeof MODEL_FIELD_LABELS> = [
    'base_url',
    'api_key',
    'model_name'
  ]

  for (const field of requiredFields) {
    if (!config[field].trim()) {
      return `模型配置“${getModelItemName(config, index)}”的 ${MODEL_FIELD_LABELS[field]} 不能为空`
    }
  }

  return ''
}

function validateAllModelConfigs(): boolean {
  for (const [index, config] of configStore.llmConfigs.entries()) {
    const validationMessage = validateModelConfig(config, index)
    if (validationMessage) {
      showValidationWarning(validationMessage)
      return false
    }
  }

  return true
}

function addNewModel(): void {
  const validationMessage = validateModelConfig(newModelConfig, configStore.llmConfigs.length)
  if (validationMessage) {
    showValidationWarning(validationMessage)
    return
  }

  const newConfigs = [...configStore.llmConfigs, { ...newModelConfig }]
  configStore.updateLLMConfigs(newConfigs)
  expandedModels.value.add(newConfigs.length - 1)

  // 如果是第一个模型，设为默认
  if (newConfigs.length === 1) {
    configStore.updateDefaultModel(newModelConfig.model_name)
  }

  triggerAutoSave()
  resetNewModelForm()
}

function resetNewModelForm(): void {
  showNewModelForm.value = false
  newModelConfig.base_url = ''
  newModelConfig.api_key = ''
  newModelConfig.model_name = ''
}

function normalizeExpandedModelsAfterDelete(deletedIndex: number): void {
  expandedModels.value = new Set(
    Array.from(expandedModels.value)
      .filter((index) => index !== deletedIndex)
      .map((index) => (index > deletedIndex ? index - 1 : index))
  )
}

function deleteModel(modelIndex: number): void {
  const modelName = configStore.llmConfigs[modelIndex]?.model_name
  if (modelName === undefined) {
    return
  }

  const newConfigs = configStore.llmConfigs.filter((_, index) => index !== modelIndex)
  configStore.updateLLMConfigs(newConfigs)

  normalizeExpandedModelsAfterDelete(modelIndex)
  if (configStore.defaultModel === modelName) {
    configStore.updateDefaultModel(newConfigs.length > 0 ? newConfigs[0].model_name : '')
  }

  triggerAutoSave()
}

function toggleModelExpand(modelIndex: number): void {
  if (expandedModels.value.has(modelIndex)) {
    expandedModels.value.delete(modelIndex)
  } else {
    expandedModels.value.add(modelIndex)
  }
}

function setDefaultModel(modelName: string): void {
  if (configStore.defaultModel === modelName) {
    return
  }

  configStore.updateDefaultModel(modelName)
  triggerAutoSave()
}

async function testModelConnection(modelIndex: number): Promise<void> {
  const config = configStore.llmConfigs[modelIndex]
  if (!config) {
    return
  }

  const validationMessage = validateModelConfig(config, modelIndex)
  if (validationMessage) {
    showValidationWarning(validationMessage)
    return
  }

  testingModelIndex.value = modelIndex
  try {
    const result = await window.api.config.testModelConnection({ ...config })
    if (result.success) {
      notify.success('模型连接测试成功', `模型“${getModelItemName(config, modelIndex)}”可用`, {
        source: 'settings'
      })
    } else {
      notify.error('模型连接测试失败', result.error || '连接测试失败', { source: 'settings' })
    }
  } catch (error) {
    notify.error('模型连接测试失败', error instanceof Error ? error.message : String(error), {
      source: 'settings'
    })
  } finally {
    testingModelIndex.value = null
  }
}

async function testNewModelConnection(): Promise<void> {
  const validationMessage = validateModelConfig(newModelConfig, configStore.llmConfigs.length)
  if (validationMessage) {
    showValidationWarning(validationMessage)
    return
  }

  testingNewModel.value = true
  try {
    const result = await window.api.config.testModelConnection({ ...newModelConfig })
    if (result.success) {
      notify.success('模型连接测试成功', `模型“${newModelConfig.model_name}”可用`, {
        source: 'settings'
      })
    } else {
      notify.error('模型连接测试失败', result.error || '连接测试失败', { source: 'settings' })
    }
  } catch (error) {
    notify.error('模型连接测试失败', error instanceof Error ? error.message : String(error), {
      source: 'settings'
    })
  } finally {
    testingNewModel.value = false
  }
}

function updateModelConfig(modelIndex: number, field: keyof LLMConfig, value: unknown): void {
  const currentConfig = configStore.llmConfigs[modelIndex]
  if (!currentConfig || currentConfig[field] === value) {
    return
  }

  const newConfigs = [...configStore.llmConfigs]
  newConfigs[modelIndex] = {
    ...currentConfig,
    [field]: value
  } as LLMConfig

  configStore.updateLLMConfigs(newConfigs)

  if (
    field === 'model_name' &&
    configStore.defaultModel === currentConfig.model_name &&
    typeof value === 'string'
  ) {
    configStore.updateDefaultModel(value)
  }

  triggerAutoSave()
}

async function flushAutoSaveQueue(): Promise<void> {
  if (autoSaveRunning.value) {
    autoSavePending.value = true
    return
  }

  autoSaveRunning.value = true
  let shouldNotify = false

  try {
    do {
      autoSavePending.value = false
      if (!validateAllModelConfigs()) {
        return
      }

      const success = await configStore.saveConfig({ silent: true })
      if (success) {
        shouldNotify = true
      }
    } while (autoSavePending.value)
  } finally {
    autoSaveRunning.value = false
  }

  if (shouldNotify) {
    uiStateStore.notifyConfigUpdate()
  }
}

function triggerAutoSave(): void {
  void flushAutoSaveQueue()
}

// 保存配置
async function handleSave(): Promise<void> {
  if (!validateAllModelConfigs()) {
    return
  }

  const success = await configStore.saveConfig()
  if (success) {
    uiStateStore.notifyConfigUpdate()
  }
}
</script>

<template>
  <div class="sm-settings-page tab-content">
    <header class="sm-settings-page__header">
      <h2 class="sm-settings-page__title">对话模型配置</h2>
      <p class="sm-settings-page__description">
        管理对话模型列表和默认模型。修改字段后会自动同步到本地配置。
      </p>
    </header>

    <section class="sm-settings-page__section">
      <div class="sm-settings-page__section-header">
        <div>
          <h3 class="sm-settings-page__section-title">模型列表</h3>
          <p class="sm-settings-page__section-description">
            当前共
            {{ configStore.llmConfigs.length }} 个模型，默认模型会同步到会话工作区的模型选择器。
          </p>
        </div>

        <span
          class="sm-settings-chip"
          :class="{ 'sm-settings-chip--accent': configStore.llmConfigs.length > 0 }"
        >
          默认模型: {{ configStore.defaultModel || '未设置' }}
        </span>
      </div>

      <div class="model-list">
        <div v-for="(config, index) in configStore.llmConfigs" :key="index" class="model-item">
          <div class="model-header" @click="toggleModelExpand(index)">
            <span class="model-name">{{ config.model_name || '未命名模型' }}</span>
            <span v-if="configStore.defaultModel === config.model_name" class="default-badge"
              >默认</span
            >
            <span class="expand-state">{{ expandedModels.has(index) ? '收起' : '展开' }}</span>
            <div class="model-actions">
              <button
                class="sm-button sm-button--small"
                :disabled="testingModelIndex === index"
                @click.stop="testModelConnection(index)"
              >
                {{ testingModelIndex === index ? '测试中...' : '测试' }}
              </button>
              <button
                v-if="configStore.defaultModel !== config.model_name"
                class="sm-button sm-button--small"
                @click.stop="setDefaultModel(config.model_name)"
              >
                设为默认
              </button>
              <button
                class="sm-button sm-button--small sm-button--danger model-action--danger"
                @click.stop="deleteModel(index)"
              >
                删除
              </button>
            </div>
          </div>
          <div v-if="expandedModels.has(index)" class="model-details">
            <div class="form-group">
              <label>API Base URL</label>
              <input
                :value="config.base_url"
                type="text"
                class="sm-input"
                placeholder="https://api.openai.com/v1"
                @input="
                  (e) => updateModelConfig(index, 'base_url', (e.target as HTMLInputElement).value)
                "
              />
            </div>
            <div class="form-group">
              <label>API Key</label>
              <input
                :value="config.api_key"
                type="password"
                class="sm-input"
                placeholder="sk-..."
                @input="
                  (e) => updateModelConfig(index, 'api_key', (e.target as HTMLInputElement).value)
                "
              />
            </div>
            <div class="form-group">
              <label>模型名称</label>
              <input
                :value="config.model_name"
                type="text"
                class="sm-input"
                placeholder="gpt-4"
                @input="
                  (e) =>
                    updateModelConfig(index, 'model_name', (e.target as HTMLInputElement).value)
                "
              />
            </div>
          </div>
        </div>

        <div
          v-if="configStore.llmConfigs.length === 0 && !showNewModelForm"
          class="sm-settings-empty"
        >
          <p>暂无模型配置</p>
        </div>
      </div>

      <div v-if="showNewModelForm" class="new-model-form">
        <h3 class="form-section-title">添加新模型配置</h3>
        <div class="form-group">
          <label>API Base URL <span class="required">*</span></label>
          <input
            v-model="newModelConfig.base_url"
            type="text"
            class="sm-input"
            placeholder="https://api.openai.com/v1"
          />
        </div>
        <div class="form-group">
          <label>API Key <span class="required">*</span></label>
          <input
            v-model="newModelConfig.api_key"
            type="password"
            class="sm-input"
            placeholder="sk-..."
          />
        </div>
        <div class="form-group">
          <label>模型名称 <span class="required">*</span></label>
          <input
            v-model="newModelConfig.model_name"
            type="text"
            class="sm-input"
            placeholder="gpt-4"
          />
        </div>
        <div class="form-actions">
          <button class="sm-button" @click="resetNewModelForm">取消</button>
          <button
            class="sm-button sm-button--secondary"
            :disabled="testingNewModel"
            @click="testNewModelConnection"
          >
            {{ testingNewModel ? '测试中...' : '测试连接' }}
          </button>
          <button class="sm-button sm-button--primary" @click="addNewModel">添加</button>
        </div>
      </div>

      <button
        v-if="!showNewModelForm"
        class="sm-button add-model-btn"
        @click="showNewModelForm = true"
      >
        添加模型配置
      </button>
    </section>

    <div class="save-actions">
      <button
        class="sm-button sm-button--primary"
        :disabled="configStore.saving"
        @click="handleSave"
      >
        {{ configStore.saving ? '保存中...' : '保存配置' }}
      </button>
    </div>
  </div>
</template>

<style scoped>
.model-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.model-item {
  background: var(--sm-color-surface-2);
  border: 1px solid var(--sm-color-border-default);
  border-radius: var(--sm-radius-md);
  overflow: hidden;
}

.model-header {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 12px 16px;
  cursor: pointer;
  transition: background-color var(--sm-transition-fast);
}

.model-header:hover {
  background: var(--sm-color-surface-hover);
}

.model-name {
  flex: 1;
  font-weight: 500;
  color: var(--sm-color-text-primary);
}

.expand-state {
  font-size: 12px;
  color: var(--sm-color-text-tertiary);
}

.default-badge {
  padding: 3px 8px;
  border: 1px solid var(--sm-color-border-accent);
  border-radius: 999px;
  background: var(--sm-color-accent-12);
  color: var(--sm-color-accent-hover);
  font-size: 11px;
  font-weight: 600;
}

.model-actions {
  display: flex;
  gap: 8px;
}

.model-details {
  padding: 16px;
  border-top: 1px solid var(--sm-color-border-subtle);
  background: var(--sm-color-surface-1);
}

.form-group label {
  color: var(--sm-color-text-secondary);
}

.required {
  color: var(--sm-color-status-danger);
}

.form-section-title {
  margin: 0 0 16px;
  font-size: 14px;
  font-weight: 600;
  color: var(--sm-color-text-primary);
}

.new-model-form {
  padding: 16px;
  border: 1px solid var(--sm-color-border-default);
  border-radius: var(--sm-radius-md);
  background: var(--sm-color-surface-2);
}

.add-model-btn {
  width: 100%;
  padding: 12px;
  border-style: dashed;
  color: var(--sm-color-text-secondary);
}

.add-model-btn:hover {
  color: var(--sm-color-accent-hover);
  border-color: var(--sm-color-border-accent);
}

.model-action--danger {
  color: var(--sm-color-status-danger);
}

.save-actions {
  display: flex;
  justify-content: flex-end;
}

@media (max-width: 720px) {
  .model-header {
    flex-wrap: wrap;
  }

  .model-actions,
  .save-actions {
    width: 100%;
    justify-content: flex-end;
  }
}
</style>
