// src/renderer/src/components/embedding/EmbeddingModelForm.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue'
import type { EmbeddingConfig } from '@shared/types/config'

interface Props {
  existingNames?: string[]
  editingName?: string
  editingConfig?: EmbeddingConfig | null
}

interface Emits {
  (e: 'submit', name: string, config: EmbeddingConfig): void
  (e: 'cancel'): void
  (e: 'test', config: EmbeddingConfig): void
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

// 表单数据
const displayName = ref('')
const baseUrl = ref('')
const apiKey = ref('')
const modelName = ref('')
const dimensions = ref('1536')
const enabled = ref(true)

// 名称冲突提示
const nameConflictError = ref('')
const dimensionError = ref('')

const testing = ref(false)
const testResult = ref<{ type: 'success' | 'error'; message: string } | null>(null)

// 如果是编辑模式，加载现有配置
onMounted(() => {
  if (props.editingConfig && props.editingName) {
    displayName.value = props.editingName
    baseUrl.value = props.editingConfig.baseUrl || ''
    apiKey.value = props.editingConfig.apiKey || ''
    modelName.value = props.editingConfig.model || ''
    dimensions.value = String(props.editingConfig.dimensions || 1536)
    enabled.value = props.editingConfig.enabled !== false
  }
})

// 监听显示名称变化，检查冲突
watch(displayName, (newName) => {
  if (!newName.trim()) {
    nameConflictError.value = ''
    return
  }

  // 如果是编辑模式，不与当前编辑的名称比较
  if (props.editingName === newName) {
    nameConflictError.value = ''
    return
  }

  // 检查是否与其他模型名称冲突
  if (props.existingNames && props.existingNames.includes(newName)) {
    nameConflictError.value = '该名称已被使用，请更换'
  } else {
    nameConflictError.value = ''
  }
})

// 验证向量维度
function validateDimension(value: string): boolean {
  const num = Number(value)
  if (!value.trim()) {
    dimensionError.value = '请输入向量维度'
    return false
  }
  if (isNaN(num)) {
    dimensionError.value = '请输入有效的数字'
    return false
  }
  if (!Number.isInteger(num)) {
    dimensionError.value = '向量维度必须是整数'
    return false
  }
  if (num <= 0) {
    dimensionError.value = '向量维度必须大于0'
    return false
  }
  dimensionError.value = ''
  return true
}

// 验证表单
function validateForm(): string | null {
  if (!displayName.value.trim()) {
    return '请输入显示名称'
  }
  if (nameConflictError.value) {
    return nameConflictError.value
  }
  if (!baseUrl.value.trim()) {
    return '请输入API基础URL'
  }
  if (!apiKey.value.trim()) {
    return '请输入API密钥'
  }
  if (!modelName.value.trim()) {
    return '请输入模型名称'
  }
  if (!validateDimension(dimensions.value)) {
    return dimensionError.value
  }
  return null
}

// 提交表单
function handleSubmit(): void {
  const error = validateForm()
  if (error) {
    testResult.value = { type: 'error', message: error }
    return
  }

  const config: EmbeddingConfig = {
    baseUrl: baseUrl.value.trim(),
    apiKey: apiKey.value.trim(),
    model: modelName.value.trim(),
    dimensions: parseInt(dimensions.value, 10),
    enabled: enabled.value,
    displayName: displayName.value.trim(),
    createdAt: props.editingConfig?.createdAt || new Date().toISOString()
  }

  emit('submit', displayName.value.trim(), config)
}

// 测试连接
async function handleTestConnection(): Promise<void> {
  const error = validateForm()
  if (error) {
    testResult.value = { type: 'error', message: error }
    return
  }

  testing.value = true
  testResult.value = null

  const config: EmbeddingConfig = {
    baseUrl: baseUrl.value.trim(),
    apiKey: apiKey.value.trim(),
    model: modelName.value.trim(),
    dimensions: parseInt(dimensions.value, 10),
    enabled: enabled.value,
    displayName: displayName.value.trim(),
    createdAt: new Date().toISOString()
  }

  try {
    emit('test', config)
  } finally {
    testing.value = false
  }
}
</script>

<template>
  <div class="form-container">
    <h3>{{ editingName ? '编辑' : '添加' }}嵌入模型</h3>

    <form @submit.prevent="handleSubmit">
      <!-- 显示名称 -->
      <div class="form-group">
        <label class="form-label">显示名称 *</label>
        <input
          v-model="displayName"
          type="text"
          class="form-input"
          :class="{ 'input-error': nameConflictError }"
          placeholder="例如: OpenAI Embedding Small"
          required
        />
        <span v-if="nameConflictError" class="error-message">{{ nameConflictError }}</span>
      </div>

      <!-- API 基础URL -->
      <div class="form-group">
        <label class="form-label">API 基础URL *</label>
        <input
          v-model="baseUrl"
          type="url"
          class="form-input"
          placeholder="https://api.openai.com/v1"
          required
        />
      </div>

      <!-- API 密钥 -->
      <div class="form-group">
        <label class="form-label">API 密钥 *</label>
        <input v-model="apiKey" type="password" class="form-input" placeholder="sk-..." required />
      </div>

      <!-- 模型名称 -->
      <div class="form-group">
        <label class="form-label">模型名称 *</label>
        <input
          v-model="modelName"
          type="text"
          class="form-input"
          placeholder="text-embedding-3-small"
          required
        />
      </div>

      <!-- 向量维度 -->
      <div class="form-group">
        <label class="form-label">向量维度 *</label>
        <input
          v-model="dimensions"
          type="text"
          class="form-input"
          :class="{ 'input-error': dimensionError }"
          placeholder="1536"
          @input="validateDimension(dimensions)"
          required
        />
        <span v-if="dimensionError" class="error-message">{{ dimensionError }}</span>
      </div>

      <!-- 测试结果 -->
      <div v-if="testResult" class="test-result" :class="testResult.type">
        {{ testResult.message }}
      </div>

      <!-- 按钮组 -->
      <div class="form-actions">
        <button type="button" class="btn btn-secondary" @click="emit('cancel')">取消</button>
        <button
          type="button"
          class="btn btn-secondary"
          :disabled="testing"
          @click="handleTestConnection"
        >
          {{ testing ? '测试中...' : '测试连接' }}
        </button>
        <button type="submit" class="btn btn-primary">保存</button>
      </div>
    </form>
  </div>
</template>

<style scoped>
.form-container {
  padding: 20px;
  border: 1px solid var(--theme-border);
  border-radius: 8px;
  background: var(--theme-background-secondary);
}

h3 {
  margin: 0 0 20px 0;
  font-size: 18px;
  color: var(--theme-text);
}

.input-error {
  border-color: #f44336 !important;
}
</style>

// src/renderer/src/components/embedding/EmbeddingModelForm.tsx
import { useState, useEffect } from 'react'
import type { EmbeddingConfig } from '@shared/types/config'
import styles from './EmbeddingModelForm.module.css'

interface EmbeddingModelFormProps {
  existingNames?: string[]
  editingName?: string
  editingConfig?: EmbeddingConfig | null
  onSubmit: (name: string, config: EmbeddingConfig) => void
  onCancel: () => void
  onTest: (config: EmbeddingConfig) => void
}

/** 验证向量维度，返回是否有效 */
function validateDimension(value: string): string {
  const num = Number(value)
  if (!value.trim()) return '请输入向量维度'
  if (isNaN(num)) return '请输入有效的数字'
  if (!Number.isInteger(num)) return '向量维度必须是整数'
  if (num <= 0) return '向量维度必须大于0'
  return ''
}

export default function EmbeddingModelForm({
  existingNames,
  editingName,
  editingConfig,
  onSubmit,
  onCancel,
  onTest
}: EmbeddingModelFormProps) {
  // 表单数据
  const [displayName, setDisplayName] = useState('')
  const [provider, setProvider] = useState<EmbeddingConfig['provider']>('custom')
  const [baseUrl, setBaseUrl] = useState('')
  const [apiKey, setApiKey] = useState('')
  const [modelName, setModelName] = useState('')
  const [dimensions, setDimensions] = useState('1536')
  const [enabled, setEnabled] = useState(true)

  // 验证错误
  const [nameConflictError, setNameConflictError] = useState('')
  const [dimensionError, setDimensionError] = useState('')
  const [formError, setFormError] = useState('')

  // 如果是编辑模式，加载现有配置
  useEffect(() => {
    if (editingConfig && editingName) {
      setDisplayName(editingName)
      setProvider(editingConfig.provider || 'custom')
      setBaseUrl(editingConfig.baseUrl || '')
      setApiKey(editingConfig.apiKey || '')
      setModelName(editingConfig.model || '')
      setDimensions(String(editingConfig.dimensions || 1536))
      setEnabled(editingConfig.enabled !== false)
    }
  }, [editingConfig, editingName])

  // 监听显示名称变化，检查冲突
  useEffect(() => {
    if (!displayName.trim()) {
      setNameConflictError('')
      return
    }
    // 编辑模式下不与当前名称比较
    if (editingName === displayName) {
      setNameConflictError('')
      return
    }
    if (existingNames && existingNames.includes(displayName)) {
      setNameConflictError('该名称已被使用，请更换')
    } else {
      setNameConflictError('')
    }
  }, [displayName, editingName, existingNames])

  // 构建配置对象
  function buildConfig(): EmbeddingConfig {
    return {
      provider,
      baseUrl: baseUrl.trim(),
      apiKey: apiKey.trim(),
      model: modelName.trim(),
      dimensions: parseInt(dimensions, 10),
      enabled,
      displayName: displayName.trim(),
      createdAt: editingConfig?.createdAt || new Date().toISOString()
    }
  }

  // 验证表单
  function validateForm(): string | null {
    if (!displayName.trim()) return '请输入显示名称'
    if (nameConflictError) return nameConflictError
    if (!baseUrl.trim()) return '请输入API基础URL'
    if (!apiKey.trim()) return '请输入API密钥'
    if (!modelName.trim()) return '请输入模型名称'
    const dimErr = validateDimension(dimensions)
    if (dimErr) return dimErr
    return null
  }

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    const error = validateForm()
    if (error) {
      setFormError(error)
      return
    }
    onSubmit(displayName.trim(), buildConfig())
  }

  function handleTestConnection() {
    const error = validateForm()
    if (error) {
      setFormError(error)
      return
    }
    onTest(buildConfig())
  }

  function handleDimensionChange(value: string) {
    setDimensions(value)
    setDimensionError(validateDimension(value))
  }

  return (
    <div className={styles['new-model-form']}>
      <h3 className={styles['form-section-title']}>{editingName ? '编辑' : '添加'}嵌入模型</h3>

      <form onSubmit={handleSubmit}>
        {/* 显示名称 */}
        <div className={styles['form-group']}>
          <label>
            显示名称 <span className={styles.required}>*</span>
          </label>
          <input
            type="text"
            className={['sm-input', nameConflictError && styles['input-error']]
              .filter(Boolean)
              .join(' ')}
            placeholder="例如: OpenAI Embedding Small"
            value={displayName}
            onChange={(e) => setDisplayName(e.target.value)}
          />
          {nameConflictError && (
            <span className={styles['error-message']}>{nameConflictError}</span>
          )}
        </div>

        {/* API 基础URL */}
        <div className={styles['form-group']}>
          <label>
            API 基础URL <span className={styles.required}>*</span>
          </label>
          <input
            type="url"
            className="sm-input"
            placeholder="https://api.openai.com/v1"
            value={baseUrl}
            onChange={(e) => setBaseUrl(e.target.value)}
          />
        </div>

        {/* API 密钥 */}
        <div className={styles['form-group']}>
          <label>
            API 密钥 <span className={styles.required}>*</span>
          </label>
          <input
            type="password"
            className="sm-input"
            placeholder="sk-..."
            value={apiKey}
            onChange={(e) => setApiKey(e.target.value)}
          />
        </div>

        {/* 模型名称 */}
        <div className={styles['form-group']}>
          <label>
            模型名称 <span className={styles.required}>*</span>
          </label>
          <input
            type="text"
            className="sm-input"
            placeholder="text-embedding-3-small"
            value={modelName}
            onChange={(e) => setModelName(e.target.value)}
          />
        </div>

        {/* 向量维度 */}
        <div className={styles['form-group']}>
          <label>
            向量维度 <span className={styles.required}>*</span>
          </label>
          <input
            type="text"
            className={['sm-input', dimensionError && styles['input-error']]
              .filter(Boolean)
              .join(' ')}
            placeholder="1536"
            value={dimensions}
            onChange={(e) => handleDimensionChange(e.target.value)}
          />
          {dimensionError && <span className={styles['error-message']}>{dimensionError}</span>}
        </div>

        {/* 表单错误 */}
        {formError && (
          <div className={[styles['test-result'], styles.error].join(' ')}>{formError}</div>
        )}

        {/* 按钮组 */}
        <div className={styles['form-actions']}>
          <button type="button" className="sm-button" onClick={onCancel}>
            取消
          </button>
          <button
            type="button"
            className="sm-button sm-button--secondary"
            onClick={handleTestConnection}
          >
            测试连接
          </button>
          <button type="submit" className="sm-button sm-button--primary">
            保存
          </button>
        </div>
      </form>
    </div>
  )
}
