// src/renderer/src/components/paper/chat/PaperChatInput.tsx
import { useCallback, useEffect, useRef, useState } from 'react'
import type {
  AttachedDocument,
  AttachedImage,
  KnowledgeBase,
  MCPTool,
  UserInteractionRequest
} from '@renderer/types'
import type { AppConfig } from '@renderer/types'
import type { PaperQuote } from '@shared/types/chat'
import SvgIcon from '@renderer/components/icons/SvgIcon'
import { useUIStateStore } from '@renderer/stores/uiStateStore'
import {
  usePaperChatDocumentUploadStore,
  type ProcessingFile
} from '@renderer/stores/paperChatDocumentUploadStore'
import {
  isImageFile,
  usePaperChatImageUploadStore,
  type ProcessingImage
} from '@renderer/stores/paperChatImageUploadStore'
import { usePaperChatQuoteStore } from '@renderer/stores/paperChatQuoteStore'
import {
  SUPPORTED_DOC_ACCEPT,
  formatFileSize,
  toPaperChatAttachedDocuments,
  toPaperChatAttachedImages
} from './input/attachmentUtils'
import PaperChatToolSelectionBar from './input/PaperChatToolSelectionBar'
import inputStyles from './PaperChatInput.module.css'
import toolbarStyles from './input/PaperChatToolSelectionBar.module.css'
import textareaStyles from './input/PaperChatTextarea.module.css'
import docStyles from './input/PaperChatAttachedDocuments.module.css'
import imageStyles from './input/PaperChatAttachedImages.module.css'
import quoteStyles from './input/PaperChatAttachedQuotes.module.css'
import processingStyles from './input/PaperChatProcessingFiles.module.css'

interface QuickReplyOption {
  id: string
  label: string
  fullText: string
}

export interface PaperChatQuickReply {
  messageId: string
  question: string
  options: QuickReplyOption[]
  suffix?: string
}

interface PaperChatInputProps {
  sessionId: string
  inputMessage: string
  selectedModel: string
  selectedMCPTools: MCPTool[]
  selectedKnowledgeBases: KnowledgeBase[]
  enableLabTools: boolean
  enablePaperWebSearch: boolean
  isSending: boolean
  disabled?: boolean
  compact?: boolean
  quickReply?: PaperChatQuickReply | null
  userInteraction?: UserInteractionRequest | null
  showUserInteraction?: boolean
  onUpdateInput: (value: string) => void
  onUpdateSelectedModel: (value: string) => void
  onUpdateSelectedTools: (value: MCPTool[]) => void
  onUpdateSelectedKnowledgeBases: (value: KnowledgeBase[]) => void
  onUpdateEnableLabTools: (value: boolean) => void
  onUpdateEnablePaperWebSearch: (value: boolean) => void
  onEnablePaperWebSearch?: () => Promise<boolean>
  onDismissQuickReply?: (messageId: string) => void
  onHideUserInteraction?: () => void
  onSend: (
    content: string,
    attachedDocuments?: AttachedDocument[],
    attachedImages?: AttachedImage[],
    attachedQuotes?: PaperQuote[]
  ) => Promise<void>
  onStop: () => Promise<void>
}

function useConfiguredModels(
  selectedModel: string,
  updateSelectedModel: (value: string) => void
): string[] {
  const configUpdateKey = useUIStateStore((s) => s.configUpdateKey)
  const [modelOptions, setModelOptions] = useState<string[]>([])

  useEffect(() => {
    let cancelled = false

    async function loadConfiguredModels(): Promise<void> {
      try {
        const config = (await window.api.config.getConfig()) as AppConfig | null
        const models = config?.llm_config?.models?.map((model) => model.model_name) || []
        if (cancelled) return
        setModelOptions(models)

        if (selectedModel && models.includes(selectedModel)) {
          return
        }

        const defaultModel = config?.llm_config?.default_model
        if (defaultModel && models.includes(defaultModel)) {
          updateSelectedModel(defaultModel)
        } else {
          updateSelectedModel(models[0] || '')
        }
      } catch (error) {
        window.api.logger.error('[PaperChatInput] 加载模型配置失败', {
          error: error instanceof Error ? error.message : String(error)
        })
        if (!cancelled) {
          setModelOptions([])
          if (selectedModel) updateSelectedModel('')
        }
      }
    }

    void loadConfiguredModels()

    return () => {
      cancelled = true
    }
  }, [configUpdateKey, selectedModel, updateSelectedModel])

  return modelOptions
}

function quotePreview(quote: PaperQuote): string {
  const text = quote.selectedText.replace(/\s+/g, ' ').trim()
  return text.length > 42 ? `${text.slice(0, 42)}...` : text
}

export default function PaperChatInput({
  sessionId,
  inputMessage,
  selectedModel,
  selectedMCPTools,
  selectedKnowledgeBases,
  enableLabTools,
  enablePaperWebSearch,
  isSending,
  disabled,
  compact = false,
  quickReply,
  userInteraction,
  showUserInteraction,
  onUpdateInput,
  onUpdateSelectedModel,
  onUpdateSelectedTools,
  onUpdateSelectedKnowledgeBases,
  onUpdateEnableLabTools,
  onUpdateEnablePaperWebSearch,
  onEnablePaperWebSearch,
  onDismissQuickReply,
  onHideUserInteraction,
  onSend,
  onStop
}: PaperChatInputProps) {
  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)
  const [isDragging, setIsDragging] = useState(false)
  const [attachmentError, setAttachmentError] = useState('')

  const modelOptions = useConfiguredModels(selectedModel, onUpdateSelectedModel)
  const pendingDocuments = usePaperChatDocumentUploadStore((s) =>
    sessionId ? s.getSessionDocuments(sessionId) : []
  )
  const processingFiles = usePaperChatDocumentUploadStore((s) =>
    sessionId ? s.getSessionProcessingFiles(sessionId) : []
  )
  const pendingImages = usePaperChatImageUploadStore((s) =>
    sessionId ? s.getSessionImages(sessionId) : []
  )
  const processingImages = usePaperChatImageUploadStore((s) =>
    sessionId ? s.getSessionProcessingImages(sessionId) : []
  )
  const pendingQuotes = usePaperChatQuoteStore((s) =>
    sessionId ? s.getSessionQuotes(sessionId) : []
  )

  const hasAttachments =
    pendingDocuments.length > 0 || pendingImages.length > 0 || pendingQuotes.length > 0
  const totalAttachmentCount = pendingDocuments.length + pendingImages.length + pendingQuotes.length
  const canSend = Boolean(inputMessage.trim() || hasAttachments) && !disabled && !isSending

  useEffect(() => {
    if (!sessionId) return
    usePaperChatDocumentUploadStore.getState().initSession(sessionId)
    usePaperChatImageUploadStore.getState().initSession(sessionId)
    usePaperChatQuoteStore.getState().initSession(sessionId)
  }, [sessionId])

  async function handleFiles(files: File[]): Promise<void> {
    if (!sessionId || files.length === 0) return
    setAttachmentError('')
    const imageFiles = files.filter(isImageFile)
    const documentFiles = files.filter((file) => !isImageFile(file))

    try {
      if (imageFiles.length > 0) {
        const result = await usePaperChatImageUploadStore
          .getState()
          .addImages(sessionId, imageFiles)
        if (result.errors.length > 0) {
          setAttachmentError(result.errors.join('；'))
        }
      }
      if (documentFiles.length > 0) {
        await usePaperChatDocumentUploadStore
          .getState()
          .uploadMultipleDocuments(sessionId, documentFiles)
      }
    } catch (error) {
      setAttachmentError(error instanceof Error ? error.message : String(error))
    }
  }

  async function handleSend(contentOverride?: string): Promise<void> {
    const content = contentOverride ?? inputMessage
    const docs = toPaperChatAttachedDocuments(
      usePaperChatDocumentUploadStore.getState().getPendingDocumentsForSending(sessionId)
    )
    const images = toPaperChatAttachedImages(
      usePaperChatImageUploadStore.getState().getSessionImages(sessionId)
    )
    const quotes = usePaperChatQuoteStore.getState().getPendingQuotesForSending(sessionId)

    await onSend(content, docs, images, quotes)
    onUpdateInput('')
    usePaperChatDocumentUploadStore.getState().clearPendingDocuments(sessionId)
    usePaperChatImageUploadStore.getState().clearImages(sessionId)
    usePaperChatQuoteStore.getState().clearQuotes(sessionId)
    onDismissQuickReply?.(quickReply?.messageId || '')
    onHideUserInteraction?.()
  }

  const togglePaperWebSearch = useCallback(async (): Promise<void> => {
    if (enablePaperWebSearch) {
      onUpdateEnablePaperWebSearch(false)
      return
    }
    const allowed = (await onEnablePaperWebSearch?.()) ?? true
    if (allowed) {
      onUpdateEnablePaperWebSearch(true)
    }
  }, [enablePaperWebSearch, onEnablePaperWebSearch, onUpdateEnablePaperWebSearch])

  return (
    <div
      className={[
        inputStyles['paper-chat-input'],
        'paper-chat-input',
        compact ? inputStyles['paper-chat-input--compact'] : '',
        compact ? 'paper-chat-input--compact' : ''
      ]
        .filter(Boolean)
        .join(' ')}
      onDragEnter={(event) => {
        event.preventDefault()
        setIsDragging(true)
      }}
      onDragOver={(event) => {
        event.preventDefault()
        setIsDragging(true)
      }}
      onDragLeave={(event) => {
        event.preventDefault()
        setIsDragging(false)
      }}
      onDrop={(event) => {
        event.preventDefault()
        setIsDragging(false)
        void handleFiles(Array.from(event.dataTransfer.files))
      }}
    >
      {quickReply && quickReply.options.length > 0 && !isSending && (
        <div className={inputStyles['paper-chat-input__quick-reply']}>
          <div className={inputStyles['paper-chat-input__quick-reply-header']}>
            <span className={inputStyles['paper-chat-input__quick-reply-title']}>
              {quickReply.question || '选择一个回复'}
            </span>
            <button
              className={inputStyles['paper-chat-input__quick-reply-custom-button']}
              type="button"
              onClick={() => onDismissQuickReply?.(quickReply.messageId)}
            >
              自定义
            </button>
          </div>
          <div className={toolbarStyles['paper-chat-input-toolbar']}>
            {quickReply.options.map((option) => (
              <button
                key={option.id}
                className="sm-button sm-button--secondary"
                type="button"
                onClick={() => handleSend(option.fullText)}
              >
                {option.label}
              </button>
            ))}
          </div>
        </div>
      )}

      {showUserInteraction && userInteraction && !isSending && (
        <div className={inputStyles['paper-chat-input__quick-reply']}>
          <div className={inputStyles['paper-chat-input__quick-reply-header']}>
            <span className={inputStyles['paper-chat-input__quick-reply-title']}>
              {userInteraction.question}
            </span>
            <button
              className={inputStyles['paper-chat-input__quick-reply-custom-button']}
              type="button"
              onClick={onHideUserInteraction}
            >
              稍后
            </button>
          </div>
          <div className={toolbarStyles['paper-chat-input-toolbar']}>
            {userInteraction.options.map((option) => (
              <button
                key={option.value}
                className="sm-button sm-button--secondary"
                type="button"
                title={option.description}
                onClick={() => handleSend(`我选择：${option.label}`)}
              >
                {option.label}
              </button>
            ))}
          </div>
        </div>
      )}

      {attachmentError && (
        <div className={inputStyles['paper-chat-input__warning']}>
          <span className={inputStyles['paper-chat-input__warning-label']}>附件</span>
          <span>{attachmentError}</span>
        </div>
      )}

      {pendingDocuments.length > 0 && (
        <div className={docStyles['paper-chat-input__pending-documents']}>
          {pendingDocuments.map((doc, index) => (
            <div
              key={`${doc.fileName}-${index}`}
              className={docStyles['paper-chat-input__pending-document']}
            >
              <span className={docStyles['paper-chat-input__pending-document-info']}>
                <span className={docStyles['paper-chat-input__pending-document-name']}>
                  {doc.fileName}
                </span>
                <span className={docStyles['paper-chat-input__pending-document-size']}>
                  {formatFileSize(doc.fileSize)}
                </span>
              </span>
              <button
                className={docStyles['paper-chat-input__pending-document-remove']}
                type="button"
                disabled={isSending}
                onClick={() =>
                  usePaperChatDocumentUploadStore.getState().removePendingDocument(sessionId, index)
                }
              >
                ×
              </button>
            </div>
          ))}
        </div>
      )}

      {pendingImages.length > 0 && (
        <div className={imageStyles['paper-chat-input__pending-images']}>
          {pendingImages.map((image, index) => (
            <div
              key={`${image.fileName}-${index}`}
              className={imageStyles['paper-chat-input__pending-image']}
            >
              <img
                className={imageStyles['paper-chat-input__pending-image-thumbnail']}
                src={image.thumbnailData}
                alt={image.fileName}
              />
              <span className={imageStyles['paper-chat-input__pending-image-info']}>
                <span className={imageStyles['paper-chat-input__pending-image-name']}>
                  {image.fileName}
                </span>
                <span className={imageStyles['paper-chat-input__pending-image-size']}>
                  {formatFileSize(image.compressedSize)}
                </span>
              </span>
              <button
                className={imageStyles['paper-chat-input__pending-image-remove']}
                type="button"
                disabled={isSending}
                onClick={() =>
                  usePaperChatImageUploadStore.getState().removeImage(sessionId, index)
                }
              >
                ×
              </button>
            </div>
          ))}
        </div>
      )}

      {pendingQuotes.length > 0 && (
        <div className={quoteStyles['paper-chat-input__pending-quotes']}>
          {pendingQuotes.map((quote) => (
            <div key={quote.id} className={quoteStyles['paper-chat-input__pending-quote']}>
              <SvgIcon
                className={quoteStyles['paper-chat-input__pending-quote-icon']}
                name="quote"
                size={12}
              />
              <span className={quoteStyles['paper-chat-input__pending-quote-label']}>
                {quote.viewKind === 'original' ? '原文引用' : '译文引用'}
              </span>
              <span className={quoteStyles['paper-chat-input__pending-quote-preview']}>
                {quotePreview(quote)}
              </span>
              {quote.surroundingContext?.contextualText.trim() && (
                <span className={quoteStyles['paper-chat-input__pending-quote-context']}>
                  上下文
                </span>
              )}
              <button
                className={quoteStyles['paper-chat-input__pending-quote-remove']}
                type="button"
                disabled={isSending}
                onClick={() => usePaperChatQuoteStore.getState().removeQuote(sessionId, quote.id)}
              >
                ×
              </button>
            </div>
          ))}
        </div>
      )}

      {(processingFiles.length > 0 || processingImages.length > 0) && (
        <div className={processingStyles['processing-files-list']}>
          {[...processingFiles, ...processingImages].map((file) => (
            <ProcessingFileRow key={file.tempId} file={file} />
          ))}
        </div>
      )}

      <div className={textareaStyles['paper-chat-input__textarea-wrapper']}>
        <textarea
          ref={textareaRef}
          className={[
            textareaStyles['paper-chat-input__textarea'],
            'paper-chat-input__textarea',
            isSending ? textareaStyles['is-sending'] || '' : '',
            isSending ? 'is-sending' : '',
            isDragging ? textareaStyles['is-dragging'] || '' : '',
            isDragging ? 'is-dragging' : ''
          ]
            .filter(Boolean)
            .join(' ')}
          value={inputMessage}
          disabled={disabled || isSending}
          placeholder={
            quickReply
              ? '输入自定义回答，或点击上方快捷选项 ...'
              : '输入命令或消息，可拖拽文件或粘贴图片上传 ...'
          }
          onChange={(event) => onUpdateInput(event.target.value)}
          onPaste={(event) => {
            const files = Array.from(event.clipboardData.files)
            if (files.length > 0) {
              void handleFiles(files)
            }
          }}
          onKeyDown={(event) => {
            if (event.key === 'Enter' && !event.shiftKey) {
              event.preventDefault()
              if (canSend) void handleSend()
            }
          }}
        />
        {isDragging && (
          <div className={textareaStyles['paper-chat-input__drag-overlay']}>
            <div className={textareaStyles['paper-chat-input__drag-hint']}>
              <SvgIcon name="attachment" size={24} />
              <p>释放以添加附件</p>
            </div>
          </div>
        )}
      </div>

      <PaperChatToolSelectionBar
        isSending={isSending}
        disabled={disabled}
        canSend={canSend}
        variant={compact ? 'compact' : 'default'}
        selectedModel={selectedModel}
        modelOptions={modelOptions}
        selectedTools={selectedMCPTools}
        selectedKnowledgeBases={selectedKnowledgeBases}
        enableLabTools={enableLabTools}
        enablePaperWebSearch={enablePaperWebSearch}
        totalAttachmentCount={totalAttachmentCount}
        onUpdateSelectedModel={onUpdateSelectedModel}
        onUpdateSelectedTools={onUpdateSelectedTools}
        onUpdateSelectedKnowledgeBases={onUpdateSelectedKnowledgeBases}
        onUpdateEnableLabTools={onUpdateEnableLabTools}
        onTogglePaperWebSearch={() => void togglePaperWebSearch()}
        onUpload={() => fileInputRef.current?.click()}
        onSend={() => void handleSend()}
        onStop={() => void onStop()}
      />

      <input
        ref={fileInputRef}
        type="file"
        multiple
        hidden
        accept={`${SUPPORTED_DOC_ACCEPT},image/*`}
        onChange={(event) => {
          const files = Array.from(event.target.files || [])
          event.currentTarget.value = ''
          void handleFiles(files)
        }}
      />
    </div>
  )
}

function ProcessingFileRow({ file }: { file: ProcessingFile | ProcessingImage }) {
  return (
    <div className={processingStyles['processing-file-item']}>
      <span
        className={`${processingStyles['processing-status']} ${processingStyles[file.status] || ''}`}
      >
        <span>{file.fileName}</span>
        <span>{file.status}</span>
        {'error' in file && file.error && (
          <span className={processingStyles['processing-error']}>{file.error}</span>
        )}
      </span>
    </div>
  )
}

// src/renderer/src/components/paper/chat/PaperChatInput.vue
<script setup lang="ts">
import { computed, inject, ref, unref, watch, type ComputedRef, type Ref } from 'vue'
import { useZustandStore } from '@renderer/composables/useZustandStore'
import PaperChatInteractionOptions from './input/PaperChatInteractionOptions.vue'
import PaperChatOptions from './input/PaperChatOptions.vue'
import PaperChatAttachedDocuments from './input/PaperChatAttachedDocuments.vue'
import PaperChatAttachedImages from './input/PaperChatAttachedImages.vue'
import PaperChatAttachedQuotes from './input/PaperChatAttachedQuotes.vue'
import PaperChatTextarea from './input/PaperChatTextarea.vue'
import PaperChatProcessingFiles from './input/PaperChatProcessingFiles.vue'
import PaperChatToolSelectionBar from './input/PaperChatToolSelectionBar.vue'
import { usePaperChatConfiguredModels } from './input/usePaperChatConfiguredModels'
import { usePaperChatDocumentUpload } from './input/usePaperChatDocumentUpload'
import { usePaperChatFileDragDrop } from './input/usePaperChatFileDragDrop'
import { usePaperChatImageUpload } from './input/usePaperChatImageUpload'
import { toPaperChatAttachedDocuments, toPaperChatAttachedImages } from './input/attachmentUtils'
import { isImageFile } from '@renderer/stores/paperChatImageUploadStore'
import { usePaperChatQuoteStore } from '@renderer/stores/paperChatQuoteStore'
import type { KnowledgeBase, MCPTool } from '@renderer/types'
import { useNotification } from '@renderer/composables/useNotification'
import { usePaperChatStreamStore } from '@renderer/stores'
import type { AttachedDocument, AttachedImage, PaperQuote } from '@shared/types/chat'
import type { MessageOptionContext, ParsedOption } from '@renderer/utils/optionParser'
import styles from './PaperChatInput.module.css'

type InjectedSessionId = string | Ref<string> | ComputedRef<string>

const props = defineProps<{
  isSending?: boolean
  inputMessage?: string
  selectedModel?: string
  selectedMCPTools?: MCPTool[]
  selectedKnowledgeBases?: KnowledgeBase[]
  enableLabTools?: boolean
  enablePaperWebSearch?: boolean
  quickReplyInfo?: MessageOptionContext | null
  variant?: 'default' | 'compact'
}>()

const emit = defineEmits<{
  (
    e: 'send',
    message: string,
    model: string,
    selectedMCPTools: MCPTool[],
    selectedKnowledgeBases: KnowledgeBase[],
    enableLabTools: boolean,
    attachedDocuments: AttachedDocument[],
    attachedImages: AttachedImage[],
    attachedQuotes: PaperQuote[]
  ): void
  (e: 'stop'): void
  (e: 'update:inputMessage', value: string): void
  (e: 'update:selectedModel', value: string): void
  (e: 'update:selectedMCPTools', value: MCPTool[]): void
  (e: 'update:selectedKnowledgeBases', value: KnowledgeBase[]): void
  (e: 'update:enableLabTools', value: boolean): void
  (e: 'update:enablePaperWebSearch', value: boolean): void
  (e: 'quick-reply-selected', messageId: string): void
}>()

const sessionId = inject<InjectedSessionId>('sessionId', '')
const TEMP_SESSION_ID = 'temp'

const localInputMessage = ref(props.inputMessage ?? '')
const localSelectedModel = ref(props.selectedModel ?? '')
const localSelectedTools = ref<MCPTool[]>(props.selectedMCPTools ?? [])
const localSelectedKnowledgeBases = ref<KnowledgeBase[]>(props.selectedKnowledgeBases ?? [])
const localEnableLabTools = ref(props.enableLabTools ?? false)
const localEnablePaperWebSearch = ref(props.enablePaperWebSearch ?? false)
const textareaRef = ref<InstanceType<typeof PaperChatTextarea> | null>(null)
const notify = useNotification()

const effectiveSessionId = computed(() => unref(sessionId) || TEMP_SESSION_ID)
const { pendingDocs, processingFiles, uploadDocuments, removePendingDoc, clearPendingDocs } =
  usePaperChatDocumentUpload(effectiveSessionId)
const { pendingImages, addImages, removePendingImage, clearPendingImages } =
  usePaperChatImageUpload(effectiveSessionId)
const paperChatQuoteStore = usePaperChatQuoteStore()
const pendingQuotes = computed(() => paperChatQuoteStore.getSessionQuotes(effectiveSessionId.value))
const totalAttachmentCount = computed(
  () => pendingDocs.value.length + pendingImages.value.length + pendingQuotes.value.length
)

const { modelOptions } = usePaperChatConfiguredModels(localSelectedModel, updateSelectedModel)
const { isDragging, handleDragOver, handleDragLeave, handleDrop, triggerFileUpload } =
  usePaperChatFileDragDrop({
    isSending: () => Boolean(props.isSending),
    uploadDocuments,
    addImages
  })

const paperChatStreamStore = useZustandStore(usePaperChatStreamStore)

watch(
  () => props.inputMessage,
  (value) => {
    if (value !== undefined && value !== localInputMessage.value) {
      localInputMessage.value = value
    }
  },
  { immediate: true }
)

watch(localInputMessage, (value) => {
  if (value !== props.inputMessage) {
    emit('update:inputMessage', value)
  }
})

watch(
  () => props.selectedModel,
  (value) => {
    if (value !== undefined && value !== localSelectedModel.value) {
      localSelectedModel.value = value
    }
  },
  { immediate: true }
)

watch(
  () => props.selectedMCPTools,
  (value) => {
    if (value !== undefined && value !== localSelectedTools.value) {
      localSelectedTools.value = value
    }
  },
  { immediate: true, deep: true }
)

watch(
  () => props.selectedKnowledgeBases,
  (value) => {
    if (value !== undefined && value !== localSelectedKnowledgeBases.value) {
      localSelectedKnowledgeBases.value = value
    }
  },
  { immediate: true, deep: true }
)

watch(
  () => props.enableLabTools,
  (value) => {
    if (value !== undefined && value !== localEnableLabTools.value) {
      localEnableLabTools.value = value
    }
  },
  { immediate: true }
)

watch(
  () => props.enablePaperWebSearch,
  (value) => {
    if (value !== undefined && value !== localEnablePaperWebSearch.value) {
      localEnablePaperWebSearch.value = value
    }
  },
  { immediate: true }
)

function updateSelectedModel(value: string): void {
  localSelectedModel.value = value
  emit('update:selectedModel', value)
}

function updateSelectedTools(tools: MCPTool[]): void {
  localSelectedTools.value = tools
  emit('update:selectedMCPTools', tools)
}

function updateSelectedKnowledgeBases(kbs: KnowledgeBase[]): void {
  localSelectedKnowledgeBases.value = kbs
  emit('update:selectedKnowledgeBases', kbs)
}

function updateEnableLabTools(enabled: boolean): void {
  localEnableLabTools.value = enabled
  emit('update:enableLabTools', enabled)
  window.api.logger.debug('[PaperChatInput] 实验室工具开关状态变更', { enabled })
}

function updateEnablePaperWebSearch(enabled: boolean): void {
  localEnablePaperWebSearch.value = enabled
  emit('update:enablePaperWebSearch', enabled)
}

function buildPaperChatAttachedDocuments(): AttachedDocument[] {
  return toPaperChatAttachedDocuments(pendingDocs.value)
}

function buildPaperChatAttachedImages(): AttachedImage[] {
  return toPaperChatAttachedImages(pendingImages.value)
}

function buildPaperChatAttachedQuotes(): PaperQuote[] {
  return paperChatQuoteStore.getPendingQuotesForSending(effectiveSessionId.value)
}

function clearAttachments(): void {
  clearPendingDocs()
  clearPendingImages()
  paperChatQuoteStore.clearQuotes(effectiveSessionId.value)
}

function sendMessage(message: string): void {
  emit(
    'send',
    message,
    localSelectedModel.value,
    localSelectedTools.value,
    localSelectedKnowledgeBases.value,
    localEnableLabTools.value,
    buildPaperChatAttachedDocuments(),
    buildPaperChatAttachedImages(),
    buildPaperChatAttachedQuotes()
  )

  localInputMessage.value = ''
  emit('update:inputMessage', '')
  clearAttachments()
}

function handleSend(): void {
  const message = localInputMessage.value.trim()
  const hasAttachments =
    pendingDocs.value.length > 0 || pendingImages.value.length > 0 || pendingQuotes.value.length > 0

  if (props.isSending) {
    notify.warning('论文对话', '正在回复中，请稍候再发送...', { source: 'chat' })
    return
  }

  if (!message && !hasAttachments) {
    return
  }

  window.api.logger.debug('[PaperChatInput] 发送消息，选中的工具', {
    count: localSelectedTools.value.length,
    labToolsEnabled: localEnableLabTools.value,
    imageCount: pendingImages.value.length,
    quoteCount: pendingQuotes.value.length
  })

  sendMessage(message)
}

function handleQuickReplySelect(option: ParsedOption): void {
  if (props.isSending || !props.quickReplyInfo) {
    return
  }

  const replyText = option.label.trim()
  if (!replyText) {
    return
  }

  emit('quick-reply-selected', props.quickReplyInfo.messageId)

  window.api.logger.debug('[PaperChatInput] 发送快捷回复', {
    messageId: props.quickReplyInfo.messageId,
    optionId: option.id
  })

  sendMessage(replyText)
}

function focusCustomReply(): void {
  textareaRef.value?.focus()
}

function handleStop(): void {
  emit('stop')
}

function handleKeydown(event: KeyboardEvent): void {
  if (event.key !== 'Enter' || event.isComposing || event.keyCode === 229) {
    return
  }

  if (event.shiftKey) {
    return
  }

  event.preventDefault()
  handleSend()
}

/**
 * 从剪贴板中提取图片文件
 */
function extractClipboardImageFiles(event: ClipboardEvent): File[] {
  const clipboardData = event.clipboardData
  if (!clipboardData) {
    return []
  }

  const filesFromItems = Array.from(clipboardData.items)
    .filter((item) => item.kind === 'file' && item.type.startsWith('image/'))
    .map((item) => item.getAsFile())
    .filter((file): file is File => file !== null)

  if (filesFromItems.length > 0) {
    return filesFromItems
  }

  return Array.from(clipboardData.files).filter(
    (file) => file.type.startsWith('image/') || isImageFile(file)
  )
}

async function handlePaste(event: ClipboardEvent): Promise<void> {
  const imageFiles = extractClipboardImageFiles(event)

  if (imageFiles.length === 0) {
    return
  }

  const hasPlainText = Boolean(event.clipboardData?.getData('text/plain').trim())

  if (!hasPlainText) {
    event.preventDefault()
  }

  if (props.isSending) {
    window.api.logger.warn('[PaperChatInput] 正在回复中，忽略粘贴图片', {
      imageCount: imageFiles.length
    })
    return
  }

  window.api.logger.info('[PaperChatInput] 检测到剪贴板图片', {
    imageCount: imageFiles.length
  })

  const errors = await addImages(imageFiles)

  if (errors.length > 0) {
    window.api.logger.warn('[PaperChatInput] 粘贴图片失败', {
      imageCount: imageFiles.length,
      errors
    })
    notify.error('粘贴图片失败', errors.join('\n'), { source: 'chat' })
  }
}

async function handleUserInteractionSelect(_value: string, label: string): Promise<void> {
  paperChatStreamStore.hideUserInteraction()

  sendMessage(`我选择：${label}`)
}
</script>

<template>
  <div
    :class="[
      styles['paper-chat-input'],
      { [styles['paper-chat-input--compact']]: props.variant === 'compact' }
    ]"
  >
    <PaperChatInteractionOptions
      v-if="paperChatStreamStore.showUserInteraction && paperChatStreamStore.userInteractionInfo"
      :interaction-info="paperChatStreamStore.userInteractionInfo"
      @select="handleUserInteractionSelect"
    />

    <div v-if="props.quickReplyInfo" :class="styles['paper-chat-input__quick-reply']">
      <div :class="styles['paper-chat-input__quick-reply-header']">
        <span :class="styles['paper-chat-input__quick-reply-title']">快捷选项</span>
        <button
          type="button"
          :class="styles['paper-chat-input__quick-reply-custom-button']"
          :disabled="props.isSending"
          @click="focusCustomReply"
        >
          自定义回答
        </button>
      </div>

      <PaperChatOptions
        :options="props.quickReplyInfo.options"
        :disabled="props.isSending"
        @select="handleQuickReplySelect"
      />
    </div>

    <PaperChatAttachedDocuments
      :documents="pendingDocs"
      :disabled="props.isSending"
      @remove="removePendingDoc"
    />
    <PaperChatAttachedImages
      :images="pendingImages"
      :disabled="props.isSending"
      @remove="removePendingImage"
    />
    <PaperChatAttachedQuotes
      :quotes="pendingQuotes"
      :disabled="props.isSending"
      @remove="(id) => paperChatQuoteStore.removeQuote(effectiveSessionId, id)"
    />
    <PaperChatProcessingFiles :files="processingFiles" />

    <PaperChatTextarea
      ref="textareaRef"
      v-model="localInputMessage"
      :is-sending="props.isSending"
      :is-dragging="isDragging"
      :has-attachments="totalAttachmentCount > 0"
      :placeholder="
        props.quickReplyInfo
          ? '输入自定义回答，或点击上方快捷选项 ...'
          : '输入命令或消息，可拖拽文件或粘贴图片上传 ...'
      "
      @keydown="handleKeydown"
      @paste="handlePaste"
      @dragover="handleDragOver"
      @dragleave="handleDragLeave"
      @drop="handleDrop"
    />

    <PaperChatToolSelectionBar
      :is-sending="props.isSending"
      :variant="props.variant"
      :selected-model="localSelectedModel"
      :model-options="modelOptions"
      :selected-tools="localSelectedTools"
      :selected-knowledge-bases="localSelectedKnowledgeBases"
      :enable-lab-tools="localEnableLabTools"
      :enable-paper-web-search="localEnablePaperWebSearch"
      :total-attachment-count="totalAttachmentCount"
      @update:selected-model="updateSelectedModel"
      @update:selected-tools="updateSelectedTools"
      @update:selected-knowledge-bases="updateSelectedKnowledgeBases"
      @update:enable-lab-tools="updateEnableLabTools"
      @update:enable-paper-web-search="updateEnablePaperWebSearch"
      @upload="triggerFileUpload"
      @send="handleSend"
      @stop="handleStop"
    />
  </div>
</template>
