// src/renderer/src/components/paper/chat/PaperChatMessageList.tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import type { Message } from '@renderer/types'
import type { PaperQuote } from '@shared/types/chat'
import PaperChatMessage from './message/PaperChatMessage'
import styles from './PaperChatMessageList.module.css'

interface PaperChatMessageListProps {
  messages: Message[]
  currentModelName?: string
  currentChatId?: string
  onQuoteClick?: (quote: PaperQuote) => void
}

export default function PaperChatMessageList({
  messages,
  currentModelName,
  currentChatId,
  onQuoteClick
}: PaperChatMessageListProps) {
  const listRef = useRef<HTMLDivElement>(null)
  const [expandedReasoningIds, setExpandedReasoningIds] = useState<Set<string>>(new Set())

  const visibleMessages = useMemo(
    () => messages.filter((message) => !message.hidden && message.role !== 'system' && message.role !== 'tool'),
    [messages]
  )
  const latestVisibleMessageContent = visibleMessages.at(-1)?.content

  useEffect(() => {
    const element = listRef.current
    if (!element) return
    requestAnimationFrame(() => {
      element.scrollTop = element.scrollHeight
    })
  }, [visibleMessages.length, latestVisibleMessageContent])

  function toggleReasoning(messageId: string): void {
    setExpandedReasoningIds((current) => {
      const next = new Set(current)
      if (next.has(messageId)) {
        next.delete(messageId)
      } else {
        next.add(messageId)
      }
      return next
    })
  }

  return (
    <div ref={listRef} className={styles['paper-chat-message-list']}>
      {visibleMessages.length === 0 ? (
        <div className="paper-chat-message-list__empty">开始针对这篇论文提问吧</div>
      ) : (
        <div className="paper-chat-message-list__items">
          {visibleMessages.map((message) => (
            <PaperChatMessage
              key={message.id}
              message={message}
              currentModelName={currentModelName}
              currentChatId={currentChatId}
              isReasoningExpanded={expandedReasoningIds.has(message.id)}
              onToggleReasoning={toggleReasoning}
              onQuoteClick={onQuoteClick}
            />
          ))}
        </div>
      )}
    </div>
  )
}

// src/renderer/src/components/paper/chat/PaperChatMessageList.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import PaperChatMessage from '@renderer/components/paper/chat/message/PaperChatMessage.vue'
import PaperChatReActSteps from '@renderer/components/paper/chat/message/PaperChatReActSteps.vue'
import type { Message } from '@renderer/types'
import styles from './PaperChatMessageList.module.css'

const props = defineProps<{
  messages: Message[]
  isSending?: boolean
  currentModelName?: string
  currentChatId?: string
}>()

const expandedReasoningIds = ref<Set<string>>(new Set())
const scrollRef = ref<HTMLElement | null>(null)
const userScrolling = ref(false)
const lastScrollTop = ref(0)
const SCROLL_THRESHOLD = 96

let scrollFrameId: number | null = null
let pendingScrollSmooth = true

const visibleMessages = computed(() =>
  props.messages.filter((message) => !message.hidden && message.role !== 'tool')
)

function isNearBottom(): boolean {
  const el = scrollRef.value
  if (!el) return true
  const { scrollTop, scrollHeight, clientHeight } = el
  return scrollHeight - scrollTop - clientHeight <= SCROLL_THRESHOLD
}

function scrollToBottom(smooth = true): void {
  const el = scrollRef.value
  if (!el) return
  el.scrollTo({
    top: el.scrollHeight,
    behavior: smooth ? 'smooth' : 'auto'
  })
}

function scheduleScrollToBottom(smooth = true): void {
  pendingScrollSmooth = pendingScrollSmooth && smooth

  if (scrollFrameId !== null) {
    return
  }

  scrollFrameId = window.requestAnimationFrame(() => {
    const shouldSmooth = pendingScrollSmooth
    pendingScrollSmooth = true
    scrollFrameId = null
    scrollToBottom(shouldSmooth)
  })
}

function cancelScheduledScroll(): void {
  if (scrollFrameId !== null) {
    window.cancelAnimationFrame(scrollFrameId)
    scrollFrameId = null
  }
  pendingScrollSmooth = true
}

function handleScroll(): void {
  const el = scrollRef.value
  if (!el) return

  const currentScrollTop = el.scrollTop
  if (isNearBottom()) {
    userScrolling.value = false
  } else if (currentScrollTop < lastScrollTop.value) {
    userScrolling.value = true
  }
  lastScrollTop.value = currentScrollTop
}

function handleWheel(event: WheelEvent): void {
  if (event.deltaY < 0) {
    userScrolling.value = true
  }
}

function smartScrollToBottom(): void {
  if (!userScrolling.value) {
    scheduleScrollToBottom(!props.isSending)
  }
}

function toggleReasoning(messageId: string): void {
  if (expandedReasoningIds.value.has(messageId)) {
    expandedReasoningIds.value.delete(messageId)
  } else {
    expandedReasoningIds.value.add(messageId)
  }
}

function isReasoningExpanded(messageId: string): boolean {
  return expandedReasoningIds.value.has(messageId)
}

function hasRenderableReact(message: Message): boolean {
  const hasIterationContent =
    message.reactIterations?.some(
      (iteration) =>
        iteration.reasoning.trim().length > 0 ||
        iteration.steps.length > 0 ||
        (iteration.content?.trim().length ?? 0) > 0
    ) || false
  const hasLegacySteps = (message.reactSteps?.length || 0) > 0
  return message.role === 'assistant' && (hasIterationContent || hasLegacySteps)
}

watch(
  () => props.messages,
  () => {
    smartScrollToBottom()
  },
  { deep: true, flush: 'post' }
)

watch(
  () => props.isSending,
  (sending) => {
    if (sending) {
      userScrolling.value = false
      scheduleScrollToBottom(false)
    }
  },
  { flush: 'post' }
)

watch(
  () => props.currentChatId,
  () => {
    userScrolling.value = false
    expandedReasoningIds.value = new Set()
    scheduleScrollToBottom(false)
  },
  { flush: 'post' }
)

onMounted(() => {
  scrollToBottom(false)
  if (scrollRef.value) {
    lastScrollTop.value = scrollRef.value.scrollTop
  }
})

onBeforeUnmount(() => {
  cancelScheduledScroll()
})
</script>

<template>
  <div
    ref="scrollRef"
    :class="styles['paper-chat-message-list']"
    @scroll="handleScroll"
    @wheel.passive="handleWheel"
  >
    <div v-if="visibleMessages.length === 0" :class="styles['paper-chat-message-list__empty']">
      <span>可直接提问这篇论文的内容。</span>
    </div>

    <div v-else :class="styles['paper-chat-message-list__items']">
      <PaperChatMessage
        v-for="message in visibleMessages"
        :key="message.id"
        :message="message"
        :current-model-name="props.currentModelName"
        :is-reasoning-expanded="isReasoningExpanded(message.id)"
        :current-chat-id="props.currentChatId"
        @toggle-reasoning="toggleReasoning"
      >
        <template #react-steps>
          <PaperChatReActSteps
            v-if="hasRenderableReact(message)"
            :steps="message.reactSteps"
            :iterations="message.reactIterations"
            :is-streaming="message.isStreaming"
          />
        </template>
      </PaperChatMessage>
    </div>
  </div>
</template>
