// src/renderer/src/components/lab/ContainerSelector.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { storeToRefs } from 'pinia'
import { useContainerStore, useLabCreatorStore } from '@renderer/stores'
import type { ContainerInfo } from '@renderer/types/lab'
import styles from './ContainerSelector.module.css'

const containerStore = useContainerStore()
const creatorStore = useLabCreatorStore()

const { isLoading: storeLoading, containers } = storeToRefs(containerStore)
const {
  containerSearchQuery,
  containerFilter,
  selectedContainerId,
  filteredContainers,
  runningCount,
  stoppedCount
} = storeToRefs(creatorStore)

/** 展开详情的容器 ID */
const expandedContainerId = ref<string | null>(null)

const emit = defineEmits<{
  (e: 'select', containerId: string): void
  (e: 'view-details', container: ContainerInfo): void
}>()

/** 点击容器卡片只高亮选中 */
function handleClickContainer(containerId: string): void {
  creatorStore.selectContainer(containerId)
}

/** 点击详情按钮 */
function handleViewDetails(container: ContainerInfo, event: Event): void {
  event.stopPropagation()
  expandedContainerId.value = expandedContainerId.value === container.id ? null : container.id
  emit('view-details', container)
}

/** 获取选中的容器信息 */
const selectedContainer = computed(() => {
  if (!selectedContainerId.value) return null
  return filteredContainers.value.find((c) => c.id === selectedContainerId.value)
})

defineExpose({
  reset: () => {
    creatorStore.resetContainerSelector()
    expandedContainerId.value = null
  },
  selectedContainerId,
  selectedContainer
})
</script>

<template>
  <div :class="styles['container-selector-section']">
    <div :class="styles['browser-header']">
      <div :class="styles['search-section']">
        <input
          v-model="containerSearchQuery"
          type="text"
          :class="styles['search-input']"
          placeholder="搜索容器..."
        />
        <button
          :class="styles['refresh-btn']"
          :disabled="storeLoading"
          @click="containerStore.loadContainers()"
        >
          刷新
        </button>
      </div>

      <div :class="styles['filter-section']">
        <button
          :class="[styles['filter-btn'], { [styles['active']]: containerFilter === 'all' }]"
          @click="containerFilter = 'all'"
        >
          全部 ({{ containers.length }})
        </button>
        <button
          :class="[styles['filter-btn'], { [styles['active']]: containerFilter === 'running' }]"
          @click="containerFilter = 'running'"
        >
          运行中 ({{ runningCount }})
        </button>
        <button
          :class="[styles['filter-btn'], { [styles['active']]: containerFilter === 'stopped' }]"
          @click="containerFilter = 'stopped'"
        >
          已停止 ({{ stoppedCount }})
        </button>
      </div>
    </div>

    <div :class="styles['container-list']">
      <div v-if="storeLoading" :class="styles['loading-state']">
        <div :class="styles['loading-spinner']"></div>
        <p>加载容器中...</p>
      </div>

      <div v-else-if="filteredContainers.length === 0" :class="styles['empty-state']">
        <p :class="styles['empty-title']">暂无容器</p>
        <p :class="styles['empty-desc']">Docker 中没有发现容器，请使用其他方式创建实验室</p>
      </div>

      <div
        v-for="container in filteredContainers"
        :key="container.id"
        :class="[
          styles['container-card'],
          {
            [styles['active']]: container.id === selectedContainerId,
            [styles['running']]: container.state === 'running',
            [styles['expanded']]: container.id === expandedContainerId
          }
        ]"
        @click="handleClickContainer(container.id)"
      >
        <div :class="styles['container-header']">
          <div :class="styles['container-title']">
            <span
              :class="[
                styles['state-indicator'],
                styles[containerStore.getStateClass(container.state)]
              ]"
            ></span>
            <span :class="styles['container-name']">{{
              container.names[0]?.replace(/^\//, '') || '未命名'
            }}</span>
          </div>
          <div :class="styles['container-actions']">
            <button
              :class="[
                styles['btn-detail'],
                { [styles['active']]: container.id === expandedContainerId }
              ]"
              title="查看详情"
              @click="handleViewDetails(container, $event)"
            >
              {{ container.id === expandedContainerId ? '收起' : '详情' }}
            </button>
            <span
              :class="[
                styles['container-state'],
                styles[containerStore.getStateClass(container.state)]
              ]"
            >
              {{ containerStore.getStateLabel(container.state) }}
            </span>
          </div>
        </div>

        <div :class="styles['container-info']">
          <div :class="styles['info-row']">
            <span :class="styles['info-label']">镜像</span>
            <span :class="styles['info-value']" :title="container.image">{{
              container.image
            }}</span>
          </div>
          <div :class="styles['info-row']">
            <span :class="styles['info-label']">创建时间</span>
            <span :class="styles['info-value']">{{
              containerStore.formatCreated(container.created)
            }}</span>
          </div>
        </div>

        <!-- 展开的详情面板 -->
        <div v-if="container.id === expandedContainerId" :class="styles['container-details']">
          <div :class="styles['detail-row']">
            <span :class="styles['detail-label']">容器 ID</span>
            <span :class="styles['detail-value']">{{ container.shortId }}</span>
          </div>
          <div :class="styles['detail-row']">
            <span :class="styles['detail-label']">完整 ID</span>
            <span :class="styles['detail-value']">{{ container.id }}</span>
          </div>
          <div v-if="container.ports && container.ports.length > 0" :class="styles['detail-row']">
            <span :class="styles['detail-label']">端口映射</span>
            <div :class="styles['ports-list']">
              <span v-for="(port, idx) in container.ports" :key="idx" :class="styles['port-item']">
                {{ port.hostPort }} -> {{ port.containerPort }}/{{ port.protocol }}
              </span>
            </div>
          </div>
          <div
            v-if="container.labels && Object.keys(container.labels).length > 0"
            :class="styles['detail-row']"
          >
            <span :class="styles['detail-label']">标签</span>
            <div :class="styles['labels-list']">
              <span
                v-for="(value, key) in container.labels"
                :key="key"
                :class="styles['label-item']"
              >
                {{ key }}: {{ value }}
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// src/renderer/src/components/lab/ContainerSelector.tsx
import { useState, useMemo } from 'react'
import { useContainerStore, useLabCreatorStore } from '@renderer/stores'
import type { ContainerInfo } from '@shared/types/lab/container'
import styles from './ContainerSelector.module.css'

export default function ContainerSelector() {
  // ─── 容器 store selectors ───
  const containers = useContainerStore((s) => s.containers)
  const isLoading = useContainerStore((s) => s.isLoading)
  const loadContainers = useContainerStore((s) => s.loadContainers)
  const getStateClass = useContainerStore((s) => s.getStateClass)
  const getStateLabel = useContainerStore((s) => s.getStateLabel)
  const formatCreated = useContainerStore((s) => s.formatCreated)

  // ─── 创建器 store selectors ───
  const containerFilter = useLabCreatorStore((s) => s.containerFilter)
  const containerSearchQuery = useLabCreatorStore((s) => s.containerSearchQuery)
  const selectedContainerId = useLabCreatorStore((s) => s.selectedContainerId)
  const setContainerFilter = useLabCreatorStore((s) => s.setContainerFilter)
  const setContainerSearchQuery = useLabCreatorStore((s) => s.setContainerSearchQuery)
  const selectContainer = useLabCreatorStore((s) => s.selectContainer)

  // ─── 本地状态 ───
  const [expandedContainerId, setExpandedContainerId] = useState<string | null>(null)

  // ─── 过滤逻辑（useMemo 重新实现，不用 store getter） ───
  const filteredContainers = useMemo(() => {
    let result = containers

    if (containerFilter === 'running') {
      result = result.filter((c) => c.state === 'running')
    } else if (containerFilter === 'stopped') {
      result = result.filter((c) => c.state === 'exited' || c.state === 'dead')
    }

    if (containerSearchQuery.trim()) {
      const query = containerSearchQuery.toLowerCase()
      result = result.filter(
        (c) =>
          c.names.some((n) => n.toLowerCase().includes(query)) ||
          c.image.toLowerCase().includes(query)
      )
    }

    return result
  }, [containers, containerFilter, containerSearchQuery])

  // ─── 计数（基于全量容器） ───
  const runningCount = useMemo(
    () => containers.filter((c) => c.state === 'running').length,
    [containers]
  )

  const stoppedCount = useMemo(
    () => containers.filter((c) => c.state === 'exited' || c.state === 'dead').length,
    [containers]
  )

  // ─── 事件处理 ───
  function handleClickContainer(containerId: string): void {
    selectContainer(containerId)
  }

  function handleViewDetails(container: ContainerInfo, event: React.MouseEvent): void {
    event.stopPropagation()
    setExpandedContainerId((prev) => (prev === container.id ? null : container.id))
  }

  return (
    <div className={styles['container-selector-section']}>
      <div className={styles['browser-header']}>
        <div className={styles['search-section']}>
          <input
            value={containerSearchQuery}
            type="text"
            className={styles['search-input']}
            placeholder="搜索容器..."
            onChange={(e) => setContainerSearchQuery(e.target.value)}
          />
          <button
            className={styles['refresh-btn']}
            disabled={isLoading}
            onClick={() => loadContainers()}
          >
            刷新
          </button>
        </div>

        <div className={styles['filter-section']}>
          <button
            className={`${styles['filter-btn']} ${containerFilter === 'all' ? styles.active : ''}`}
            onClick={() => setContainerFilter('all')}
          >
            全部 ({containers.length})
          </button>
          <button
            className={`${styles['filter-btn']} ${containerFilter === 'running' ? styles.active : ''}`}
            onClick={() => setContainerFilter('running')}
          >
            运行中 ({runningCount})
          </button>
          <button
            className={`${styles['filter-btn']} ${containerFilter === 'stopped' ? styles.active : ''}`}
            onClick={() => setContainerFilter('stopped')}
          >
            已停止 ({stoppedCount})
          </button>
        </div>
      </div>

      <div className={styles['container-list']}>
        {isLoading ? (
          <div className={styles['loading-state']}>
            <div className={styles['loading-spinner']}></div>
            <p>加载容器中...</p>
          </div>
        ) : filteredContainers.length === 0 ? (
          <div className={styles['empty-state']}>
            <p className={styles['empty-title']}>暂无容器</p>
            <p className={styles['empty-desc']}>Docker 中没有发现容器，请使用其他方式创建实验室</p>
          </div>
        ) : (
          filteredContainers.map((container) => (
            <div
              key={container.id}
              className={[
                styles['container-card'],
                container.id === selectedContainerId ? styles.active : '',
                container.state === 'running' ? styles.running : ''
              ]
                .filter(Boolean)
                .join(' ')}
              onClick={() => handleClickContainer(container.id)}
            >
              <div className={styles['container-header']}>
                <div className={styles['container-title']}>
                  <span
                    className={`${styles['state-indicator']} ${styles[getStateClass(container.state)]}`}
                  ></span>
                  <span className={styles['container-name']}>
                    {container.names[0]?.replace(/^\//, '') || '未命名'}
                  </span>
                </div>
                <div className={styles['container-actions']}>
                  <button
                    className={[
                      styles['btn-detail'],
                      container.id === expandedContainerId ? styles.active : ''
                    ]
                      .filter(Boolean)
                      .join(' ')}
                    title="查看详情"
                    onClick={(e) => handleViewDetails(container, e)}
                  >
                    {container.id === expandedContainerId ? '收起' : '详情'}
                  </button>
                  <span
                    className={`${styles['container-state']} ${styles[getStateClass(container.state)]}`}
                  >
                    {getStateLabel(container.state)}
                  </span>
                </div>
              </div>

              <div className={styles['container-info']}>
                <div className={styles['info-row']}>
                  <span className={styles['info-label']}>镜像</span>
                  <span className={styles['info-value']} title={container.image}>
                    {container.image}
                  </span>
                </div>
                <div className={styles['info-row']}>
                  <span className={styles['info-label']}>创建时间</span>
                  <span className={styles['info-value']}>{formatCreated(container.created)}</span>
                </div>
              </div>

              {/* 展开的详情面板 */}
              {container.id === expandedContainerId && (
                <div className={styles['container-details']}>
                  <div className={styles['detail-row']}>
                    <span className={styles['detail-label']}>容器 ID</span>
                    <span className={styles['detail-value']}>{container.shortId}</span>
                  </div>
                  <div className={styles['detail-row']}>
                    <span className={styles['detail-label']}>完整 ID</span>
                    <span className={styles['detail-value']}>{container.id}</span>
                  </div>
                  {container.ports && container.ports.length > 0 && (
                    <div className={styles['detail-row']}>
                      <span className={styles['detail-label']}>端口映射</span>
                      <div className={styles['ports-list']}>
                        {container.ports.map((port, idx) => (
                          <span key={idx} className={styles['port-item']}>
                            {port.hostPort} {'->'} {port.containerPort}/{port.protocol}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}
                  {container.labels && Object.keys(container.labels).length > 0 && (
                    <div className={styles['detail-row']}>
                      <span className={styles['detail-label']}>标签</span>
                      <div className={styles['labels-list']}>
                        {Object.entries(container.labels).map(([key, value]) => (
                          <span key={key} className={styles['label-item']}>
                            {key}: {value}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          ))
        )}
      </div>
    </div>
  )
}
