// src/renderer/src/components/lab/LabCreator.vue
<script setup lang="ts">
import { nextTick, onBeforeUnmount, ref, watch } from 'vue'
import { storeToRefs } from 'pinia'
import { useContainerStore, useDockerConfigStore, useLabCreatorStore } from '@renderer/stores'
import { useNotification } from '@renderer/composables/useNotification'
import ContainerSelector from './ContainerSelector.vue'
import ComposeEditor from './ComposeEditor.vue'
import DockerfileEditor from './DockerfileEditor.vue'
import SaveConfigDialog from './SaveConfigDialog.vue'
import { CreateActions, CreateTypeSelector, PortMappingSection } from './creator'
import { useCreateFlow } from './creator/composables/useCreateFlow'
import type { DockerStatus } from '@renderer/types/lab'

const props = defineProps<{
  visible: boolean
  dockerStatus?: DockerStatus | null
}>()

const emit = defineEmits<{
  (e: 'close'): void
}>()

const containerStore = useContainerStore()
const configStore = useDockerConfigStore()
const creatorStore = useLabCreatorStore()
const notify = useNotification()

const {
  showSaveDialog,
  saveDialogType,
  isCreating,
  createError,
  portMappings,
  createType,
  composeContent,
  composeProjectName,
  dockerfileContent,
  dockerfileContext,
  dockerfileProjectName,
  sshConfig
} = storeToRefs(creatorStore)

const containerSelectorRef = ref<InstanceType<typeof ContainerSelector> | null>(null)
const creatorRef = ref<HTMLElement | null>(null)
const contentShellRef = ref<HTMLElement | null>(null)
const contentInnerRef = ref<HTMLElement | null>(null)
const isContentMeasured = ref(false)
const isContentVisible = ref(true)
const isContentHeightTransitioning = ref(false)
const isTestingSsh = ref(false)
let contentResizeObserver: ResizeObserver | null = null
let contentHeightAnimationFrame: number | null = null
let pendingContentVisible = false
let contentTransitionTimer: number | null = null

const CONTENT_HEIGHT_TRANSITION_MS = 220
const CONTENT_HEIGHT_TRANSITION_FALLBACK_MS = CONTENT_HEIGHT_TRANSITION_MS + 80

function clearContentHeightAnimationFrame(): void {
  if (contentHeightAnimationFrame !== null) {
    window.cancelAnimationFrame(contentHeightAnimationFrame)
    contentHeightAnimationFrame = null
  }
}

function clearContentTransitionTimer(): void {
  if (contentTransitionTimer !== null) {
    window.clearTimeout(contentTransitionTimer)
    contentTransitionTimer = null
  }
}

function animateCreatorContentHeightTo(nextHeight: number): void {
  clearContentHeightAnimationFrame()
  contentHeightAnimationFrame = window.requestAnimationFrame(() => {
    contentHeightAnimationFrame = null
    setCreatorContentHeight(nextHeight)
  })
}

function finishPendingContentTransition(): void {
  if (!pendingContentVisible) {
    return
  }

  pendingContentVisible = false
  isContentHeightTransitioning.value = false
  isContentVisible.value = true
  clearContentTransitionTimer()
}

function handleContentShellTransitionEnd(event: TransitionEvent): void {
  if (
    event.target !== contentShellRef.value ||
    event.propertyName !== 'height' ||
    !isContentHeightTransitioning.value
  ) {
    return
  }

  isContentHeightTransitioning.value = false

  if (pendingContentVisible) {
    finishPendingContentTransition()
    return
  }

  clearContentTransitionTimer()
}

function readCreatorContentAvailableHeight(): number {
  const creator = creatorRef.value
  const shell = contentShellRef.value
  if (!creator || !shell) {
    return Number.POSITIVE_INFINITY
  }

  const creatorStyles = window.getComputedStyle(creator)
  const creatorRect = creator.getBoundingClientRect()
  const shellRect = shell.getBoundingClientRect()
  const maxHeightValue = creatorStyles.maxHeight
  const maxCreatorHeight = maxHeightValue.endsWith('vh')
    ? (window.innerHeight * parseFloat(maxHeightValue)) / 100
    : parseFloat(maxHeightValue)
  const creatorHeightLimit = Number.isFinite(maxCreatorHeight)
    ? maxCreatorHeight
    : creator.clientHeight
  const shellTop = shellRect.top - creatorRect.top

  return Math.max(1, Math.floor(creatorHeightLimit - shellTop))
}

function readCreatorContentHeight(): number {
  const shell = contentShellRef.value
  const inner = contentInnerRef.value
  if (!inner) {
    return 0
  }

  if (!shell) {
    return Math.ceil(inner.scrollHeight)
  }

  const availableHeight = readCreatorContentAvailableHeight()
  const previousShellHeight = shell.style.height
  const previousShellOverflow = shell.style.overflow
  const previousShellTransition = shell.style.transition
  const previousInnerMaxHeight = inner.style.maxHeight
  const previousInnerOverflowY = inner.style.overflowY

  try {
    shell.style.height = 'auto'
    shell.style.overflow = 'visible'
    shell.style.transition = 'none'
    inner.style.maxHeight = 'none'
    inner.style.overflowY = 'visible'

    return Math.min(Math.ceil(inner.scrollHeight), availableHeight)
  } finally {
    shell.style.height = previousShellHeight
    shell.style.overflow = previousShellOverflow
    shell.style.transition = previousShellTransition
    inner.style.maxHeight = previousInnerMaxHeight
    inner.style.overflowY = previousInnerOverflowY
  }
}

function setCreatorContentHeight(height: number): void {
  const shell = contentShellRef.value
  if (!shell || height <= 0) {
    return
  }

  isContentMeasured.value = true
  shell.style.height = `${Math.min(height, readCreatorContentAvailableHeight())}px`
}

function lockCreatorContentHeight(): void {
  const shell = contentShellRef.value
  if (!shell) {
    return
  }

  setCreatorContentHeight(Math.ceil(shell.offsetHeight))
  void shell.offsetHeight
}

function syncCreatorContentHeight(): void {
  const nextHeight = readCreatorContentHeight()
  if (nextHeight <= 0) {
    return
  }

  lockCreatorContentHeight()
  clearContentHeightAnimationFrame()
  contentHeightAnimationFrame = window.requestAnimationFrame(() => {
    contentHeightAnimationFrame = null
    setCreatorContentHeight(nextHeight)
  })
}

async function transitionCreatorContentHeight(): Promise<void> {
  if (!props.visible) {
    return
  }

  isContentHeightTransitioning.value = true

  pendingContentVisible = false
  clearContentTransitionTimer()
  clearContentHeightAnimationFrame()

  lockCreatorContentHeight()

  await nextTick()

  // 等待浏览器完成布局计算（ContainerSelector 等复杂组件需要）
  await new Promise<void>((resolve) => {
    requestAnimationFrame(() => {
      requestAnimationFrame(() => resolve())
    })
  })

  const nextHeight = readCreatorContentHeight()
  if (nextHeight <= 0) {
    isContentHeightTransitioning.value = false
    return
  }

  isContentVisible.value = false
  pendingContentVisible = true

  await nextTick()

  void contentShellRef.value?.offsetHeight

  animateCreatorContentHeightTo(nextHeight)

  contentTransitionTimer = window.setTimeout(
    finishPendingContentTransition,
    CONTENT_HEIGHT_TRANSITION_FALLBACK_MS
  )
}

function observeCreatorContent(): void {
  contentResizeObserver?.disconnect()

  if (typeof ResizeObserver === 'undefined' || !contentInnerRef.value) {
    return
  }

  contentResizeObserver = new ResizeObserver(() => {
    if (props.visible && isContentVisible.value && !isContentHeightTransitioning.value) {
      syncCreatorContentHeight()
    }
  })
  contentResizeObserver.observe(contentInnerRef.value)
}

async function initializeCreatorContentHeight(): Promise<void> {
  await nextTick()

  // 等待浏览器完成布局计算
  await new Promise<void>((resolve) => {
    requestAnimationFrame(() => {
      requestAnimationFrame(() => resolve())
    })
  })

  observeCreatorContent()
  syncCreatorContentHeight()
  isContentVisible.value = true
}

const {
  canCreate,
  containerSelectHint,
  createPhaseText,
  createProgress,
  clearError,
  close,
  handleCreate
} = useCreateFlow({
  containerSelectorRef,
  closeDialog: () => emit('close')
})

watch(
  () => props.visible,
  async (visible) => {
    if (!visible) {
      return
    }

    createType.value = 'compose'
    composeContent.value = creatorStore.getComposeTemplate('mixed')
    dockerfileContent.value = `FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
`
    dockerfileContext.value = ''
    composeProjectName.value = ''
    dockerfileProjectName.value = ''
    creatorStore.resetSshConfig()
    containerSelectorRef.value?.reset()
    clearError()

    await Promise.all([
      containerStore.loadContainers(),
      configStore.loadDockerfileConfigs(),
      configStore.loadComposeConfigs()
    ])

    await initializeCreatorContentHeight()
  }
)

watch(createType, async (newType) => {
  if (newType === 'existing' && containerStore.containers.length === 0) {
    await containerStore.loadContainers()
  }

  await transitionCreatorContentHeight()
})

watch(
  () => sshConfig.value.authType,
  async () => {
    await transitionCreatorContentHeight()
  }
)

watch([containerSelectHint, isCreating, createError], async () => {
  await transitionCreatorContentHeight()
})

onBeforeUnmount(() => {
  contentResizeObserver?.disconnect()
  clearContentHeightAnimationFrame()
  clearContentTransitionTimer()
})

async function handleSaveConfig(name: string): Promise<void> {
  creatorStore.saveConfigName = name.trim()
  await creatorStore.handleSaveConfig()
}

async function testSshConnection(): Promise<void> {
  const ssh = sshConfig.value
  if (!ssh.host.trim() || !ssh.username.trim()) {
    notify.warning('请填写必填项', '主机地址和用户名不能为空', { source: 'lab' })
    return
  }

  isTestingSsh.value = true
  try {
    const result = await window.api.ssh.config.test(
      {
        id: '',
        name: 'test',
        host: ssh.host,
        port: ssh.port,
        username: ssh.username,
        authType: ssh.authType,
        keyName: ssh.authType === 'key' ? ssh.keyName : undefined,
        keyContent: ssh.authType === 'key' ? ssh.keyContent : undefined
      },
      ssh.authType === 'password' ? ssh.password : undefined
    )

    if (result.success) {
      const detail = result.systemInfo
        ? `${result.systemInfo.hostname} (${result.systemInfo.platform})`
        : 'SSH 连接测试成功'
      notify.success('连接成功', detail, { source: 'lab' })
    } else {
      notify.error('连接失败', result.error || '未知错误', { source: 'lab' })
    }
  } finally {
    isTestingSsh.value = false
  }
}
</script>

<template>
  <Transition name="sm-modal">
    <div v-if="visible" class="sm-modal__overlay lab-creator-overlay" @click.self="close">
      <div ref="creatorRef" class="sm-modal__surface lab-creator">
        <div class="creator-header">
          <h2>创建新实验室</h2>
          <button class="close-btn" @click="close">×</button>
        </div>

        <CreateTypeSelector
          v-model="createType"
          :docker-ready="props.dockerStatus?.available ?? true"
        />

        <div
          ref="contentShellRef"
          class="creator-content-shell"
          :class="{ 'is-measured': isContentMeasured }"
          @transitionend="handleContentShellTransitionEnd"
        >
          <div
            ref="contentInnerRef"
            class="creator-content-inner"
            :class="{ 'is-visible': isContentVisible }"
          >
            <ContainerSelector
              v-if="createType === 'existing'"
              ref="containerSelectorRef"
              class="creator-section"
            />

            <div v-if="containerSelectHint" class="container-hint">
              {{ containerSelectHint }}
            </div>

            <div v-if="isCreating" class="create-progress">
              <div class="progress-header">
                <span class="progress-text">{{ createPhaseText }}</span>
                <span class="progress-percent">{{ createProgress }}%</span>
              </div>
              <div class="progress-bar">
                <div class="progress-fill" :style="{ width: `${createProgress}%` }"></div>
              </div>
            </div>

            <div v-if="createError && !isCreating" class="create-error">
              <div class="error-header">
                <span class="error-icon">⚠</span>
                <span class="error-title">创建失败</span>
                <button class="error-close" @click="clearError">×</button>
              </div>
              <div class="error-message">{{ createError }}</div>
            </div>

            <ComposeEditor
              v-if="createType === 'compose'"
              v-model="composeContent"
              v-model:project-name="composeProjectName"
              class="creator-section"
              @save-config="creatorStore.openSaveDialog('compose')"
            />

            <template v-else-if="createType === 'dockerfile'">
              <div class="project-name-section">
                <label class="form-label">实验室名称 <span class="required">*</span></label>
                <input
                  v-model="dockerfileProjectName"
                  type="text"
                  class="form-input"
                  placeholder="请输入实验室名称"
                />
              </div>
              <DockerfileEditor
                v-model="dockerfileContent"
                v-model:context="dockerfileContext"
                class="creator-section"
                @save-config="creatorStore.openSaveDialog('dockerfile')"
              />
            </template>

            <div v-else-if="createType === 'ssh'" class="creator-section ssh-form">
              <div class="ssh-form__field">
                <label class="form-label">主机地址 <span class="required">*</span></label>
                <input
                  v-model="sshConfig.host"
                  type="text"
                  class="form-input"
                  placeholder="192.168.1.100"
                />
              </div>

              <div class="ssh-form__field ssh-form__field--inline">
                <div class="ssh-form__field-half">
                  <label class="form-label">端口</label>
                  <input
                    v-model.number="sshConfig.port"
                    type="number"
                    class="form-input"
                    placeholder="22"
                  />
                </div>
                <div class="ssh-form__field-half">
                  <label class="form-label">用户名 <span class="required">*</span></label>
                  <input
                    v-model="sshConfig.username"
                    type="text"
                    class="form-input"
                    placeholder="root"
                  />
                </div>
              </div>

              <div class="ssh-form__field">
                <label class="form-label">认证方式</label>
                <div class="ssh-form__toggle">
                  <button
                    class="ssh-form__toggle-btn"
                    :class="{ active: sshConfig.authType === 'password' }"
                    @click="creatorStore.updateSshConfig({ authType: 'password' })"
                  >
                    密码
                  </button>
                  <button
                    class="ssh-form__toggle-btn"
                    :class="{ active: sshConfig.authType === 'key' }"
                    @click="creatorStore.updateSshConfig({ authType: 'key' })"
                  >
                    密钥
                  </button>
                </div>
              </div>

              <div v-if="sshConfig.authType === 'password'" class="ssh-form__field">
                <label class="form-label">密码</label>
                <input
                  v-model="sshConfig.password"
                  type="password"
                  class="form-input"
                  placeholder="输入 SSH 密码"
                />
              </div>

              <template v-else>
                <div class="ssh-form__field">
                  <label class="form-label">密钥名称 <span class="required">*</span></label>
                  <input
                    v-model="sshConfig.keyName"
                    type="text"
                    class="form-input"
                    placeholder="my-key"
                  />
                </div>
                <div class="ssh-form__field">
                  <label class="form-label">密钥内容 <span class="required">*</span></label>
                  <textarea
                    v-model="sshConfig.keyContent"
                    class="form-input ssh-form__key-textarea"
                    placeholder="-----BEGIN OPENSSH PRIVATE KEY-----&#10;...&#10;-----END OPENSSH PRIVATE KEY-----"
                    rows="6"
                  ></textarea>
                </div>
              </template>

              <button
                class="btn ssh-form__test-btn"
                :disabled="isTestingSsh"
                @click="testSshConnection"
              >
                {{ isTestingSsh ? '测试连接中...' : '测试连接' }}
              </button>
            </div>

            <PortMappingSection
              v-if="createType !== 'ssh'"
              :create-type="createType"
              :port-mappings="portMappings"
              @refresh="creatorStore.refreshPorts()"
              @add="creatorStore.addPortMapping()"
              @update="(index, patch) => creatorStore.updatePortMapping(index, patch)"
              @remove="creatorStore.removePortMapping"
            />

            <CreateActions
              :is-creating="isCreating"
              :can-create="canCreate"
              :create-type="createType"
              :create-phase-text="createPhaseText"
              @close="close"
              @create="handleCreate"
            />
          </div>
        </div>

        <SaveConfigDialog
          :visible="showSaveDialog"
          :config-type="saveDialogType"
          @close="creatorStore.closeSaveDialog()"
          @save="handleSaveConfig"
        />
      </div>
    </div>
  </Transition>
</template>

<style scoped>
@import './creator/lab-creator.css';

.ssh-form {
  display: flex;
  flex-direction: column;
  gap: 16px;
  padding: 20px;
}

.ssh-form__field {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.ssh-form__field--inline {
  flex-direction: row;
  gap: 12px;
}

.ssh-form__field-half {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.ssh-form__toggle {
  display: flex;
  gap: 8px;
}

.ssh-form__toggle-btn {
  padding: 8px 16px;
  border: 1px solid var(--sm-color-border-default);
  border-radius: 6px;
  background-color: var(--sm-color-bg-app);
  color: var(--sm-color-text-primary);
  font-size: 13px;
  cursor: pointer;
  transition: all 0.15s ease;
}

.ssh-form__toggle-btn.active {
  border-color: var(--sm-color-border-selected);
  background-color: var(--sm-color-surface-selected);
}

.ssh-form__toggle-btn:hover:not(.active) {
  border-color: var(--sm-color-text-secondary);
}

.ssh-form__input-row {
  display: flex;
  gap: 8px;
  align-items: center;
}

.ssh-form__input-row .form-input {
  flex: 1;
}

.ssh-form__test-btn {
  align-self: flex-start;
}

.ssh-form__key-textarea {
  resize: vertical;
  font-family: monospace;
  font-size: 12px;
  line-height: 1.5;
  min-height: 80px;
}
</style>

// src/renderer/src/components/lab/LabCreator.tsx
import { useCallback, useEffect, useLayoutEffect, useRef, useState } from 'react'
import {
  useContainerStore,
  useLabCreatorStore,
  useComposeConfigStore,
  useDockerfileConfigStore,
  useDockerConfigStore,
  usePortMappingStore
} from '@renderer/stores'
import { useNotification } from '@renderer/composables/useNotification'
import { CssTransition } from '@renderer/components/motion/CssTransition'
import ContainerSelector from './ContainerSelector'
import ComposeEditor from './ComposeEditor'
import DockerfileEditor from './DockerfileEditor'
import SaveConfigDialog from './SaveConfigDialog'
import CreateTypeSelector from './creator/CreateTypeSelector'
import CreateActions from './creator/CreateActions'
import PortMappingSection from './creator/PortMappingSection'
import type { DockerStatus } from '@renderer/types/lab'
import './creator/lab-creator.css'
import styles from './LabCreator.module.css'

const CONTENT_HEIGHT_TRANSITION_MS = 220
const CONTENT_HEIGHT_TRANSITION_FALLBACK_MS = CONTENT_HEIGHT_TRANSITION_MS + 80
const DOCKER_CREATE_TYPES = new Set(['compose', 'dockerfile', 'existing'])

interface LabCreatorProps {
  visible: boolean
  dockerStatus?: DockerStatus | null
  onClose: () => void
}

export default function LabCreator({ visible, dockerStatus, onClose }: LabCreatorProps) {
  const creatorStore = useLabCreatorStore()
  const composeConfigStore = useComposeConfigStore()
  const dockerfileConfigStore = useDockerfileConfigStore()
  const notify = useNotification()

  const [isTestingSsh, setIsTestingSsh] = useState(false)
  const [isContentMeasured, setIsContentMeasured] = useState(false)
  const [isContentVisible, setIsContentVisible] = useState(true)
  const [isContentHeightTransitioning, setIsContentHeightTransitioning] = useState(false)
  const creatorRef = useRef<HTMLDivElement | null>(null)
  const contentShellRef = useRef<HTMLDivElement | null>(null)
  const contentInnerRef = useRef<HTMLDivElement | null>(null)
  const contentResizeObserverRef = useRef<ResizeObserver | null>(null)
  const contentResizeFrameRef = useRef<number | null>(null)
  const contentHeightFrameRef = useRef<number | null>(null)
  const contentTransitionTimerRef = useRef<number | null>(null)
  const pendingContentVisibleRef = useRef(false)
  const wasVisibleRef = useRef(false)
  const containers = useContainerStore((s) => s.containers) || []

  const clearCreateError = (): void => {
    creatorStore.clearCreateError()
  }

  const clearContentHeightFrame = useCallback((): void => {
    if (contentHeightFrameRef.current !== null) {
      window.cancelAnimationFrame(contentHeightFrameRef.current)
      contentHeightFrameRef.current = null
    }
  }, [])

  const clearContentResizeFrame = useCallback((): void => {
    if (contentResizeFrameRef.current !== null) {
      window.cancelAnimationFrame(contentResizeFrameRef.current)
      contentResizeFrameRef.current = null
    }
  }, [])

  const clearContentTransitionTimer = useCallback((): void => {
    if (contentTransitionTimerRef.current !== null) {
      window.clearTimeout(contentTransitionTimerRef.current)
      contentTransitionTimerRef.current = null
    }
  }, [])

  const readCreatorContentAvailableHeight = useCallback((): number => {
    const creator = creatorRef.current
    const shell = contentShellRef.current
    if (!creator || !shell) return Number.POSITIVE_INFINITY

    const creatorStyles = window.getComputedStyle(creator)
    const creatorRect = creator.getBoundingClientRect()
    const shellRect = shell.getBoundingClientRect()
    const maxHeightValue = creatorStyles.maxHeight
    const maxCreatorHeight = maxHeightValue.endsWith('vh')
      ? (window.innerHeight * Number.parseFloat(maxHeightValue)) / 100
      : Number.parseFloat(maxHeightValue)
    const creatorHeightLimit = Number.isFinite(maxCreatorHeight)
      ? maxCreatorHeight
      : creator.clientHeight
    const shellTop = shellRect.top - creatorRect.top

    return Math.max(1, Math.floor(creatorHeightLimit - shellTop))
  }, [])

  const setCreatorContentHeight = useCallback(
    (height: number): void => {
      const shell = contentShellRef.current
      if (!shell || height <= 0) return

      setIsContentMeasured(true)
      shell.style.height = `${Math.min(height, readCreatorContentAvailableHeight())}px`
    },
    [readCreatorContentAvailableHeight]
  )

  const readCreatorContentHeight = useCallback((): number => {
    const shell = contentShellRef.current
    const inner = contentInnerRef.current
    if (!inner) return 0
    if (!shell) return Math.ceil(inner.scrollHeight)

    const availableHeight = readCreatorContentAvailableHeight()
    const previousShellHeight = shell.style.height
    const previousShellOverflow = shell.style.overflow
    const previousShellTransition = shell.style.transition
    const previousInnerMaxHeight = inner.style.maxHeight
    const previousInnerOverflowY = inner.style.overflowY

    try {
      shell.style.height = 'auto'
      shell.style.overflow = 'visible'
      shell.style.transition = 'none'
      inner.style.maxHeight = 'none'
      inner.style.overflowY = 'visible'

      return Math.min(Math.ceil(inner.scrollHeight), availableHeight)
    } finally {
      shell.style.height = previousShellHeight
      shell.style.overflow = previousShellOverflow
      shell.style.transition = previousShellTransition
      inner.style.maxHeight = previousInnerMaxHeight
      inner.style.overflowY = previousInnerOverflowY
    }
  }, [readCreatorContentAvailableHeight])

  const lockCreatorContentHeight = useCallback((): void => {
    const shell = contentShellRef.current
    if (!shell) return

    setCreatorContentHeight(Math.ceil(shell.offsetHeight))
    void shell.offsetHeight
  }, [setCreatorContentHeight])

  const animateCreatorContentHeightTo = useCallback(
    (nextHeight: number): void => {
      clearContentHeightFrame()
      contentHeightFrameRef.current = window.requestAnimationFrame(() => {
        contentHeightFrameRef.current = null
        setCreatorContentHeight(nextHeight)
      })
    },
    [clearContentHeightFrame, setCreatorContentHeight]
  )

  const finishPendingContentTransition = useCallback((): void => {
    if (!pendingContentVisibleRef.current) return

    pendingContentVisibleRef.current = false
    setIsContentHeightTransitioning(false)
    setIsContentVisible(true)
    clearContentTransitionTimer()
  }, [clearContentTransitionTimer])

  const syncCreatorContentHeight = useCallback((): void => {
    const nextHeight = readCreatorContentHeight()
    if (nextHeight <= 0) return

    lockCreatorContentHeight()
    animateCreatorContentHeightTo(nextHeight)
  }, [animateCreatorContentHeightTo, lockCreatorContentHeight, readCreatorContentHeight])

  const observeCreatorContent = useCallback((): void => {
    contentResizeObserverRef.current?.disconnect()
    clearContentResizeFrame()

    if (typeof ResizeObserver === 'undefined' || !contentInnerRef.current) return

    contentResizeObserverRef.current = new ResizeObserver(() => {
      if (!visible || !isContentVisible || isContentHeightTransitioning) return
      if (contentResizeFrameRef.current !== null) return

      contentResizeFrameRef.current = window.requestAnimationFrame(() => {
        contentResizeFrameRef.current = null
        syncCreatorContentHeight()
      })
    })
    contentResizeObserverRef.current.observe(contentInnerRef.current)
  }, [
    clearContentResizeFrame,
    isContentHeightTransitioning,
    isContentVisible,
    syncCreatorContentHeight,
    visible
  ])

  const initializeCreatorContentHeight = useCallback((): void => {
    clearContentHeightFrame()
    contentHeightFrameRef.current = window.requestAnimationFrame(() => {
      contentHeightFrameRef.current = window.requestAnimationFrame(() => {
        contentHeightFrameRef.current = null
        observeCreatorContent()
        syncCreatorContentHeight()
        setIsContentVisible(true)
      })
    })
  }, [clearContentHeightFrame, observeCreatorContent, syncCreatorContentHeight])

  const transitionCreatorContentHeight = useCallback((): void => {
    if (!visible) return

    setIsContentHeightTransitioning(true)
    pendingContentVisibleRef.current = false
    clearContentTransitionTimer()
    clearContentHeightFrame()
    lockCreatorContentHeight()

    contentHeightFrameRef.current = window.requestAnimationFrame(() => {
      contentHeightFrameRef.current = window.requestAnimationFrame(() => {
        contentHeightFrameRef.current = null
        const nextHeight = readCreatorContentHeight()
        if (nextHeight <= 0) {
          setIsContentHeightTransitioning(false)
          return
        }

        setIsContentVisible(false)
        pendingContentVisibleRef.current = true
        void contentShellRef.current?.offsetHeight
        animateCreatorContentHeightTo(nextHeight)
        contentTransitionTimerRef.current = window.setTimeout(
          finishPendingContentTransition,
          CONTENT_HEIGHT_TRANSITION_FALLBACK_MS
        )
      })
    })
  }, [
    animateCreatorContentHeightTo,
    clearContentHeightFrame,
    clearContentTransitionTimer,
    finishPendingContentTransition,
    lockCreatorContentHeight,
    readCreatorContentHeight,
    visible
  ])

  const handleContentShellTransitionEnd = useCallback(
    (event: React.TransitionEvent<HTMLDivElement>): void => {
      if (
        event.target !== contentShellRef.current ||
        event.propertyName !== 'height' ||
        !isContentHeightTransitioning
      ) {
        return
      }

      setIsContentHeightTransitioning(false)

      if (pendingContentVisibleRef.current) {
        finishPendingContentTransition()
        return
      }

      clearContentTransitionTimer()
    },
    [clearContentTransitionTimer, finishPendingContentTransition, isContentHeightTransitioning]
  )

  useEffect(() => {
    if (!visible) {
      wasVisibleRef.current = false
      return
    }

    if (wasVisibleRef.current) return
    wasVisibleRef.current = true

    const creatorState = useLabCreatorStore.getState()
    const containerState = useContainerStore.getState()
    const configState = useDockerConfigStore.getState()
    const initialCreateType = dockerStatus?.available === false ? 'ssh' : 'compose'

    setIsContentMeasured(false)
    setIsContentVisible(false)
    creatorState.setCreateType(initialCreateType)
    creatorState.setComposeContent(creatorState.getComposeTemplate('mixed'))
    creatorState.setDockerfileContent(
      `FROM node:18-alpine\n\nWORKDIR /app\n\nCOPY package*.json ./\nRUN npm install\n\nCOPY . .\n\nEXPOSE 3000\n\nCMD ["npm", "start"]\n`
    )
    creatorState.setDockerfileContext('')
    creatorState.setComposeProjectName('')
    creatorState.setDockerfileProjectName('')
    creatorState.resetSshConfig()
    creatorState.clearCreateError()

    void Promise.all([
      containerState.loadContainers(),
      configState.loadDockerfileConfigs(),
      configState.loadComposeConfigs()
    ])
  }, [dockerStatus?.available, visible])

  useEffect(() => {
    if (!visible || dockerStatus?.available !== false) return

    const creatorState = useLabCreatorStore.getState()
    if (DOCKER_CREATE_TYPES.has(creatorState.createType)) {
      creatorState.setCreateType('ssh')
    }
  }, [dockerStatus?.available, visible])

  useEffect(() => {
    if (visible) {
      initializeCreatorContentHeight()
    }
  }, [initializeCreatorContentHeight, visible])

  useEffect(() => {
    return () => {
      contentResizeObserverRef.current?.disconnect()
      clearContentHeightFrame()
      clearContentResizeFrame()
      clearContentTransitionTimer()
    }
  }, [clearContentHeightFrame, clearContentResizeFrame, clearContentTransitionTimer])

  async function handleSaveConfig(name: string): Promise<void> {
    useLabCreatorStore.setState({ saveConfigName: name.trim() })
    await creatorStore.handleSaveConfig()
  }

  async function testSshConnection(): Promise<void> {
    const ssh = creatorStore.sshConfig
    if (!ssh?.host?.trim() || !ssh?.username?.trim()) {
      notify.warning('请填写必填项', '主机地址和用户名不能为空', { source: 'lab' })
      return
    }
    setIsTestingSsh(true)
    try {
      const result = await window.api.ssh.config.test(
        {
          id: '',
          name: 'test',
          host: ssh.host,
          port: ssh.port,
          username: ssh.username,
          authType: ssh.authType,
          keyName: ssh.authType === 'key' ? ssh.keyName : undefined,
          keyContent: ssh.authType === 'key' ? ssh.keyContent : undefined
        },
        ssh.authType === 'password' ? ssh.password : undefined
      )
      if (result.success) notify.success('连接成功', undefined, { source: 'lab' })
      else notify.error('连接失败', result.error || '未知错误', { source: 'lab' })
    } finally {
      setIsTestingSsh(false)
    }
  }

  // 从各 store 获取响应式数据
  const createType = creatorStore.createType || 'compose'
  const showSaveDialog = creatorStore.showSaveDialog || false
  const isCreating = creatorStore.isCreating || false
  const createError = creatorStore.createError || ''
  const createPhaseText = creatorStore.getCreatePhaseText() || ''
  const createProgress = creatorStore.getCreateProgress()
  const containerSelectHint = creatorStore.getContainerSelectHint()
  const canCreate = creatorStore.getCanCreate()
  const composeContent = composeConfigStore.composeContent || ''
  const composeProjectName = composeConfigStore.composeProjectName || ''
  const dockerfileContent = dockerfileConfigStore.dockerfileContent || ''
  const dockerfileContext = dockerfileConfigStore.dockerfileContext || ''
  const dockerfileProjectName = dockerfileConfigStore.dockerfileProjectName || ''
  const portMappings = usePortMappingStore((s) => s.portMappings)
  const sshConfig = creatorStore.sshConfig

  const renderPortMappingSection = (type: 'compose' | 'dockerfile') => (
    <PortMappingSection
      createType={type}
      portMappings={portMappings}
      onRefresh={() => creatorStore.refreshPorts()}
      onAdd={() => creatorStore.addPortMapping()}
      onUpdate={(i, p) => creatorStore.updatePortMapping(i, p)}
      onRemove={(i) => creatorStore.removePortMapping(i)}
    />
  )

  useLayoutEffect(() => {
    if (!visible || !isContentMeasured) return
    transitionCreatorContentHeight()
  }, [
    containerSelectHint,
    createError,
    createType,
    isContentMeasured,
    isCreating,
    portMappings.length,
    sshConfig?.authType,
    transitionCreatorContentHeight,
    visible
  ])

  return (
    <CssTransition name="sm-modal" show={visible} appear>
      {({ className, ref }) => (
        <div
          ref={ref}
          className={['sm-modal__overlay', 'lab-creator-overlay', className]
            .filter(Boolean)
            .join(' ')}
          onClick={onClose}
        >
          <div
            ref={creatorRef}
            className="sm-modal__surface lab-creator"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="creator-header">
              <h2>创建新实验室</h2>
              <button className="close-btn" onClick={onClose}>
                ×
              </button>
            </div>

            <CreateTypeSelector
              createType={createType}
              dockerReady={dockerStatus?.available ?? true}
              onChange={(t) => {
                creatorStore.setCreateType(t)
              }}
            />

            <div
              ref={contentShellRef}
              className={['creator-content-shell', isContentMeasured && 'is-measured']
                .filter(Boolean)
                .join(' ')}
              onTransitionEnd={handleContentShellTransitionEnd}
            >
              <div
                ref={contentInnerRef}
                className={['creator-content-inner', isContentVisible && 'is-visible']
                  .filter(Boolean)
                  .join(' ')}
              >
                {createType === 'existing' && (
                  <ContainerSelector
                    containers={containers}
                    onSelect={(containerId) => {
                      creatorStore.selectContainer(containerId)
                    }}
                  />
                )}

                {containerSelectHint && <div className="container-hint">{containerSelectHint}</div>}

                {isCreating && (
                  <div className="create-progress">
                    <div className="progress-header">
                      <span className="progress-text">{createPhaseText}</span>
                      <span className="progress-percent">{createProgress}%</span>
                    </div>
                    <div className="progress-bar">
                      <div className="progress-fill" style={{ width: `${createProgress}%` }}></div>
                    </div>
                  </div>
                )}

                {createError && !isCreating && (
                  <div className="create-error">
                    <div className="error-header">
                      <span className="error-icon">⚠</span>
                      <span className="error-title">创建失败</span>
                      <button className="error-close" onClick={clearCreateError}>
                        ×
                      </button>
                    </div>
                    <div className="error-message">{createError}</div>
                  </div>
                )}

                {createType === 'compose' && (
                  <>
                    <ComposeEditor
                      modelValue={composeContent}
                      projectName={composeProjectName}
                      onUpdateModelValue={(v) => {
                        creatorStore.setComposeContent(v)
                      }}
                      onUpdateProjectName={(v) => {
                        creatorStore.setComposeProjectName(v)
                      }}
                      onSaveConfig={() => {
                        creatorStore.openSaveDialog('compose')
                      }}
                    />
                    {renderPortMappingSection('compose')}
                  </>
                )}

                {createType === 'dockerfile' && (
                  <>
                    <div className="project-name-section">
                      <label className="form-label">
                        实验室名称 <span className="required">*</span>
                      </label>
                      <input
                        value={dockerfileProjectName}
                        type="text"
                        className="form-input"
                        placeholder="请输入实验室名称"
                        onChange={(e) => {
                          creatorStore.setDockerfileProjectName(e.target.value)
                        }}
                      />
                    </div>
                    <DockerfileEditor
                      modelValue={dockerfileContent}
                      context={dockerfileContext}
                      onUpdateModelValue={(v) => {
                        creatorStore.setDockerfileContent(v)
                      }}
                      onUpdateContext={(v) => {
                        creatorStore.setDockerfileContext(v)
                      }}
                      onSaveConfig={() => {
                        creatorStore.openSaveDialog('dockerfile')
                      }}
                    />
                    {renderPortMappingSection('dockerfile')}
                  </>
                )}

                {createType === 'ssh' && (
                  <div className={`${styles['ssh-form']} creator-section`}>
                    <div className={styles['ssh-form__field']}>
                      <label className="form-label">
                        主机地址 <span className="required">*</span>
                      </label>
                      <input
                        value={sshConfig?.host || ''}
                        type="text"
                        className="form-input"
                        placeholder="192.168.1.100"
                        onChange={(e) => creatorStore.updateSshConfig({ host: e.target.value })}
                      />
                    </div>
                    <div
                      className={`${styles['ssh-form__field']} ${styles['ssh-form__field--inline']}`}
                    >
                      <div className={styles['ssh-form__field-half']}>
                        <label className="form-label">端口</label>
                        <input
                          value={sshConfig?.port || 22}
                          type="number"
                          className="form-input"
                          placeholder="22"
                          onChange={(e) =>
                            creatorStore.updateSshConfig({ port: Number(e.target.value) })
                          }
                        />
                      </div>
                      <div className={styles['ssh-form__field-half']}>
                        <label className="form-label">
                          用户名 <span className="required">*</span>
                        </label>
                        <input
                          value={sshConfig?.username || ''}
                          type="text"
                          className="form-input"
                          placeholder="root"
                          onChange={(e) =>
                            creatorStore.updateSshConfig({ username: e.target.value })
                          }
                        />
                      </div>
                    </div>
                    <div className={styles['ssh-form__field']}>
                      <label className="form-label">认证方式</label>
                      <div className={styles['ssh-form__toggle']}>
                        <button
                          className={[
                            styles['ssh-form__toggle-btn'],
                            sshConfig?.authType === 'password' && styles.active
                          ]
                            .filter(Boolean)
                            .join(' ')}
                          onClick={() => creatorStore.updateSshConfig({ authType: 'password' })}
                        >
                          密码
                        </button>
                        <button
                          className={[
                            styles['ssh-form__toggle-btn'],
                            sshConfig?.authType === 'key' && styles.active
                          ]
                            .filter(Boolean)
                            .join(' ')}
                          onClick={() => creatorStore.updateSshConfig({ authType: 'key' })}
                        >
                          密钥
                        </button>
                      </div>
                    </div>

                    {sshConfig?.authType === 'password' ? (
                      <div className={styles['ssh-form__field']}>
                        <label className="form-label">密码</label>
                        <input
                          value={sshConfig?.password || ''}
                          type="password"
                          className="form-input"
                          placeholder="输入 SSH 密码"
                          onChange={(e) =>
                            creatorStore.updateSshConfig({ password: e.target.value })
                          }
                        />
                      </div>
                    ) : (
                      <>
                        <div className={styles['ssh-form__field']}>
                          <label className="form-label">
                            密钥名称 <span className="required">*</span>
                          </label>
                          <input
                            value={sshConfig?.keyName || ''}
                            type="text"
                            className="form-input"
                            placeholder="my-key"
                            onChange={(e) =>
                              creatorStore.updateSshConfig({ keyName: e.target.value })
                            }
                          />
                        </div>
                        <div className={styles['ssh-form__field']}>
                          <label className="form-label">
                            密钥内容 <span className="required">*</span>
                          </label>
                          <textarea
                            value={sshConfig?.keyContent || ''}
                            className={`form-input ${styles['ssh-form__key-textarea']}`}
                            placeholder={
                              '-----BEGIN OPENSSH PRIVATE KEY-----\n...\n-----END OPENSSH PRIVATE KEY-----'
                            }
                            rows={6}
                            onChange={(e) =>
                              creatorStore.updateSshConfig({ keyContent: e.target.value })
                            }
                          ></textarea>
                        </div>
                      </>
                    )}
                    <button
                      className={styles['ssh-form__test-btn']}
                      disabled={isTestingSsh}
                      onClick={testSshConnection}
                    >
                      {isTestingSsh ? '测试连接中...' : '测试连接'}
                    </button>
                  </div>
                )}

                <CreateActions
                  isCreating={isCreating}
                  canCreate={canCreate}
                  createPhaseText={createPhaseText}
                  onClose={onClose}
                  onCreate={async () => {
                    const created = await creatorStore.handleCreate()
                    if (created) onClose()
                  }}
                />
              </div>
            </div>

            <SaveConfigDialog
              visible={showSaveDialog}
              onClose={() => {
                creatorStore.closeSaveDialog()
              }}
              onSave={handleSaveConfig}
            />
          </div>
        </div>
      )}
    </CssTransition>
  )
}
