// src/renderer/src/components/lab/LabToolsToggle.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue'
import styles from './LabToolsToggle.module.css'

const props = defineProps<{
  modelValue: boolean
  disabled?: boolean
  compact?: boolean
}>()

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void
  (e: 'change', value: boolean): void
}>()

const isEnabled = ref(props.modelValue)

// 同步 props 到本地状态
watch(
  () => props.modelValue,
  (newVal) => {
    isEnabled.value = newVal
  }
)

function toggle(): void {
  if (!props.disabled) {
    isEnabled.value = !isEnabled.value
    emit('update:modelValue', isEnabled.value)
    emit('change', isEnabled.value)
  }
}

onMounted(() => {
  window.api.logger.debug('[LabToolsToggle] 组件挂载', {
    enabled: isEnabled.value
  })
})
</script>

<template>
  <div
    :class="[
      styles['lab-tools-toggle'],
      {
        [styles['enabled']]: isEnabled,
        [styles['disabled']]: disabled,
        [styles['is-compact']]: props.compact
      }
    ]"
    @click="toggle"
  >
    <div :class="styles['toggle-switch']">
      <div :class="styles['toggle-thumb']"></div>
    </div>
    <span :class="styles['toggle-label']">实验室</span>
  </div>
</template>

// src/renderer/src/components/lab/LabToolsToggle.tsx
import { useState, useEffect } from 'react'
import styles from './LabToolsToggle.module.css'

interface LabToolsToggleProps {
  modelValue: boolean
  disabled?: boolean
  compact?: boolean
  onUpdateModelValue: (value: boolean) => void
  onChange?: (value: boolean) => void
}

export default function LabToolsToggle({
  modelValue,
  disabled,
  compact,
  onUpdateModelValue,
  onChange
}: LabToolsToggleProps) {
  const [isEnabled, setIsEnabled] = useState(modelValue)

  useEffect(() => {
    setIsEnabled(modelValue)
  }, [modelValue])

  useEffect(() => {
    window.api.logger.debug('[LabToolsToggle] 组件挂载', { enabled: isEnabled })
  }, [])

  function toggle(): void {
    if (!disabled) {
      const next = !isEnabled
      setIsEnabled(next)
      onUpdateModelValue(next)
      onChange?.(next)
    }
  }

  return (
    <div
      className={`${styles['lab-tools-toggle']} ${isEnabled ? styles.enabled : ''} ${disabled ? styles.disabled : ''} ${compact ? styles['is-compact'] : ''}`}
      role="button"
      tabIndex={disabled ? -1 : 0}
      aria-pressed={isEnabled}
      aria-disabled={disabled}
      onClick={toggle}
      onKeyDown={(event) => {
        if (event.key === 'Enter' || event.key === ' ') {
          event.preventDefault()
          toggle()
        }
      }}
    >
      <span className={styles['toggle-switch']} aria-hidden="true">
        <span className={styles['toggle-thumb']}></span>
      </span>
      <span className={styles['toggle-label']}>实验室</span>
    </div>
  )
}
