// src/renderer/src/components/lab/SaveConfigDialog.tsx
import { useState } from 'react'
import styles from './SaveConfigDialog.module.css'

interface SaveConfigDialogProps {
  visible: boolean
  onClose: () => void
  onSave: (name: string) => void
}

export default function SaveConfigDialog({ visible, onClose, onSave }: SaveConfigDialogProps) {
  const [configName, setConfigName] = useState('')
  const [isComposing, setIsComposing] = useState(false)

  function handleKeydown(event: React.KeyboardEvent): void {
    if (isComposing || event.key !== 'Enter') return
    event.preventDefault()
    handleSave()
  }

  function handleSave(): void {
    if (!configName.trim()) return
    onSave(configName.trim())
    setConfigName('')
  }

  function handleClose(): void {
    setConfigName('')
    onClose()
  }

  if (!visible) return null

  return (
    <div className={styles['save-dialog-overlay']} onClick={handleClose}>
      <div className={styles['save-dialog']} onClick={(e) => e.stopPropagation()}>
        <div className={styles['save-dialog-header']}>
          <h4>保存配置</h4>
          <button className={`${styles['close-btn']} ${styles.small}`} onClick={handleClose}>
            ×
          </button>
        </div>
        <div className={styles['save-dialog-body']}>
          <input
            value={configName}
            type="text"
            className="sm-input"
            placeholder="输入配置名称..."
            onChange={(e) => setConfigName(e.target.value)}
            onKeyDown={handleKeydown}
            onCompositionStart={() => setIsComposing(true)}
            onCompositionEnd={() => setIsComposing(false)}
          />
          <button className="sm-button sm-button--primary" onClick={handleSave}>
            保存
          </button>
        </div>
      </div>
    </div>
  )
}

// src/renderer/src/components/lab/SaveConfigDialog.vue
<script setup lang="ts">
import { ref } from 'vue'
import styles from './SaveConfigDialog.module.css'

defineProps<{
  visible: boolean
}>()

const configName = ref('')
const isComposing = ref(false)

const emit = defineEmits<{
  (e: 'close'): void
  (e: 'save', name: string): void
}>()

function handleCompositionStart(): void {
  isComposing.value = true
}

function handleCompositionEnd(): void {
  isComposing.value = false
}

function handleKeydown(event: KeyboardEvent): void {
  if (isComposing.value || event.key !== 'Enter') return
  event.preventDefault()
  handleSave()
}

function handleSave(): void {
  if (!configName.value.trim()) return
  emit('save', configName.value.trim())
  configName.value = ''
}

function handleClose(): void {
  configName.value = ''
  emit('close')
}
</script>

<template>
  <div v-if="visible" :class="styles['save-dialog-overlay']" @click.self="handleClose">
    <div :class="styles['save-dialog']">
      <div :class="styles['save-dialog-header']">
        <h4>保存配置</h4>
        <button :class="[styles['close-btn'], styles['small']]" @click="handleClose">×</button>
      </div>
      <div :class="styles['save-dialog-body']">
        <div :class="styles['form-field']">
          <label>配置名称</label>
          <input
            v-model="configName"
            type="text"
            :class="styles['input']"
            placeholder="请输入配置名称"
            @keydown="handleKeydown"
            @compositionstart="handleCompositionStart"
            @compositionend="handleCompositionEnd"
          />
        </div>
      </div>
      <div :class="styles['save-dialog-footer']">
        <button :class="styles['btn']" @click="handleClose">取消</button>
        <button :class="styles['btn-primary']" :disabled="!configName.trim()" @click="handleSave">
          保存
        </button>
      </div>
    </div>
  </div>
</template>
