// src/renderer/src/components/lab/SshReconnectPrompt.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { LabData } from '@renderer/types/lab'
import styles from './SshReconnectPrompt.module.css'

const props = defineProps<{
  lab: LabData
  password: string
  connecting?: boolean
}>()

const emit = defineEmits<{
  (e: 'update:password', value: string): void
  (e: 'connect'): void
}>()

const ssh = computed(() => props.lab.ssh)
const isPasswordAuth = computed(() => ssh.value?.authType === 'password')
const targetLabel = computed(() => {
  if (!ssh.value) {
    return '远程服务器'
  }

  return `${ssh.value.username}@${ssh.value.host}:${ssh.value.port}`
})

function handlePasswordInput(event: Event): void {
  emit('update:password', (event.target as HTMLInputElement).value)
}
</script>

<template>
  <section v-if="ssh" :class="styles['ssh-reconnect-prompt']" role="status">
    <div :class="styles['ssh-reconnect-prompt__copy']">
      <span :class="styles['ssh-reconnect-prompt__title']">SSH 未连接</span>
      <span :class="styles['ssh-reconnect-prompt__target']">{{ targetLabel }}</span>
    </div>

    <input
      v-if="isPasswordAuth"
      :value="password"
      type="password"
      :class="styles['ssh-reconnect-prompt__password']"
      placeholder="输入 SSH 密码"
      :disabled="connecting"
      @input="handlePasswordInput"
      @keydown.enter="emit('connect')"
    />

    <button
      class="sm-button sm-button--primary sm-button--small"
      :disabled="connecting || (isPasswordAuth && !password.trim())"
      @click="emit('connect')"
    >
      {{ connecting ? '连接中...' : '重新连接' }}
    </button>
  </section>
</template>

// src/renderer/src/components/lab/SshReconnectPrompt.tsx
import styles from './SshReconnectPrompt.module.css'
import type { LabData } from '@renderer/types/lab'

interface SshReconnectPromptProps {
  password: string
  lab: LabData
  connecting: boolean
  onUpdatePassword: (password: string) => void
  onConnect: () => void
}

export default function SshReconnectPrompt({
  password,
  lab,
  connecting,
  onUpdatePassword,
  onConnect
}: SshReconnectPromptProps) {
  const needPassword = lab.ssh?.authType === 'password'

  return (
    <div className={styles['ssh-reconnect-prompt']}>
      <div className={styles['reconnect-info']}>
        <span className={styles['reconnect-label']}>SSH 已断开</span>
        <span className={styles['reconnect-host']}>
          {lab.ssh?.host}:{lab.ssh?.port}
        </span>
      </div>
      {needPassword && (
        <input
          value={password}
          type="password"
          className="sm-input"
          placeholder="SSH 密码"
          onChange={(e) => onUpdatePassword(e.target.value)}
        />
      )}
      <button
        className="sm-button sm-button--primary sm-button--small"
        disabled={connecting || (needPassword && !password.trim())}
        onClick={onConnect}
      >
        {connecting ? '连接中...' : '重新连接'}
      </button>
    </div>
  )
}
