// src/renderer/src/pages/KnowledgePage.tsx
import { useState, useCallback, useEffect } from 'react'
import { useKnowledgeStore } from '@renderer/stores/knowledgeStore'
import { useUIStateStore } from '@renderer/stores/uiStateStore'
import { useNotification } from '@renderer/composables/useNotification'
import KnowledgeMain from '@renderer/components/KnowledgeMain'
import KnowledgeForm from '@renderer/components/knowledge/KnowledgeForm'
import FileManagerModal from '@renderer/components/knowledge/FileManagerModal'
import FileSelectorModal from '@renderer/components/knowledge/FileSelectorModal'
import type { FileItem } from '@renderer/types'
import styles from './KnowledgePage.module.css'

export default function KnowledgePage() {
  const knowledgeBases = useKnowledgeStore((s) => s.knowledgeBases)
  const activeKbId = useKnowledgeStore((s) => s.activeKbId) ?? undefined
  const showForm = useKnowledgeStore((s) => s.showForm)
  const loadKnowledgeBases = useKnowledgeStore((s) => s.loadKnowledgeBases)
  const handleFormSubmit = useKnowledgeStore((s) => s.handleFormSubmit)
  const closeForm = useKnowledgeStore((s) => s.closeForm)

  const showKnowledgeFileManager = useUIStateStore((s) => s.showKnowledgeFileManager)
  const closeKnowledgeFileManager = useUIStateStore((s) => s.closeKnowledgeFileManager)

  const notify = useNotification()

  const [showFileSelector, setShowFileSelector] = useState(false)
  const [currentKBIdForSelector, setCurrentKBIdForSelector] = useState('')

  useEffect(() => {
    loadKnowledgeBases()
  }, [loadKnowledgeBases])

  const activeKnowledgeBase = knowledgeBases.find((kb) => kb.id === activeKbId)

  const handleKnowledgeSubmit = useCallback(
    async (data: {
      name: string
      description: string
      embeddingConfig: {
        baseUrl: string
        apiKey?: string
        displayName?: string
        model: string
        dimensions: number
      }
      embeddingDimension: number
      chunkSize: number
      chunkOverlap: number
    }) => {
      const success = await handleFormSubmit(data)
      if (!success) {
        notify.error('创建知识库失败', useKnowledgeStore.getState().error || '未知错误', {
          source: 'knowledge'
        })
      }
    },
    [handleFormSubmit, notify]
  )

  const handleAddFiles = useCallback((kbId: string) => {
    setCurrentKBIdForSelector(kbId)
    setShowFileSelector(true)
  }, [])

  const handleFileSelectorClose = useCallback(() => {
    setShowFileSelector(false)
    setCurrentKBIdForSelector('')
  }, [])

  const handleFilesLinked = useCallback(
    (files: FileItem[]) => {
      const kb = knowledgeBases.find((k) => k.id === currentKBIdForSelector)
      if (kb) {
        const newFileIds = files.map((f) => f.id)
        kb.linkedFileIds = [...(kb.linkedFileIds || []), ...newFileIds]
        kb.documentCount = kb.linkedFileIds.length
      }
    },
    [knowledgeBases, currentKBIdForSelector]
  )

  const handleFileUnlinked = useCallback(
    (kbId: string, fileId: string) => {
      const kb = knowledgeBases.find((k) => k.id === kbId)
      if (kb && kb.linkedFileIds) {
        kb.linkedFileIds = kb.linkedFileIds.filter((id) => id !== fileId)
        kb.documentCount = kb.linkedFileIds.length
      }
    },
    [knowledgeBases]
  )

  const handleDescriptionUpdated = useCallback(
    (kbId: string, description: string) => {
      const kb = knowledgeBases.find((k) => k.id === kbId)
      if (kb) {
        kb.description = description
      }
    },
    [knowledgeBases]
  )

  const linkedFileIdsForSelector =
    knowledgeBases.find((kb) => kb.id === currentKBIdForSelector)?.linkedFileIds || []

  return (
    <div className={`${styles.page} sm-workspace-view`}>
      <KnowledgeMain
        knowledgeBase={activeKnowledgeBase}
        onAddFiles={handleAddFiles}
        onFileUnlinked={handleFileUnlinked}
        onDescriptionUpdated={handleDescriptionUpdated}
      />

      {showForm && <KnowledgeForm onSubmit={handleKnowledgeSubmit} onCancel={closeForm} />}

      {showKnowledgeFileManager && <FileManagerModal onClose={closeKnowledgeFileManager} />}

      {showFileSelector && (
        <FileSelectorModal
          kbId={currentKBIdForSelector}
          linkedFileIds={linkedFileIdsForSelector}
          onClose={handleFileSelectorClose}
          onFilesLinked={handleFilesLinked}
        />
      )}
    </div>
  )
}

// src/renderer/src/pages/KnowledgePage.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import KnowledgeSidebar from '@renderer/components/KnowledgeSidebar.vue'
import KnowledgeMain from '@renderer/components/KnowledgeMain.vue'
import KnowledgeForm from '@renderer/components/knowledge/KnowledgeForm.vue'

import FileManagerModal from '@renderer/components/knowledge/FileManagerModal.vue'
import FileSelectorModal from '@renderer/components/knowledge/FileSelectorModal.vue'
import { useKnowledgeStore, useUIStateStore } from '@renderer/stores'
import type { FileItem } from '@renderer/types'

// ==================== 知识库管理（直接使用 Store）====================
const knowledgeStore = useKnowledgeStore()
const { knowledgeBases, activeKbId: storeActiveKbId, showForm } = storeToRefs(knowledgeStore)
const uiStateStore = useUIStateStore()
const { knowledgeSidebarCollapsed } = storeToRefs(uiStateStore)

// 兼容旧接口命名（将 null 转为 undefined）
const activeKbId = computed(() => storeActiveKbId.value ?? undefined)
const showKnowledgeForm = showForm

// ==================== 生命周期 ====================
onMounted(async () => {
  await knowledgeStore.loadKnowledgeBases()
})

// ==================== 知识库操作 ====================
function handleSelectKB(kbId: string): void {
  knowledgeStore.setActiveKb(kbId)
}

function handleCreateKB(): void {
  knowledgeStore.openCreateForm()
}

async function handleDeleteKB(kbId: string): Promise<void> {
  if (confirm('确定要删除这个知识库吗？此操作不可撤销。')) {
    const success = await knowledgeStore.deleteKnowledgeBase(kbId)
    if (!success) {
      alert('删除知识库失败: ' + (knowledgeStore.error || '未知错误'))
    }
  }
}

async function handleKnowledgeSubmit(data: {
  name: string
  description: string
  embeddingConfig: {
    baseUrl: string
    apiKey?: string
    displayName?: string
    model: string
    dimensions: number
  }
  embeddingDimension: number
  chunkSize: number
  chunkOverlap: number
}): Promise<void> {
  const success = await knowledgeStore.handleFormSubmit(data)
  if (!success) {
    alert('创建知识库失败: ' + (knowledgeStore.error || '未知错误'))
  }
}

function handleKnowledgeCancel(): void {
  knowledgeStore.closeForm()
}

// ==================== 文件管理 ====================
const showFileManager = ref(false)
const showFileSelector = ref(false)
const currentKBIdForSelector = ref<string>('')

// KnowledgeMain 组件引用
const knowledgeMainRef = ref<InstanceType<typeof KnowledgeMain> | null>(null)

function handleManageFiles(): void {
  showFileManager.value = true
}

function handleFileManagerClose(): void {
  showFileManager.value = false
}

function handleAddFiles(kbId: string): void {
  currentKBIdForSelector.value = kbId
  showFileSelector.value = true
}

function handleFileSelectorClose(): void {
  showFileSelector.value = false
  currentKBIdForSelector.value = ''
}

function handleFilesLinked(files: FileItem[]): void {
  // 通过 ref 调用 KnowledgeMain 组件的方法更新 UI
  if (knowledgeMainRef.value) {
    knowledgeMainRef.value.handleFilesLinked(files)
  }

  // 更新 knowledgeBases 中的 linkedFileIds 和 documentCount，确保 Sidebar 能正确显示
  const kb = knowledgeBases.value.find((k) => k.id === currentKBIdForSelector.value)
  if (kb) {
    const newFileIds = files.map((f) => f.id)
    kb.linkedFileIds = [...(kb.linkedFileIds || []), ...newFileIds]
    kb.documentCount = kb.linkedFileIds.length
  }
}

function handleFileUnlinked(kbId: string, fileId: string): void {
  // 更新 knowledgeBases 中的 linkedFileIds 和 documentCount，确保 Sidebar 能正确显示
  const kb = knowledgeBases.value.find((k) => k.id === kbId)
  if (kb && kb.linkedFileIds) {
    kb.linkedFileIds = kb.linkedFileIds.filter((id) => id !== fileId)
    kb.documentCount = kb.linkedFileIds.length
  }
}

function handleDescriptionUpdated(kbId: string, description: string): void {
  // 更新 knowledgeBases 中的描述，确保数据同步
  const kb = knowledgeBases.value.find((k) => k.id === kbId)
  if (kb) {
    kb.description = description
  }
}
</script>

<template>
  <div class="knowledge-page sm-workspace-page">
    <div class="sm-sidebar-frame" :class="{ 'is-collapsed': knowledgeSidebarCollapsed }">
      <KnowledgeSidebar
        :knowledge-bases="knowledgeBases"
        :active-kb-id="activeKbId"
        @select-kb="handleSelectKB"
        @create-kb="handleCreateKB"
        @delete-kb="handleDeleteKB"
        @manage-files="handleManageFiles"
      />
    </div>
    <div class="sm-page-main">
      <KnowledgeMain
        ref="knowledgeMainRef"
        :knowledge-base="knowledgeBases.find((kb) => kb.id === activeKbId)"
        @add-files="handleAddFiles"
        @file-unlinked="handleFileUnlinked"
        @description-updated="handleDescriptionUpdated"
      />
    </div>
  </div>

  <!-- 知识库表单模态框 -->
  <KnowledgeForm
    v-if="showKnowledgeForm"
    @submit="handleKnowledgeSubmit"
    @cancel="handleKnowledgeCancel"
  />

  <!-- 文件管理模态框 -->
  <FileManagerModal v-if="showFileManager" @close="handleFileManagerClose" />

  <!-- 文件选择模态框 -->
  <FileSelectorModal
    v-if="showFileSelector"
    :kb-id="currentKBIdForSelector"
    :linked-file-ids="
      knowledgeBases.find((kb) => kb.id === currentKBIdForSelector)?.linkedFileIds || []
    "
    @close="handleFileSelectorClose"
    @files-linked="handleFilesLinked"
  />
</template>

<style scoped>
.knowledge-page {
  position: relative;
}
</style>
