// src/renderer/src/pages/PaperReaderPage.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, provide, ref, watch } from 'vue'
import { storeToRefs } from 'pinia'
import { usePaperReaderStore } from '@renderer/stores/paperReaderStore'
import { useUIStateStore } from '@renderer/stores/uiStateStore'
import { usePaperChatQuoteStore } from '@renderer/stores/paperChatQuoteStore'
import { useNotification } from '@renderer/composables/useNotification'
import type { PaperQuote } from '@shared/types/chat'
import PaperMarkdownView from '@renderer/components/paper/PaperMarkdownView.vue'
import PaperOriginalPdfView from '@renderer/components/paper/PaperOriginalPdfView.vue'
import PaperFigurePreview from '@renderer/components/paper/PaperFigurePreview.vue'
import PaperChatPanel from '@renderer/components/paper/chat/PaperChatPanel.vue'

const store = usePaperReaderStore()
const uiStateStore = useUIStateStore()
const paperChatQuoteStore = usePaperChatQuoteStore()
const notify = useNotification()

const {
  currentPaperId,
  currentPaper,
  markdownContent,
  markdownLoading,
  isOcrCompleted,
  paperBasePath,
  currentAnnotations,
  currentReaderDocument,
  originalPdfVisible,
  translationVisible,
  currentTranslationCache
} = storeToRefs(store)
const { paperChatPanelOpen, paperChatPanelWidth } = storeToRefs(uiStateStore)
const isResizingPaperChat = ref(false)
const markdownViewRef = ref<InstanceType<typeof PaperMarkdownView> | null>(null)
const isPaperChatPanelVisible = computed(
  () => paperChatPanelOpen.value && Boolean(currentPaper.value) && isOcrCompleted.value
)

provide('scrollToQuote', (quote: PaperQuote) => {
  markdownViewRef.value?.scrollToQuoteAndHighlight(quote)
})

async function handleAddToChat(quote: PaperQuote): Promise<void> {
  const paperId = currentPaper.value?.id
  if (!paperId) {
    return
  }

  const sessionResult = await store.ensurePaperChatSession(paperId)
  const sessionId = sessionResult.data
  if (!sessionResult.success || !sessionId) {
    notify.error('论文对话', sessionResult.error || '创建论文对话失败', { source: 'chat' })
    return
  }

  paperChatQuoteStore.addQuote(sessionId, quote)
  uiStateStore.setPaperChatPanelOpen(true)
}

function handlePaperChatResizeMove(event: PointerEvent): void {
  if (!isResizingPaperChat.value) {
    return
  }

  uiStateStore.setPaperChatPanelWidth(window.innerWidth - event.clientX)
}

function stopPaperChatResize(): void {
  if (!isResizingPaperChat.value) {
    return
  }

  isResizingPaperChat.value = false
  document.body.style.cursor = ''
  document.body.style.userSelect = ''
  window.removeEventListener('pointermove', handlePaperChatResizeMove)
  window.removeEventListener('pointerup', stopPaperChatResize)
}

function startPaperChatResize(event: PointerEvent): void {
  event.preventDefault()
  isResizingPaperChat.value = true
  document.body.style.cursor = 'col-resize'
  document.body.style.userSelect = 'none'
  window.addEventListener('pointermove', handlePaperChatResizeMove)
  window.addEventListener('pointerup', stopPaperChatResize)
  handlePaperChatResizeMove(event)
}

onMounted(async () => {
  store.ensureOcrProgressListener()
  await store.loadPapers()

  if (!currentPaperId.value && uiStateStore.lastPaperId) {
    store.selectPaper(uiStateStore.lastPaperId)
  }

  if (currentPaperId.value && isOcrCompleted.value) {
    await store.loadMarkdown(currentPaperId.value)
  }
})

watch([currentPaperId, isOcrCompleted], ([paperId, completed]) => {
  if (!paperId || !completed) {
    uiStateStore.setPaperChatPanelOpen(false)
  }
})

watch(markdownLoading, async (loading, wasLoading) => {
  if (loading || !wasLoading) return

  const progress = currentPaper.value?.readingProgress
  if (!progress?.translationVisible) return

  const revisionId = currentReaderDocument.value?.sourceRevisionId
  if (revisionId && progress.sourceRevisionId !== revisionId) return

  if (!store.translationVisible) {
    await store.toggleTranslationVisible()
  }
})

onBeforeUnmount(() => {
  stopPaperChatResize()
  store.resetFigureUiState()
  store.hideOriginalPdf()
})
</script>

<template>
  <div class="paper-reader-page sm-workspace-view">
    <div
      class="paper-reader-page__main"
      :class="{ 'paper-reader-page__main--reader': isOcrCompleted }"
    >
      <div v-if="!currentPaperId" class="paper-reader-page__empty-state">
        <div class="sm-empty paper-reader-page__empty-card">
          <h2>选择一篇论文开始阅读</h2>
          <p>从左侧列表中选择已有文献，或直接上传 PDF 开始阅读。</p>
          <button
            class="sm-button sm-button--primary"
            type="button"
            @click="store.uploadAndRenderPdf()"
          >
            上传 PDF
          </button>
        </div>
      </div>

      <PaperOriginalPdfView
        v-else-if="isOcrCompleted && originalPdfVisible && currentPaper"
        :paper-id="currentPaperId || ''"
        :page-assets="currentPaper.pageAssets"
        :page-count="currentPaper.pageCount"
      />

      <PaperMarkdownView
        v-else-if="isOcrCompleted"
        ref="markdownViewRef"
        :content="markdownContent"
        :loading="markdownLoading"
        :paper-id="currentPaperId || ''"
        :base-path="paperBasePath || undefined"
        :annotations="currentAnnotations"
        :reader-document="currentReaderDocument"
        :translation-visible="translationVisible"
        :translation-cache="currentTranslationCache"
        :reading-progress="currentPaper?.readingProgress"
        @add-to-chat="handleAddToChat"
      />
    </div>

    <div
      class="paper-reader-page__chat-slot"
      :class="{
        'paper-reader-page__chat-slot--open': isPaperChatPanelVisible,
        'paper-reader-page__chat-slot--resizing': isResizingPaperChat
      }"
      :style="{ '--paper-chat-panel-width': `${paperChatPanelWidth}px` }"
    >
      <Transition name="paper-chat-panel-slide">
        <aside v-if="isPaperChatPanelVisible && currentPaper" class="paper-reader-page__chat">
          <div
            class="paper-reader-page__chat-resize"
            role="separator"
            aria-orientation="vertical"
            title="拖拽调整聊天窗口宽度"
            @pointerdown="startPaperChatResize"
          ></div>
          <PaperChatPanel
            :paper="currentPaper"
            @close="uiStateStore.setPaperChatPanelOpen(false)"
          />
        </aside>
      </Transition>
    </div>

    <PaperFigurePreview />
  </div>
</template>

<style scoped>
.paper-reader-page {
  position: relative;
  flex-direction: row;
  background: var(--sm-color-bg-canvas);
}

.paper-reader-page__main {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 0;
  overflow: auto;
  padding: var(--sm-space-5);
}

.paper-reader-page__main--reader {
  align-items: stretch;
  justify-content: stretch;
  overflow: hidden;
  padding: 0;
}

.paper-reader-page__empty-state {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: var(--sm-space-6);
}

.paper-reader-page__empty-card {
  width: min(520px, 100%);
  background: var(--sm-color-surface-2);
  border-style: solid;
}

.paper-reader-page__empty-card h2 {
  margin: 0;
  font-size: 18px;
  color: var(--sm-color-text-primary);
}

.paper-reader-page__empty-card p {
  margin: 0;
  max-width: 420px;
  line-height: 1.6;
}

.paper-reader-page__chat-slot {
  position: relative;
  flex: 0 0 0;
  width: 0;
  height: 100%;
  min-width: 0;
  min-height: 0;
  overflow: visible;
  transition:
    flex-basis 180ms cubic-bezier(0.2, 0, 0, 1),
    width 180ms cubic-bezier(0.2, 0, 0, 1);
  will-change: flex-basis, width;
}

.paper-reader-page__chat-slot--open {
  flex-basis: var(--paper-chat-panel-width);
  width: var(--paper-chat-panel-width);
}

.paper-reader-page__chat-slot--resizing {
  transition: none;
}

.paper-reader-page__chat {
  position: relative;
  flex: 0 0 auto;
  box-sizing: border-box;
  width: var(--paper-chat-panel-width);
  min-width: 340px;
  max-width: min(680px, 100vw);
  height: calc(100% - var(--sm-paper-toolbar-height) - var(--sm-space-2));
  min-height: 0;
  margin-top: var(--sm-paper-toolbar-height);
  margin-bottom: var(--sm-space-2);
  border: 1px solid var(--sm-color-border-default);
  border-radius: var(--sm-radius-lg);
  background: var(--sm-color-bg-canvas);
  overflow: hidden;
}

.paper-chat-panel-slide-enter-active,
.paper-chat-panel-slide-leave-active {
  transition:
    opacity 150ms linear,
    transform 180ms cubic-bezier(0.2, 0, 0, 1);
  will-change: transform, opacity;
}

.paper-chat-panel-slide-enter-from,
.paper-chat-panel-slide-leave-to {
  opacity: 0;
  transform: translateX(calc(var(--sm-motion-distance-md) * 2));
}

.paper-chat-panel-slide-enter-to,
.paper-chat-panel-slide-leave-from {
  opacity: 1;
  transform: translateX(0);
}

.paper-reader-page__chat-resize {
  position: absolute;
  top: 0;
  left: -4px;
  z-index: 3;
  width: 8px;
  height: 100%;
  cursor: col-resize;
}

.paper-reader-page__chat-resize::after {
  content: '';
  position: absolute;
  top: 0;
  left: 3px;
  width: 1px;
  height: 100%;
  background: transparent;
  transition: background-color var(--sm-transition-fast);
}

.paper-reader-page__chat-resize:hover::after {
  background: var(--sm-color-border-selected);
}

@media (max-width: 760px) {
  .paper-reader-page__chat-slot {
    position: absolute;
    top: var(--sm-paper-toolbar-height);
    right: 0;
    bottom: var(--sm-space-2);
    z-index: 20;
    flex-basis: 0;
    width: min(100vw, 420px);
    height: auto;
    pointer-events: none;
    transition: none;
  }

  .paper-reader-page__chat-slot--open {
    flex-basis: 0;
    width: min(100vw, 420px);
  }

  .paper-reader-page__chat {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    width: min(100vw, 420px) !important;
    height: auto;
    margin: 0;
    min-width: min(100vw, 340px);
    pointer-events: auto;
  }
}

@media (prefers-reduced-motion: reduce) {
  .paper-reader-page__chat-slot,
  .paper-chat-panel-slide-enter-active,
  .paper-chat-panel-slide-leave-active {
    transition: none;
  }
}
</style>

// src/renderer/src/pages/PaperReaderPage.tsx
import { useState, useRef, useEffect, useMemo, useCallback } from 'react'
import { usePiniaStore } from '@renderer/composables/usePiniaStore'
import { usePaperReaderStore } from '@renderer/stores/paperReaderStore'
import { useUIStateStore } from '@renderer/stores/uiStateStore'
import { usePaperChatQuoteStore } from '@renderer/stores/paperChatQuoteStore'
import { useNotification } from '@renderer/composables/useNotification'
import { PaperQuoteContext } from '@renderer/contexts/PaperQuoteContext'
import type { PaperQuote } from '@shared/types/chat'
import styles from './PaperReaderPage.module.css'

import PaperMarkdownView, {
  type PaperMarkdownViewHandle
} from '@renderer/components/paper/PaperMarkdownView'
import PaperOriginalPdfView from '@renderer/components/paper/PaperOriginalPdfView'
import PaperFigurePreview from '@renderer/components/paper/PaperFigurePreview'
import PaperChatPanel from '@renderer/components/paper/chat/PaperChatPanel'

export default function PaperReaderPage() {
  const store = usePiniaStore(usePaperReaderStore)
  const paperChatPanelOpen = useUIStateStore((s) => s.paperChatPanelOpen)
  const setPaperChatPanelOpen = useUIStateStore((s) => s.setPaperChatPanelOpen)
  const paperChatPanelWidth = useUIStateStore((s) => s.paperChatPanelWidth)
  const setPaperChatPanelWidth = useUIStateStore((s) => s.setPaperChatPanelWidth)
  const lastPaperId = useUIStateStore((s) => s.lastPaperId)

  const paperChatQuoteStore = usePaperChatQuoteStore()
  const notify = useNotification()

  const [isResizingPaperChat, setIsResizingPaperChat] = useState(false)
  const markdownViewRef = useRef<PaperMarkdownViewHandle>(null)

  // Derive state from store (Pinia auto-unwraps refs in return type)
  const currentPaperId = store.currentPaperId ?? null
  const currentPaper = store.currentPaper ?? null
  const markdownContent = store.markdownContent ?? ''
  const markdownLoading = store.markdownLoading ?? false
  const isOcrCompleted = store.isOcrCompleted ?? false
  const paperBasePath = store.paperBasePath ?? null
  const currentAnnotations = store.currentAnnotations ?? []
  const currentReaderDocument = store.currentReaderDocument ?? null
  const originalPdfVisible = store.originalPdfVisible ?? false
  const translationVisible = store.translationVisible ?? false
  const currentTranslationCache = store.currentTranslationCache ?? null

  const isPaperChatPanelVisible =
    paperChatPanelOpen && Boolean(currentPaper) && isOcrCompleted

  // scrollToQuote implementation for PaperQuoteContext
  const scrollToQuote = useCallback((quote: PaperQuote) => {
    markdownViewRef.current?.scrollToQuoteAndHighlight(quote)
  }, [])

  const paperQuoteContextValue = useMemo(() => ({ scrollToQuote }), [scrollToQuote])

  // Handle add to chat
  const handleAddToChat = useCallback(
    async (quote: PaperQuote) => {
      const paperId = currentPaper?.id
      if (!paperId) {
        return
      }

      const sessionResult = await store.ensurePaperChatSession(paperId)
      const sessionId = sessionResult.data
      if (!sessionResult.success || !sessionId) {
        notify.error('论文对话', sessionResult.error || '创建论文对话失败', { source: 'chat' })
        return
      }

      paperChatQuoteStore.addQuote(sessionId, quote)
      setPaperChatPanelOpen(true)
    },
    [currentPaper, store, paperChatQuoteStore, notify, setPaperChatPanelOpen]
  )

  // Chat panel resize
  const handlePaperChatResizeMove = useCallback(
    (event: PointerEvent) => {
      if (!isResizingPaperChat) {
        return
      }

      setPaperChatPanelWidth(window.innerWidth - event.clientX)
    },
    [isResizingPaperChat, setPaperChatPanelWidth]
  )

  const stopPaperChatResize = useCallback(() => {
    setIsResizingPaperChat(false)
    document.body.style.cursor = ''
    document.body.style.userSelect = ''
    window.removeEventListener('pointermove', handlePaperChatResizeMove)
    window.removeEventListener('pointerup', stopPaperChatResize)
  }, [handlePaperChatResizeMove])

  const startPaperChatResize = useCallback(
    (event: React.PointerEvent) => {
      event.preventDefault()
      setIsResizingPaperChat(true)
      document.body.style.cursor = 'col-resize'
      document.body.style.userSelect = 'none'
      window.addEventListener('pointermove', handlePaperChatResizeMove)
      window.addEventListener('pointerup', stopPaperChatResize)
      handlePaperChatResizeMove(event.nativeEvent)
    },
    [handlePaperChatResizeMove, stopPaperChatResize]
  )

  // Load papers on mount
  useEffect(() => {
    store.ensureOcrProgressListener()
    void store.loadPapers().then(() => {
      if (!store.currentPaperId && lastPaperId) {
        store.selectPaper(lastPaperId)
      }

      if (store.currentPaperId && store.isOcrCompleted) {
        void store.loadMarkdown(store.currentPaperId)
      }
    })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // Close chat when paper changes to non-readable
  useEffect(() => {
    if (!currentPaperId || !isOcrCompleted) {
      setPaperChatPanelOpen(false)
    }
  }, [currentPaperId, isOcrCompleted, setPaperChatPanelOpen])

  // Auto-open translation on markdown load
  const wasMarkdownLoadingRef = useRef(markdownLoading)
  useEffect(() => {
    const wasLoading = wasMarkdownLoadingRef.current
    wasMarkdownLoadingRef.current = markdownLoading

    if (markdownLoading || !wasLoading) return

    const progress = currentPaper?.readingProgress
    if (!progress?.translationVisible) return

    const storeTranslationVisible = store.translationVisible
    if (!storeTranslationVisible) {
      void store.toggleTranslationVisible()
    }
  }, [markdownLoading, currentPaper, store])

  // Cleanup
  useEffect(() => {
    return () => {
      stopPaperChatResize()
      store.resetFigureUiState()
      store.hideOriginalPdf()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return (
    <PaperQuoteContext.Provider value={paperQuoteContextValue}>
      <div className={[styles.page, 'sm-workspace-view'].join(' ')}>
        <div
          className={[styles.main, isOcrCompleted ? styles.mainReader : '']
            .filter(Boolean)
            .join(' ')}
        >
          {!currentPaperId ? (
            <div className={styles.emptyState}>
              <div className={['sm-empty', styles.emptyCard].join(' ')}>
                <h2>选择一篇论文开始阅读</h2>
                <p>从左侧列表中选择已有文献，或直接上传 PDF 开始阅读。</p>
                <button
                  className="sm-button sm-button--primary"
                  type="button"
                  onClick={() => store.uploadAndRenderPdf()}
                >
                  上传 PDF
                </button>
              </div>
            </div>
          ) : isOcrCompleted && originalPdfVisible && currentPaper ? (
            <PaperOriginalPdfView
              paperId={currentPaperId || ''}
              pageAssets={currentPaper.pageAssets}
              pageCount={currentPaper.pageCount}
            />
          ) : isOcrCompleted ? (
            <PaperMarkdownView
              ref={markdownViewRef}
              content={markdownContent}
              loading={markdownLoading}
              paperId={currentPaperId || ''}
              basePath={paperBasePath || undefined}
              annotations={currentAnnotations}
              readerDocument={currentReaderDocument}
              translationVisible={translationVisible}
              translationCache={currentTranslationCache}
              readingProgress={currentPaper?.readingProgress}
              onAddToChat={handleAddToChat}
            />
          ) : null}
        </div>

        <div
          className={[
            styles.chatSlot,
            isPaperChatPanelVisible ? styles.chatSlotOpen : '',
            isResizingPaperChat ? styles.chatSlotResizing : ''
          ]
            .filter(Boolean)
            .join(' ')}
          style={
            {
              '--paper-chat-panel-width': `${paperChatPanelWidth}px`
            } as React.CSSProperties
          }
        >
          {isPaperChatPanelVisible && currentPaper && (
            <aside className={styles.chat}>
              <div
                className={styles.chatResize}
                role="separator"
                aria-orientation="vertical"
                title="拖拽调整聊天窗口宽度"
                onPointerDown={startPaperChatResize}
              />
              <PaperChatPanel paper={currentPaper} />
            </aside>
          )}
        </div>

        <PaperFigurePreview />
      </div>
    </PaperQuoteContext.Provider>
  )
}
