// src/renderer/src/components/paper/chat/input/PaperChatMcpToolsPanel.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { MCPTool } from '@renderer/types'
import { useMCPStore } from '@renderer/stores/mcpStore'
import styles from './PaperChatMcpToolsPanel.module.css'

interface PaperChatMcpToolsPanelProps {
  selectedTools?: MCPTool[]
  compact?: boolean
  onToolsSelected: (tools: MCPTool[]) => void
}

function toolKey(tool: MCPTool): string {
  return `${tool.serverName}::${tool.name}`
}

export default function PaperChatMcpToolsPanel({
  selectedTools = [],
  compact,
  onToolsSelected
}: PaperChatMcpToolsPanelProps) {
  const toolsByServer = useMCPStore((s) => s.toolsByServer)
  const statuses = useMCPStore((s) => s.statuses)
  const searchQuery = useMCPStore((s) => s.searchQuery)
  const setSearchQuery = useMCPStore((s) => s.setSearchQuery)
  const loadAllTools = useMCPStore((s) => s.loadAllTools)
  const isServerConnected = useMCPStore((s) => s.isServerConnected)
  const [showPanel, setShowPanel] = useState(false)
  const [expandedServers, setExpandedServers] = useState<Set<string>>(new Set())
  const [localSelectedTools, setLocalSelectedTools] = useState<MCPTool[]>(selectedTools)
  const [expandedDescriptions, setExpandedDescriptions] = useState<Set<string>>(new Set())
  const [needsExpandButton, setNeedsExpandButton] = useState<Set<string>>(new Set())
  const [highlightedTools, setHighlightedTools] = useState<Set<string>>(new Set())
  const mcpContainerRef = useRef<HTMLDivElement | null>(null)
  const descriptionRefs = useRef<Map<string, HTMLElement>>(new Map())

  useEffect(() => {
    setLocalSelectedTools(selectedTools)
  }, [selectedTools])

  const selectedToolKeys = useMemo(
    () => new Set(localSelectedTools.map((tool) => toolKey(tool))),
    [localSelectedTools]
  )

  const totalToolsCount = useMemo(
    () => Object.values(toolsByServer).reduce((sum, tools) => sum + tools.length, 0),
    [toolsByServer]
  )
  const connectedServersCount = useMemo(
    () => statuses.filter((status) => status.connected).length,
    [statuses]
  )

  const filteredToolsByServer = useMemo(() => {
    const query = searchQuery.trim().toLowerCase()
    if (!query) {
      return toolsByServer
    }

    const result: Record<string, MCPTool[]> = {}
    for (const [serverName, tools] of Object.entries(toolsByServer)) {
      const filtered = tools.filter(
        (tool) =>
          tool.name.toLowerCase().includes(query) ||
          (tool.description || '').toLowerCase().includes(query)
      )
      if (filtered.length > 0) {
        result[serverName] = filtered
      }
    }
    return result
  }, [searchQuery, toolsByServer])

  const refreshOverflowChecks = useCallback(() => {
    window.requestAnimationFrame(() => {
      setNeedsExpandButton((previous) => {
        const next = new Set(previous)
        for (const [key, element] of descriptionRefs.current.entries()) {
          if (element.scrollHeight > element.clientHeight + 1) {
            next.add(key)
          }
        }
        return next
      })
    })
  }, [])

  const loadTools = useCallback(async (): Promise<void> => {
    await loadAllTools()
    const nextStatuses = useMCPStore.getState().statuses
    setNeedsExpandButton(new Set())
    descriptionRefs.current.clear()
    setExpandedDescriptions(new Set())
    setExpandedServers(
      new Set(nextStatuses.filter((status) => status.connected).map((s) => s.serverName))
    )
    refreshOverflowChecks()
  }, [loadAllTools, refreshOverflowChecks])

  useEffect(() => {
    if (showPanel) {
      refreshOverflowChecks()
    }
  }, [expandedServers, filteredToolsByServer, refreshOverflowChecks, showPanel])

  useEffect(() => {
    function handleClickOutside(event: MouseEvent): void {
      const container = mcpContainerRef.current
      if (showPanel && container && !container.contains(event.target as Node)) {
        setShowPanel(false)
      }
    }

    document.addEventListener('click', handleClickOutside)
    return () => document.removeEventListener('click', handleClickOutside)
  }, [showPanel])

  useEffect(() => {
    const unsubscribe = window.api.mcp.onStatusChange(() => {
      void loadTools()
    })
    return () => unsubscribe()
  }, [loadTools])

  function emitToolsSelected(next: MCPTool[]): void {
    setLocalSelectedTools(next)
    onToolsSelected(next)
  }

  function togglePanel(): void {
    setShowPanel((current) => {
      const next = !current
      if (next) {
        void loadTools()
      }
      return next
    })
  }

  function isToolSelected(tool: MCPTool): boolean {
    return selectedToolKeys.has(toolKey(tool))
  }

  function toggleTool(tool: MCPTool): void {
    const key = toolKey(tool)
    emitToolsSelected(
      selectedToolKeys.has(key)
        ? localSelectedTools.filter((selected) => toolKey(selected) !== key)
        : [...localSelectedTools, tool]
    )
  }

  function isServerGroupFullySelected(tools: MCPTool[]): boolean {
    return tools.length > 0 && tools.every((tool) => isToolSelected(tool))
  }

  function toggleServerGroupTools(tools: MCPTool[]): void {
    if (isServerGroupFullySelected(tools)) {
      const toolKeys = new Set(tools.map((tool) => toolKey(tool)))
      emitToolsSelected(localSelectedTools.filter((selected) => !toolKeys.has(toolKey(selected))))
      return
    }

    const next = [...localSelectedTools]
    for (const tool of tools) {
      if (!selectedToolKeys.has(toolKey(tool))) {
        next.push(tool)
      }
    }
    emitToolsSelected(next)
  }

  function toggleServer(serverName: string): void {
    setExpandedServers((previous) => {
      const next = new Set(previous)
      if (next.has(serverName)) {
        next.delete(serverName)
      } else {
        next.add(serverName)
      }
      return next
    })
  }

  function setDescriptionRef(tool: MCPTool, element: HTMLDivElement | null): void {
    const key = toolKey(tool)
    if (!element) {
      descriptionRefs.current.delete(key)
      return
    }

    descriptionRefs.current.set(key, element)
    window.requestAnimationFrame(() => {
      if (element.scrollHeight > element.clientHeight + 1) {
        setNeedsExpandButton((previous) => new Set(previous).add(key))
      }
    })
  }

  function toggleDescription(tool: MCPTool): void {
    const key = toolKey(tool)
    setExpandedDescriptions((previous) => {
      const next = new Set(previous)
      if (next.has(key)) {
        next.delete(key)
      } else {
        next.add(key)
      }
      return next
    })
  }

  function highlightTool(tool: MCPTool): void {
    const key = toolKey(tool)
    setHighlightedTools((previous) => new Set(previous).add(key))
    window.setTimeout(() => {
      setHighlightedTools((previous) => {
        const next = new Set(previous)
        next.delete(key)
        return next
      })
    }, 1500)
  }

  return (
    <div
      ref={mcpContainerRef}
      className={[
        styles['paper-chat-mcp-tools'],
        'paper-chat-mcp-tools',
        compact ? styles['is-compact'] || '' : '',
        compact ? 'is-compact' : ''
      ]
        .filter(Boolean)
        .join(' ')}
    >
      <button
        type="button"
        className={[
          'btn',
          styles['paper-chat-mcp-tools__trigger'],
          showPanel ? styles.active || '' : '',
          localSelectedTools.length > 0 ? styles['has-selection'] || '' : ''
        ]
          .filter(Boolean)
          .join(' ')}
        aria-expanded={showPanel}
        onClick={togglePanel}
      >
        {localSelectedTools.length > 0 ? (
          <span className={styles['paper-chat-mcp-tools__selected-name']}>
            已选 {localSelectedTools.length} 个工具
          </span>
        ) : (
          <span>{compact ? 'MCP' : 'MCP 工具'}</span>
        )}
        {totalToolsCount > 0 && (
          <span className={styles['paper-chat-mcp-tools__count']}>{totalToolsCount}</span>
        )}
        <span
          className={[
            styles['paper-chat-mcp-tools__dropdown-arrow'],
            showPanel ? styles.open || '' : ''
          ]
            .filter(Boolean)
            .join(' ')}
        >
          ▼
        </span>
      </button>

      {showPanel && (
        <div className={`${styles['paper-chat-mcp-tools-panel']} paper-chat-mcp-tools-panel`}>
          <div className={styles['paper-chat-mcp-tools-panel__header']}>
            <span className={styles['paper-chat-mcp-tools-panel__title']}>MCP 工具（多选）</span>
            <span className={styles['paper-chat-mcp-tools-panel__connection-info']}>
              {connectedServersCount} 个服务器已连接
            </span>
          </div>

          <div className={styles['paper-chat-mcp-tools-panel__search']}>
            <input
              className={`input ${styles['paper-chat-mcp-tools-panel__search-input']}`}
              type="text"
              value={searchQuery}
              placeholder="搜索工具..."
              aria-label="搜索 MCP 工具"
              onChange={(event) => setSearchQuery(event.target.value)}
            />
          </div>

          <div className={styles['paper-chat-mcp-tools-panel__tools']}>
            {Object.keys(filteredToolsByServer).length === 0 ? (
              <div className={styles['paper-chat-mcp-tools-panel__empty']}>
                <p>
                  {searchQuery ? '未找到匹配的工具' : '暂无可用工具，请在设置中配置 MCP 服务器'}
                </p>
              </div>
            ) : (
              Object.entries(filteredToolsByServer).map(([serverName, tools]) => {
                const serverExpanded = expandedServers.has(serverName)
                const serverConnected = isServerConnected(serverName)
                return (
                  <div key={serverName} className={styles['paper-chat-mcp-tools-panel__server']}>
                    <div
                      className={styles['paper-chat-mcp-tools-panel__server-header']}
                      role="button"
                      tabIndex={0}
                      aria-expanded={serverExpanded}
                      onClick={() => toggleServer(serverName)}
                      onKeyDown={(event) => {
                        if (event.key === 'Enter' || event.key === ' ') {
                          event.preventDefault()
                          toggleServer(serverName)
                        }
                      }}
                    >
                      <span className={styles['paper-chat-mcp-tools-panel__expand-icon']}>
                        {serverExpanded ? '▼' : '▶'}
                      </span>
                      <span className={styles['paper-chat-mcp-tools-panel__server-name']}>
                        {serverName}
                      </span>
                      <button
                        className={`btn ${styles['paper-chat-mcp-tools-panel__server-select-all']}`}
                        type="button"
                        onClick={(event) => {
                          event.stopPropagation()
                          toggleServerGroupTools(tools)
                        }}
                      >
                        {isServerGroupFullySelected(tools) ? '取消全选' : '全选'}
                      </button>
                      <span
                        className={[
                          styles['paper-chat-mcp-tools-panel__server-status'],
                          serverConnected ? styles.connected || '' : ''
                        ]
                          .filter(Boolean)
                          .join(' ')}
                      >
                        {serverConnected ? '●' : '○'}
                      </span>
                      <span className={styles['paper-chat-mcp-tools__count-badge']}>
                        {tools.length}
                      </span>
                    </div>

                    {serverExpanded && (
                      <div className={styles['paper-chat-mcp-tools-panel__server-tools']}>
                        {tools.map((tool) => {
                          const selected = isToolSelected(tool)
                          const key = toolKey(tool)
                          const expanded = expandedDescriptions.has(key)
                          return (
                            <div
                              id={`tool-${serverName}-${tool.name}`}
                              key={key}
                              className={[
                                styles['paper-chat-mcp-tools-panel__tool'],
                                selected ? styles.selected || '' : '',
                                highlightedTools.has(key) ? styles.highlight || '' : ''
                              ]
                                .filter(Boolean)
                                .join(' ')}
                              role="button"
                              tabIndex={0}
                              aria-selected={selected}
                              onClick={() => {
                                toggleTool(tool)
                                highlightTool(tool)
                              }}
                              onKeyDown={(event) => {
                                if (event.key === 'Enter' || event.key === ' ') {
                                  event.preventDefault()
                                  toggleTool(tool)
                                  highlightTool(tool)
                                }
                              }}
                            >
                              <div className={styles['paper-chat-mcp-tools-panel__tool-header']}>
                                <span
                                  className={styles['paper-chat-mcp-tools-panel__tool-checkbox']}
                                >
                                  {selected ? '☑' : '☐'}
                                </span>
                                <span className={styles['paper-chat-mcp-tools-panel__tool-name']}>
                                  {tool.name}
                                </span>
                              </div>
                              {tool.description && (
                                <div
                                  className={
                                    styles['paper-chat-mcp-tools-panel__tool-description-wrapper']
                                  }
                                >
                                  <div
                                    ref={(element) => setDescriptionRef(tool, element)}
                                    className={[
                                      styles['paper-chat-mcp-tools-panel__tool-description'],
                                      expanded ? styles.expanded || '' : ''
                                    ]
                                      .filter(Boolean)
                                      .join(' ')}
                                  >
                                    {tool.description}
                                  </div>
                                  {needsExpandButton.has(key) && (
                                    <button
                                      className={
                                        styles['paper-chat-mcp-tools-panel__description-toggle']
                                      }
                                      type="button"
                                      onClick={(event) => {
                                        event.stopPropagation()
                                        toggleDescription(tool)
                                      }}
                                    >
                                      {expanded ? '收起' : '展开'}
                                    </button>
                                  )}
                                </div>
                              )}
                            </div>
                          )
                        })}
                      </div>
                    )}
                  </div>
                )
              })
            )}
          </div>
        </div>
      )}
    </div>
  )
}

// src/renderer/src/components/paper/chat/input/PaperChatMcpToolsPanel.vue
<script setup lang="ts">
import { ref, inject, watch, nextTick, onMounted, onUnmounted, computed, type Ref } from 'vue'
import { useZustandStore } from '@renderer/composables/useZustandStore'
import type { MCPTool } from '@renderer/types'
import { useMCPStore } from '@renderer/stores'
import { useMCPUI } from '@renderer/composables/mcp/useMCPUI'
import styles from './PaperChatMcpToolsPanel.module.css'

const props = defineProps<{
  selectedTools?: MCPTool[]
  compact?: boolean
}>()

const emit = defineEmits<{
  (e: 'tools-selected', tools: MCPTool[]): void
}>()

// 注入 MCP 更新标志
const mcpUpdateKey = inject<Ref<number>>('mcpUpdateKey', ref(0))

// 直接使用 MCP Store
const mcpStore = useZustandStore(useMCPStore)

// 搜索查询（双向绑定用 computed）
const searchQuery = computed({
  get: () => mcpStore.searchQuery,
  set: (val) => mcpStore.setSearchQuery(val)
})

// 兼容旧命名（statuses 保留在 mcpStore 上直接访问）
const totalToolsCount = computed(() => mcpStore.totalToolsCount())
const connectedServersCount = computed(() => mcpStore.connectedServersCount())
const expandedServers = ref<Set<string>>(new Set())

// getter 函数需通过 computed 包装以保持模板响应性
const filteredToolsByServer = computed(() => mcpStore.filteredToolsByServer())

// 本地选择状态（从 props 初始化，保持与会话同步）
const localSelectedTools = ref<MCPTool[]>(props.selectedTools ?? [])

// 同步 props 到本地状态
watch(
  () => props.selectedTools,
  (newVal) => {
    if (newVal !== undefined) {
      localSelectedTools.value = newVal
    }
  },
  { immediate: true, deep: true }
)

// 已选择的工具数量
const selectedToolsCount = computed(() => {
  return localSelectedTools.value.length
})

/**
 * 检查工具是否被选中
 */
function isToolSelected(tool: MCPTool): boolean {
  return localSelectedTools.value.some(
    (t) => t.name === tool.name && t.serverName === tool.serverName
  )
}

/**
 * 选择/取消选择工具（多选模式）
 */
function toggleTool(tool: MCPTool): void {
  const index = localSelectedTools.value.findIndex(
    (t) => t.name === tool.name && t.serverName === tool.serverName
  )

  if (index >= 0) {
    // 取消选择
    localSelectedTools.value.splice(index, 1)
  } else {
    // 添加选择
    localSelectedTools.value.push(tool)
  }

  window.api.logger.debug('[PaperChatMcpToolsPanel] 工具选择变更', {
    action: index >= 0 ? 'removed' : 'added',
    tool: `${tool.serverName}/${tool.name}`,
    selectedCount: localSelectedTools.value.length
  })
}

/**
 * 获取选中的工具列表
 */
function getSelectedTools(): MCPTool[] {
  return [...localSelectedTools.value]
}

const {
  showPanel,
  togglePanel,
  mcpContainerRef,
  toggleDescription,
  isDescriptionExpanded,
  shouldShowExpandButton,
  setDescriptionRef,
  refreshAllOverflowChecks,
  clearAllStates: clearDescriptionStates
} = useMCPUI(mcpStore.loadAllTools, expandedServers)

/**
 * 加载工具列表（包装版本，添加额外逻辑）
 */
async function loadTools(): Promise<void> {
  await mcpStore.loadAllTools()

  // 清空之前的展开状态
  clearDescriptionStates()
  expandedServers.value = new Set()

  // 默认展开所有已连接的服务器
  for (const status of mcpStore.statuses) {
    if (status.connected) {
      expandedServers.value.add(status.serverName)
    }
  }
}

/**
 * 选择/取消选择工具（包装版本，触发 emit）
 */
function handleToggleTool(tool: MCPTool): void {
  toggleTool(tool)
  emit('tools-selected', getSelectedTools())
}

/**
 * 检查指定服务分组是否已全选
 */
function isServerGroupFullySelected(tools: MCPTool[]): boolean {
  return tools.length > 0 && tools.every((tool) => isToolSelected(tool))
}

/**
 * 切换指定服务分组的工具全选状态
 */
function handleToggleServerGroupTools(tools: MCPTool[]): void {
  const allSelected = isServerGroupFullySelected(tools)

  if (allSelected) {
    localSelectedTools.value = localSelectedTools.value.filter(
      (selectedTool) =>
        !tools.some(
          (tool) => tool.name === selectedTool.name && tool.serverName === selectedTool.serverName
        )
    )
  } else {
    const selectedKeys = new Set(
      localSelectedTools.value.map((tool) => `${tool.serverName}::${tool.name}`)
    )

    for (const tool of tools) {
      const toolKey = `${tool.serverName}::${tool.name}`
      if (!selectedKeys.has(toolKey)) {
        localSelectedTools.value.push(tool)
      }
    }
  }

  emit('tools-selected', getSelectedTools())
}

/**
 * 切换服务器展开状态（包装版本，刷新溢出检查）
 */
function handleToggleServer(serverName: string): void {
  if (expandedServers.value.has(serverName)) {
    expandedServers.value.delete(serverName)
  } else {
    expandedServers.value.add(serverName)
  }

  // 展开服务器后，检查工具描述溢出状态
  if (expandedServers.value.has(serverName)) {
    nextTick(() => {
      refreshAllOverflowChecks()
    })
  }
}

// 监听搜索查询变化，重新检查溢出状态
watch(
  () => mcpStore.searchQuery,
  () => {
    nextTick(() => {
      refreshAllOverflowChecks()
    })
  }
)

// 监听 MCP 更新
watch(mcpUpdateKey, () => {
  loadTools()
})

// 监听 MCP 状态变更
const unsubscribeMCPStatusChange = window.api.mcp.onStatusChange(() => {
  loadTools()
})

/**
 * 点击外部关闭面板
 */
function handleClickOutside(event: MouseEvent): void {
  const container = mcpContainerRef.value as HTMLElement | null
  if (showPanel.value && container && !container.contains(event.target as Node)) {
    showPanel.value = false
  }
}

// 挂载时添加全局点击监听
onMounted(() => {
  document.addEventListener('click', handleClickOutside)
})

// 卸载时移除监听
onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
  unsubscribeMCPStatusChange()
})
</script>

<template>
  <div ref="mcpContainerRef" class="paper-chat-mcp-tools" :class="{ 'is-compact': props.compact }">
    <!-- 触发按钮 -->
    <button
      type="button"
      :class="[
        'btn',
        styles['paper-chat-mcp-tools__trigger'],
        { active: showPanel, 'has-selection': selectedToolsCount > 0 }
      ]"
      :aria-expanded="showPanel"
      @click="togglePanel"
    >
      <span v-if="selectedToolsCount > 0" :class="styles['paper-chat-mcp-tools__selected-name']">
        已选 {{ selectedToolsCount }} 个工具
      </span>
      <span v-else>{{ props.compact ? 'MCP' : 'MCP 工具' }}</span>
      <span v-if="totalToolsCount > 0" :class="styles['paper-chat-mcp-tools__count']">{{
        totalToolsCount
      }}</span>
      <span class="paper-chat-mcp-tools__dropdown-arrow" :class="{ open: showPanel }">▼</span>
    </button>

    <!-- 工具面板 -->
    <div v-if="showPanel" :class="styles['paper-chat-mcp-tools-panel']">
      <!-- 头部 -->
      <div :class="styles['paper-chat-mcp-tools-panel__header']">
        <span :class="styles['paper-chat-mcp-tools-panel__title']">MCP 工具（多选）</span>
        <span :class="styles['paper-chat-mcp-tools-panel__connection-info']">
          {{ connectedServersCount }} 个服务器已连接
        </span>
      </div>

      <!-- 搜索框 -->
      <div :class="styles['paper-chat-mcp-tools-panel__search']">
        <input
          v-model="searchQuery"
          type="text"
          :class="['input', styles['paper-chat-mcp-tools-panel__search-input']]"
          placeholder="搜索工具..."
          aria-label="搜索 MCP 工具"
        />
      </div>

      <!-- 工具列表 -->
      <div :class="styles['paper-chat-mcp-tools-panel__tools']">
        <div
          v-if="Object.keys(filteredToolsByServer).length === 0"
          :class="styles['paper-chat-mcp-tools-panel__empty']"
        >
          <p v-if="searchQuery">未找到匹配的工具</p>
          <p v-else>暂无可用工具，请在设置中配置 MCP 服务器</p>
        </div>

        <div
          v-for="(tools, serverName) in filteredToolsByServer"
          :key="serverName"
          :class="styles['paper-chat-mcp-tools-panel__server']"
        >
          <div
            :class="styles['paper-chat-mcp-tools-panel__server-header']"
            role="button"
            tabindex="0"
            :aria-expanded="expandedServers.has(serverName as string)"
            @click="handleToggleServer(serverName as string)"
            @keydown.enter.prevent="handleToggleServer(serverName as string)"
            @keydown.space.prevent="handleToggleServer(serverName as string)"
          >
            <span :class="styles['paper-chat-mcp-tools-panel__expand-icon']">{{
              expandedServers.has(serverName as string) ? '▼' : '▶'
            }}</span>
            <span :class="styles['paper-chat-mcp-tools-panel__server-name']">{{ serverName }}</span>
            <button
              type="button"
              :class="['btn', styles['paper-chat-mcp-tools-panel__server-select-all']]"
              @click.stop="handleToggleServerGroupTools(tools)"
            >
              {{ isServerGroupFullySelected(tools) ? '取消全选' : '全选' }}
            </button>
            <span
              :class="[
                styles['paper-chat-mcp-tools-panel__server-status'],
                { connected: mcpStore.isServerConnected(serverName as string) }
              ]"
            >
              {{ mcpStore.isServerConnected(serverName as string) ? '●' : '○' }}
            </span>
            <span :class="styles['paper-chat-mcp-tools__count-badge']">{{ tools.length }}</span>
          </div>

          <div
            v-if="expandedServers.has(serverName as string)"
            :class="styles['paper-chat-mcp-tools-panel__server-tools']"
          >
            <div
              v-for="tool in tools"
              :id="`tool-${serverName}-${tool.name}`"
              :key="`${serverName}-${tool.name}`"
              :class="[
                styles['paper-chat-mcp-tools-panel__tool'],
                { selected: isToolSelected(tool) }
              ]"
              role="button"
              tabindex="0"
              :aria-selected="isToolSelected(tool)"
              @click="handleToggleTool(tool)"
              @keydown.enter.prevent="handleToggleTool(tool)"
              @keydown.space.prevent="handleToggleTool(tool)"
            >
              <div :class="styles['paper-chat-mcp-tools-panel__tool-header']">
                <span :class="styles['paper-chat-mcp-tools-panel__tool-checkbox']">{{
                  isToolSelected(tool) ? '☑' : '☐'
                }}</span>
                <span :class="styles['paper-chat-mcp-tools-panel__tool-name']">{{
                  tool.name
                }}</span>
              </div>
              <div
                v-if="tool.description"
                :class="styles['paper-chat-mcp-tools-panel__tool-description-wrapper']"
              >
                <div
                  :ref="(el) => setDescriptionRef(tool, el)"
                  :class="[
                    styles['paper-chat-mcp-tools-panel__tool-description'],
                    { expanded: isDescriptionExpanded(tool) }
                  ]"
                >
                  {{ tool.description }}
                </div>
                <button
                  v-if="shouldShowExpandButton(tool)"
                  type="button"
                  :class="styles['paper-chat-mcp-tools-panel__description-toggle']"
                  @click.stop="toggleDescription(tool)"
                >
                  {{ isDescriptionExpanded(tool) ? '收起' : '展开' }}
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
