// src/renderer/src/components/paper/chat/input/PaperChatToolSelectionBar.tsx
import { useEffect, useRef, useState, type ReactNode } from 'react'
import type { KnowledgeBase, MCPTool } from '@renderer/types'
import SvgIcon from '@renderer/components/icons/SvgIcon'
import LabToolsToggle from '@renderer/components/lab/LabToolsToggle'
import PaperChatMcpToolsPanel from './PaperChatMcpToolsPanel'
import PaperChatKnowledgeBasePanel from './PaperChatKnowledgeBasePanel'
import styles from './PaperChatToolSelectionBar.module.css'

interface PaperChatToolSelectionBarProps {
  isSending?: boolean
  disabled?: boolean
  canSend?: boolean
  selectedTools: MCPTool[]
  selectedKnowledgeBases: KnowledgeBase[]
  enableLabTools?: boolean
  enablePaperWebSearch?: boolean
  totalAttachmentCount?: number
  onUpdateSelectedTools: (value: MCPTool[]) => void
  onUpdateSelectedKnowledgeBases: (value: KnowledgeBase[]) => void
  onUpdateEnableLabTools: (value: boolean) => void
  onTogglePaperWebSearch: () => void
  onUpload: () => void
  onSend: () => void
  onStop: () => void
  children?: ReactNode
}

type AccordionSection = 'kb' | 'mcp'

export default function PaperChatToolSelectionBar({
  isSending,
  disabled,
  canSend = true,
  selectedTools,
  selectedKnowledgeBases,
  enableLabTools,
  enablePaperWebSearch,
  totalAttachmentCount = 0,
  onUpdateSelectedTools,
  onUpdateSelectedKnowledgeBases,
  onUpdateEnableLabTools,
  onTogglePaperWebSearch,
  onUpload,
  onSend,
  onStop,
  children
}: PaperChatToolSelectionBarProps) {
  const controlsDisabled = Boolean(disabled || isSending)
  const [showMenu, setShowMenu] = useState(false)
  const [expandedSection, setExpandedSection] = useState<AccordionSection | null>(null)
  const menuRef = useRef<HTMLDivElement>(null)

  const activeCount =
    selectedTools.length +
    selectedKnowledgeBases.length +
    (enablePaperWebSearch ? 1 : 0) +
    (enableLabTools ? 1 : 0)

  useEffect(() => {
    function handleClickOutside(event: MouseEvent): void {
      const container = menuRef.current
      if (showMenu && container && !container.contains(event.target as Node)) {
        setShowMenu(false)
        setExpandedSection(null)
      }
    }

    function handleEscape(event: KeyboardEvent): void {
      if (event.key === 'Escape' && showMenu) {
        setShowMenu(false)
        setExpandedSection(null)
      }
    }

    document.addEventListener('click', handleClickOutside)
    document.addEventListener('keydown', handleEscape)
    return () => {
      document.removeEventListener('click', handleClickOutside)
      document.removeEventListener('keydown', handleEscape)
    }
  }, [showMenu])

  function toggleMenu(): void {
    if (!controlsDisabled) {
      setShowMenu((current) => {
        if (current) {
          setExpandedSection(null)
        }
        return !current
      })
    }
  }

  function toggleAccordion(section: AccordionSection): void {
    setExpandedSection((prev) => (prev === section ? null : section))
  }

  function handleUploadClick(): void {
    setShowMenu(false)
    setExpandedSection(null)
    onUpload()
  }

  const kbCount = selectedKnowledgeBases.length
  const mcpCount = selectedTools.length

  return (
    <div className={styles['paper-chat-input-toolbar']}>
      <div className={styles['paper-chat-input-toolbar__left']}>
        {/* "+" 按钮，展开综合菜单 */}
        <div ref={menuRef} className={styles['plus-menu-wrapper']}>
          <button
            className={[
              styles['plus-menu-trigger'],
              showMenu ? styles['plus-menu-trigger--active'] || '' : '',
              activeCount > 0 || totalAttachmentCount > 0
                ? styles['plus-menu-trigger--has-active'] || ''
                : ''
            ]
              .filter(Boolean)
              .join(' ')}
            type="button"
            disabled={controlsDisabled}
            title="添加附件或配置工具"
            onClick={toggleMenu}
          >
            <SvgIcon name="add" size={20} />
            {(activeCount > 0 || totalAttachmentCount > 0) && (
              <span className={styles['plus-menu-trigger__badge']}>
                {activeCount + totalAttachmentCount}
              </span>
            )}
          </button>

          {showMenu && (
            <div className={styles['plus-menu']}>
              {/* 上传附件 */}
              <button
                type="button"
                className={styles['plus-menu__row']}
                disabled={controlsDisabled}
                onClick={handleUploadClick}
              >
                <SvgIcon name="attachment" size={16} />
                <span className={styles['plus-menu__row-label']}>添加附件</span>
              </button>

              {/* 搜索开关 */}
              <button
                type="button"
                className={styles['plus-menu__row']}
                disabled={controlsDisabled}
                onClick={onTogglePaperWebSearch}
              >
                <SvgIcon name="search" size={16} />
                <span className={styles['plus-menu__row-label']}>搜索</span>
                <span className={styles['plus-menu__row-right']}>
                  <span
                    className={[
                      styles['plus-menu__toggle-switch'],
                      enablePaperWebSearch ? styles['plus-menu__toggle-switch--on'] || '' : ''
                    ]
                      .filter(Boolean)
                      .join(' ')}
                    aria-hidden="true"
                  >
                    <span className={styles['plus-menu__toggle-thumb']} />
                  </span>
                </span>
              </button>

              {/* 实验室开关 */}
              <div className={styles['plus-menu__row']}>
                <SvgIcon name="lab" size={16} />
                <LabToolsToggle
                  className={styles['plus-menu__lab-toggle']}
                  modelValue={Boolean(enableLabTools)}
                  disabled={controlsDisabled}
                  onUpdateModelValue={onUpdateEnableLabTools}
                />
              </div>

              {/* 知识库手风琴 */}
              <div
                className={`${styles['plus-menu__row']} ${styles['plus-menu__row--interactive']}`}
                onClick={() => toggleAccordion('kb')}
              >
                <SvgIcon name="knowledge" size={16} />
                <span className={styles['plus-menu__row-label']}>知识库</span>
                <span className={styles['plus-menu__row-right']}>
                  {kbCount > 0 && (
                    <span className={styles['plus-menu__count-badge']}>{kbCount}</span>
                  )}
                  <span
                    className={[
                      styles['plus-menu__accordion-arrow'],
                      expandedSection === 'kb'
                        ? styles['plus-menu__accordion-arrow--open'] || ''
                        : ''
                    ]
                      .filter(Boolean)
                      .join(' ')}
                  >
                    ▶
                  </span>
                </span>
              </div>

              <div
                className={[
                  styles['plus-menu__accordion-body'],
                  expandedSection !== 'kb'
                    ? styles['plus-menu__accordion-body--collapsed'] || ''
                    : ''
                ]
                  .filter(Boolean)
                  .join(' ')}
              >
                <div className={styles['plus-menu__accordion-inner']}>
                  <div className={styles['plus-menu__accordion-content']}>
                    <PaperChatKnowledgeBasePanel
                      embedded
                      selectedKnowledgeBases={selectedKnowledgeBases}
                      onSelectionChange={onUpdateSelectedKnowledgeBases}
                    />
                  </div>
                </div>
              </div>

              {/* MCP 手风琴 */}
              <div
                className={`${styles['plus-menu__row']} ${styles['plus-menu__row--interactive']}`}
                onClick={() => toggleAccordion('mcp')}
              >
                <SvgIcon name="mcp" size={16} />
                <span className={styles['plus-menu__row-label']}>MCP</span>
                <span className={styles['plus-menu__row-right']}>
                  {mcpCount > 0 && (
                    <span className={styles['plus-menu__count-badge']}>{mcpCount}</span>
                  )}
                  <span
                    className={[
                      styles['plus-menu__accordion-arrow'],
                      expandedSection === 'mcp'
                        ? styles['plus-menu__accordion-arrow--open'] || ''
                        : ''
                    ]
                      .filter(Boolean)
                      .join(' ')}
                  >
                    ▶
                  </span>
                </span>
              </div>

              <div
                className={[
                  styles['plus-menu__accordion-body'],
                  expandedSection !== 'mcp'
                    ? styles['plus-menu__accordion-body--collapsed'] || ''
                    : ''
                ]
                  .filter(Boolean)
                  .join(' ')}
              >
                <div className={styles['plus-menu__accordion-inner']}>
                  <div className={styles['plus-menu__accordion-content']}>
                    <PaperChatMcpToolsPanel
                      embedded
                      selectedTools={selectedTools}
                      onToolsSelected={onUpdateSelectedTools}
                    />
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      <div className={styles['paper-chat-input-toolbar__actions']}>
        {children}
        {!isSending ? (
          <button
            className={styles['paper-chat-input-toolbar__execute-button']}
            type="button"
            disabled={!canSend}
            title="发送"
            aria-label="发送"
            onClick={onSend}
          >
            <SvgIcon name="send" size={16} />
          </button>
        ) : (
          <button
            className={styles['paper-chat-input-toolbar__stop-button']}
            type="button"
            title="停止"
            aria-label="停止"
            onClick={onStop}
          >
            <SvgIcon name="stop" size={16} />
          </button>
        )}
      </div>
    </div>
  )
}

// src/renderer/src/components/paper/chat/input/PaperChatToolSelectionBar.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import type { KnowledgeBase, MCPTool } from '@renderer/types'
import PaperChatMcpToolsPanel from '@renderer/components/paper/chat/input/PaperChatMcpToolsPanel.vue'
import PaperChatKnowledgeBasePanel from '@renderer/components/paper/chat/input/PaperChatKnowledgeBasePanel.vue'
import SvgIcon from '@renderer/components/icons/SvgIcon.vue'
import LabToolsToggle from '@renderer/components/lab/LabToolsToggle.vue'
import { SUPPORTED_DOC_TYPES } from './attachmentUtils'
import styles from './PaperChatToolSelectionBar.module.css'

const props = defineProps<{
  isSending?: boolean
  selectedModel?: string
  modelOptions: string[]
  selectedTools: MCPTool[]
  selectedKnowledgeBases: KnowledgeBase[]
  enableLabTools?: boolean
  enablePaperWebSearch?: boolean
  totalAttachmentCount?: number
  variant?: 'default' | 'compact'
}>()

const emit = defineEmits<{
  (e: 'update:selectedModel', value: string): void
  (e: 'update:selectedTools', value: MCPTool[]): void
  (e: 'update:selectedKnowledgeBases', value: KnowledgeBase[]): void
  (e: 'update:enableLabTools', value: boolean): void
  (e: 'update:enablePaperWebSearch', value: boolean): void
  (e: 'upload'): void
  (e: 'send'): void
  (e: 'stop'): void
}>()

const showModelDropdown = ref(false)
const modelSelectorRef = ref<HTMLElement | null>(null)
const supportedDocumentLabel = SUPPORTED_DOC_TYPES.map((type) => type.slice(1)).join(', ')

function selectModel(model: string): void {
  emit('update:selectedModel', model)
  showModelDropdown.value = false
}

function toggleModelDropdown(): void {
  if (!props.isSending) {
    showModelDropdown.value = !showModelDropdown.value
  }
}

function handleClickOutside(event: MouseEvent): void {
  if (!showModelDropdown.value || !modelSelectorRef.value) {
    return
  }

  const target = event.target as Node
  if (!modelSelectorRef.value.contains(target)) {
    showModelDropdown.value = false
  }
}

onMounted(() => {
  document.addEventListener('click', handleClickOutside)
})

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
})
</script>

<template>
  <div
    :class="styles['paper-chat-input-toolbar']"
    :class="{ [styles['paper-chat-input-toolbar--compact']]: props.variant === 'compact' }"
  >
    <div ref="modelSelectorRef" :class="styles['paper-chat-input-toolbar__model-selector']">
      <button
        :class="['btn', styles['paper-chat-input-toolbar__model-button']]"
        :disabled="props.isSending"
        @click="toggleModelDropdown"
      >
        <span>{{ props.selectedModel || '选择模型' }}</span>
        <span class="paper-chat-input-toolbar__dropdown-arrow" :class="{ open: showModelDropdown }"
          >▼</span
        >
      </button>
      <div v-if="showModelDropdown" :class="styles['paper-chat-input-toolbar__model-dropdown']">
        <div
          v-if="props.modelOptions.length === 0"
          :class="[styles['paper-chat-input-toolbar__model-option'], 'empty']"
        >
          暂无模型配置
        </div>
        <div
          v-for="model in props.modelOptions"
          :key="model"
          :class="styles['paper-chat-input-toolbar__model-option']"
          :class="{ active: model === props.selectedModel }"
          @click="selectModel(model)"
        >
          {{ model }}
        </div>
      </div>
    </div>

    <PaperChatMcpToolsPanel
      :compact="props.variant === 'compact'"
      :selected-tools="props.selectedTools"
      @tools-selected="emit('update:selectedTools', $event)"
    />

    <PaperChatKnowledgeBasePanel
      :compact="props.variant === 'compact'"
      :selected-knowledge-bases="props.selectedKnowledgeBases"
      @selection-change="emit('update:selectedKnowledgeBases', $event)"
    />

    <button
      type="button"
      :class="styles['paper-chat-input-toolbar__search-toggle']"
      :class="{
        enabled: props.enablePaperWebSearch,
        disabled: props.isSending,
        'is-compact': props.variant === 'compact'
      }"
      :disabled="props.isSending"
      :aria-pressed="props.enablePaperWebSearch ? 'true' : 'false'"
      title="联网搜索：允许模型在需要时搜索学术资料补充论文信息"
      @click="emit('update:enablePaperWebSearch', !props.enablePaperWebSearch)"
    >
      <span class="toggle-switch" aria-hidden="true">
        <span class="toggle-thumb"></span>
      </span>
      <span class="toggle-label">搜索</span>
    </button>

    <LabToolsToggle
      :compact="props.variant === 'compact'"
      :model-value="props.enableLabTools"
      :disabled="props.isSending"
      @update:model-value="emit('update:enableLabTools', $event)"
      @change="emit('update:enableLabTools', $event)"
    />

    <div :class="styles['paper-chat-input-toolbar__actions']">
      <button
        :class="styles['paper-chat-input-toolbar__upload-button']"
        :class="{ 'has-attachments': (props.totalAttachmentCount || 0) > 0 }"
        :disabled="props.isSending"
        :title="`上传文件 (文档: ${supportedDocumentLabel} / 图片: jpg, png, webp, bmp, tiff)`"
        @click="emit('upload')"
      >
        <SvgIcon name="attachment" :size="18" />
        <span
          v-if="(props.totalAttachmentCount || 0) > 0"
          :class="styles['paper-chat-input-toolbar__attachment-count']"
        >
          {{ props.totalAttachmentCount }}
        </span>
      </button>

      <button
        v-if="!props.isSending"
        :class="['btn-primary', styles['paper-chat-input-toolbar__execute-button']]"
        :class="{
          'paper-chat-input-toolbar__execute-button--compact': props.variant === 'compact'
        }"
        title="执行"
        aria-label="执行"
        @click="emit('send')"
      >
        <SvgIcon v-if="props.variant === 'compact'" name="send" :size="17" />
        <template v-else>
          <span>执行</span>
        </template>
      </button>
      <button
        v-else
        :class="['btn-danger', styles['paper-chat-input-toolbar__stop-button']]"
        title="停止"
        aria-label="停止"
        @click="emit('stop')"
      >
        <SvgIcon name="stop" :size="18" />
      </button>
    </div>
  </div>
</template>
