// src/renderer/src/components/paper/PaperMarkdownView.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, watch } from 'vue'
import { storeToRefs } from 'pinia'
import type { PaperQuote } from '@shared/types/chat'
import type {
  PaperAnnotation,
  PaperReadingProgress,
  PaperReaderDocument,
  PaperTranslationCache
} from '@shared/types/paper'
import { useNotification } from '@renderer/composables/useNotification'
import { usePaperReaderStore } from '@renderer/stores/paperReaderStore'
import {
  usePaperMarkdownEngine,
  getTranslationRenderKey
} from './composables/usePaperMarkdownEngine'
import { usePaperAnnotationComposer } from './composables/usePaperAnnotationComposer'
import { usePaperQuoteHighlight } from './composables/usePaperQuoteHighlight'
import { usePaperReadingProgress } from './composables/usePaperReadingProgress'
import { usePaperTextSearch } from './composables/usePaperTextSearch'
import { useZoomAnchor } from './composables/useZoomAnchor'
import PaperAnnotationHoverPopover from './annotation/PaperAnnotationHoverPopover.vue'
import PaperAnnotationNoteEditor from './annotation/PaperAnnotationNoteEditor.vue'
import PaperAnnotationSelectionMenu from './annotation/PaperAnnotationSelectionMenu.vue'
import PaperMarkdownSegmentList from './PaperMarkdownSegmentList.vue'
import PaperMarkdownStatusPanels from './PaperMarkdownStatusPanels.vue'
import PaperMarkdownAnnotationManager from './PaperMarkdownAnnotationManager.vue'

const props = defineProps<{
  content: string
  loading: boolean
  paperId: string
  basePath?: string
  translationVisible: boolean
  translationCache?: PaperTranslationCache | null
  readerDocument?: PaperReaderDocument | null
  annotations?: PaperAnnotation[]
  readingProgress?: PaperReadingProgress | null
}>()

const emit = defineEmits<{
  (e: 'add-to-chat', quote: import('@shared/types/chat').PaperQuote): void
}>()

const quoteHighlight = usePaperQuoteHighlight()

defineExpose({ scrollToQuoteAndHighlight: quoteHighlight.scrollToQuoteAndHighlight })

const scrollContainerRef = ref<HTMLElement | null>(null)
const searchInputRef = ref<HTMLInputElement | null>(null)
const paperReaderStore = usePaperReaderStore()
const notify = useNotification()
const { markdownZoomLevel } = storeToRefs(paperReaderStore)
const textSearch = usePaperTextSearch()

const contentZoomStyle = computed(() => ({
  zoom: markdownZoomLevel.value
}))

interface TableDragState {
  wrap: HTMLElement
  pointerId: number
  startClientX: number
  startScrollLeft: number
  hasDragged: boolean
}

const TABLE_DRAG_THRESHOLD = 4
let tableDragState: TableDragState | null = null
let lastTableDragEndedAt = 0

const engine = usePaperMarkdownEngine({
  content: () => props.content,
  basePath: () => props.basePath,
  translationVisible: () => props.translationVisible,
  translationCache: () => props.translationCache,
  readerDocument: () => props.readerDocument,
  annotations: () => props.annotations,
  setTocOutline: paperReaderStore.setPaperTocOutline,
  clearToc: paperReaderStore.clearPaperToc
})

usePaperReadingProgress({
  scrollContainer: scrollContainerRef,
  paperId: () => props.paperId,
  renderedSegments: engine.renderedSegments,
  loading: () => props.loading,
  sourceRevisionId: () => props.readerDocument?.sourceRevisionId,
  readingProgress: () => props.readingProgress,
  translationVisible: () => props.translationVisible
})

const zoomAnchor = useZoomAnchor({
  containerRef: scrollContainerRef,
  zoomLevelRef: markdownZoomLevel
})

const composer = usePaperAnnotationComposer({
  paperId: () => props.paperId,
  translationCache: () => props.translationCache,
  annotations: () => props.annotations,
  renderedSegments: engine.renderedSegments,
  getSourceSegments: engine.getSourceSegments,
  createAnnotation: paperReaderStore.createAnnotation,
  reanchorAnnotation: paperReaderStore.reanchorAnnotation,
  updateAnnotation: paperReaderStore.updateAnnotation,
  deleteAnnotation: paperReaderStore.deleteAnnotation,
  onAddToChat: (quote) => emit('add-to-chat', quote)
})

const annotationManagerActions = computed(() => ({
  orphanAnnotations: composer.orphanAnnotations.value,
  outdatedAnnotations: composer.outdatedAnnotations.value,
  rebindAnnotationId: composer.rebindAnnotationId.value,
  outdatedUpdating: composer.outdatedAnnotationUpdating.value,
  outdatedError: composer.outdatedAnnotationError.value,
  getAnnotationTypeLabel: composer.getAnnotationTypeLabel,
  getAnnotationStatusLabel: composer.getAnnotationStatusLabel,
  startRebind: composer.startRebind,
  resolveAnnotationForCurrentTranslation: handleResolveAnnotationForCurrentTranslation,
  handleDeleteAnnotation: composer.handleDeleteAnnotation,
  handleCancelComposer: composer.handleCancelComposer
}))

function isTableWrapHorizontallyScrollable(wrap: HTMLElement): boolean {
  return wrap.scrollWidth > wrap.clientWidth + 1
}

function syncScrollableTableWrapState(): void {
  scrollContainerRef.value
    ?.querySelectorAll<HTMLElement>('.paper-markdown-view__table-wrap')
    .forEach((wrap) => {
      wrap.classList.toggle(
        'paper-markdown-view__table-wrap--scrollable',
        isTableWrapHorizontallyScrollable(wrap)
      )
    })
}

function cleanupTableDragListeners(): void {
  if (typeof window === 'undefined') {
    return
  }

  window.removeEventListener('pointermove', handleTablePointerMove)
  window.removeEventListener('pointerup', handleTablePointerUp)
  window.removeEventListener('pointercancel', handleTablePointerUp)
}

function clearTableDragState(): void {
  tableDragState?.wrap.classList.remove('paper-markdown-view__table-wrap--dragging')
  tableDragState = null
  cleanupTableDragListeners()
}

function shouldIgnoreTableDragTarget(target: Element): boolean {
  return !!target.closest(
    [
      'a',
      'button',
      'input',
      'textarea',
      'select',
      'mark.paper-annotation-highlight',
      '.paper-markdown-view__retranslate-btn'
    ].join(', ')
  )
}

function handleTablePointerDown(event: PointerEvent): void {
  if (event.button !== 0 || typeof window === 'undefined') {
    return
  }

  const target = event.target
  if (!(target instanceof Element) || shouldIgnoreTableDragTarget(target)) {
    return
  }

  const wrap = target.closest<HTMLElement>('.paper-markdown-view__table-wrap')
  if (!wrap || !isTableWrapHorizontallyScrollable(wrap)) {
    return
  }

  clearTableDragState()
  tableDragState = {
    wrap,
    pointerId: event.pointerId,
    startClientX: event.clientX,
    startScrollLeft: wrap.scrollLeft,
    hasDragged: false
  }

  window.addEventListener('pointermove', handleTablePointerMove, { passive: false })
  window.addEventListener('pointerup', handleTablePointerUp)
  window.addEventListener('pointercancel', handleTablePointerUp)
}

function handleTablePointerMove(event: PointerEvent): void {
  if (!tableDragState || event.pointerId !== tableDragState.pointerId) {
    return
  }

  const deltaX = event.clientX - tableDragState.startClientX
  if (!tableDragState.hasDragged && Math.abs(deltaX) < TABLE_DRAG_THRESHOLD) {
    return
  }

  if (!tableDragState.hasDragged) {
    tableDragState.hasDragged = true
    tableDragState.wrap.classList.add('paper-markdown-view__table-wrap--dragging')
    window.getSelection()?.removeAllRanges()
  }

  event.preventDefault()
  tableDragState.wrap.scrollLeft = tableDragState.startScrollLeft - deltaX
}

function handleTablePointerUp(event: PointerEvent): void {
  if (!tableDragState || event.pointerId !== tableDragState.pointerId) {
    return
  }

  if (tableDragState.hasDragged) {
    lastTableDragEndedAt = Date.now()
  }

  clearTableDragState()
}

function renderContentAndSyncTables(): Promise<void> {
  return engine.renderContent().then(async () => {
    await nextTick()
    syncScrollableTableWrapState()
  })
}

type AnnotationMarkViewKind = 'original' | 'translation'

function findAnnotationMark(
  annotationId: string,
  viewKind?: AnnotationMarkViewKind
): HTMLElement | null {
  const surfaceSelector = viewKind
    ? `[data-paper-selection-surface="true"][data-view-kind="${viewKind}"]`
    : '[data-paper-selection-surface="true"]'
  const marks = scrollContainerRef.value?.querySelectorAll<HTMLElement>(
    `${surfaceSelector} mark.paper-annotation-highlight`
  )
  if (!marks) {
    return null
  }

  return Array.from(marks).find((mark) => mark.dataset.annotationId === annotationId) || null
}

function scrollToAndPulseAnnotation(
  annotationId: string,
  viewKind?: AnnotationMarkViewKind
): boolean {
  const mark = findAnnotationMark(annotationId, viewKind)
  if (!mark) {
    return false
  }

  const scrollContainer = scrollContainerRef.value
  if (scrollContainer) {
    const containerRect = scrollContainer.getBoundingClientRect()
    const markRect = mark.getBoundingClientRect()
    const markTopInContent = markRect.top - containerRect.top + scrollContainer.scrollTop
    const targetScrollTop = markTopInContent - containerRect.height / 2 + markRect.height / 2
    scrollContainer.scrollTo({
      top: Math.max(0, targetScrollTop),
      behavior: 'smooth'
    })
  } else {
    mark.scrollIntoView({ behavior: 'smooth', block: 'center' })
  }

  mark.classList.remove('paper-annotation-highlight--locating')
  void mark.offsetWidth
  mark.classList.add('paper-annotation-highlight--locating')

  window.setTimeout(() => {
    mark.classList.remove('paper-annotation-highlight--locating')
  }, 8000)

  return true
}

async function highlightUpdatedTranslationAnnotation(annotationIds: string[]): Promise<void> {
  await nextTick()
  requestAnimationFrame(() => {
    const targetAnnotationId = annotationIds.find((annotationId) =>
      findAnnotationMark(annotationId, 'translation')
    )
    if (targetAnnotationId) {
      scrollToAndPulseAnnotation(targetAnnotationId, 'translation')
    }
  })
}

function getFirstTranslationMissingAnnotation(): PaperAnnotation | null {
  const sourceOrderMap = new Map(
    engine.getSourceSegments().map((segment, index) => [segment.stableId, index])
  )

  return (
    [...composer.translationMissingAnnotations.value].sort((left, right) => {
      const leftOrder = sourceOrderMap.get(left.semanticAnchor.segmentStableId) ?? Number.MAX_VALUE
      const rightOrder =
        sourceOrderMap.get(right.semanticAnchor.segmentStableId) ?? Number.MAX_VALUE
      return leftOrder - rightOrder || left.createdAt.localeCompare(right.createdAt)
    })[0] || null
  )
}

async function handleViewTranslationMissingInOriginal(): Promise<void> {
  const targetAnnotation = getFirstTranslationMissingAnnotation()
  paperReaderStore.hideTranslation()

  if (!targetAnnotation) {
    return
  }

  await nextTick()
  await renderContentAndSyncTables()

  requestAnimationFrame(() => {
    if (
      targetAnnotation.originalAnchor &&
      scrollToAndPulseAnnotation(targetAnnotation.id, 'original')
    ) {
      return
    }

    composer.scrollToSegment(targetAnnotation.semanticAnchor.segmentStableId)
  })
}

function buildAnnotationQuote(annotation: PaperAnnotation): PaperQuote | null {
  const sourceSegment = engine
    .getSourceSegments()
    .find((segment) => segment.stableId === annotation.semanticAnchor.segmentStableId)
  const textAnchor = annotation.originalAnchor
  if (!sourceSegment || !textAnchor) {
    return null
  }

  return {
    id: `annotation-rebind-${annotation.id}-${Date.now()}`,
    paperId: props.paperId,
    segmentStableId: annotation.semanticAnchor.segmentStableId,
    segmentIndex: sourceSegment.index,
    viewKind: 'original',
    selectedText: textAnchor.selectedText,
    sourceType: 'original',
    sourceLocation: {
      segmentStableId: annotation.semanticAnchor.segmentStableId,
      segmentIndex: sourceSegment.index,
      pageIndexes: [...annotation.semanticAnchor.sourceRefs.pageIndexes],
      blockIndexes: [...annotation.semanticAnchor.sourceRefs.blockIndexes],
      startOffset: textAnchor.startOffset,
      endOffset: textAnchor.endOffset
    },
    textAnchor,
    sourceRevisionId: annotation.semanticAnchor.sourceRevisionId,
    segmentTextHash: annotation.semanticAnchor.segmentTextHash
  }
}

async function highlightAnnotationFallback(annotation: PaperAnnotation): Promise<void> {
  await nextTick()
  const quote = buildAnnotationQuote(annotation)
  if (quote) {
    quoteHighlight.scrollToQuoteAndHighlight(quote)
    return
  }

  composer.scrollToSegment(annotation.semanticAnchor.segmentStableId)
}

async function handleUpdateAnnotationToCurrentTranslation(
  annotation: PaperAnnotation
): ReturnType<typeof composer.updateAnnotationToCurrentTranslation> {
  const result = await composer.updateAnnotationToCurrentTranslation(annotation)
  if (result.success) {
    await highlightUpdatedTranslationAnnotation([annotation.id])
  } else {
    await highlightAnnotationFallback(annotation)
  }
  return result
}

async function handleResolveAnnotationForCurrentTranslation(
  annotation: PaperAnnotation
): Promise<void> {
  if (composer.isAnnotationOutdated(annotation)) {
    await handleUpdateAnnotationToCurrentTranslation(annotation)
    return
  }

  composer.startRebind(annotation)
  await highlightAnnotationFallback(annotation)
}

async function handleUpdateOutdatedAnnotationsToCurrentTranslation(): Promise<void> {
  const candidateAnnotationIds = composer.outdatedAnnotations.value.map(
    (annotation) => annotation.id
  )
  const candidateAnnotations = [...composer.outdatedAnnotations.value]
  await composer.updateOutdatedAnnotationsToCurrentTranslation()
  const rebindAnnotation = candidateAnnotations.find(
    (annotation) => annotation.id === composer.rebindAnnotationId.value
  )
  if (rebindAnnotation) {
    await highlightAnnotationFallback(rebindAnnotation)
    return
  }

  await highlightUpdatedTranslationAnnotation(candidateAnnotationIds)
}

function recordMarkdownScrollPosition(): void {
  if (!props.paperId || !scrollContainerRef.value || zoomAnchor.isZooming()) {
    return
  }

  paperReaderStore.setMarkdownScrollPosition(props.paperId, {
    scrollTop: scrollContainerRef.value.scrollTop,
    scrollLeft: scrollContainerRef.value.scrollLeft
  })
}

async function restoreMarkdownScrollPosition(paperId: string): Promise<void> {
  const position = paperReaderStore.getMarkdownScrollPosition(paperId)
  if (!position) {
    return
  }

  await nextTick()
  requestAnimationFrame(() => {
    if (props.paperId !== paperId || !scrollContainerRef.value) {
      return
    }

    scrollContainerRef.value.scrollTop = position.scrollTop
    scrollContainerRef.value.scrollLeft = position.scrollLeft
  })
}

watch(
  () => [
    props.content,
    props.basePath,
    props.translationVisible,
    getTranslationRenderKey(props.translationCache),
    props.readerDocument?.sourceRevisionId,
    composer.currentAnnotations.value.length,
    composer.currentAnnotations.value.map((annotation) => annotation.updatedAt).join('|')
  ],
  async (newValues, oldValues) => {
    await renderContentAndSyncTables()

    if (!oldValues) {
      composer.clearComposer()
      composer.cancelRebindMode()
      await restoreMarkdownScrollPosition(props.paperId)
      return
    }

    const contentChanged = newValues[0] !== oldValues[0]
    const basePathChanged = newValues[1] !== oldValues[1]
    const translationVisibleChanged = newValues[2] !== oldValues[2]
    const sourceRevisionIdChanged = newValues[4] !== oldValues[4]

    if (contentChanged || basePathChanged || translationVisibleChanged || sourceRevisionIdChanged) {
      composer.clearComposer()
      composer.cancelRebindMode()
    }

    if (contentChanged || basePathChanged || sourceRevisionIdChanged) {
      await restoreMarkdownScrollPosition(props.paperId)
    }
  },
  { immediate: true }
)

const hasContent = computed(() => !!props.content.trim())

async function handleRetranslateSegment(params: {
  segmentId: string
  stableId: string
}): Promise<void> {
  if (!props.paperId) {
    return
  }

  const result = await paperReaderStore.retranslateSegment(
    props.paperId,
    params.segmentId,
    params.stableId
  )
  if (!result.success) {
    notify.error('重新翻译失败', result.error || '请稍后再试', {
      source: 'paper',
      dedupeKey: `paper-retranslate:${props.paperId}:${params.segmentId}:${result.error || ''}`
    })
  }
}

function handleHoverPopoverDelete(): void {
  const annotation = composer.hoverPopoverAnnotation.value
  if (!annotation) {
    return
  }

  void composer.handleDeleteAnnotation(annotation.id)
}

function handleHoverPopoverOpenNoteEditor(): void {
  composer.handleOpenNoteEditorFromHover()
}

function handleMarkdownClick(event: MouseEvent): void {
  if (Date.now() - lastTableDragEndedAt < 160) {
    event.preventDefault()
    event.stopPropagation()
    return
  }

  composer.handleSurfaceAnnotationClick(event)
}

function handleDocumentKeyDown(event: KeyboardEvent): void {
  // 搜索快捷键优先处理
  if ((event.metaKey || event.ctrlKey) && event.key === 'f') {
    event.preventDefault()
    if (textSearch.isOpen.value) {
      searchInputRef.value?.focus()
      searchInputRef.value?.select()
    } else {
      textSearch.openSearch()
      const selection = window.getSelection()?.toString().trim()
      if (selection && selection.length <= 200) {
        textSearch.query.value = selection
      }
    }
    return
  }

  if (event.key === 'Escape' && textSearch.isOpen.value) {
    event.preventDefault()
    textSearch.closeSearch()
    return
  }

  composer.handleDocumentKeyDown(event)
}

function handleSearchInputKeydown(event: KeyboardEvent): void {
  if (event.key === 'Enter' && !event.isComposing) {
    event.preventDefault()
    const contentEl = scrollContainerRef.value?.querySelector('.paper-markdown-view__content')
    if (contentEl instanceof HTMLElement) {
      textSearch.search(contentEl, textSearch.query.value)
    }
    if (event.shiftKey) {
      textSearch.goToPrevious()
    } else {
      textSearch.goToNext()
    }
  }
}

watch(textSearch.query, (newQuery) => {
  if (!textSearch.isOpen.value) return
  const contentEl = scrollContainerRef.value?.querySelector('.paper-markdown-view__content')
  if (contentEl instanceof HTMLElement) {
    textSearch.search(contentEl, newQuery)
  }
})

watch(textSearch.isOpen, (open) => {
  if (open) {
    nextTick(() => {
      searchInputRef.value?.focus()
      if (textSearch.query.value) {
        searchInputRef.value?.select()
      }
    })
  }
})

watch(markdownZoomLevel, async () => {
  await nextTick()
  syncScrollableTableWrapState()
})

if (typeof document !== 'undefined') {
  document.addEventListener('mousedown', composer.handleDocumentPointerDown)
  document.addEventListener('keydown', handleDocumentKeyDown)
}

if (typeof window !== 'undefined') {
  window.addEventListener('resize', syncScrollableTableWrapState)
}

onBeforeUnmount(() => {
  recordMarkdownScrollPosition()
  paperReaderStore.clearPaperToc()
  textSearch.closeSearch()
  clearTableDragState()
  if (typeof document !== 'undefined') {
    document.removeEventListener('mousedown', composer.handleDocumentPointerDown)
    document.removeEventListener('keydown', handleDocumentKeyDown)
  }
  if (typeof window !== 'undefined') {
    window.removeEventListener('resize', syncScrollableTableWrapState)
  }
})
</script>

<template>
  <div class="paper-markdown-view">
    <div v-if="textSearch.isOpen.value" class="paper-markdown-view__search-bar">
      <input
        ref="searchInputRef"
        v-model="textSearch.query.value"
        type="text"
        class="paper-markdown-view__search-input"
        placeholder="搜索..."
        @keydown="handleSearchInputKeydown"
      />
      <span v-if="textSearch.hasMatches.value" class="paper-markdown-view__search-count">
        {{ textSearch.currentIndex.value + 1 }} / {{ textSearch.matchCount.value }}
      </span>
      <span v-else-if="textSearch.query.value.trim()" class="paper-markdown-view__search-count">
        无结果
      </span>
      <button
        class="paper-markdown-view__search-btn"
        type="button"
        :disabled="!textSearch.hasMatches.value"
        title="上一个 (Shift+Enter)"
        @click="textSearch.goToPrevious()"
      >
        <svg
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <polyline points="18 15 12 9 6 15" />
        </svg>
      </button>
      <button
        class="paper-markdown-view__search-btn"
        type="button"
        :disabled="!textSearch.hasMatches.value"
        title="下一个 (Enter)"
        @click="textSearch.goToNext()"
      >
        <svg
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <polyline points="6 9 12 15 18 9" />
        </svg>
      </button>
      <button
        class="paper-markdown-view__search-btn paper-markdown-view__search-btn--close"
        type="button"
        title="关闭 (Esc)"
        @click="textSearch.closeSearch()"
      >
        <svg
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <line x1="18" y1="6" x2="6" y2="18" />
          <line x1="6" y1="6" x2="18" y2="18" />
        </svg>
      </button>
    </div>

    <div
      ref="scrollContainerRef"
      class="paper-markdown-view__scroll"
      @mouseup="composer.updateComposerFromSelection"
      @click="handleMarkdownClick"
      @pointerdown="handleTablePointerDown"
      @scroll="recordMarkdownScrollPosition"
      @wheel="paperReaderStore.handleWheelZoom"
    >
      <div v-if="loading" class="paper-markdown-view__loading">
        <p>正在加载内容...</p>
      </div>

      <div v-else-if="engine.parseError.value" class="paper-markdown-view__error">
        <p>{{ engine.parseError.value }}</p>
      </div>

      <div v-else-if="!hasContent" class="paper-markdown-view__empty">
        <p>暂无内容</p>
      </div>

      <article v-else class="paper-markdown-view__content" :style="contentZoomStyle">
        <PaperMarkdownStatusPanels
          :translation-missing-count="composer.translationMissingAnnotations.value.length"
          :outdated-count="composer.outdatedAnnotations.value.length"
          :outdated-updating="composer.outdatedAnnotationUpdating.value"
          :outdated-error="composer.outdatedAnnotationError.value"
          :on-retranslate="paperReaderStore.toggleTranslationVisible"
          :on-view-in-original="handleViewTranslationMissingInOriginal"
          :on-update-outdated="handleUpdateOutdatedAnnotationsToCurrentTranslation"
        />

        <PaperMarkdownAnnotationManager :actions="annotationManagerActions" />

        <PaperMarkdownSegmentList
          :segments="engine.renderedSegments.value"
          @retranslate="handleRetranslateSegment"
        />
      </article>
    </div>

    <PaperAnnotationSelectionMenu
      v-if="composer.selectionActionMenu.value"
      :state="composer.selectionActionMenu.value"
      :highlight-color-options="composer.highlightColorOptions"
      :error="composer.selectionActionMenuError.value"
      @create-highlight="composer.handleCreateHighlight"
      @open-note-editor="composer.handleOpenNoteEditorFromSelection"
      @add-to-chat="composer.handleAddToChat"
      @cancel="composer.handleCancelComposer"
    />

    <PaperAnnotationNoteEditor
      v-if="composer.noteEditorDraft.value"
      :state="composer.noteEditorDraft.value"
      :comment="composer.noteEditorComment.value"
      :is-existing-note="composer.noteEditorIsExistingNote.value"
      :can-update="composer.noteEditorCanUpdate.value"
      :saving="composer.noteEditorSaving.value"
      :error="composer.noteEditorError.value"
      @update:comment="composer.noteEditorComment.value = $event"
      @save="composer.handleSaveNote"
      @update-note="composer.handleUpdateNote"
      @delete-note="composer.handleDeleteNoteFromEditor"
      @close="composer.handleCloseNoteEditor"
      @move="composer.handleMoveNoteEditor"
    />

    <PaperAnnotationHoverPopover
      v-if="composer.annotationHoverPopover.value && composer.hoverPopoverAnnotation.value"
      :state="composer.annotationHoverPopover.value"
      :annotation="composer.hoverPopoverAnnotation.value"
      :highlight-color-options="composer.highlightColorOptions"
      :error="composer.hoverPopoverError.value"
      @delete="handleHoverPopoverDelete"
      @open-note-editor="handleHoverPopoverOpenNoteEditor"
      @update-color="composer.handleUpdateHoverColor"
    />
  </div>
</template>

<style scoped>
.paper-markdown-view {
  flex: 1;
  width: 100%;
  min-width: 0;
  min-height: 0;
  display: flex;
  flex-direction: column;
  height: 100%;
  overflow: hidden;
  position: relative;
}

.paper-markdown-view__scroll {
  flex: 1;
  min-height: 0;
  overflow-y: auto;
  overflow-x: hidden;
  scrollbar-width: thin;
  scrollbar-color: var(--sm-color-border-strong) transparent;
  scrollbar-gutter: stable;
  padding: calc(var(--sm-paper-toolbar-height) + var(--sm-space-2)) var(--sm-space-4)
    var(--sm-space-6);
}

.paper-markdown-view__scroll::-webkit-scrollbar {
  width: 10px;
}

.paper-markdown-view__scroll::-webkit-scrollbar-track {
  background: transparent;
}

.paper-markdown-view__scroll::-webkit-scrollbar-thumb {
  border: 3px solid transparent;
  border-radius: 999px;
  background: var(--sm-color-border-strong);
  background-clip: content-box;
}

.paper-markdown-view__scroll::-webkit-scrollbar-thumb:hover {
  background: var(--sm-color-text-tertiary);
  background-clip: content-box;
}

.paper-markdown-view__loading,
.paper-markdown-view__error,
.paper-markdown-view__empty {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 200px;
  font-size: 14px;
  color: var(--sm-color-text-tertiary);
}

.paper-markdown-view__error {
  color: var(--sm-color-status-danger);
}

.paper-markdown-view__content {
  width: 100%;
  max-width: 760px;
  margin: 0 auto;
}

:deep(mark.paper-markdown-view__quote-highlight) {
  background: color-mix(in srgb, var(--sm-color-accent) 22%, transparent);
  border-radius: 3px;
  color: inherit;
  animation: quote-highlight-fade 8s ease-out forwards;
}

:deep(mark.paper-markdown-view__quote-highlight *) {
  color: inherit;
}

@keyframes quote-highlight-fade {
  0% {
    background: color-mix(in srgb, var(--sm-color-accent) 30%, transparent);
  }
  70% {
    background: color-mix(in srgb, var(--sm-color-accent) 12%, transparent);
  }
  100% {
    background: transparent;
  }
}

.paper-markdown-view__search-bar {
  position: absolute;
  top: calc(var(--sm-paper-toolbar-height) + var(--sm-space-2));
  right: 24px;
  z-index: 20;
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 6px 10px;
  border-radius: 10px;
  border: 1px solid var(--sm-color-border-default);
  background: var(--sm-color-surface-1);
  box-shadow:
    0 16px 40px rgba(15, 23, 42, 0.18),
    inset 0 1px 0 rgba(255, 255, 255, 0.04);
  backdrop-filter: blur(18px);
  font-size: 13px;
}

.paper-markdown-view__search-input {
  width: 180px;
  padding: 4px 8px;
  border: 1px solid var(--sm-color-border-default);
  border-radius: var(--sm-radius-sm);
  background: var(--sm-color-surface-2);
  color: var(--sm-color-text-primary);
  font-size: 13px;
  outline: none;
  transition: border-color var(--sm-transition-fast);
}

.paper-markdown-view__search-input:focus {
  border-color: var(--sm-color-accent);
}

.paper-markdown-view__search-count {
  color: var(--sm-color-text-secondary);
  font-size: 12px;
  min-width: 48px;
  text-align: center;
  user-select: none;
}

.paper-markdown-view__search-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 24px;
  padding: 0;
  border: none;
  border-radius: var(--sm-radius-sm);
  background: transparent;
  color: var(--sm-color-text-secondary);
  cursor: pointer;
  font-size: 14px;
  line-height: 1;
  transition:
    background-color var(--sm-transition-fast),
    color var(--sm-transition-fast);
}

.paper-markdown-view__search-btn:hover:not(:disabled) {
  background: var(--sm-color-surface-hover);
  color: var(--sm-color-text-primary);
}

.paper-markdown-view__search-btn:disabled {
  opacity: 0.4;
  cursor: not-allowed;
}

:deep(mark.paper-markdown-view__search-highlight) {
  background: color-mix(in srgb, var(--sm-color-accent) 20%, transparent);
  border-radius: 2px;
  color: inherit;
}

:deep(mark.paper-markdown-view__search-highlight--current) {
  background: color-mix(in srgb, var(--sm-color-accent) 50%, transparent);
  box-shadow: 0 0 0 1px color-mix(in srgb, var(--sm-color-accent) 70%, transparent);
}
</style>

// src/renderer/src/components/paper/PaperMarkdownView.tsx
import {
  useRef,
  useEffect,
  useLayoutEffect,
  useMemo,
  useCallback,
  useImperativeHandle,
  forwardRef
} from 'react'
import { usePaperViewStore } from '@renderer/stores/paper'
import { usePaperAnnotationStore } from '@renderer/stores/paper'
import { retranslateSegment } from '@renderer/stores/paper'
import { useNotification } from '@renderer/composables/useNotification'
import type {
  PaperAnnotation,
  PaperReadingProgress,
  PaperReaderDocument,
  PaperTranslationCache
} from '@shared/types/paper'
import type { PaperQuote } from '@shared/types/chat'
import {
  usePaperMarkdownEngine,
  getTranslationRenderKey,
  type RenderedSegment
} from './hooks/usePaperMarkdownEngine'
import { usePaperAnnotationComposer } from './hooks/usePaperAnnotationComposer'
import { usePaperTextSearch } from './hooks/usePaperTextSearch'
import { usePaperQuoteHighlight } from './composables/usePaperQuoteHighlight'
import { useZoomAnchor } from './composables/useZoomAnchor'
import { useTableDragScroll } from './hooks/useTableDragScroll'
import { useMarkdownScrollPersistence } from './hooks/useMarkdownScrollPersistence'
import { syncFormulaSelectionOnDrag } from './composables/paperDragSelectionSync'
import PaperAnnotationHoverPopover from './annotation/PaperAnnotationHoverPopover'
import PaperAnnotationNoteEditor from './annotation/PaperAnnotationNoteEditor'
import PaperAnnotationSelectionMenu from './annotation/PaperAnnotationSelectionMenu'
import PaperMarkdownSegmentList from './PaperMarkdownSegmentList'
import styles from './PaperMarkdownView.module.css'

interface ReadonlyValueRef<T> {
  readonly value: T
}

interface PaperMarkdownViewProps {
  content: string
  loading: boolean
  paperId: string
  basePath?: string
  translationVisible: boolean
  translationCache?: PaperTranslationCache | null
  readerDocument?: PaperReaderDocument | null
  annotations?: PaperAnnotation[]
  readingProgress?: PaperReadingProgress | null
  onAddToChat?: (quote: PaperQuote) => void
}

export interface PaperMarkdownViewHandle {
  scrollToQuoteAndHighlight: (quote: PaperQuote) => void
}

const PaperMarkdownView = forwardRef<PaperMarkdownViewHandle, PaperMarkdownViewProps>(
  function PaperMarkdownView(
    {
      content,
      loading,
      paperId,
      basePath,
      translationVisible,
      translationCache,
      readerDocument,
      annotations = [],
      readingProgress,
      onAddToChat
    },
    ref
  ) {
    const notify = useNotification()
    const zoomLevel = usePaperViewStore((state) => state.zoomLevel)
    const setPaperTocOutline = usePaperViewStore((state) => state.setPaperTocOutline)
    const clearPaperToc = usePaperViewStore((state) => state.clearPaperToc)
    const handleWheelZoom = usePaperViewStore((state) => state.handleWheelZoom)

    const createAnnotation = usePaperAnnotationStore((state) => state.createAnnotation)
    const updateAnnotation = usePaperAnnotationStore((state) => state.updateAnnotation)
    const deleteAnnotation = usePaperAnnotationStore((state) => state.deleteAnnotation)

    const scrollContainerRef = useRef<HTMLDivElement>(null)
    const searchInputRef = useRef<HTMLInputElement>(null)

    // Text search
    const textSearch = usePaperTextSearch()

    // Zoom anchor
    const zoomAnchorRef = useRef(useZoomAnchor())
    const zoomAnchor = zoomAnchorRef.current
    const quoteHighlightRef = useRef(usePaperQuoteHighlight())
    const quoteHighlight = quoteHighlightRef.current
    const zoomSettleTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)
    const hasMountedZoomRef = useRef(false)
    const previousZoomLevelRef = useRef(zoomLevel)

    // Markdown engine
    const engine = usePaperMarkdownEngine({
      content,
      basePath,
      translationVisible,
      translationCache,
      readerDocument,
      annotations,
      setTocOutline: setPaperTocOutline,
      clearToc: clearPaperToc
    })

    const renderedSegmentsRef = useMemo(
      () =>
        ({
          get value() {
            return engine.renderedSegments
          }
        }) as ReadonlyValueRef<RenderedSegment[]>,
      [engine.renderedSegments]
    )

    const composer = usePaperAnnotationComposer({
      paperId: () => paperId,
      translationCache: () => translationCache,
      annotations: () => annotations,
      renderedSegments: renderedSegmentsRef,
      getSourceSegments: engine.getSourceSegments,
      createAnnotation,
      updateAnnotation,
      deleteAnnotation,
      onAddToChat
    })

    const hasContent = content.trim().length > 0

    // Expose scrollToQuoteAndHighlight to parent
    useImperativeHandle(
      ref,
      () => ({
        scrollToQuoteAndHighlight: quoteHighlight.scrollToQuoteAndHighlight
      }),
      [quoteHighlight]
    )

    // Content zoom style
    const contentZoomStyle = useMemo(
      () => ({
        zoom: zoomLevel
      }),
      [zoomLevel]
    )

    // Sync scrollable table wrap state
    const syncScrollableTableWrapState = useCallback(() => {
      scrollContainerRef.current
        ?.querySelectorAll<HTMLElement>('.paper-markdown-view__table-wrap')
        .forEach((wrap) => {
          wrap.classList.toggle(
            'paper-markdown-view__table-wrap--scrollable',
            wrap.scrollWidth > wrap.clientWidth + 1
          )
        })
    }, [])

    // Table drag scroll
    const { handlePointerDown, lastDragEndedAt } = useTableDragScroll()

    // Scroll persistence
    const { recordScrollPosition, restoreScrollPosition } = useMarkdownScrollPersistence({
      scrollContainerRef,
      paperId,
      readingProgress,
      loading,
      zoomAnchor,
      zoomLevel,
      translationVisible
    })

    // 未恢复批注通知（每次论文加载只提示一次）
    const unresolvedNotifiedRef = useRef(false)

    // Render content and sync tables
    const renderContentAndSyncTables = useCallback(async (): Promise<void> => {
      await engine.renderContent()
      // Use microtask to let React render
      await new Promise((resolve) => setTimeout(resolve, 0))
      syncScrollableTableWrapState()
    }, [engine, syncScrollableTableWrapState])

    // 通知未恢复批注
    // 论文切换时重置通知标记
    useEffect(() => {
      unresolvedNotifiedRef.current = false
    }, [paperId])

    // 检查并通知未恢复的批注
    useEffect(() => {
      if (unresolvedNotifiedRef.current) return
      const ids = engine.unresolvedAnnotationIds
      if (ids.length > 0) {
        unresolvedNotifiedRef.current = true
        const uniqueCount = new Set(ids).size
        notify.info('批注恢复', `${uniqueCount} 条批注因文本变化未能恢复高亮`, {
          source: 'paper',
          dedupeKey: `paper-unresolved-annotations:${paperId}`
        })
      }
    }, [engine.unresolvedAnnotationIds, notify, paperId])

    // Search helpers
    const getSearchContentElement = useCallback((): HTMLElement | null => {
      const contentEl = scrollContainerRef.current?.querySelector('.paper-markdown-view__content')
      return contentEl instanceof HTMLElement ? contentEl : null
    }, [])

    const refreshTextSearch = useCallback(
      (options: { preserveCurrentIndex?: boolean } = {}) => {
        if (!textSearch.isOpen || !textSearch.query.trim()) {
          return
        }

        const contentEl = getSearchContentElement()
        if (!contentEl) {
          return
        }

        textSearch.search(contentEl, textSearch.query, options)
      },
      [textSearch, getSearchContentElement]
    )

    // Keyboard handlers
    const handleDocumentKeyDown = useCallback(
      (event: KeyboardEvent) => {
        if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'f') {
          event.preventDefault()
          if (textSearch.isOpen) {
            searchInputRef.current?.focus()
            searchInputRef.current?.select()
          } else {
            textSearch.openSearch()
            const selection = window.getSelection()?.toString().trim()
            if (selection && selection.length <= 200) {
              textSearch.setQuery(selection)
            }
          }
          return
        }

        if (event.key === 'Escape' && textSearch.isOpen) {
          event.preventDefault()
          textSearch.closeSearch()
          return
        }

        composer.handleDocumentKeyDown(event)
      },
      [composer, textSearch]
    )

    const handleSearchInputKeydown = useCallback(
      (event: React.KeyboardEvent) => {
        if (event.key === 'Enter' && !event.nativeEvent.isComposing) {
          event.preventDefault()
          if (event.shiftKey) {
            textSearch.goToPrevious()
          } else {
            textSearch.goToNext()
          }
        }
      },
      [textSearch]
    )

    // Handle markdown click (prevent after table drag)
    const handleMarkdownClick = useCallback(
      (event: React.MouseEvent) => {
        if (Date.now() - lastDragEndedAt.current < 160) {
          event.preventDefault()
          event.stopPropagation()
          return
        }

        composer.handleSurfaceAnnotationClick(event.nativeEvent)
      },
      [composer, lastDragEndedAt]
    )

    // Retranslate handler
    const handleRetranslateSegment = useCallback(
      async (params: { segmentId: string; stableId: string }): Promise<void> => {
        if (!paperId) {
          return
        }

        const result = await retranslateSegment(paperId, params.segmentId, params.stableId)
        if (!result.success) {
          notify.error('重新翻译失败', result.error || '请稍后再试', {
            source: 'paper',
            dedupeKey: `paper-retranslate:${paperId}:${params.segmentId}:${result.error || ''}`
          })
        }
      },
      [paperId, retranslateSegment, notify]
    )

    // Content change effect
    const prevContentRef = useRef(content)
    const prevBasePathRef = useRef(basePath)
    const prevSourceRevisionIdRef = useRef(readerDocument?.sourceRevisionId)
    const translationRenderKey = useMemo(
      () => (translationVisible ? getTranslationRenderKey(translationCache) : ''),
      [translationCache, translationVisible]
    )
    const annotationUpdateKey = useMemo(
      () =>
        [
          annotations.length,
          readerDocument?.sourceRevisionId ?? '',
          ...annotations.map(
            (annotation) => `${annotation.updatedAt}:${annotation.semanticAnchor.segmentTextHash}`
          )
        ].join('|'),
      [annotations, readerDocument?.sourceRevisionId]
    )

    useEffect(() => {
      const prevContent = prevContentRef.current
      const prevBasePath = prevBasePathRef.current
      const prevSourceRevisionId = prevSourceRevisionIdRef.current

      const contentChanged = content !== prevContent
      const basePathChanged = basePath !== prevBasePath
      const sourceRevisionIdChanged = readerDocument?.sourceRevisionId !== prevSourceRevisionId

      prevContentRef.current = content
      prevBasePathRef.current = basePath
      prevSourceRevisionIdRef.current = readerDocument?.sourceRevisionId

      void renderContentAndSyncTables().then(() => {
        // 仅当菜单和笔记编辑器都未打开时才清除 composer，避免破坏活跃的选区状态
        if (!composer.selectionActionMenu && !composer.noteEditorDraft) {
          composer.clearComposer()
        }

        // Restore scroll position on initial load or major content change
        if (contentChanged || basePathChanged || sourceRevisionIdChanged) {
          void restoreScrollPosition(paperId)
        }
        refreshTextSearch({ preserveCurrentIndex: true })
      })
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [
      content,
      basePath,
      translationVisible,
      translationRenderKey,
      readerDocument?.sourceRevisionId,
      annotations.length,
      annotationUpdateKey
    ])

    // Search query change effect
    useEffect(() => {
      if (!textSearch.isOpen) return
      const contentEl = getSearchContentElement()
      if (contentEl) {
        textSearch.search(contentEl, textSearch.query)
      }
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [textSearch.query])

    // Search open effect
    useEffect(() => {
      if (textSearch.isOpen) {
        setTimeout(() => {
          searchInputRef.current?.focus()
          if (textSearch.query) {
            searchInputRef.current?.select()
          }
        }, 0)
      }
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [textSearch.isOpen])

    // Zoom level effect — useLayoutEffect 确保在浏览器绘制前同步修正滚动位置
    useLayoutEffect(() => {
      if (!hasMountedZoomRef.current) {
        hasMountedZoomRef.current = true
        previousZoomLevelRef.current = zoomLevel
        return
      }

      const prevLevel = previousZoomLevelRef.current
      if (prevLevel === zoomLevel) {
        return
      }

      previousZoomLevelRef.current = zoomLevel

      const container = scrollContainerRef.current
      if (!container) return

      if (!zoomAnchor.isZooming()) {
        // 首次缩放步进：DOM 已更新缩放但 scrollTop 未变，需先用数学方式修正滚动位置
        // 再捕获锚点，否则 beginZoom 捕获的是已偏移的错误锚点
        const ratio = zoomLevel / prevLevel
        const scrollTop = container.scrollTop
        const clientHeight = container.clientHeight
        container.scrollTop = scrollTop * ratio + (clientHeight / 2) * (ratio - 1)
        zoomAnchor.beginZoom(container)
      }

      // 强制同步布局重计算，确保滚动修正基于新的缩放布局
      void container.offsetHeight

      // 同步修正滚动位置（在浏览器绘制前完成，消除抖动）
      zoomAnchor.applyZoomFrame(container)
      syncScrollableTableWrapState()

      if (zoomSettleTimerRef.current !== null) clearTimeout(zoomSettleTimerRef.current)
      zoomSettleTimerRef.current = setTimeout(() => {
        zoomSettleTimerRef.current = null
        zoomAnchor.endZoom()
      }, 150)
    }, [zoomLevel, zoomAnchor, syncScrollableTableWrapState])

    // 实时同步公式拖选高亮
    useEffect(() => {
      const container = scrollContainerRef.current
      if (!container) return

      const cleanup = syncFormulaSelectionOnDrag(container)
      return cleanup
    }, [content, paperId])

    // Keyboard listeners
    useEffect(() => {
      document.addEventListener('mousedown', composer.handleDocumentPointerDown)
      document.addEventListener('keydown', handleDocumentKeyDown)
      return () => {
        document.removeEventListener('mousedown', composer.handleDocumentPointerDown)
        document.removeEventListener('keydown', handleDocumentKeyDown)
      }
    }, [composer.handleDocumentPointerDown, handleDocumentKeyDown])

    // Resize listener for table wraps
    useEffect(() => {
      window.addEventListener('resize', syncScrollableTableWrapState)
      return () => window.removeEventListener('resize', syncScrollableTableWrapState)
    }, [syncScrollableTableWrapState])

    // Cleanup on unmount
    useEffect(() => {
      return () => {
        clearPaperToc()
        textSearch.closeSearch()
        composer.clearComposer()
      }
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])

    return (
      <div className={[styles['paper-markdown-view'], 'paper-markdown-view'].join(' ')}>
        {textSearch.isOpen && (
          <div
            className={[
              styles['paper-markdown-view__search-bar'],
              'paper-markdown-view__search-bar'
            ].join(' ')}
          >
            <input
              ref={searchInputRef}
              type="text"
              className={[
                styles['paper-markdown-view__search-input'],
                'paper-markdown-view__search-input'
              ].join(' ')}
              placeholder="搜索..."
              value={textSearch.query}
              onChange={(e) => textSearch.setQuery(e.target.value)}
              onKeyDown={handleSearchInputKeydown}
            />
            {textSearch.hasMatches ? (
              <span
                className={[
                  styles['paper-markdown-view__search-count'],
                  'paper-markdown-view__search-count'
                ].join(' ')}
              >
                {textSearch.currentIndex + 1} / {textSearch.matchCount}
              </span>
            ) : textSearch.query.trim() ? (
              <span
                className={[
                  styles['paper-markdown-view__search-count'],
                  'paper-markdown-view__search-count'
                ].join(' ')}
              >
                无结果
              </span>
            ) : null}
            <button
              className={[
                styles['paper-markdown-view__search-btn'],
                'paper-markdown-view__search-btn'
              ].join(' ')}
              type="button"
              disabled={!textSearch.hasMatches}
              title="上一个 (Shift+Enter)"
              onClick={textSearch.goToPrevious}
            >
              <svg
                width="14"
                height="14"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <polyline points="18 15 12 9 6 15" />
              </svg>
            </button>
            <button
              className={[
                styles['paper-markdown-view__search-btn'],
                'paper-markdown-view__search-btn'
              ].join(' ')}
              type="button"
              disabled={!textSearch.hasMatches}
              title="下一个 (Enter)"
              onClick={textSearch.goToNext}
            >
              <svg
                width="14"
                height="14"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <polyline points="6 9 12 15 18 9" />
              </svg>
            </button>
            <button
              className={[
                styles['paper-markdown-view__search-btn'],
                'paper-markdown-view__search-btn',
                'paper-markdown-view__search-btn--close'
              ].join(' ')}
              type="button"
              title="关闭 (Esc)"
              onClick={textSearch.closeSearch}
            >
              <svg
                width="14"
                height="14"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <line x1="18" y1="6" x2="6" y2="18" />
                <line x1="6" y1="6" x2="18" y2="18" />
              </svg>
            </button>
          </div>
        )}

        <div
          ref={scrollContainerRef}
          className={[styles['paper-markdown-view__scroll'], 'paper-markdown-view__scroll'].join(
            ' '
          )}
          onMouseUp={(e) => composer.updateComposerFromSelection(e.nativeEvent)}
          onClick={handleMarkdownClick}
          onPointerDown={handlePointerDown}
          onScroll={recordScrollPosition}
          onWheel={(e) => handleWheelZoom(e.nativeEvent)}
        >
          {loading ? (
            <div
              className={[
                styles['paper-markdown-view__loading'],
                'paper-markdown-view__loading'
              ].join(' ')}
            >
              <p>正在加载内容...</p>
            </div>
          ) : engine.parseError ? (
            <div
              className={[styles['paper-markdown-view__error'], 'paper-markdown-view__error'].join(
                ' '
              )}
            >
              <p>{engine.parseError}</p>
            </div>
          ) : !hasContent ? (
            <div
              className={[styles['paper-markdown-view__empty'], 'paper-markdown-view__empty'].join(
                ' '
              )}
            >
              <p>暂无内容</p>
            </div>
          ) : (
            <article
              className={[
                styles['paper-markdown-view__content'],
                'paper-markdown-view__content'
              ].join(' ')}
              style={contentZoomStyle}
            >
              <PaperMarkdownSegmentList
                segments={engine.renderedSegments}
                onRetranslate={handleRetranslateSegment}
              />
            </article>
          )}
        </div>

        {composer.selectionActionMenu && (
          <PaperAnnotationSelectionMenu
            state={composer.selectionActionMenu}
            highlightColorOptions={composer.highlightColorOptions}
            error={composer.selectionActionMenuError}
            onCreateHighlight={composer.handleCreateHighlight}
            onOpenNoteEditor={composer.handleOpenNoteEditorFromSelection}
            onAddToChat={composer.handleAddToChat}
          />
        )}

        {composer.noteEditorDraft && (
          <PaperAnnotationNoteEditor
            state={composer.noteEditorDraft}
            comment={composer.noteEditorComment}
            isExistingNote={composer.noteEditorIsExistingNote}
            canUpdate={composer.noteEditorCanUpdate}
            saving={composer.noteEditorSaving}
            error={composer.noteEditorError}
            onCommentChange={composer.setNoteEditorComment}
            onSave={composer.handleSaveNote}
            onUpdateNote={composer.handleUpdateNote}
            onDeleteNote={composer.handleDeleteNoteFromEditor}
            onClose={composer.handleCloseNoteEditor}
            onMove={composer.handleMoveNoteEditor}
          />
        )}

        {composer.annotationHoverPopover && composer.hoverPopoverAnnotation && (
          <PaperAnnotationHoverPopover
            state={composer.annotationHoverPopover}
            annotation={composer.hoverPopoverAnnotation}
            highlightColorOptions={composer.highlightColorOptions}
            error={composer.hoverPopoverError}
            onDelete={() => {
              const annotation = composer.hoverPopoverAnnotation
              if (annotation) {
                void composer.handleDeleteAnnotation(annotation.id)
              }
            }}
            onOpenNoteEditor={composer.handleOpenNoteEditorFromHover}
            onUpdateColor={composer.handleUpdateHoverColor}
          />
        )}
      </div>
    )
  }
)

export default PaperMarkdownView
