// src/renderer/src/components/chrome/WorkspaceToolbar.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { ReactNode } from 'react'
import { usePiniaStore } from '@renderer/composables/usePiniaStore'
import SvgIcon from '@renderer/components/icons/SvgIcon'
import { useUIStateStore } from '@renderer/stores/uiStateStore'
import { usePaperReaderStore } from '@renderer/stores/paperReaderStore'
import type { PaperFigureItem, PaperTocEntry, PaperTocItem } from '@shared/types/paper'
import { hasPaperTranslationResult } from '@shared/utils/paperTranslation'
import styles from './WorkspaceToolbar.module.css'

interface PaperTocTreeNode {
  item: PaperTocItem
  children: PaperTocTreeNode[]
}

export default function WorkspaceToolbar() {
  const currentView = useUIStateStore((s) => s.currentView)
  const isCurrentSidebarCollapsed = useUIStateStore((s) => s.isCurrentSidebarCollapsed())
  const paperChatPanelOpen = useUIStateStore((s) => s.paperChatPanelOpen)
  const togglePaperChatPanel = useUIStateStore((s) => s.togglePaperChatPanel)
  const paperReaderStore = usePiniaStore(usePaperReaderStore)

  const tocContainerRef = useRef<HTMLDivElement>(null)
  const figureContainerRef = useRef<HTMLDivElement>(null)
  const figurePanelRef = useRef<HTMLDivElement>(null)
  const [showTocPanel, setShowTocPanel] = useState(false)

  const currentPaperId = paperReaderStore.currentPaperId ?? null
  const paperTocTitle = paperReaderStore.paperTocTitle ?? null
  const paperTocItems = useMemo<PaperTocItem[]>(
    () => paperReaderStore.paperTocItems ?? [],
    [paperReaderStore.paperTocItems]
  )
  const currentPaperFigures = useMemo<PaperFigureItem[]>(
    () => paperReaderStore.currentPaperFigures ?? [],
    [paperReaderStore.currentPaperFigures]
  )
  const currentTranslationCache = paperReaderStore.currentTranslationCache ?? null
  const figureCaptionTranslationMap = useMemo<Record<string, string>>(
    () => paperReaderStore.figureCaptionTranslationMap ?? {},
    [paperReaderStore.figureCaptionTranslationMap]
  )
  const figureLoadingByPaperId = useMemo<Record<string, boolean>>(
    () => paperReaderStore.figureLoadingByPaperId ?? {},
    [paperReaderStore.figureLoadingByPaperId]
  )
  const isOcrCompleted = paperReaderStore.isOcrCompleted ?? false
  const isCurrentPaperTranslating = paperReaderStore.isCurrentPaperTranslating ?? false
  const markdownLoading = paperReaderStore.markdownLoading ?? false
  const originalPdfVisible = paperReaderStore.originalPdfVisible ?? false
  const showFigurePanel = paperReaderStore.showFigurePanel ?? false
  const translationVisible = paperReaderStore.translationVisible ?? false
  const canZoomIn = paperReaderStore.canZoomIn ?? false
  const canZoomOut = paperReaderStore.canZoomOut ?? false
  const zoomPercent = paperReaderStore.zoomPercent ?? 100

  const isPaperView = currentView === 'paper'
  const isKnowledgeView = currentView === 'knowledge'
  const isPaperToolbar = isPaperView && Boolean(currentPaperId)
  const isKnowledgeToolbar = isKnowledgeView
  const canOpenToc = Boolean(currentPaperId)
  const canOpenFigurePanel = Boolean(currentPaperId)
  const canOpenPaperChat = Boolean(currentPaperId && isOcrCompleted)
  const hasTranslationCache = hasPaperTranslationResult(currentTranslationCache)
  const currentFigureLoading = currentPaperId
    ? Boolean(figureLoadingByPaperId[currentPaperId])
    : false
  const hasAnyTocEntries = Boolean(paperTocTitle) || paperTocItems.length > 0

  const translationButtonTitle = useMemo(() => {
    if (translationVisible) {
      return isCurrentPaperTranslating ? '隐藏译文（后台继续翻译）' : '隐藏译文'
    }

    if (hasTranslationCache) {
      return isCurrentPaperTranslating ? '显示译文（后台正在翻译）' : '显示译文'
    }

    return isCurrentPaperTranslating ? '显示译文（后台正在翻译）' : '翻译论文'
  }, [hasTranslationCache, isCurrentPaperTranslating, translationVisible])

  const paperTocTree = useMemo<PaperTocTreeNode[]>(() => {
    const roots: PaperTocTreeNode[] = []
    let currentLevel1: PaperTocTreeNode | null = null
    let currentLevel2: PaperTocTreeNode | null = null

    for (const item of paperTocItems) {
      const node: PaperTocTreeNode = {
        item,
        children: []
      }

      if (item.level === 1) {
        roots.push(node)
        currentLevel1 = node
        currentLevel2 = null
        continue
      }

      if (item.level === 2) {
        if (currentLevel1) {
          currentLevel1.children.push(node)
        } else {
          roots.push(node)
        }

        currentLevel2 = node
        continue
      }

      if (currentLevel2) {
        currentLevel2.children.push(node)
      } else if (currentLevel1) {
        currentLevel1.children.push(node)
      } else {
        roots.push(node)
      }
    }

    return roots
  }, [paperTocItems])

  const closeTocPanel = useCallback((): void => {
    setShowTocPanel(false)
  }, [])

  const closeFigurePanel = useCallback((): void => {
    paperReaderStore.closeFigurePanel()
  }, [paperReaderStore])

  const handleToggleOriginalPdf = useCallback((): void => {
    if (!currentPaperId) {
      return
    }

    closeTocPanel()
    closeFigurePanel()
    paperReaderStore.closeFigurePreview()
    paperReaderStore.toggleOriginalPdfVisible()
  }, [closeFigurePanel, closeTocPanel, currentPaperId, paperReaderStore])

  const handleToggleTranslation = useCallback(async (): Promise<void> => {
    if (!currentPaperId) {
      return
    }

    closeTocPanel()
    closeFigurePanel()
    await paperReaderStore.toggleTranslationVisible()
  }, [closeFigurePanel, closeTocPanel, currentPaperId, paperReaderStore])

  const handleToggleToc = useCallback((): void => {
    if (!canOpenToc) {
      return
    }

    closeFigurePanel()
    setShowTocPanel((value) => !value)
  }, [canOpenToc, closeFigurePanel])

  const handleToggleFigurePanel = useCallback(async (): Promise<void> => {
    if (!canOpenFigurePanel) {
      return
    }

    closeTocPanel()
    await paperReaderStore.toggleFigurePanel()
  }, [canOpenFigurePanel, closeTocPanel, paperReaderStore])

  const handleTogglePaperChat = useCallback((): void => {
    if (!canOpenPaperChat) {
      return
    }

    closeTocPanel()
    closeFigurePanel()
    togglePaperChatPanel()
  }, [canOpenPaperChat, closeFigurePanel, closeTocPanel, togglePaperChatPanel])

  const handleSelectTocItem = useCallback(
    (headingId: string): void => {
      if (paperReaderStore.scrollToHeading(headingId)) {
        closeTocPanel()
      }
    },
    [closeTocPanel, paperReaderStore]
  )

  const getFigureItemLabel = useCallback(
    (figure: PaperFigureItem): string => {
      if (translationVisible) {
        const translated = figureCaptionTranslationMap[figure.id]
        if (translated) return translated
      }
      return figure.caption || figure.subCaption || '暂无图注'
    },
    [figureCaptionTranslationMap, translationVisible]
  )

  const getTocEntryDisplayText = useCallback(
    (entry: PaperTocEntry): string => {
      if (translationVisible && entry.translatedText) {
        return entry.translatedText
      }
      return entry.text
    },
    [translationVisible]
  )

  const handlePreviewFigure = useCallback(
    (figure: PaperFigureItem): void => {
      const panelRect = figurePanelRef.current?.getBoundingClientRect()

      paperReaderStore.openFigurePreview(figure, {
        initialRect: panelRect
          ? {
              left: panelRect.left,
              top: panelRect.top,
              width: panelRect.width
            }
          : undefined
      })
    },
    [paperReaderStore]
  )

  const handleClickOutside = useCallback(
    (event: MouseEvent): void => {
      const target = event.target as Node

      if (showTocPanel && tocContainerRef.current && !tocContainerRef.current.contains(target)) {
        closeTocPanel()
      }

      if (
        showFigurePanel &&
        figureContainerRef.current &&
        !figureContainerRef.current.contains(target)
      ) {
        closeFigurePanel()
      }
    },
    [closeFigurePanel, closeTocPanel, showFigurePanel, showTocPanel]
  )

  const handleKeyDown = useCallback(
    (event: KeyboardEvent): void => {
      if (event.key !== 'Escape') {
        return
      }

      if (showTocPanel) {
        closeTocPanel()
      }

      if (showFigurePanel) {
        closeFigurePanel()
      }
    },
    [closeFigurePanel, closeTocPanel, showFigurePanel, showTocPanel]
  )

  useEffect(() => {
    if (!isPaperView) {
      closeTocPanel()
      closeFigurePanel()
    }
  }, [closeFigurePanel, closeTocPanel, isPaperView])

  useEffect(() => {
    closeTocPanel()
    closeFigurePanel()
  }, [closeFigurePanel, closeTocPanel, currentPaperId])

  useEffect(() => {
    if (markdownLoading) {
      closeTocPanel()
      closeFigurePanel()
    }
  }, [closeFigurePanel, closeTocPanel, markdownLoading])

  useEffect(() => {
    document.addEventListener('click', handleClickOutside)
    document.addEventListener('keydown', handleKeyDown)
    return () => {
      document.removeEventListener('click', handleClickOutside)
      document.removeEventListener('keydown', handleKeyDown)
    }
  }, [handleClickOutside, handleKeyDown])

  function renderTocTree(nodes: PaperTocTreeNode[]): ReactNode {
    return nodes.map((node) => (
      <li key={node.item.id} className={styles['sm-workspace-toolbar__toc-node']}>
        <button
          className={[
            styles['sm-workspace-toolbar__toc-item'],
            styles[`sm-workspace-toolbar__toc-item--level-${node.item.level}`]
          ].join(' ')}
          title={getTocEntryDisplayText(node.item)}
          type="button"
          onClick={() => handleSelectTocItem(node.item.id)}
        >
          {getTocEntryDisplayText(node.item)}
        </button>

        {node.children.length > 0 && (
          <ul
            className={[
              styles['sm-workspace-toolbar__toc-list'],
              styles['sm-workspace-toolbar__toc-list--child']
            ].join(' ')}
          >
            {renderTocTree(node.children)}
          </ul>
        )}
      </li>
    ))
  }

  return (
    <div
      className={[
        styles['sm-workspace-toolbar__controls'],
        isPaperToolbar && styles['sm-workspace-toolbar__controls--paper'],
        isKnowledgeToolbar &&
          !isPaperToolbar &&
          styles['sm-workspace-toolbar__controls--knowledge'],
        isPaperToolbar &&
          isCurrentSidebarCollapsed &&
          styles['sm-workspace-toolbar__controls--chrome-safe']
      ]
        .filter(Boolean)
        .join(' ')}
    >
      {isPaperView && currentPaperId && (
        <>
          <button
            className={['sm-icon-button', styles['sm-workspace-toolbar__button']].join(' ')}
            title="缩小"
            aria-label="缩小"
            disabled={!canZoomOut}
            onClick={() => paperReaderStore.zoomOut()}
          >
            <SvgIcon name="zoom-out" size={14} />
          </button>
          <button
            className={[
              'sm-icon-button',
              styles['sm-workspace-toolbar__button'],
              styles['sm-workspace-toolbar__zoom-display']
            ].join(' ')}
            title={`${zoomPercent}%`}
            aria-label="重置缩放"
            disabled={zoomPercent === 100}
            onClick={() => paperReaderStore.resetZoom()}
          >
            <span className={styles['sm-workspace-toolbar__zoom-text']}>{zoomPercent}%</span>
          </button>
          <button
            className={['sm-icon-button', styles['sm-workspace-toolbar__button']].join(' ')}
            title="放大"
            aria-label="放大"
            disabled={!canZoomIn}
            onClick={() => paperReaderStore.zoomIn()}
          >
            <SvgIcon name="zoom-in" size={14} />
          </button>
        </>
      )}

      {isPaperView && currentPaperId && !originalPdfVisible && (
        <button
          className={[
            'sm-icon-button',
            styles['sm-workspace-toolbar__button'],
            translationVisible && styles['is-active'],
            isCurrentPaperTranslating && styles['is-pending']
          ]
            .filter(Boolean)
            .join(' ')}
          title={translationButtonTitle}
          aria-label={translationButtonTitle}
          onClick={() => {
            void handleToggleTranslation()
          }}
        >
          <SvgIcon name="translate" size={14} />
        </button>
      )}

      {isPaperView && currentPaperId && !originalPdfVisible && (
        <div ref={tocContainerRef} className={styles['sm-workspace-toolbar__toc']}>
          <button
            className={[
              'sm-icon-button',
              styles['sm-workspace-toolbar__button'],
              showTocPanel && styles['is-active']
            ]
              .filter(Boolean)
              .join(' ')}
            title="论文目录"
            aria-label="打开论文目录"
            aria-haspopup="dialog"
            aria-expanded={showTocPanel}
            disabled={!canOpenToc}
            onClick={handleToggleToc}
          >
            <SvgIcon name="toc" size={14} />
          </button>

          {showTocPanel && (
            <div
              className={styles['sm-workspace-toolbar__toc-panel']}
              role="dialog"
              aria-label="论文目录"
            >
              <div className={styles['sm-workspace-toolbar__toc-header']}>论文目录</div>

              {markdownLoading ? (
                <div className={styles['sm-workspace-toolbar__toc-state']}>目录加载中</div>
              ) : !hasAnyTocEntries ? (
                <div className={styles['sm-workspace-toolbar__toc-state']}>未识别到可用目录</div>
              ) : (
                <div className={styles['sm-workspace-toolbar__toc-scroll']}>
                  {paperTocTitle && (
                    <button
                      className={styles['sm-workspace-toolbar__toc-title']}
                      title={getTocEntryDisplayText(paperTocTitle)}
                      type="button"
                      onClick={() => handleSelectTocItem(paperTocTitle.id)}
                    >
                      {getTocEntryDisplayText(paperTocTitle)}
                    </button>
                  )}

                  {paperTocTitle && paperTocItems.length > 0 && (
                    <div
                      className={styles['sm-workspace-toolbar__toc-divider']}
                      aria-hidden="true"
                    />
                  )}

                  {paperTocItems.length > 0 && (
                    <ul className={styles['sm-workspace-toolbar__toc-list']}>
                      {renderTocTree(paperTocTree)}
                    </ul>
                  )}
                </div>
              )}
            </div>
          )}
        </div>
      )}

      {isPaperView && currentPaperId && !originalPdfVisible && (
        <div ref={figureContainerRef} className={styles['sm-workspace-toolbar__figures']}>
          <button
            className={[
              'sm-icon-button',
              styles['sm-workspace-toolbar__button'],
              showFigurePanel && styles['is-active']
            ]
              .filter(Boolean)
              .join(' ')}
            title="论文图片"
            aria-label="打开论文图片列表"
            aria-haspopup="dialog"
            aria-expanded={showFigurePanel}
            disabled={!canOpenFigurePanel}
            onClick={() => {
              void handleToggleFigurePanel()
            }}
          >
            <SvgIcon name="image" size={14} />
          </button>

          {showFigurePanel && (
            <div
              ref={figurePanelRef}
              className={styles['sm-workspace-toolbar__figure-panel']}
              role="dialog"
              aria-label="论文图片列表"
            >
              <div className={styles['sm-workspace-toolbar__toc-header']}>论文图片</div>

              {currentFigureLoading ? (
                <div className={styles['sm-workspace-toolbar__toc-state']}>图片加载中</div>
              ) : currentPaperFigures.length === 0 ? (
                <div className={styles['sm-workspace-toolbar__toc-state']}>未识别到可用图片</div>
              ) : (
                <div className={styles['sm-workspace-toolbar__figure-scroll']}>
                  {currentPaperFigures.map((figure) => (
                    <div key={figure.id} className={styles['sm-workspace-toolbar__figure-item']}>
                      <img
                        src={figure.imagePath}
                        alt={getFigureItemLabel(figure)}
                        className={styles['sm-workspace-toolbar__figure-thumb']}
                      />

                      <div className={styles['sm-workspace-toolbar__figure-copy']}>
                        <div
                          className={styles['sm-workspace-toolbar__figure-caption']}
                          title={getFigureItemLabel(figure)}
                        >
                          {getFigureItemLabel(figure)}
                        </div>
                      </div>

                      <button
                        className={styles['sm-workspace-toolbar__figure-preview']}
                        type="button"
                        onClick={() => handlePreviewFigure(figure)}
                      >
                        预览
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      )}

      {isPaperView && currentPaperId && (
        <button
          className={[
            'sm-icon-button',
            styles['sm-workspace-toolbar__button'],
            originalPdfVisible && styles['is-active']
          ]
            .filter(Boolean)
            .join(' ')}
          title="PDF 原件"
          aria-label="PDF 原件"
          type="button"
          onClick={handleToggleOriginalPdf}
        >
          <span className={styles['sm-workspace-toolbar__original-text']}>原</span>
        </button>
      )}

      {isPaperView && canOpenPaperChat && (
        <button
          className={[
            'sm-icon-button',
            styles['sm-workspace-toolbar__button'],
            paperChatPanelOpen && styles['is-active']
          ]
            .filter(Boolean)
            .join(' ')}
          title="聊天"
          aria-label="聊天"
          type="button"
          onClick={handleTogglePaperChat}
        >
          <SvgIcon name="chat" size={14} />
        </button>
      )}
    </div>
  )
}

// src/renderer/src/components/chrome/WorkspaceToolbar.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { storeToRefs } from 'pinia'
import { useZustandStore } from '@renderer/composables/useZustandStore'
import SvgIcon from '@renderer/components/icons/SvgIcon.vue'
import { useUIStateStore } from '@renderer/stores'
import { usePaperReaderStore } from '@renderer/stores/paperReaderStore'
import type { PaperFigureItem, PaperTocEntry, PaperTocItem } from '@shared/types/paper'
import { hasPaperTranslationResult } from '@shared/utils/paperTranslation'
import styles from './WorkspaceToolbar.module.css'

const uiState = useZustandStore(useUIStateStore)

const paperReaderStore = usePaperReaderStore()
const {
  currentPaperId,
  currentPaperFigures,
  currentTranslationCache,
  figureCaptionTranslationMap,
  figureLoadingByPaperId,
  isOcrCompleted,
  isCurrentPaperTranslating,
  paperTocTitle,
  paperTocItems,
  markdownLoading,
  originalPdfVisible,
  showFigurePanel,
  translationVisible,
  canZoomIn,
  canZoomOut,
  zoomPercent
} = storeToRefs(paperReaderStore)

interface PaperTocTreeNode {
  item: PaperTocItem
  children: PaperTocTreeNode[]
}

const tocContainerRef = ref<HTMLElement | null>(null)
const figureContainerRef = ref<HTMLElement | null>(null)
const figurePanelRef = ref<HTMLElement | null>(null)
const showTocPanel = ref(false)

const isPaperView = computed(() => uiState.isPaperView())
const isKnowledgeView = computed(() => uiState.isKnowledgeView())
const isCurrentSidebarCollapsed = computed(() => uiState.isCurrentSidebarCollapsed())
const paperChatPanelOpen = computed(() => uiState.paperChatPanelOpen)

const isPaperToolbar = computed(() => {
  return isPaperView.value && !!currentPaperId.value
})

const isKnowledgeToolbar = computed(() => {
  return isKnowledgeView.value
})

const canOpenToc = computed(() => {
  return !!currentPaperId.value
})

const canOpenFigurePanel = computed(() => {
  return !!currentPaperId.value
})

const canOpenPaperChat = computed(() => {
  return !!currentPaperId.value && isOcrCompleted.value
})

const hasTranslationCache = computed(() => {
  return hasPaperTranslationResult(currentTranslationCache.value)
})

const translationButtonTitle = computed(() => {
  if (translationVisible.value) {
    return isCurrentPaperTranslating.value ? '隐藏译文（后台继续翻译）' : '隐藏译文'
  }

  if (hasTranslationCache.value) {
    return isCurrentPaperTranslating.value ? '显示译文（后台正在翻译）' : '显示译文'
  }

  return isCurrentPaperTranslating.value ? '显示译文（后台正在翻译）' : '翻译论文'
})

const currentFigureLoading = computed(() => {
  if (!currentPaperId.value) {
    return false
  }

  return !!figureLoadingByPaperId.value[currentPaperId.value]
})

const hasAnyTocEntries = computed(() => {
  return !!paperTocTitle.value || paperTocItems.value.length > 0
})

const paperTocTree = computed<PaperTocTreeNode[]>(() => {
  const roots: PaperTocTreeNode[] = []
  let currentLevel1: PaperTocTreeNode | null = null
  let currentLevel2: PaperTocTreeNode | null = null

  for (const item of paperTocItems.value) {
    const node: PaperTocTreeNode = {
      item,
      children: []
    }

    if (item.level === 1) {
      roots.push(node)
      currentLevel1 = node
      currentLevel2 = null
      continue
    }

    if (item.level === 2) {
      if (currentLevel1) {
        currentLevel1.children.push(node)
      } else {
        roots.push(node)
      }

      currentLevel2 = node
      continue
    }

    if (currentLevel2) {
      currentLevel2.children.push(node)
    } else if (currentLevel1) {
      currentLevel1.children.push(node)
    } else {
      roots.push(node)
    }
  }

  return roots
})

function closeTocPanel(): void {
  showTocPanel.value = false
}

function closeFigurePanel(): void {
  paperReaderStore.closeFigurePanel()
}

function handleToggleOriginalPdf(): void {
  if (!currentPaperId.value) {
    return
  }

  closeTocPanel()
  closeFigurePanel()
  paperReaderStore.closeFigurePreview()
  paperReaderStore.toggleOriginalPdfVisible()
}

async function handleToggleTranslation(): Promise<void> {
  if (!currentPaperId.value) {
    return
  }

  closeTocPanel()
  closeFigurePanel()
  await paperReaderStore.toggleTranslationVisible()
}

function handleToggleToc(): void {
  if (!canOpenToc.value) {
    return
  }

  closeFigurePanel()
  showTocPanel.value = !showTocPanel.value
}

async function handleToggleFigurePanel(): Promise<void> {
  if (!canOpenFigurePanel.value) {
    return
  }

  closeTocPanel()
  await paperReaderStore.toggleFigurePanel()
}

function handleTogglePaperChat(): void {
  if (!canOpenPaperChat.value) {
    return
  }

  closeTocPanel()
  closeFigurePanel()
  uiState.togglePaperChatPanel()
}

function handleSelectTocItem(headingId: string): void {
  if (paperReaderStore.scrollToHeading(headingId)) {
    closeTocPanel()
  }
}

function getFigureItemLabel(figure: PaperFigureItem): string {
  if (translationVisible.value) {
    const translated = figureCaptionTranslationMap.value[figure.id]
    if (translated) return translated
  }
  return figure.caption || figure.subCaption || '暂无图注'
}

function getTocEntryDisplayText(entry: PaperTocEntry): string {
  if (translationVisible.value && entry.translatedText) {
    return entry.translatedText
  }
  return entry.text
}

function handlePreviewFigure(figure: PaperFigureItem): void {
  const panelRect = figurePanelRef.value?.getBoundingClientRect()

  paperReaderStore.openFigurePreview(figure, {
    initialRect: panelRect
      ? {
          left: panelRect.left,
          top: panelRect.top,
          width: panelRect.width
        }
      : undefined
  })
}

function handleClickOutside(event: MouseEvent): void {
  const target = event.target as Node

  if (showTocPanel.value && tocContainerRef.value && !tocContainerRef.value.contains(target)) {
    closeTocPanel()
  }

  if (
    showFigurePanel.value &&
    figureContainerRef.value &&
    !figureContainerRef.value.contains(target)
  ) {
    closeFigurePanel()
  }
}

function handleKeyDown(event: KeyboardEvent): void {
  if (event.key === 'Escape') {
    if (showTocPanel.value) {
      closeTocPanel()
    }

    if (showFigurePanel.value) {
      closeFigurePanel()
    }
  }
}

watch(isPaperView, (value) => {
  if (!value) {
    closeTocPanel()
    closeFigurePanel()
  }
})

watch(currentPaperId, () => {
  closeTocPanel()
  closeFigurePanel()
})

watch(markdownLoading, (loading) => {
  if (loading) {
    closeTocPanel()
    closeFigurePanel()
  }
})

onMounted(() => {
  document.addEventListener('click', handleClickOutside)
  document.addEventListener('keydown', handleKeyDown)
})

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
  document.removeEventListener('keydown', handleKeyDown)
})
</script>

<template>
  <div
    :class="[
      styles['sm-workspace-toolbar__controls'],
      {
        [styles['sm-workspace-toolbar__controls--paper']]: isPaperToolbar,
        [styles['sm-workspace-toolbar__controls--knowledge']]:
          isKnowledgeToolbar && !isPaperToolbar,
        [styles['sm-workspace-toolbar__controls--chrome-safe']]:
          isPaperToolbar && isCurrentSidebarCollapsed
      }
    ]"
  >
    <template v-if="isPaperView && currentPaperId">
      <button
        :class="['sm-icon-button', styles['sm-workspace-toolbar__button']]"
        title="缩小"
        aria-label="缩小"
        :disabled="!canZoomOut"
        @click="paperReaderStore.zoomOut()"
      >
        <SvgIcon name="zoom-out" :size="14" />
      </button>
      <button
        :class="[
          'sm-icon-button',
          styles['sm-workspace-toolbar__button'],
          styles['sm-workspace-toolbar__zoom-display']
        ]"
        :title="`${zoomPercent}%`"
        aria-label="重置缩放"
        :disabled="zoomPercent === 100"
        @click="paperReaderStore.resetZoom()"
      >
        <span :class="styles['sm-workspace-toolbar__zoom-text']">{{ zoomPercent }}%</span>
      </button>
      <button
        :class="['sm-icon-button', styles['sm-workspace-toolbar__button']]"
        title="放大"
        aria-label="放大"
        :disabled="!canZoomIn"
        @click="paperReaderStore.zoomIn()"
      >
        <SvgIcon name="zoom-in" :size="14" />
      </button>
    </template>

    <button
      v-if="isPaperView && currentPaperId && !originalPdfVisible"
      :class="[
        'sm-icon-button',
        styles['sm-workspace-toolbar__button'],
        {
          [styles['is-active']]: translationVisible,
          [styles['is-pending']]: isCurrentPaperTranslating
        }
      ]"
      :title="translationButtonTitle"
      :aria-label="translationButtonTitle"
      @click="handleToggleTranslation"
    >
      <SvgIcon name="translate" :size="14" />
    </button>

    <div
      v-if="isPaperView && currentPaperId && !originalPdfVisible"
      ref="tocContainerRef"
      :class="styles['sm-workspace-toolbar__toc']"
    >
      <button
        :class="[
          'sm-icon-button',
          styles['sm-workspace-toolbar__button'],
          { [styles['is-active']]: showTocPanel }
        ]"
        title="论文目录"
        aria-label="打开论文目录"
        aria-haspopup="dialog"
        :aria-expanded="showTocPanel"
        :disabled="!canOpenToc"
        @click="handleToggleToc"
      >
        <SvgIcon name="toc" :size="14" />
      </button>

      <div
        v-if="showTocPanel"
        :class="styles['sm-workspace-toolbar__toc-panel']"
        role="dialog"
        aria-label="论文目录"
      >
        <div :class="styles['sm-workspace-toolbar__toc-header']">论文目录</div>

        <div v-if="markdownLoading" :class="styles['sm-workspace-toolbar__toc-state']">
          目录加载中
        </div>

        <div v-else-if="!hasAnyTocEntries" :class="styles['sm-workspace-toolbar__toc-state']">
          未识别到可用目录
        </div>

        <div v-else :class="styles['sm-workspace-toolbar__toc-scroll']">
          <button
            v-if="paperTocTitle"
            :class="styles['sm-workspace-toolbar__toc-title']"
            :title="getTocEntryDisplayText(paperTocTitle)"
            type="button"
            @click="handleSelectTocItem(paperTocTitle.id)"
          >
            {{ getTocEntryDisplayText(paperTocTitle) }}
          </button>

          <div
            v-if="paperTocTitle && paperTocItems.length > 0"
            :class="styles['sm-workspace-toolbar__toc-divider']"
            aria-hidden="true"
          />

          <ul v-if="paperTocItems.length > 0" :class="styles['sm-workspace-toolbar__toc-list']">
            <li
              v-for="node in paperTocTree"
              :key="node.item.id"
              :class="styles['sm-workspace-toolbar__toc-node']"
            >
              <button
                :class="[
                  styles['sm-workspace-toolbar__toc-item'],
                  styles[`sm-workspace-toolbar__toc-item--level-${node.item.level}`]
                ]"
                :title="getTocEntryDisplayText(node.item)"
                type="button"
                @click="handleSelectTocItem(node.item.id)"
              >
                {{ getTocEntryDisplayText(node.item) }}
              </button>

              <ul
                v-if="node.children.length > 0"
                :class="[
                  styles['sm-workspace-toolbar__toc-list'],
                  styles['sm-workspace-toolbar__toc-list--child']
                ]"
              >
                <li
                  v-for="child in node.children"
                  :key="child.item.id"
                  :class="styles['sm-workspace-toolbar__toc-node']"
                >
                  <button
                    :class="[
                      styles['sm-workspace-toolbar__toc-item'],
                      styles[`sm-workspace-toolbar__toc-item--level-${child.item.level}`]
                    ]"
                    :title="getTocEntryDisplayText(child.item)"
                    type="button"
                    @click="handleSelectTocItem(child.item.id)"
                  >
                    {{ getTocEntryDisplayText(child.item) }}
                  </button>

                  <ul
                    v-if="child.children.length > 0"
                    :class="[
                      styles['sm-workspace-toolbar__toc-list'],
                      styles['sm-workspace-toolbar__toc-list--child']
                    ]"
                  >
                    <li
                      v-for="grandchild in child.children"
                      :key="grandchild.item.id"
                      :class="styles['sm-workspace-toolbar__toc-node']"
                    >
                      <button
                        :class="[
                          styles['sm-workspace-toolbar__toc-item'],
                          styles[`sm-workspace-toolbar__toc-item--level-${grandchild.item.level}`]
                        ]"
                        :title="getTocEntryDisplayText(grandchild.item)"
                        type="button"
                        @click="handleSelectTocItem(grandchild.item.id)"
                      >
                        {{ getTocEntryDisplayText(grandchild.item) }}
                      </button>
                    </li>
                  </ul>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div
      v-if="isPaperView && currentPaperId && !originalPdfVisible"
      ref="figureContainerRef"
      :class="styles['sm-workspace-toolbar__figures']"
    >
      <button
        :class="[
          'sm-icon-button',
          styles['sm-workspace-toolbar__button'],
          { [styles['is-active']]: showFigurePanel }
        ]"
        title="论文图片"
        aria-label="打开论文图片列表"
        aria-haspopup="dialog"
        :aria-expanded="showFigurePanel"
        :disabled="!canOpenFigurePanel"
        @click="handleToggleFigurePanel"
      >
        <SvgIcon name="image" :size="14" />
      </button>

      <div
        v-if="showFigurePanel"
        ref="figurePanelRef"
        :class="styles['sm-workspace-toolbar__figure-panel']"
        role="dialog"
        aria-label="论文图片列表"
      >
        <div :class="styles['sm-workspace-toolbar__toc-header']">论文图片</div>

        <div v-if="currentFigureLoading" :class="styles['sm-workspace-toolbar__toc-state']">
          图片加载中
        </div>

        <div
          v-else-if="currentPaperFigures.length === 0"
          :class="styles['sm-workspace-toolbar__toc-state']"
        >
          未识别到可用图片
        </div>

        <div v-else :class="styles['sm-workspace-toolbar__figure-scroll']">
          <div
            v-for="figure in currentPaperFigures"
            :key="figure.id"
            :class="styles['sm-workspace-toolbar__figure-item']"
          >
            <img
              :src="figure.imagePath"
              :alt="getFigureItemLabel(figure)"
              :class="styles['sm-workspace-toolbar__figure-thumb']"
            />

            <div :class="styles['sm-workspace-toolbar__figure-copy']">
              <div
                :class="styles['sm-workspace-toolbar__figure-caption']"
                :title="getFigureItemLabel(figure)"
              >
                {{ getFigureItemLabel(figure) }}
              </div>
            </div>

            <button
              :class="styles['sm-workspace-toolbar__figure-preview']"
              type="button"
              @click="handlePreviewFigure(figure)"
            >
              预览
            </button>
          </div>
        </div>
      </div>
    </div>

    <button
      v-if="isPaperView && currentPaperId"
      :class="[
        'sm-icon-button',
        styles['sm-workspace-toolbar__button'],
        { [styles['is-active']]: originalPdfVisible }
      ]"
      title="PDF 原件"
      aria-label="PDF 原件"
      type="button"
      @click="handleToggleOriginalPdf"
    >
      <span :class="styles['sm-workspace-toolbar__original-text']">原</span>
    </button>

    <button
      v-if="isPaperView && canOpenPaperChat"
      :class="[
        'sm-icon-button',
        styles['sm-workspace-toolbar__button'],
        { [styles['is-active']]: paperChatPanelOpen }
      ]"
      title="聊天"
      aria-label="聊天"
      type="button"
      @click="handleTogglePaperChat"
    >
      <SvgIcon name="chat" :size="14" />
    </button>
  </div>
</template>
